#!/bin/sh

me=`whoami`
cdate=`date +%d%b%Y-%H%M`
if [ -n "$1" ]; then                                                                                                                                   
mysqldump --hex-blob -v --add-drop-database --add-drop-table --default-character-set=utf8 -R --single-transaction -u amp --databases $1 > tmp-$1-$cdate-$me.sql
echo " "
echo " "
echo "Replacing dg_site_domain sites with 'localhost' and removing references to user amp@localhost ..."
echo " "

cat tmp-$1-$cdate-$me.sql | awk '
BEGIN { 
   FS = ",";
    }
/`amp`@`localhost`/ {
  gsub(/`amp`@/, "`root`@");
 }
/^INSERT INTO `dg_site_domain` VALUES/ {
   printf $1;
   for (i=2; i<=NF; i++){
      printf ",";
      if ($i ~ /ampdev.net/)
         printf ("\047localhost\047"); 
      else
         printf $i; 
   }
   printf "\n";
}
!/^INSERT INTO `dg_site_domain` VALUES/{ 
    print $0;
}
' > tmp2-$1-$cdate-$me.sql;
rm -f tmp-$1-$cdate-$me.sql
cat tmp2-$1-$cdate-$me.sql | bzip2 > $1-$cdate.sql.bz2
rm -f tmp2-$1-$cdate-$me.sql

echo " "
echo " "
echo "Export saved as $1-$cdate.sql.bz2"
echo "To download locally, paste this command: scp $me@ampdev.net:$1-$cdate.sql.bz2 ."
else
echo "usage $0 [database_name]"
fi

