#!/bin/bash
# dbsnapshot tool for ampdev.net
# version 0.2
# Copyright (c) 2009 Development Gateway Foundation, Inc
# author: Mihai Postelnicu - mpostelnicu@dgfoundation.org

me=`whoami`
cdate=`date +%d%b%Y-%H%M`
cdir=`pwd`

function help {
	echo "Creates a 7zipped AMP database snapshot from the specified database engine"
        echo "Usage:  $0 [database_type] [database_name]"
	echo "database_type = mysql|postgres|oracle"
	echo ""
	echo "Examples: $0 mysql amp_generic"
	echo "          $0 oracle amp_madagascar"
	echo ""
}

if [ -n "$1" -a -n "$2" ]; then
    case "$1" in
    mysql)    
        zipfile=$2-$cdate.mysql.7z                                                                                                                               
	mysqldump --hex-blob -v --add-drop-database --add-drop-table --default-character-set=utf8 -R --single-transaction -c -e -u amp --databases $2 | dbstrip | p7zip > $zipfile
    ;;
    postgres)
	zipfile=$2-$cdate.pgsql.7z
	pg_dump -vFt -U postgres $2 | p7zip > $zipfile
    ;;
    oracle)
	zipfile=$2-$cdate.orcl.7z
	expcommand="'./expdaemon $2'"
	ssh -o "StrictHostKeyChecking no" -i /usr/local/share/identity-ampdev-oracle oracle@localhost -p21212 "./expdaemon $2" | p7zip > $zipfile
    ;;
    *)
	help
    ;;
    esac
    echo " "
    echo " "
    echo "Export saved as $zipfile"
    echo "To download on a linux machine, paste this command: scp -P22222 $me@ampdev.net:$cdir/$zipfile ."
else
    help
fi
