package org.digijava.module.aim.helper;

import java.io.*;

public class ParisIndicator7Jrxml
{
	public void createJrxml(String filePath, int cols, int rows,String type)
	throws IOException
	{
		try
		{
			 FileOutputStream out,out2; // declare a file output object
     PrintStream p,p2; // declare a print stream object

				out = new FileOutputStream(filePath);
				out2 = new FileOutputStream(filePath,true);
				p = new PrintStream(out);
				p.println("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>");
				//p.println("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>");
				p2 = new PrintStream(out2);
				System.out.println("creating now- dynamic trend...");
				
				
				p2.println("<!-- Created with iReport - A designer for JasperReports -->");
				p2.println("<!DOCTYPE jasperReport PUBLIC '//JasperReports//DTD Report Design//EN' 'http://jasperreports.sourceforge.net/dtds/jasperreport.dtd'>");
				p2.println("<jasperReport");
				p2.println("		 name='indicator7pdf'");
				p2.println("		 columnCount='1'");
				p2.println("		 printOrder='Vertical'");
				p2.println("		 orientation='Portrait'");
				p2.println("		 pageWidth='892'");
				p2.println("		 pageHeight='842'");
				p2.println("		 columnWidth='535'");
				p2.println("		 columnSpacing='0'");
				p2.println("		 leftMargin='30'");
				p2.println("		 rightMargin='30'");
				p2.println("		 topMargin='20'");
				p2.println("		 bottomMargin='20'");
				p2.println("		 whenNoDataType='NoPages'");
				p2.println("		 isTitleNewPage='false'");
				p2.println("		 isSummaryNewPage='false'>");
				p2.println("	<property name='ireport.scriptlethandling' value='2' />");
				p2.println("<parameter name='qu' isForPrompting='false' class='java.lang.String'>");
				p2.println("<defaultValueExpression ><![CDATA[\"select * from my_table\"]]></defaultValueExpression>");
				p2.println("</parameter>");
				p2.println("<parameter name='nam' isForPrompting='false' class='java.lang.String'>");
				p2.println("<defaultValueExpression ><![CDATA[\"zzzz\"]]></defaultValueExpression>");
				p2.println("</parameter>");
				p2.println("<queryString><![CDATA[$P!{qu}]]></queryString>");

//							DYNAMIC CCCCCCCCC
							String dc;
							int colCnt =13;
							System.out.println(" Cnt = " + colCnt);
//							 gets the no of fields = 4 constants fields + YearCnt*3 + yearCnt
							for(int k=1; k<=colCnt; k++)
							{
								System.out.println("k="+k);
								dc="m"+k;
								p2.println("<field name='"+dc+"' class='java.lang.String'/>");
							}

				p2.println("<group  name='Data' isStartNewColumn='false' isStartNewPage='false' isResetPageNumber='false' isReprintHeaderOnEachPage='false' minHeightToStartNewPage='0' >");
				p2.println("<groupExpression><![CDATA[$F{m1}]]></groupExpression>");
				p2.println("<groupHeader>");

				p2.println("</groupHeader>");
				p2.println("<groupFooter>");
				p2.println("<band height='0'  isSplitAllowed='true' >");
				p2.println("</band>");
				p2.println("</groupFooter>");
				p2.println("</group>");
				if(type.equals("xls"))
				{
				
					p2.println("		<background>");
					p2.println("			<band height='0'  isSplitAllowed='true' >");
					p2.println("			</band>");
					p2.println("		</background>");
					p2.println("		<title>");
					p2.println("			<band height='22'  isSplitAllowed='true' >");
					p2.println("				<staticText>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='141'");
					p2.println("						y='0'");
					p2.println("						width='300'");
					p2.println("						height='22'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='staticText-1'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='18' isBold='true' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<text><![CDATA[PARIS REPORT 7]]></text>");
					p2.println("				</staticText>");
					p2.println("			</band>");
					p2.println("		</title>");
					p2.println("		<pageHeader>");
					p2.println("			<band height='49'  isSplitAllowed='true' >");
					p2.println("			</band>");
					p2.println("		</pageHeader>");
					p2.println("		<columnHeader>");
					p2.println("			<band height='125'  isSplitAllowed='true' >");
					
					p2.println("				<staticText>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='2'");
					p2.println("						y='2'");
					p2.println("						width='80'");
					p2.println("						height='123'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#CCCCCC'");
					p2.println("						key='staticText-2'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='true' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<text><![CDATA[Donors]]></text>");
					p2.println("				</staticText>");
					
					p2.println("				<staticText>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='84'");
					p2.println("						y='25'");
					p2.println("						width='80'");
					p2.println("						height='100'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#CCCCCC'");
					p2.println("						key='staticText-7'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='true' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<text><![CDATA[ Aid flows to the government sector scheduled for fiscal year]]></text>");
					p2.println("				</staticText>");
					p2.println("				<textField isStretchWithOverflow='false' pattern='' isBlankWhenNull='false' evaluationTime='Now' hyperlinkType='None' >");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='84'");
					p2.println("						y='2'");
					p2.println("						width='243'");
					p2.println("						height='23'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='textField-3'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='false' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<textFieldExpression   class='java.lang.String'><![CDATA[$F{m2}]]></textFieldExpression>");
					p2.println("				</textField>");
					p2.println("				<textField isStretchWithOverflow='false' pattern='' isBlankWhenNull='false' evaluationTime='Now' hyperlinkType='None' >");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='329'");
					p2.println("						y='2'");
					p2.println("						width='243'");
					p2.println("						height='23'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='textField-18'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='false' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<textFieldExpression   class='java.lang.String'><![CDATA[$F{m6}]]></textFieldExpression>");
					p2.println("				</textField>");
					p2.println("				<textField isStretchWithOverflow='false' pattern='' isBlankWhenNull='false' evaluationTime='Now' hyperlinkType='None' >");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='574'");
					p2.println("						y='2'");
					p2.println("						width='243'");
					p2.println("						height='23'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='textField-19'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='false' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<textFieldExpression   class='java.lang.String'><![CDATA[$F{m10}]]></textFieldExpression>");
					p2.println("				</textField>");
					
					
					p2.println("				<staticText>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='166'");
					p2.println("						y='25'");
					p2.println("						width='80'");
					p2.println("						height='100'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#CCCCCC'");
					p2.println("						key='staticText-8'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='true' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<text><![CDATA[ Total Aid flows disbursed to the government sector]]></text>");
					p2.println("				</staticText>");
					
					p2.println("				<staticText>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='248'");
					p2.println("						y='25'");
					p2.println("						width='80'");
					p2.println("						height='100'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#CCCCCC'");
					p2.println("						key='staticText-9'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='true' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<text><![CDATA[ Proportion of aid to the government sector disbursed within the fiscal year it was scheduled]]></text>");
					p2.println("				</staticText>");
					
					p2.println("				<staticText>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='329'");
					p2.println("						y='25'");
					p2.println("						width='80'");
					p2.println("						height='100'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#CCCCCC'");
					p2.println("						key='staticText-10'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='true' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<text><![CDATA[ Aid flows to the government sector scheduled for fiscal year]]></text>");
					p2.println("				</staticText>");
					p2.println("				<staticText>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='411'");
					p2.println("						y='25'");
					p2.println("						width='80'");
					p2.println("						height='100'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#CCCCCC'");
					p2.println("						key='staticText-11'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='true' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<text><![CDATA[ Total Aid flows disbursed to the government sector]]></text>");
					p2.println("				</staticText>");
					
					p2.println("				<staticText>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='493'");
					p2.println("						y='25'");
					p2.println("						width='80'");
					p2.println("						height='100'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#CCCCCC'");
					p2.println("						key='staticText-12'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='true' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<text><![CDATA[ Proportion of aid to the government sector disbursed within the fiscal year it was scheduled]]></text>");
					p2.println("				</staticText>");
					
					p2.println("				<staticText>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='575'");
					p2.println("						y='25'");
					p2.println("						width='80'");
					p2.println("						height='100'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#CCCCCC'");
					p2.println("						key='staticText-13'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='true' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<text><![CDATA[ Aid flows to the government sector scheduled for fiscal year]]></text>");
					p2.println("				</staticText>");
					p2.println("				<staticText>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='657'");
					p2.println("						y='25'");
					p2.println("						width='80'");
					p2.println("						height='100'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#CCCCCC'");
					p2.println("						key='staticText-14'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='true' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<text><![CDATA[ Total Aid flows disbursed to the government sector]]></text>");
					p2.println("				</staticText>");
					p2.println("				<staticText>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='739'");
					p2.println("						y='25'");
					p2.println("						width='80'");
					p2.println("						height='100'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#CCCCCC'");
					p2.println("						key='staticText-15'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='true' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<text><![CDATA[ Proportion of aid to the government sector disbursed within the fiscal year it was scheduled]]></text>");
					p2.println("				</staticText>");
					
					p2.println("			</band>");
					p2.println("		</columnHeader>");
					p2.println("		<detail>");
					p2.println("			<band height='31'  isSplitAllowed='true' >");
					p2.println("				<textField isStretchWithOverflow='false' pattern='' isBlankWhenNull='false' evaluationTime='Now' hyperlinkType='None' >");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='2'");
					p2.println("						y='2'");
					p2.println("						width='80'");
					p2.println("						height='27'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='textField-2'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='false' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<textFieldExpression   class='java.lang.String'><![CDATA[$F{m1}]]></textFieldExpression>");
					p2.println("				</textField>");
					
					p2.println("				<textField isStretchWithOverflow='false' pattern='' isBlankWhenNull='false' evaluationTime='Now' hyperlinkType='None' >");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='84'");
					p2.println("						y='2'");
					p2.println("						width='80'");
					p2.println("						height='27'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='textField-20'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='false' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<textFieldExpression   class='java.lang.String'><![CDATA[$F{m3}]]></textFieldExpression>");
					p2.println("				</textField>");
					p2.println("				<textField isStretchWithOverflow='false' pattern='' isBlankWhenNull='false' evaluationTime='Now' hyperlinkType='None' >");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='166'");
					p2.println("						y='2'");
					p2.println("						width='80'");
					p2.println("						height='27'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='textField-21'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='false' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<textFieldExpression   class='java.lang.String'><![CDATA[$F{m4}]]></textFieldExpression>");
					p2.println("				</textField>");
					p2.println("				<textField isStretchWithOverflow='false' pattern='' isBlankWhenNull='false' evaluationTime='Now' hyperlinkType='None' >");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='248'");
					p2.println("						y='2'");
					p2.println("						width='80'");
					p2.println("						height='27'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='textField-22'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='false' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<textFieldExpression   class='java.lang.String'><![CDATA[$F{m5}]]></textFieldExpression>");
					p2.println("				</textField>");
					p2.println("				<textField isStretchWithOverflow='false' pattern='' isBlankWhenNull='false' evaluationTime='Now' hyperlinkType='None' >");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='329'");
					p2.println("						y='2'");
					p2.println("						width='80'");
					p2.println("						height='27'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='textField-23'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='false' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<textFieldExpression   class='java.lang.String'><![CDATA[$F{m7}]]></textFieldExpression>");
					p2.println("				</textField>");
					p2.println("				<textField isStretchWithOverflow='false' pattern='' isBlankWhenNull='false' evaluationTime='Now' hyperlinkType='None' >");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='411'");
					p2.println("						y='2'");
					p2.println("						width='80'");
					p2.println("						height='27'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='textField-24'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='false' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<textFieldExpression   class='java.lang.String'><![CDATA[$F{m8}]]></textFieldExpression>");
					p2.println("				</textField>");
					p2.println("				<textField isStretchWithOverflow='false' pattern='' isBlankWhenNull='false' evaluationTime='Now' hyperlinkType='None' >");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='493'");
					p2.println("						y='2'");
					p2.println("						width='80'");
					p2.println("						height='27'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='textField-25'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='false' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<textFieldExpression   class='java.lang.String'><![CDATA[$F{m9}]]></textFieldExpression>");
					p2.println("				</textField>");
					p2.println("				<textField isStretchWithOverflow='false' pattern='' isBlankWhenNull='false' evaluationTime='Now' hyperlinkType='None' >");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='575'");
					p2.println("						y='2'");
					p2.println("						width='80'");
					p2.println("						height='27'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='textField-26'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='false' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<textFieldExpression   class='java.lang.String'><![CDATA[$F{m11}]]></textFieldExpression>");
					p2.println("				</textField>");
					p2.println("				<textField isStretchWithOverflow='false' pattern='' isBlankWhenNull='false' evaluationTime='Now' hyperlinkType='None' >");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='657'");
					p2.println("						y='2'");
					p2.println("						width='80'");
					p2.println("						height='27'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='textField-27'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='false' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<textFieldExpression   class='java.lang.String'><![CDATA[$F{m12}]]></textFieldExpression>");
					p2.println("				</textField>");
					p2.println("				<textField isStretchWithOverflow='false' pattern='' isBlankWhenNull='false' evaluationTime='Now' hyperlinkType='None' >");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='739'");
					p2.println("						y='2'");
					p2.println("						width='80'");
					p2.println("						height='27'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='textField-28'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='false' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<textFieldExpression   class='java.lang.String'><![CDATA[$F{m13}]]></textFieldExpression>");
					p2.println("				</textField>");
				
					p2.println("			</band>");
					p2.println("		</detail>");
					p2.println("		<columnFooter>");
					p2.println("			<band height='0'  isSplitAllowed='true' >");
					p2.println("			</band>");
					p2.println("		</columnFooter>");
					p2.println("		<pageFooter>");
					p2.println("			<band height='0'  isSplitAllowed='true' >");
					p2.println("			</band>");
					p2.println("		</pageFooter>");
					p2.println("		<summary>");
					p2.println("			<band height='0'  isSplitAllowed='true' >");
					p2.println("			</band>");
					p2.println("		</summary>");
					p2.println("</jasperReport>");


				}
				
				else
				{
					p2.println("		<background>");
					p2.println("			<band height='0'  isSplitAllowed='true' >");
					p2.println("			</band>");
					p2.println("		</background>");
					p2.println("		<title>");
					p2.println("			<band height='22'  isSplitAllowed='true' >");
					p2.println("				<staticText>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='141'");
					p2.println("						y='0'");
					p2.println("						width='300'");
					p2.println("						height='22'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='staticText-1'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='18' isBold='true' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<text><![CDATA[PARIS REPORT 7]]></text>");
					p2.println("				</staticText>");
					p2.println("			</band>");
					p2.println("		</title>");
					p2.println("		<pageHeader>");
					p2.println("			<band height='49'  isSplitAllowed='true' >");
					p2.println("			</band>");
					p2.println("		</pageHeader>");
					p2.println("		<columnHeader>");
					p2.println("			<band height='125'  isSplitAllowed='true' >");
					p2.println("				<line direction='TopDown'>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='2'");
					p2.println("						y='1'");
					p2.println("						width='817'");
					p2.println("						height='0'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='line-29'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<graphicElement stretchType='NoStretch' pen='Thin' fill='Solid' />");
					p2.println("				</line>");
					p2.println("				<staticText>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='2'");
					p2.println("						y='2'");
					p2.println("						width='80'");
					p2.println("						height='123'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#CCCCCC'");
					p2.println("						key='staticText-2'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='true' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<text><![CDATA[Donors]]></text>");
					p2.println("				</staticText>");
					p2.println("				<line direction='TopDown'>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='4360'");
					p2.println("						y='1'");
					p2.println("						width='0'");
					p2.println("						height='34'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='line-11'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<graphicElement stretchType='NoStretch' pen='Thin' fill='Solid' />");
					p2.println("				</line>");
					p2.println("				<staticText>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='84'");
					p2.println("						y='25'");
					p2.println("						width='80'");
					p2.println("						height='100'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#CCCCCC'");
					p2.println("						key='staticText-7'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='true' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<text><![CDATA[ Aid flows to the government sector scheduled for fiscal year]]></text>");
					p2.println("				</staticText>");
					p2.println("				<textField isStretchWithOverflow='false' pattern='' isBlankWhenNull='false' evaluationTime='Now' hyperlinkType='None' >");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='84'");
					p2.println("						y='2'");
					p2.println("						width='243'");
					p2.println("						height='23'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='textField-3'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='false' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<textFieldExpression   class='java.lang.String'><![CDATA[$F{m2}]]></textFieldExpression>");
					p2.println("				</textField>");
					p2.println("				<textField isStretchWithOverflow='false' pattern='' isBlankWhenNull='false' evaluationTime='Now' hyperlinkType='None' >");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='329'");
					p2.println("						y='2'");
					p2.println("						width='243'");
					p2.println("						height='23'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='textField-18'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='false' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<textFieldExpression   class='java.lang.String'><![CDATA[$F{m6}]]></textFieldExpression>");
					p2.println("				</textField>");
					p2.println("				<textField isStretchWithOverflow='false' pattern='' isBlankWhenNull='false' evaluationTime='Now' hyperlinkType='None' >");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='574'");
					p2.println("						y='2'");
					p2.println("						width='243'");
					p2.println("						height='23'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='textField-19'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='false' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<textFieldExpression   class='java.lang.String'><![CDATA[$F{m10}]]></textFieldExpression>");
					p2.println("				</textField>");
					p2.println("				<line direction='TopDown'>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='83'");
					p2.println("						y='2'");
					p2.println("						width='0'");
					p2.println("						height='123'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='line-30'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<graphicElement stretchType='NoStretch' pen='Thin' fill='Solid' />");
					p2.println("				</line>");
					p2.println("				<line direction='TopDown'>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='83'");
					p2.println("						y='24'");
					p2.println("						width='734'");
					p2.println("						height='0'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='line-31'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<graphicElement stretchType='NoStretch' pen='Thin' fill='Solid' />");
					p2.println("				</line>");
					p2.println("				<line direction='TopDown'>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='165'");
					p2.println("						y='24'");
					p2.println("						width='0'");
					p2.println("						height='100'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='line-32'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<graphicElement stretchType='NoStretch' pen='Thin' fill='Solid' />");
					p2.println("				</line>");
					p2.println("				<staticText>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='166'");
					p2.println("						y='25'");
					p2.println("						width='80'");
					p2.println("						height='100'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#CCCCCC'");
					p2.println("						key='staticText-8'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='true' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<text><![CDATA[ Total Aid flows disbursed to the government sector]]></text>");
					p2.println("				</staticText>");
					p2.println("				<line direction='TopDown'>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='247'");
					p2.println("						y='25'");
					p2.println("						width='0'");
					p2.println("						height='100'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='line-33'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<graphicElement stretchType='NoStretch' pen='Thin' fill='Solid' />");
					p2.println("				</line>");
					p2.println("				<staticText>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='248'");
					p2.println("						y='25'");
					p2.println("						width='80'");
					p2.println("						height='100'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#CCCCCC'");
					p2.println("						key='staticText-9'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='true' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<text><![CDATA[ Proportion of aid to the government sector disbursed within the fiscal year it was scheduled]]></text>");
					p2.println("				</staticText>");
					p2.println("				<line direction='TopDown'>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='328'");
					p2.println("						y='1'");
					p2.println("						width='0'");
					p2.println("						height='123'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='line-34'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<graphicElement stretchType='NoStretch' pen='Thin' fill='Solid' />");
					p2.println("				</line>");
					p2.println("				<line direction='TopDown'>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='574'");
					p2.println("						y='1'");
					p2.println("						width='0'");
					p2.println("						height='123'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='line-35'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<graphicElement stretchType='NoStretch' pen='Thin' fill='Solid' />");
					p2.println("				</line>");
					p2.println("				<staticText>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='329'");
					p2.println("						y='25'");
					p2.println("						width='80'");
					p2.println("						height='100'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#CCCCCC'");
					p2.println("						key='staticText-10'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='true' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<text><![CDATA[ Aid flows to the government sector scheduled for fiscal year]]></text>");
					p2.println("				</staticText>");
					p2.println("				<staticText>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='411'");
					p2.println("						y='25'");
					p2.println("						width='80'");
					p2.println("						height='100'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#CCCCCC'");
					p2.println("						key='staticText-11'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='true' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<text><![CDATA[ Total Aid flows disbursed to the government sector]]></text>");
					p2.println("				</staticText>");
					p2.println("				<line direction='TopDown'>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='410'");
					p2.println("						y='25'");
					p2.println("						width='0'");
					p2.println("						height='100'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='line-36'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<graphicElement stretchType='NoStretch' pen='Thin' fill='Solid' />");
					p2.println("				</line>");
					p2.println("				<line direction='TopDown'>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='492'");
					p2.println("						y='25'");
					p2.println("						width='0'");
					p2.println("						height='100'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='line-37'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<graphicElement stretchType='NoStretch' pen='Thin' fill='Solid' />");
					p2.println("				</line>");
					p2.println("				<staticText>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='493'");
					p2.println("						y='25'");
					p2.println("						width='80'");
					p2.println("						height='100'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#CCCCCC'");
					p2.println("						key='staticText-12'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='true' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<text><![CDATA[ Proportion of aid to the government sector disbursed within the fiscal year it was scheduled]]></text>");
					p2.println("				</staticText>");
					p2.println("				<line direction='TopDown'>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='820'");
					p2.println("						y='1'");
					p2.println("						width='0'");
					p2.println("						height='123'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='line-38'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<graphicElement stretchType='NoStretch' pen='Thin' fill='Solid' />");
					p2.println("				</line>");
					p2.println("				<staticText>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='575'");
					p2.println("						y='25'");
					p2.println("						width='80'");
					p2.println("						height='100'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#CCCCCC'");
					p2.println("						key='staticText-13'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='true' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<text><![CDATA[ Aid flows to the government sector scheduled for fiscal year]]></text>");
					p2.println("				</staticText>");
					p2.println("				<staticText>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='657'");
					p2.println("						y='25'");
					p2.println("						width='80'");
					p2.println("						height='100'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#CCCCCC'");
					p2.println("						key='staticText-14'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='true' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<text><![CDATA[ Total Aid flows disbursed to the government sector]]></text>");
					p2.println("				</staticText>");
					p2.println("				<staticText>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='739'");
					p2.println("						y='25'");
					p2.println("						width='80'");
					p2.println("						height='100'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#CCCCCC'");
					p2.println("						key='staticText-15'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='true' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<text><![CDATA[ Proportion of aid to the government sector disbursed within the fiscal year it was scheduled]]></text>");
					p2.println("				</staticText>");
					p2.println("				<line direction='TopDown'>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='656'");
					p2.println("						y='25'");
					p2.println("						width='0'");
					p2.println("						height='100'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='line-39'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<graphicElement stretchType='NoStretch' pen='Thin' fill='Solid' />");
					p2.println("				</line>");
					p2.println("				<line direction='TopDown'>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='738'");
					p2.println("						y='25'");
					p2.println("						width='0'");
					p2.println("						height='100'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='line-40'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<graphicElement stretchType='NoStretch' pen='Thin' fill='Solid' />");
					p2.println("				</line>");
					p2.println("				<line direction='TopDown'>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='1'");
					p2.println("						y='1'");
					p2.println("						width='0'");
					p2.println("						height='123'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='line-42'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<graphicElement stretchType='NoStretch' pen='Thin' fill='Solid' />");
					p2.println("				</line>");
					p2.println("			</band>");
					p2.println("		</columnHeader>");
					p2.println("		<detail>");
					p2.println("			<band height='31'  isSplitAllowed='true' >");
					p2.println("				<textField isStretchWithOverflow='false' pattern='' isBlankWhenNull='false' evaluationTime='Now' hyperlinkType='None' >");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='2'");
					p2.println("						y='2'");
					p2.println("						width='80'");
					p2.println("						height='27'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='textField-2'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='false' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<textFieldExpression   class='java.lang.String'><![CDATA[$F{m1}]]></textFieldExpression>");
					p2.println("				</textField>");
					p2.println("				<line direction='TopDown'>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='1'");
					p2.println("						y='1'");
					p2.println("						width='817'");
					p2.println("						height='0'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='line-41'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<graphicElement stretchType='NoStretch' pen='Thin' fill='Solid' />");
					p2.println("				</line>");
					p2.println("				<line direction='TopDown'>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='1'");
					p2.println("						y='30'");
					p2.println("						width='818'");
					p2.println("						height='0'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='line-43'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<graphicElement stretchType='NoStretch' pen='Thin' fill='Solid' />");
					p2.println("				</line>");
					p2.println("				<line direction='TopDown'>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='1'");
					p2.println("						y='1'");
					p2.println("						width='0'");
					p2.println("						height='28'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='line-44'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<graphicElement stretchType='NoStretch' pen='Thin' fill='Solid' />");
					p2.println("				</line>");
					p2.println("				<line direction='TopDown'>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='820'");
					p2.println("						y='1'");
					p2.println("						width='0'");
					p2.println("						height='27'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='line-45'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<graphicElement stretchType='NoStretch' pen='Thin' fill='Solid' />");
					p2.println("				</line>");
					p2.println("				<textField isStretchWithOverflow='false' pattern='' isBlankWhenNull='false' evaluationTime='Now' hyperlinkType='None' >");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='84'");
					p2.println("						y='2'");
					p2.println("						width='80'");
					p2.println("						height='27'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='textField-20'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='false' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<textFieldExpression   class='java.lang.String'><![CDATA[$F{m3}]]></textFieldExpression>");
					p2.println("				</textField>");
					p2.println("				<textField isStretchWithOverflow='false' pattern='' isBlankWhenNull='false' evaluationTime='Now' hyperlinkType='None' >");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='166'");
					p2.println("						y='2'");
					p2.println("						width='80'");
					p2.println("						height='27'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='textField-21'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='false' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<textFieldExpression   class='java.lang.String'><![CDATA[$F{m4}]]></textFieldExpression>");
					p2.println("				</textField>");
					p2.println("				<textField isStretchWithOverflow='false' pattern='' isBlankWhenNull='false' evaluationTime='Now' hyperlinkType='None' >");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='248'");
					p2.println("						y='2'");
					p2.println("						width='80'");
					p2.println("						height='27'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='textField-22'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='false' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<textFieldExpression   class='java.lang.String'><![CDATA[$F{m5}]]></textFieldExpression>");
					p2.println("				</textField>");
					p2.println("				<textField isStretchWithOverflow='false' pattern='' isBlankWhenNull='false' evaluationTime='Now' hyperlinkType='None' >");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='329'");
					p2.println("						y='2'");
					p2.println("						width='80'");
					p2.println("						height='27'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='textField-23'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='false' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<textFieldExpression   class='java.lang.String'><![CDATA[$F{m7}]]></textFieldExpression>");
					p2.println("				</textField>");
					p2.println("				<textField isStretchWithOverflow='false' pattern='' isBlankWhenNull='false' evaluationTime='Now' hyperlinkType='None' >");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='411'");
					p2.println("						y='2'");
					p2.println("						width='80'");
					p2.println("						height='27'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='textField-24'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='false' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<textFieldExpression   class='java.lang.String'><![CDATA[$F{m8}]]></textFieldExpression>");
					p2.println("				</textField>");
					p2.println("				<textField isStretchWithOverflow='false' pattern='' isBlankWhenNull='false' evaluationTime='Now' hyperlinkType='None' >");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='493'");
					p2.println("						y='2'");
					p2.println("						width='80'");
					p2.println("						height='27'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='textField-25'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='false' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<textFieldExpression   class='java.lang.String'><![CDATA[$F{m9}]]></textFieldExpression>");
					p2.println("				</textField>");
					p2.println("				<textField isStretchWithOverflow='false' pattern='' isBlankWhenNull='false' evaluationTime='Now' hyperlinkType='None' >");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='575'");
					p2.println("						y='2'");
					p2.println("						width='80'");
					p2.println("						height='27'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='textField-26'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='false' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<textFieldExpression   class='java.lang.String'><![CDATA[$F{m11}]]></textFieldExpression>");
					p2.println("				</textField>");
					p2.println("				<textField isStretchWithOverflow='false' pattern='' isBlankWhenNull='false' evaluationTime='Now' hyperlinkType='None' >");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='657'");
					p2.println("						y='2'");
					p2.println("						width='80'");
					p2.println("						height='27'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='textField-27'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='false' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<textFieldExpression   class='java.lang.String'><![CDATA[$F{m12}]]></textFieldExpression>");
					p2.println("				</textField>");
					p2.println("				<textField isStretchWithOverflow='false' pattern='' isBlankWhenNull='false' evaluationTime='Now' hyperlinkType='None' >");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='739'");
					p2.println("						y='2'");
					p2.println("						width='80'");
					p2.println("						height='27'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='textField-28'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<textElement textAlignment='Center' verticalAlignment='Middle' rotation='None' lineSpacing='Single'>");
					p2.println("						<font fontName='Arial' pdfFontName='Helvetica' size='10' isBold='false' isItalic='false' isUnderline='false' isPdfEmbedded ='false' pdfEncoding ='Cp1252' isStrikeThrough='false' />");
					p2.println("					</textElement>");
					p2.println("				<textFieldExpression   class='java.lang.String'><![CDATA[$F{m13}]]></textFieldExpression>");
					p2.println("				</textField>");
					p2.println("				<line direction='TopDown'>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='83'");
					p2.println("						y='2'");
					p2.println("						width='0'");
					p2.println("						height='27'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='line-46'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<graphicElement stretchType='NoStretch' pen='Thin' fill='Solid' />");
					p2.println("				</line>");
					p2.println("				<line direction='TopDown'>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='165'");
					p2.println("						y='2'");
					p2.println("						width='0'");
					p2.println("						height='27'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='line-47'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<graphicElement stretchType='NoStretch' pen='Thin' fill='Solid' />");
					p2.println("				</line>");
					p2.println("				<line direction='TopDown'>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='247'");
					p2.println("						y='2'");
					p2.println("						width='0'");
					p2.println("						height='27'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='line-48'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<graphicElement stretchType='NoStretch' pen='Thin' fill='Solid' />");
					p2.println("				</line>");
					p2.println("				<line direction='TopDown'>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='328'");
					p2.println("						y='2'");
					p2.println("						width='0'");
					p2.println("						height='27'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='line-49'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<graphicElement stretchType='NoStretch' pen='Thin' fill='Solid' />");
					p2.println("				</line>");
					p2.println("				<line direction='TopDown'>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='410'");
					p2.println("						y='2'");
					p2.println("						width='0'");
					p2.println("						height='27'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='line-50'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<graphicElement stretchType='NoStretch' pen='Thin' fill='Solid' />");
					p2.println("				</line>");
					p2.println("				<line direction='TopDown'>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='492'");
					p2.println("						y='2'");
					p2.println("						width='0'");
					p2.println("						height='27'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='line-51'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<graphicElement stretchType='NoStretch' pen='Thin' fill='Solid' />");
					p2.println("				</line>");
					p2.println("				<line direction='TopDown'>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='574'");
					p2.println("						y='2'");
					p2.println("						width='0'");
					p2.println("						height='27'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='line-52'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<graphicElement stretchType='NoStretch' pen='Thin' fill='Solid' />");
					p2.println("				</line>");
					p2.println("				<line direction='TopDown'>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='656'");
					p2.println("						y='2'");
					p2.println("						width='0'");
					p2.println("						height='27'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='line-53'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<graphicElement stretchType='NoStretch' pen='Thin' fill='Solid' />");
					p2.println("				</line>");
					p2.println("				<line direction='TopDown'>");
					p2.println("					<reportElement");
					p2.println("						mode='Opaque'");
					p2.println("						x='738'");
					p2.println("						y='2'");
					p2.println("						width='0'");
					p2.println("						height='27'");
					p2.println("						forecolor='#000000'");
					p2.println("						backcolor='#FFFFFF'");
					p2.println("						key='line-54'");
					p2.println("						stretchType='NoStretch'");
					p2.println("						positionType='FixRelativeToTop'");
					p2.println("						isPrintRepeatedValues='true'");
					p2.println("						isRemoveLineWhenBlank='false'");
					p2.println("						isPrintInFirstWholeBand='false'");
					p2.println("						isPrintWhenDetailOverflows='false'/>");
					p2.println("					<graphicElement stretchType='NoStretch' pen='Thin' fill='Solid' />");
					p2.println("				</line>");
					p2.println("			</band>");
					p2.println("		</detail>");
					p2.println("		<columnFooter>");
					p2.println("			<band height='0'  isSplitAllowed='true' >");
					p2.println("			</band>");
					p2.println("		</columnFooter>");
					p2.println("		<pageFooter>");
					p2.println("			<band height='0'  isSplitAllowed='true' >");
					p2.println("			</band>");
					p2.println("		</pageFooter>");
					p2.println("		<summary>");
					p2.println("			<band height='0'  isSplitAllowed='true' >");
					p2.println("			</band>");
					p2.println("		</summary>");
					p2.println("</jasperReport>");
					}



				
		System.out.println("hyup");			
		}
		
		catch(Exception e)
		{
			
		}
	}
}