//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.15 at 03:55:13 PM EEST 
//


package org.digijava.module.gateperm.feed.schema.impl;

public class JAXBVersion {

    public final static java.lang.String version = "1.0.5";

}
