package org.dgfoundation.amp.nireports.testcases.drc.dimensions;

import org.dgfoundation.amp.nireports.testcases.HNDNode;
import org.dgfoundation.amp.nireports.testcases.HardcodedNiDimension;

import java.util.Arrays;
import java.util.List;

import static org.dgfoundation.amp.nireports.testcases.HNDNode.element;

public class OrganizationsTestDimension extends HardcodedNiDimension {

    public OrganizationsTestDimension(String name, int depth) {
        super(name, depth);
    }

    public final static OrganizationsTestDimension instance = new OrganizationsTestDimension("orgs", 3);

    @Override
    protected List<HNDNode> buildHardcodedElements() {
        return Arrays.asList(
        element(1, "Gouvernement et Secteur Public", 
            element(788, "DECENTRALISATION ET AMENAGEMENT DU TERRITOIRE", 
                element(3731, "Ministère de la Décentralisation et Aménagement du Territoire" ), 
                element(3851, "Cellule pour la Décentralisation" ) ), 
            element(789, "AFFAIRES ETRANGERES", 
                element(3161, "Ministère des Affaires Entragères" ), 
                element(3182, "Ministère des Affaires Etrangères" ) ), 
            element(790, "JUSTICE", 
                element(4376, "Pouvoir Judiciaire" ), 
                element(3735, "Ministère de la Justice" ) ), 
            element(791, "DEVELOPPEMENT RURAL", 
                element(3248, "Service National d'Hydraulique Rurale" ), 
                element(3251, "S.G. Développement Rural" ), 
                element(3732, "Ministère du Développement Rural" ) ), 
            element(792, "PETITES ET MOYENNES ENTREPRISES", 
                element(3730, "Ministère des Petites et Moyennnes Entreprises" ) ), 
            element(793, "RECHERCHE SCIENTIFIQUE", 
                element(3729, "Ministère de la Recherche Scientifique" ) ), 
            element(795, "RELATION AVEC LE PARLEMENT", 
                element(3733, "Ministère des Relations avec le Parlement" ) ), 
            element(812, "Cour des Comptes", 
                element(3360, "S.G. Cour des Comptes" ) ), 
            element(643, "INTERIEUR ET SECURITE", 
                element(3141, "S.G. Affaires Intérieures,Décentralisation et Sécurité" ), 
                element(3143, "Comité Provincial Equateur" ), 
                element(3147, "Comité Provincial Kinshasa" ), 
                element(3149, "Comité Provincial Nord-Kivu" ), 
                element(3150, "Comité Provincial Oriental" ), 
                element(3151, "Comité Provincial Sud-Kivu" ), 
                element(3152, "Comité Provincial Bandundu" ), 
                element(4186, "Police Nationale Congolaise" ), 
                element(3253, "Ministère de l'Intérieur et Sécurité" ), 
                element(3362, "Commission Electorale Nationale  Indépendante" ), 
                element(3916, "Bandundu" ) ), 
            element(644, "COOPERATION INTERNATIONALE ET REGIONALE", 
                element(3153, "Ministère de la Coopération Internationale et Régionale" ), 
                element(3180, "S.G. Coopération Internationale" ), 
                element(3181, "S.G. Intégration régionale" ) ), 
            element(645, "URBANISME ET HABITAT", 
                element(3154, "S.G. Urbanisme et Habitat" ), 
                element(3375, "Ministère de l'Urbanisme et Habitat" ) ), 
            element(646, "AFFAIRES FONCIERES", 
                element(3155, "Ministère des Affaires Foncières" ), 
                element(3187, "S.G. Affaires Foncières" ) ), 
            element(647, "FONCTION PUBLIQUE", 
                element(3213, "Ministère de la Fonction Publique" ) ), 
            element(648, "AFFAIRES SOCIALES,ACTION HUMANITAIRE ET SOLIDARITE NATIONALE", 
                element(3158, "Ministère des Affaires Sociales,Action Humanitaire et Solidarité Nationale" ), 
                element(3176, "S.G. Affaires Humanitaires" ), 
                element(3177, "S.G. Affaires Sociales" ) ), 
            element(649, "PRIMATURE", 
                element(3159, "Cabinet du Premier Ministre" ), 
                element(3363, "PRIMATURE" ) ), 
            element(650, "AGRICULTURE", 
                element(3160, "Ministère de l'Agriculture" ), 
                element(4210, "Unité Nationale de Coordination de Projet" ), 
                element(3247, "Direction des Voies de Desserte Agricole" ), 
                element(3249, "Service National des Energies Nouvelles" ), 
                element(3250, "S.G. Agriculture, Pêche et Elevage" ) ), 
            element(651, "FINANCES(Trésor public)", 
                element(3162, "S.G. Finances" ), 
                element(3163, "Direction Générale  des Douanes et Assises" ), 
                element(3164, "Direction Générale des Impôts" ), 
                element(3165, "Direction Générale des Recettes Administratives et Domaniales" ), 
                element(3166, "Inspection Générale des Finances" ), 
                element(3167, "Conseil Permanent de la Comptabilite au Congo" ), 
                element(3168, "Ecole Nationale des Finances" ), 
                element(3170, "Banque Centrale du Congo" ), 
                element(3171, "Direction de Gestion de la Dette Publique" ), 
                element(3207, "Ministère des Finances" ) ), 
            element(652, "BUDGET", 
                element(3172, "Ministère du Budget" ), 
                element(3268, "S.G. Budget" ), 
                element(3269, "RENAPI" ) ), 
            element(653, "ECONOMIE NATIONALE et COMMERCE", 
                element(3173, "S.G. Economie" ), 
                element(3174, "S.G. Commerce Extérieur" ), 
                element(3186, "Ministère de l'Economie Nationale et Commerce" ) ), 
            element(654, "COMMUNICATION ET MEDIAS", 
                element(3241, "Haute Autorité des Médias" ), 
                element(3242, "Ministère de la Communication et Médias" ), 
                element(3243, "Radio Télévision Nationale Congolaise" ), 
                element(3244, "Agence Congolaise de Presse" ), 
                element(3245, "Renatelsat" ), 
                element(3807, "S.G. Communications et Médias" ) ), 
            element(655, "CULTURE ET ARTS", 
                element(3178, "Ministère de Culture et Arts" ) ), 
            element(656, "DEFENSE NATIONALE ET ANCIENS COMBATTANTS", 
                element(3183, "Ministère de la Défense Nationale et Anciens Combattants" ), 
                element(3256, "S.G. Défense Nationale" ), 
                element(3257, "S.G. Anciens Combattants" ), 
                element(3866, "Unité d'Exécution du Programme National de Désarmement, Démobilisation et Réinsertion" ) ), 
            element(657, "PORTEFEUILLE", 
                element(3184, "S.G. Portefeuille" ), 
                element(3270, "Ministère du Portefeuille" ) ), 
            element(658, "EMPLOI,TRAVAIL ET PREVOYANCE SOCIALE", 
                element(3188, "Ministère de l'Emploi,Travail et Prévoyance Sociale" ), 
                element(3208, "S.G. Travail" ), 
                element(3209, "Institut National de Sécurité Sociale" ), 
                element(3210, "S.G. Prévoyance Sociale" ), 
                element(3212, "Institut National de Préparation Professionnelle" ) ), 
            element(659, "MINES", 
                element(3189, "S.G. Mines" ), 
                element(3262, "Ministère des Mines" ) ), 
            element(660, "ENERGIE", 
                element(3192, "Ministère de l'Energie" ), 
                element(3230, "S.G. Energie" ), 
                element(3231, "Régie de Distribution d'Eau" ), 
                element(3232, "Société Nationale d'Electricité" ), 
                element(3846, "Unité de coordination et de gestion du projet" ), 
                element(3918, "Cellule d'exécution des projets-Eau" ) ), 
            element(661, "ENSEIGNEMENT SUPERIEUR ET UNIVERSITAIRE", 
                element(3193, "S.G. Enseignement Supérieur et Universitaire" ), 
                element(3194, "S.G. Recherche Scientifique" ), 
                element(3195, "Institut National d'Etudes et des Recherches Agronomiques" ), 
                element(3196, "Centre des Recherches d'Energie Nucléaire" ), 
                element(3197, "Institut Géographique du Congo" ), 
                element(3201, "Ministère de l'Enseignement Supérieur et Universitaire" ), 
                element(4378, "Université de Kinshasa" ), 
                element(4379, "Université de Lubumbashi" ), 
                element(4380, "Université de Kisangani" ), 
                element(4381, "Université Pédagogique Nationale" ) ), 
            element(662, "ENSEIGNEMENT PRIMAIRE,SECONDAIRE ET PROFESSIONNEL", 
                element(4196, "Unité de Coordinnation du Projet/PARSE" ), 
                element(3199, "Ministère de l'Enseignement Primaire,Secondaire et Professionnel" ), 
                element(3261, "S.G. E.P.S.P." ) ), 
            element(663, "GENRE,FAMILLE ET ENFANT", 
                element(3200, "S.G. Condition Féminine et Famille" ), 
                element(3229, "Ministère du Genre,Famille et Enfant" ) ), 
            element(664, "POSTES, TELECOMMUNICATIONS et NOUVELLES TECHNOLOGIES de l'INFORMATION de la COMMUNICATION", 
                element(3202, "S.G. Postes, Téléphones et Télécommunications" ), 
                element(3203, "Service Congolais des Postes et Télécommunications" ), 
                element(3274, "Ministère des Postes, Téléphones et Télécommunications" ) ), 
            element(665, "ENVIRONNEMENT,CONSERVATION DE LA NATURE ET TOURISME", 
                element(4192, "Unité de Coordinnation du Projet PFCN" ), 
                element(3204, "Ministère de l'Environnement,Conservation de la Nature et Tourisme" ), 
                element(3364, "S.G. Environnement et Conservation de la Nature" ), 
                element(3365, "Programme National d'Assainissement" ), 
                element(3366, "Institut des Jardins Zoologique et Botanique du Congo" ), 
                element(3368, "Office National du Tourisme" ), 
                element(3856, "Institut Congolais pour la Conservation de la Nature" ), 
                element(3881, "Service National des Reboisements" ) ), 
            element(666, "Plan et Suivi de Mise en Oeuvre de la Révolution de la Modernité", 
                element(3205, "S.G. Plan" ), 
                element(3267, "Ministère du Plan" ), 
                element(3570, "Unité de Coordination des Projets" ), 
                element(3922, "Institut National de Statistiques" ), 
                element(3923, "Agence Nationale pour la Promotion des Investissements" ) ), 
            element(667, "TRANSPORTS ET VOIES DE COMMUNICATION", 
                element(3214, "S.G. Transports et voies de communication" ), 
                element(3215, "Groupe d'Etude de Transports" ), 
                element(3216, "Organisation pour l'Equipement Banana - Kinshasa" ), 
                element(3217, "Société Nationale des Chemins de Fer du Congo" ), 
                element(3218, "Régie des Voies Aériennes" ), 
                element(3219, "Régie des Voies Fluviales" ), 
                element(3220, "Régie des Voies Maritimes" ), 
                element(3222, "Chemin de Fer des Uélés" ), 
                element(3223, "Lignes Aériennes Congolaises" ), 
                element(3224, "Commission Nationale de Prévention Routière" ), 
                element(3225, "Office National des Transports du Congo" ), 
                element(3227, "Compagnie Maritime du Congo" ), 
                element(3228, "Méteorologie et Télecommunication par Satellite" ), 
                element(3373, "Ministère des Transports et Voies de Communication" ), 
                element(3707, "Commission Internationale du Bassin Congo-Oubangi-Sangha" ) ), 
            element(668, "HYDROCARBURES", 
                element(3234, "Ministère des Hydrocarbures" ), 
                element(3271, "S.G. Hydrocarbures" ), 
                element(3273, "Congolaise des Hydrocarbures" ) ), 
            element(669, "INFRASTRUCTURES, TRAVAUX PUBLICS ET RECONSTRUCTION", 
                element(3236, "Office de Voiries et Drainage" ), 
                element(3237, "S.G. Infrastructures,Travaux Publics et Reconstruction" ), 
                element(3238, "Bureau d'Etudes d'Aménagement et 'Urbanisme" ), 
                element(3239, "Office des Routes (OR)" ), 
                element(3246, "Ministère des Infrastructures,Travaux Publics et Reconstruction" ), 
                element(3844, "Cellule infrastructure" ) ), 
            element(670, "INDUSTRIE", 
                element(3240, "Ministère de l'Industrie" ), 
                element(3370, "S.G. Petites et Moyennes Entreprises" ), 
                element(3371, "Office des Petites et Moyennes Entreprises" ), 
                element(3372, "S.G. Industrie" ) ), 
            element(671, "JEUNESSE ET SPORTS", 
                element(3255, "Ministère de la Jeunesse et Sports" ), 
                element(3376, "S.G. Jeunesse" ), 
                element(3377, "S.G. Sports et Loisirs" ) ), 
            element(672, "DROITS HUMAINS", 
                element(3260, "Ministère des Droits Humains" ), 
                element(3266, "S.G. Justice" ) ), 
            element(673, "PRESIDENCE DE LA REPUBLIQUE", 
                element(4194, "ACGT/Agence Congolaise des Grands Travaux" ), 
                element(3263, "Cabinet du Président de la République" ), 
                element(3327, "Fonds Social de la République Démocratique du Congo" ), 
                element(4374, "Service National" ), 
                element(4375, "Chancellerie des Ordres Nationaux" ), 
                element(3358, "PRESIDENCE DE LA REPUBLIQUE" ) ), 
            element(674, "ASSEMBLEE NATIONALE", 
                element(3264, "PARLEMENT" ), 
                element(3359, "S.G. Assemblée Nationale" ), 
                element(3361, "S.G. Senat" ) ), 
            element(711, "SANTE PUBLIQUE", 
                element(4195, "Unité de Coordinnation du Projet/PARSS" ), 
                element(4382, "Institut National de Recherche Biologique" ), 
                element(3369, "Ministère de la Santé Publique" ), 
                element(3374, "S.G. Santé" ), 
                element(3855, "Programme National Mutlisectoriel de Lutte contre le SIDA" ), 
                element(3865, "Programme national de lutte contre le SIDA" ) ), 
            element(713, "SENAT" ), 
            element(722, "UNITES PARALLELES", 
                element(4190, "Cellule d'Exécution des Projets PMR RH" ), 
                element(3169, "Bureau Central de Coordination" ), 
                element(3413, "Bureau de Coordination des Marchés des Infrastructures" ), 
                element(3591, "Comité Pilote de Réforme des Entreprises Publiques" ) ) ), 
        element(3, "Multilatéral", 
            element(805, "Fonds Mondial de l'Environnement", 
                element(3888, "Global Environment Fund Truste" ) ), 
            element(820, "Union Africaine", 
                element(4209, "Union Africaine" ) ), 
            element(821, "Fonds Monétaire International", 
                element(3325, "Fonds monétaire international" ) ), 
            element(822, "Fonds Mondial Malaria", 
                element(4216, "Fonds mondial malaria (à supprimer)" ) ), 
            element(823, "Fonds Mondial Tuberculose", 
                element(4217, "Fonds mondial tuberculose (à supprimer)" ) ), 
            element(824, "Fonds Mondial", 
                element(4223, "Fonds Mondial" ) ), 
            element(825, "GAVI", 
                element(4221, "The Global Alliance for Vaccination and Immunisation(GAVI)" ) ), 
            element(827, "Fonds International pour le Développement 'Agricole", 
                element(3382, "Fonds International pour le Développement Agricole" ) ), 
            element(695, "Nations Unies", 
                element(4214, "PNUD Trac1.1.2" ), 
                element(4218, "Office International d'Immigration" ), 
                element(3301, "Organisation des Nations Unies" ), 
                element(3302, "Programme des Nations Unies pour le Développement" ), 
                element(3303, "Programme alimentaire mondial" ), 
                element(3304, "Fonds des Nations Unies pour l'enfance" ), 
                element(3305, "Haut Commissariat des Nations Unies pour les Refugiés" ), 
                element(3306, "Organisation des Nations Unies pour l'alimentation et l'agriculture" ), 
                element(3307, "Organisation mondiale de la santé" ), 
                element(3308, "Organisation internationale du travail" ), 
                element(3310, "Fonds des Nations Unies pour la population" ), 
                element(3311, "ONUSIDA/Programme des Nations Unies sur le VIH/SIDA" ), 
                element(3312, "Bureau de coordination des affaires humanitaires des Nations Unies" ), 
                element(3313, "Organisation des Nations Unies pour la science et l'éducation" ), 
                element(3314, "Mission  des Nations Unies pour la Stabilisation et Consolidation de la paix" ), 
                element(3315, "Bureau des Nations Unies pour les services d'Appui aux Projets" ), 
                element(3316, "Fonds de Développement des Nations Unies pour la femme" ), 
                element(3317, "Haut Commissariat des Nations Unies pour les droits humains" ), 
                element(3319, "Fonds des Nations Unies pour la démocratie" ), 
                element(3320, "Programme des Nations Unies pour les établissements humains" ), 
                element(3321, "Fonds d'équipement des Nations Unies (admin PNUD)" ), 
                element(3322, "Organisation des Nations Unies pour le développement industriel" ), 
                element(3324, "Organisation mondiale du commerce" ), 
                element(3385, "PNUD TRAC1.1.1" ), 
                element(3391, "PNUD country co financing CS 11888" ), 
                element(3392, "PNUD PAF - UNAIDS Fund 11940" ), 
                element(3397, "PNUD Programme Cost Sharing 30000" ), 
                element(3398, "PNUD Cost Sharing WB1 30011" ), 
                element(3401, "PNUD cost sharing Gouv 30071" ), 
                element(3403, "PNUD EEC DRC Elections 36204" ), 
                element(3405, "PNUD EEC Sécurité 36207" ), 
                element(3416, "Pooled Fund Humanitaire" ), 
                element(3577, "UNICEF Fonds des Nations Unies pour l'Enfance" ), 
                element(3578, "UNICEF Fonds d'urgence" ), 
                element(3593, "Organisation Internationale pour les Migrations" ), 
                element(3603, "Conférence des Nations Unies sur le commerce et le développement" ), 
                element(3604, "Volontaires des Nations Unies (admin PNUD)" ), 
                element(3605, "Département des opérations de maintien de la paix" ), 
                element(3854, "Central Emergency Reponse Fund (CERF)" ), 
                element(3917, "UNICEF Autres Ressources" ), 
                element(3951, "World Food Programme" ) ), 
            element(696, "Organisation de l'Aviation Civile Internationale" ), 
            element(697, "Organisation Mondiale du Commerce" ), 
            element(699, "Banque Africaine de Développement", 
                element(3357, "Fonds Africain de Développement" ), 
                element(3381, "Banque Africaine de Développement" ), 
                element(3897, "Fonds Forestiers pour le Bassin du Congo" ), 
                element(3899, "Facilité des Etats Fragiles" ) ), 
            element(700, "Banque Mondiale" ), 
            element(701, "Commission Européenne" ), 
            element(702, "Marché Commun d'Afrique Orientale et Australe" ), 
            element(703, "Banque de Développement de Grands Lacs" ), 
            element(705, "Comité pour le Développement de l'Afrique Australe", 
                element(3332, "Comité pour le Développement de l'Afrique Australe" ) ), 
            element(721, "Programme des Nations Unies pour le Développement" ), 
            element(724, "Fonds des Nations Unies pour l'Enfance" ), 
            element(727, "Programme Alimentaire Mondial" ), 
            element(730, "Fonds des Nations Unies pour la Démocratie" ), 
            element(734, "Fonds Mondial contre HIV/SIDA", 
                element(3402, "Fonds Mondial HIV/SIDA (à supprimer)" ) ), 
            element(735, "Fondation pour le Renforcement des Capacités en Afrique", 
                element(3592, "Fondantion pour le Développement des Capacités en Afrique" ) ), 
            element(738, "Organisation Mondiale de la Santé" ), 
            element(739, "Organisation des Nations Unies pour l'Alimentation et l'Agriculture" ), 
            element(742, "Organisation des Nationa Unies pour la Science et l'Education" ), 
            element(744, "Organisation Internationale pour les Migrations" ), 
            element(749, "Ligue des états arabes", 
                element(3562, "Européenne à suprimer" ) ), 
            element(750, "Union Européenne", 
                element(9, "Banque Européenne d'Investissement" ), 
                element(3328, "Commission Européenne" ), 
                element(3344, "Cellule d'appui à l'Ordonnateur  Fonds Européen pour le Développement" ), 
                element(3559, "Office d'aide humanitaire de la Commission européenne" ), 
                element(3584, "Lignes budgétaires Commission Européenne" ), 
                element(3595, "Mission de police de l'Union européenne à Kinshasa" ), 
                element(3596, "Mission de conseil et d’assistance en matière de réforme du secteur de la sécurité en RDC" ) ), 
            element(751, "ONU (entités sous As.gén = CNUCED, PNUE, UNICEF, PNUD, UNIFEM, FNUAP, HCR, PAM, HABITAT, HCDH, UNOPS, ONUSIDA)" ), 
            element(752, "ONU (entités sous ECOSOC hors Groupe Banque Mondiale = OIT, FAO, UNESCO, OMS, FMI, FIDA, ONUDI, OMC)" ), 
            element(753, "ONU (entités sous Secrétariat et Conseil de Sécurité = DAP, DAD, DOMP,/DPKO, BCAH/OCHA, DAES/DESA, MONUSCO)" ), 
            element(754, "Banque Mondiale = BIRD, AID, SFI, TF,AMGI, CIRDI))", 
                element(4193, "Trust Found (Banque Mondiale)" ), 
                element(3349, "SFI/Société financière internationale" ), 
                element(3350, "Banque internationale pour la reconstruction et le développement" ), 
                element(3351, "Association internationale de développement (Banque mondiale)" ), 
                element(3845, "Bureau local RDC" ) ) ), 
        element(4, "Bilatéral", 
            element(768, "Australie", 
                element(3644, "Ministère des Affaires Etrangères d'Australie" ) ), 
            element(6, "Belgique", 
                element(1, "Coopération Technique Belge" ), 
                element(2, "Direction Générale de la Coopération au Développement Belge" ), 
                element(3278, "Ambassade de Belgique" ) ), 
            element(11, "Suisse", 
                element(12, "Direction du Développement et de la Coopération Suisse" ), 
                element(3299, "Ambassade de Suisse" ), 
                element(3913, "Coopération Technique Suisse" ) ), 
            element(12, "ALLEMAGNE", 
                element(3276, "Ambassade d'Allemagne" ), 
                element(3380, "Kredistanst FW" ), 
                element(3454, "Deutsche Gesellschaft Technische Zusammenarbeit" ), 
                element(3891, "Caritas allemagne" ), 
                element(3892, "Ministère de Coopération Economique et du Développement" ), 
                element(3893, "Ministère des Affaires Etrangères Allemande" ) ), 
            element(13, "Royaume-Uni", 
                element(3, "Department for International Development" ), 
                element(3649, "Ambassade de Royaume Uni" ) ), 
            element(14, "Japon", 
                element(4165, "Japan International Cooperation System" ), 
                element(3291, "Ambassade du Japon" ), 
                element(3347, "Agence de Coopération Internationale Japonaise" ) ), 
            element(15, "Norvège", 
                element(10, "Agence Norvégienne de Développement" ), 
                element(3295, "Ambassade de Norvège" ), 
                element(3635, "Ministère des Affaires Etrangères de la Norvège" ) ), 
            element(16, "Pays-Bas", 
                element(3296, "Ambassade des Pays-Bas" ) ), 
            element(17, "Etats-Unis d'Amérique", 
                element(3285, "Ambassade des Etats-Unis d'Amérique" ), 
                element(3342, "Agence Américaine pour le Développement International" ), 
                element(3894, "Center for Disease Control And Prevention" ) ), 
            element(799, "Thailande", 
                element(3853, "Ministère des Affaires Entragères Thailandaise" ) ), 
            element(801, "Albanie", 
                element(3884, "Ministère des Affaires Etrangères d'Albanie" ) ), 
            element(802, "Equateur" ), 
            element(803, "El Salvador" ), 
            element(804, "Kyrgyzstan" ), 
            element(806, "Pologne", 
                element(3914, "Ministère des Affaires Etrangères de Pologne" ) ), 
            element(807, "Portugal" ), 
            element(808, "Chypre" ), 
            element(818, "Russie", 
                element(4191, "Ambassade de Russie" ) ), 
            element(675, "Afrique du Sud", 
                element(3275, "Ambassade d'Afrique du Sud" ) ), 
            element(677, "Autriche", 
                element(3277, "Ambassade d'Autriche" ) ), 
            element(678, "Brésil", 
                element(3279, "Ambassade du Brésil" ) ), 
            element(679, "Canada", 
                element(3280, "Agence Canadienne de Développement International" ), 
                element(4383, "Ministère des Affaires Etrangères,Commerce et Développement" ), 
                element(3677, "Ambassade du Canada" ) ), 
            element(680, "Chine", 
                element(3281, "Ambassade de Chine" ), 
                element(3848, "Coopération technique chinoise" ) ), 
            element(681, "Danemark", 
                element(3634, "Ministères des Affaires Etrangères" ), 
                element(3639, "Ministère des Affaires Etrangères de Danmark" ) ), 
            element(682, "Egypte" ), 
            element(683, "Espagne", 
                element(3284, "Ambassade d'Espagne" ), 
                element(3915, "Agence espagnole de coopération internationale et développement" ) ), 
            element(684, "France", 
                element(3286, "Ambassade de France" ), 
                element(3343, "Agence Française de Développement" ) ), 
            element(685, "Inde", 
                element(3288, "Ambassade de l'Inde" ), 
                element(3594, "Eximbank of India" ) ), 
            element(686, "Israël" ), 
            element(687, "Italie", 
                element(3290, "Ambassade d'Italie" ), 
                element(3601, "Coopération italienne" ) ), 
            element(688, "Koweit" ), 
            element(689, "Libye" ), 
            element(690, "Maroc" ), 
            element(691, "République Démocratique du Congo" ), 
            element(692, "Suède", 
                element(3587, "PMU InterLife" ), 
                element(3588, "LO-TCO Bistandasnämnd" ), 
                element(3589, "Forum Syd" ), 
                element(3660, "Ambassade de Suède" ), 
                element(3867, "Agence Suèdoise Internationale de Développement (ASDI)" ) ), 
            element(694, "Yougoslavie" ), 
            element(725, "Turquie", 
                element(3580, "Agence Turque de développement" ), 
                element(3581, "Ambassade de Turquie" ), 
                element(3582, "Municipalité métropolitaine d'Istanbul" ) ), 
            element(726, "Corée du Sud", 
                element(3583, "Ambassade de la République de Corée" ), 
                element(3882, "Agence Coréenne de Coopération Internationale" ) ), 
            element(761, "Irlande", 
                element(3636, "Ministère des Affaires Etrangères d'Irlande" ) ), 
            element(762, "Finlande", 
                element(3637, "Finlande" ), 
                element(3638, "Ministère des Affaires Etrangères de Finlande" ) ), 
            element(763, "Grèce", 
                element(3640, "Ministère des Affaires Etrangères de la Grèce" ) ), 
            element(765, "République Tchèque", 
                element(3641, "Ministère des Affaires Etrangères de la République Tchèque" ) ), 
            element(766, "Switzerland" ), 
            element(767, "Luxembourg", 
                element(3643, "Ministère des Affaires Etrangères Luxembourg" ) ) ), 
        element(999999999, "Undefined" ), 
        element(7, "Autres / EN VOIE DE SUPPRESSION", 
            element(723, "Pooled Fund (humanitaire)" ), 
            element(760, "Autres", 
                element(3686, "Commission Electorale Indépendante" ), 
                element(3708, "Commission justice et paix belge" ), 
                element(3711, "Damiaanactie" ), 
                element(3713, "Komyuniti cons" ), 
                element(3715, "Port de Bruxelles" ), 
                element(3717, "SHC" ), 
                element(3718, "Solidarité Protestante" ), 
                element(3721, "Vredeseilanden" ), 
                element(3725, "Itineras cons" ), 
                element(3782, "SLCD" ), 
                element(3796, "IITA" ), 
                element(3802, "Protos" ), 
                element(3904, "Fondation Konrad Adenauer" ), 
                element(3905, "IFPRODUCTIONS" ), 
                element(3906, "Le Centre Carter" ), 
                element(3907, "The mines advisory group" ), 
                element(3908, "Stichting Vluchteling" ), 
                element(3926, "UNITED NATIONS VOLUNTEERS" ), 
                element(3927, "UNITED NATIONS DEVELOPMENT PRO" ), 
                element(3928, "UN INDUSTRIAL DEVELOPMENT ORGA" ), 
                element(3929, "UN CENTRE FOR HUMAN SETTLEMENT" ), 
                element(3932, "GOVERNMENT OF BELGIUM" ), 
                element(3933, "International Labour Organisat" ), 
                element(3935, "Intenational Org for Migration" ), 
                element(3936, "International Trade Centre" ), 
                element(3937, "GOVERNMENT OF FRANCE" ), 
                element(3940, "DRC-National Execution" ), 
                element(3941, "GOVERNMENT OF ITALY" ), 
                element(3942, "GOVERNMENT OF JAPAN" ), 
                element(3943, "GOVERNMENT OF LUXEMBOURG" ), 
                element(3944, "GOVERNMENT OF NETHERLANDS" ), 
                element(3945, "GOVERNMENT OF NORWAY" ), 
                element(3947, "UN Dept of Economic and Social" ), 
                element(3948, "UNDP" ), 
                element(3950, "UN Office for Project Services" ), 
                element(3952, "UN Development Programme" ), 
                element(3953, "GOVERNMENT OF SPAIN" ), 
                element(3955, "GOVERNMENT OF SWEDEN" ), 
                element(3956, "GOVERNMENT OF SWITZERLAND" ), 
                element(3957, "Cooperazione Intermazionale" ), 
                element(3959, "GOVERNMENT OF UNITED KINGDOM" ), 
                element(3962, "COD-Conseil National des ONGs" ), 
                element(3967, "EUROPEAN UNION" ), 
                element(3968, "MALTESER" ), 
                element(3969, "SOLIDARITE" ), 
                element(3970, "FOODS FOR HUNGRY INTERNATIONAL" ), 
                element(3972, "NORWEGIAN REFUGEE COUNCIL" ), 
                element(3973, "COD-PROGRAMME PROMOTION SOINS" ), 
                element(3978, "Jesuit Refugee Service" ), 
                element(3979, "LUTHERIAN WORLD FEDERATION" ), 
                element(3980, "Norwegian Chruch Aid" ), 
                element(3984, "UNAIDS" ), 
                element(3985, "MAC ARTHUR FOUNDATION" ), 
                element(3990, "OXFAM GB" ), 
                element(3991, "COD-Bureua Diocesain de Develo" ), 
                element(3995, "Missionnaires du Divin Maitre" ), 
                element(3996, "NGO - WORLD VISION" ), 
                element(3997, "NGO-DAN CHURCH AID" ), 
                element(3998, "NGO-GOAL IRELAND" ), 
                element(3999, "NGO-FONDATION FEMMES PLUS" ), 
                element(4000, "NGO-CRAFOD" ), 
                element(4001, "NGO-Org Catholique d'Aide et d" ), 
                element(4003, "DRC - CARJTAS MANIEMA" ), 
                element(4004, "GLOBAL FUND TO FIGHT AIDS" ), 
                element(4006, "EQUILIBRE" ), 
                element(4007, "GTM-FUNDACION SOLAR" ), 
                element(4008, "COD-GROUP ETUDE ACTION DEVELOP" ), 
                element(4009, "CESADEMA ONG/ASBL" ), 
                element(4010, "OXFAM SOLIDARITES BELGIQUE" ), 
                element(4011, "SERVICE D' APPUI AU DEVELOPPME" ), 
                element(4012, "Multi Action d' Assistances au" ), 
                element(4014, "Institut Saint Joseph" ), 
                element(4016, "Association pour la Protection" ), 
                element(4017, "INTERACTIONS" ), 
                element(4020, "Commission Diocesaine Justice" ), 
                element(4022, "Commission d' Encadrement pour" ), 
                element(4027, "TEARFUNND" ), 
                element(4031, "CROIX ROUGE BELGIQUE" ), 
                element(4032, "VETERINAIRES SANS FRONTIERES" ), 
                element(4035, "CANADIAN INTERNATIONAL DEVELOP" ), 
                element(4036, "DEPARTMENT FOR INT'L DEVELOPME" ), 
                element(4039, "MONTREAL PROTOCOL" ), 
                element(4042, "UN DEMOCRACY FUND (UNDEF)" ), 
                element(4043, "ORG. INTERNATIONALE DE LA FRAN" ), 
                element(4044, "SPAIN MDG FUND" ) ) ), 
        element(8, "Groupe Thématique et Autres Orgs.", 
            element(774, "GT2 Gouvernance politique et administrative" ), 
            element(775, "GT3 Medias et culture" ), 
            element(776, "GT4 Gouvernance économique", 
                element(3665, "GT4 Groupe gouvernance économique" ) ), 
            element(777, "GT5 Infrastructures et transport", 
                element(3666, "GT5 Groupe infrastructures et transport" ) ), 
            element(778, "GT6 Energie" ), 
            element(779, "GT7 Mines et hydrocarbures" ), 
            element(780, "GT8 Agriculture et développement rural", 
                element(3669, "GT8 Groupe agriculture et développement rural" ) ), 
            element(781, "GT9 Industries et services" ), 
            element(782, "GT16 Education et Recherche Scientifique", 
                element(3671, "GT16 Education et Recherche Scientifique" ) ), 
            element(783, "GT11 Santé" ), 
            element(784, "GT12 Protection sociale, genre et pauvreté" ), 
            element(785, "GT13 Environnement, eau et assainissement" ), 
            element(786, "GT14 VIH/SIDA" ), 
            element(787, "GT15 Dynamique communautaire" ), 
            element(712, "GT1 Gouvernance judiciaire et sécuritaire", 
                element(3378, "Education" ) ) ), 
        element(9, "Secteur Privé Lucratif", 
            element(755, "Entreprises de secteur primaire (production)", 
                element(4173, "Investissement privé émiratie" ), 
                element(4174, "Investissement privé gilbratar" ), 
                element(4175, "Investissement privé turque" ), 
                element(4176, "Investissement privé bahaméen" ), 
                element(4177, "Investissement privé luxembourgois" ), 
                element(4178, "Investissement privé hellenique" ), 
                element(4179, "Investissement privé ukrainien" ), 
                element(4180, "Investissement privé pakistanais" ), 
                element(4181, "Investissement privé nigérian" ), 
                element(4182, "Investissement privé centrafricain" ), 
                element(4183, "Investissement privé guernesey" ), 
                element(4184, "Investissement privé ghanéen" ), 
                element(4185, "Investissement privé néerlandais" ), 
                element(4188, "Investissemement privé camerounais" ), 
                element(4189, "Investissemement privé tanzanien" ), 
                element(3608, "Investissement privé américain" ), 
                element(3609, "Investssement privé autrichien" ), 
                element(3610, "Investissement privé belge" ), 
                element(3611, "Investissemnt privé béninois" ), 
                element(3612, "Investissement privé britanique" ), 
                element(3613, "Investissement privé canadien" ), 
                element(3614, "Investissement privé chinois" ), 
                element(3615, "Investissement privé allemand" ), 
                element(3616, "Investissement privé français" ), 
                element(3617, "Investissement privé gambien" ), 
                element(3618, "Investissement privé indien" ), 
                element(3619, "Investissement privé israëlien" ), 
                element(3620, "Investissement privé italien" ), 
                element(3621, "Investissemement privé libanais" ), 
                element(3622, "Investissement privé portugais" ), 
                element(3623, "Investissement privé sénégalais" ), 
                element(3624, "Investissement privé sud africain" ), 
                element(3625, "Investissement privé sud coréen" ), 
                element(3626, "Investissement privé swazilandais" ), 
                element(3627, "Investissement privé togolais" ), 
                element(3628, "Investissement privé zambien" ), 
                element(3629, "Investissement privé mauricien" ), 
                element(3630, "Investissement privé congolais" ) ), 
            element(758, "Entreprises de secteur secondaire (transformation)" ), 
            element(759, "Entreprises de secteur tertiaire (services)" ) ), 
        element(10, "Société Civile (hors ASBL et EUP)", 
            element(715, "Syndicats" ), 
            element(716, "Académies (enseignement et recherche)", 
                element(3703, "Université de Bercelona" ) ), 
            element(717, "Groupements communautaires / villageois" ), 
            element(719, "Populations non organisées en groupe", 
                element(4054, "Pesonnes âgées" ), 
                element(4056, "Réfugiés politiques" ) ) ), 
        element(11, "Association sans but lucratif", 
            element(771, "ONG nationale humanit. / développement enregistrée au Plan", 
                element(3337, "Centre Intégré de Bwamanda" ), 
                element(3428, "ASSOCIATION POUR LA SANTE FAMILIALE" ), 
                element(3538, "Action pour la Paix, l'éducation et le Développement" ), 
                element(3541, "Action pour le Développement et la Paix Endogènes" ), 
                element(3565, "Association pour le Développement Social et la Sauvegarde de l'Environnement" ), 
                element(3566, "Association Provinciale pour l'Approvisionnement enMédicaments Essentiels au Sud-Kivu" ), 
                element(3567, "Association Régionale d'Approvisionnement en Médicaments Essentiels" ), 
                element(3568, "Avenir Meilleur pour les Orphelins du Congo" ), 
                element(3659, "Centre Congolais de Culture , de Formation et de Développement" ), 
                element(3706, "Africa Parks" ), 
                element(3716, "Rotary Belgique" ), 
                element(3720, "Trias" ), 
                element(3724, "FOMETRO" ), 
                element(3785, "Bureau Diocesain des Oeuvres Médicales" ), 
                element(3797, "Centre Bethanie" ), 
                element(3837, "Coopération de Plantation et d'élevage de LUIZA" ), 
                element(3864, "FOLECO" ), 
                element(3871, "ANES-Congo" ), 
                element(3963, "Association de Sante Familiale" ), 
                element(4034, "Caritas  Uvira" ), 
                element(4078, "KOREA INTERNATIONAL VOLUNTEER ORGANIZATION" ), 
                element(4091, "Action Bio" ), 
                element(4092, "Avenir Congo" ) ), 
            element(772, "ONG nationale humanit. / développement non enregistrée au Plan", 
                element(4102, "Koninklijk Museum voor Midden-Afrika in Tervuren" ), 
                element(4103, "SOS Kinderdorp - België help de wereld" ), 
                element(4104, "Frères des Hommes" ), 
                element(4105, "Vlaams Internationaal Centrum" ), 
                element(4106, "Dokters van de Wereld" ), 
                element(4109, "Petits Pas" ), 
                element(4112, "Caritate Aegrorum Servi" ), 
                element(4114, "Vrijwilligers voor het Onderwijs - VRIJOND" ), 
                element(3534, "Action contre la pauvreté" ), 
                element(3537, "Action pour Enfants Oubliés" ), 
                element(3909, "Action de carême" ), 
                element(4019, "Action pour le Bien-Etre Commun" ), 
                element(4024, "Accompagnement Technique pour" ) ), 
            element(797, "ONG de Développement et Humanitaire", 
                element(3960, "Adventist Develop&amp;Relief Agenc" ), 
                element(3976, "ACTION CONTRE LA FAIM" ), 
                element(4018, "Action Contre la Pauvrete" ) ), 
            element(809, "Association économique , sociale et culturelle", 
                element(3903, "University of Guelph" ), 
                element(3910, "Entraide prot. Suisse" ) ), 
            element(811, "Bénéficiaire" ), 
            element(714, "ONG étrangère humanit. / dével. enregistrée au Plan", 
                element(4349, "Non-Governmental Organisations (NGOs) and Civil Society" ), 
                element(3333, "Save the Children UK" ), 
                element(3334, "International Rescue Committee" ), 
                element(3336, "OXFAM" ), 
                element(3415, "ACTED" ), 
                element(3419, "AFRICA CONSERVATION FUND" ), 
                element(3421, "Agence Européenne pour le Développement" ), 
                element(3422, "AGRO ACTION ALLEMANDE" ), 
                element(3423, "AIDE MEDICALE INTERNATIONALE" ), 
                element(3424, "AIR SERV INTERNATIONALE" ), 
                element(3430, "Associazione Volntarin Per  Il Servizio Internazionale" ), 
                element(3433, "Aviation sans frontière Belgique" ), 
                element(3434, "Aviation sans frontière Française" ), 
                element(3435, "BUREAU INTERNATIONAL CATHOLIQUE POUR L'ENFANCE" ), 
                element(3437, "CARITAS" ), 
                element(3438, "CARITAS INTERNATIONAL-BELGIQUE" ), 
                element(3439, "CARITAS INTERNATIONALIS" ), 
                element(3440, "CARITAS DEVELOPPEMENT" ), 
                element(3441, "CATHOLIC ORGANIZATION FOR RELIEF AND DEVELOPEMENT AID" ), 
                element(3442, "Catholic Relief Services" ), 
                element(3443, "CENTRE SCIENTIFIQUE ET MEDICAL DE L'UNIVERSITE LIBRE DE BRUXELLES POUR SES ACTIVITES DE COOPERATION" ), 
                element(3444, "CENTRES SOCIAUX SANITAIRES -CONGO" ), 
                element(3445, "CHRISTIAN AID" ), 
                element(3448, "COMITATO INTERNAZIONALE PER DE SVILUPPO DEI POPULI" ), 
                element(3450, "CONCERN WORLD WIDE" ), 
                element(3451, "COOPERAZIONE E SVILUPPO" ), 
                element(3453, "Norway Red Cross" ), 
                element(3458, "EQUILIBRE DE L'AIDE D'URGENCE AU DEVELOPPEMENT COMMUNAUTAIRE" ), 
                element(3459, "Family Health International" ), 
                element(3463, "Fonds Médical Tropical" ), 
                element(3466, "Global rights" ), 
                element(3467, "Goal Ireland" ), 
                element(3468, "Groupe de Recherche et d'Echanges Technologiques" ), 
                element(3469, "Groupe de Recherche et d'action sur le développement durable et le développement économique durable" ), 
                element(3470, "Handicap International- Belgique" ), 
                element(3471, "Handicap International/Atlas Logistique" ), 
                element(3472, "Heal Africa" ), 
                element(3474, "Human Rights Watch" ), 
                element(3475, "ICCO" ), 
                element(3478, "International Foundation for Education and Self-Help" ), 
                element(3483, "Johanniter International Assistance" ), 
                element(3486, "Life and Peace Institute" ), 
                element(3488, "Louvain Développement" ), 
                element(3489, "Lutheran World Federation" ), 
                element(3490, "Malteser International" ), 
                element(3491, "Medecins du Monde-Belgique" ), 
                element(3492, "Medecins du Monde -France" ), 
                element(3493, "Medecins sans Frontières-Belgique" ), 
                element(3495, "Medecins sans Frontières-France" ), 
                element(3498, "Medical Emergency Relief International" ), 
                element(3500, "Medicus Mundi Navarra" ), 
                element(3501, "Mercy Corps" ), 
                element(3502, "Groupe contre les mines" ), 
                element(3504, "Norwegian Church Aid" ), 
                element(3505, "Norwegian Refugee Council" ), 
                element(3506, "Oxfam-Grande-Bretagne" ), 
                element(3507, "Oxfam-Quebec" ), 
                element(3508, "Oxfam-Solidarité Belgique" ), 
                element(3509, "Pact Building Capacity Worldwide" ), 
                element(3513, "Pmu Interlife" ), 
                element(3514, "Première Urgence" ), 
                element(3515, "Programme International de Conservation des Gorilles" ), 
                element(3516, "RCN Justice&Démocratie" ), 
                element(3517, "Search For Common Ground" ), 
                element(3519, "Solidarité aide humanitaire d'urgence" ), 
                element(3521, "Tearfund" ), 
                element(3523, "The National Democratic Institute for International Affairs" ), 
                element(3524, "TRIAS VZW" ), 
                element(3527, "Vision Environnement et Développement Communautaire" ), 
                element(3529, "Widelife Conservation Society" ), 
                element(3530, "Woman for women International" ), 
                element(3531, "World Vision International" ), 
                element(3532, "World Wide Fund for Nature" ), 
                element(3544, "AIDES" ), 
                element(3571, "AEDES" ), 
                element(3572, "CREDES" ), 
                element(3573, "MEDAIR" ), 
                element(3574, "NOVIB-OXFAM" ), 
                element(3575, "FEDECAME" ), 
                element(3576, "ACDLg" ), 
                element(3633, "Comité International de la Croix Rouge" ), 
                element(3645, "Deutsche Welthungerhilf e.v." ), 
                element(3646, "International Federation of Red Cross and Red Crescent Societies" ), 
                element(3647, "International Committee of the Red Cross" ), 
                element(3648, "Danchurchaid" ), 
                element(3651, "Médécin Sans Frontière" ), 
                element(3653, "Véterinaire Sans Frontières" ), 
                element(3655, "COOPERA" ), 
                element(3657, "Matres Mundi" ), 
                element(3658, "Fundacion Albihar" ), 
                element(3678, "CEBA" ), 
                element(3680, "Care Canada" ), 
                element(3682, "Terre sans Frontière" ), 
                element(3685, "OCCDP" ), 
                element(3687, "ACCC" ), 
                element(3688, "World Vision Canada" ), 
                element(3689, "AUCC" ), 
                element(3690, "United Nations Mine Action Service" ), 
                element(3691, "UNEP" ), 
                element(3692, "UICN" ), 
                element(3693, "Organization Navarra de Ayuda entre los Pueblos" ), 
                element(3694, "Fondacion Internacional de Solidaridad Compania de Maria" ), 
                element(3696, "Missionnaires Claretiennes" ), 
                element(3697, "Fondation pour la Promotion Sociale de la Culture" ), 
                element(3698, "Fundation IEPALA" ), 
                element(3700, "Federacion de Asociaciones Meddicus Mundi en Espagne" ), 
                element(3701, "Don Bosco" ), 
                element(3702, "Asociacion Ayuda a Los Desempleados Del Tercer Mundo" ), 
                element(3704, "CIF Santé" ), 
                element(3709, "Croix Rouge Belge" ), 
                element(3712, "Enfance Tiers Monde" ), 
                element(3728, "Carter Center" ), 
                element(3738, "Various" ), 
                element(3739, "World Health Organisation" ), 
                element(3740, "World Vision" ), 
                element(3741, "SECID" ), 
                element(3743, "International Polio Virus Response" ), 
                element(3744, "PAGE" ), 
                element(3745, "Population Service International" ), 
                element(3746, "Safe Blood for Africa Foundation" ), 
                element(3747, "Search Common Ground" ), 
                element(3749, "Agence d'aide à la Coopération Tecnhique et au Développement" ), 
                element(3754, "SNV Organisation Néerlandaise de Développement" ), 
                element(3756, "MEDICUS MUNDI BIZKAIA" ), 
                element(3757, "Education Développement Center, Inc" ), 
                element(3761, "South-East Consortiun for International Développement" ), 
                element(3763, "Avocats sans frontières" ), 
                element(3764, "German Agro Action" ), 
                element(3766, "Forum Sociale Deutsch-Land KONGO e.v" ), 
                element(3772, "Electoral Institule of Southeren Africa" ), 
                element(3774, "Solidarité Socialiste" ), 
                element(3776, "Atlas Logistique" ), 
                element(3778, "Action Médicale Missionnaire Belgique" ), 
                element(3779, "Healthnet International" ), 
                element(3780, "Innovative Recourses Management" ), 
                element(3787, "Careas" ), 
                element(3789, "Association de Coopération et de Recherches pour le Développement" ), 
                element(3793, "Food for The Hungry International" ), 
                element(3794, "Avocats Sans Frontières Belgique" ), 
                element(3795, "Interchurch Medical Assistance" ), 
                element(3800, "Armée du Salut" ), 
                element(3801, "African Wildlife Foudation" ), 
                element(3803, "Action contre la faim" ), 
                element(3814, "Msaada et Solidarité Internationale pour la Promotiondes Energies Renouvelables dans le tiers Monde" ), 
                element(3818, "BROEDERLIJK DELEN" ), 
                element(3819, "DIAKONIA" ), 
                element(3822, "Abt Associates" ), 
                element(3877, "CDI BWAMANDA" ), 
                element(3879, "Action Damien" ), 
                element(4028, "Association africaine de défense des Droits de l'Homme" ) ), 
            element(718, "Associations confessionnelles", 
                element(4377, "Commission Episcopale Nationale Congolaise" ), 
                element(3710, "Conférence épiscopale" ), 
                element(3912, "Commission épiscopale" ), 
                element(4045, "001981" ) ), 
            element(748, "ONG étrangère humanit. / dévelop. non enregistrée au Plan", 
                element(4096, "Association des Rotary clubs belges pour la coopération au développement" ), 
                element(4098, "Internationale Medische Samenwerking (ex AZV_MSV Artsen Zonder Vakantie)" ), 
                element(4099, "Vereniging voor Technische Samenwerking - TRIAS" ), 
                element(4100, "Katholiek Beurzenfonds voor Afrikanen" ), 
                element(4101, "UniverSud Liège (ex-ACDLg/ACDST)" ), 
                element(4107, "Kinderen Derde Wereld - KDW/ETM" ), 
                element(4116, "GROUPE ONE" ), 
                element(4120, "APEFE - Association pour la Promotion de l'Education et de la Formation à l'Etranger - APEFE" ), 
                element(4126, "CIAT - International Center for Tropical Agriculture - CGIAR - PRT" ), 
                element(4128, "Conseil Interuniversitaire de la Communauté française de Belgique" ), 
                element(4129, "DGD" ), 
                element(4133, "ICRAF International Council for Research in Agro-Forestry - CGIAR - PRT" ), 
                element(4136, "Internationaal Comité Rode Kruis (niet-Belgische afdeling) - ICRC/CICR - PRT" ), 
                element(4137, "International Centre for Transitional Justice" ), 
                element(4147, "Service Laïque de Coopération au Développement" ), 
                element(4160, "VZW CAP SANTE" ), 
                element(4167, "Paul Carlson Partnership" ), 
                element(4168, "Intrenational  Resources Group lt" ), 
                element(4169, "IBRD(Emergency response to cassava mosaic outbr)" ), 
                element(4170, "Program for Apporpriate Technology in Health (PATH)" ), 
                element(4297, "Medical Care Development International" ), 
                element(3335, "Action contre la faim USA" ), 
                element(3348, "Diakonie" ), 
                element(3436, "POPULATION MEDIA CENTER" ), 
                element(3456, "DOCTORS ON CALL FOR SERVICE" ), 
                element(3558, "Canadian Catholic Organization for Development and Peace" ), 
                element(3695, "Soeurs de Sainte Marie de Matadi" ), 
                element(3699, "Comite International de RESCATE" ), 
                element(3705, "ALBOAN" ), 
                element(3719, "SOS Faim" ), 
                element(3722, "WSM" ), 
                element(3723, "NGO Solidarité Socialiste - FCD" ), 
                element(3726, "Management Science for health" ), 
                element(3727, "UNCODED" ), 
                element(3748, "Georgetown Unversity" ), 
                element(3783, "11.11.11" ), 
                element(3784, "BD" ), 
                element(3798, "Internews Network" ), 
                element(3874, "ERAIFT" ), 
                element(3920, "Johanniter" ), 
                element(3921, "Franziskaner" ), 
                element(3931, "Consortuin CCICD-CHUM" ), 
                element(3954, "Winrock international" ), 
                element(3958, "Development & training service" ), 
                element(3964, "John Snow inc" ), 
                element(3965, "World Hope International" ), 
                element(3966, "COLLABORATION SANTE INTERNATIONAL" ), 
                element(3971, "MINES ADVISORY GROUP" ), 
                element(3974, "Tetra Technic DPK" ), 
                element(3975, "CRC Sogema" ), 
                element(3982, "Air Services" ), 
                element(3983, "Development alternatives incorporated" ), 
                element(3986, "Organisation de Cooperation etde Développement Economique" ), 
                element(3987, "Vlaamse Interuniversitaire Raad" ), 
                element(3988, "Jane Goodall Institute for Wildlife Research, Education and Conservation" ), 
                element(3989, "CCISD/USI" ), 
                element(3993, "Action Agro Allemande" ), 
                element(3994, "RESULT BASED MANAGEMENT GROUP (a division of 3186687 canada inc)" ), 
                element(4005, "University of North Carolina" ), 
                element(4013, "War Child Canada" ), 
                element(4015, "Collaboration Santé Internationale" ), 
                element(4021, "New York University" ), 
                element(4023, "Caritas Allemagne" ), 
                element(4025, "Engender heath" ), 
                element(4026, "Action Aid International DRC" ), 
                element(4030, "Groupe Consultation CCISD et MIR" ), 
                element(4038, "Global Witness" ), 
                element(4040, "Research Triangle Institute" ), 
                element(4094, "CHAKA (ADG Gembloux - CODEART - ISF) - CHAKA" ), 
                element(4095, "VZW / civ.mij  : onbepaald" ) ) ), 
        element(12, "Etablissement d'Utilité Publique", 
            element(814, "Philanthropique", 
                element(4002, "MEMISA BELGIQUE" ) ), 
            element(815, "Scientifique" ), 
            element(816, "Artistique" ), 
            element(817, "Pédagogique", 
                element(3992, "Université Protestante du Congo" ), 
                element(4041, "Université Catholique de Kinshasa" ) ) ), 
        element(14, "A spécifier", 
            element(810, "A spécifier", 
                element(4049, "A spécifier" ), 
                element(4062, "A préciser" ) ), 
            element(826, "A préciser" ) ), 
        element(15, "Provincial", 
            element(819, "Provincial", 
                element(4197, "Province de Kinshasa" ), 
                element(4198, "Province du Nord Kivu" ), 
                element(4199, "Province du Bas-Congo" ), 
                element(4200, "Province du Sud Kivu" ), 
                element(4201, "Province de l'Equateur" ), 
                element(4202, "Province Orientale" ), 
                element(4203, "Province du Kasai Occidental" ), 
                element(4204, "Province du Kasai Oriental" ), 
                element(4205, "Province du Katanga" ), 
                element(4206, "Province de Maniema" ), 
                element(4207, "Province de Bandundu" ), 
                element(4208, "Administration centrale" ), 
                element(4211, "Province Nationale" ), 
                element(4224, "Province Administration Centrale" ) ) ), 
        element(16, "FUND", 
            element(999999999, "Undefined", 
                element(0, null ), 
                element(4345, "Joint United Nations Programme on HIV/AIDS" ), 
                element(4346, "Journal Transaction" ), 
                element(4350, "Other." ), 
                element(4352, "Population Services International" ), 
                element(4355, "Staff Member" ), 
                element(4359, "Third Country Government (Delegated co-operation)" ), 
                element(4363, "United Nations agency, fund or commission (UN)" ), 
                element(4364, "United Nations Children’s Fund" ), 
                element(4369, "University, college or other teaching institution, research institute or think-tank" ) ) ));
    }
}

