package org.dgfoundation.amp.nireports.testcases.drc.dimensions;

import org.dgfoundation.amp.nireports.testcases.HNDNode;
import org.dgfoundation.amp.nireports.testcases.HardcodedNiDimension;

import java.util.Arrays;
import java.util.List;

import static org.dgfoundation.amp.nireports.testcases.HNDNode.element;

public class ProgramsTestDimension extends HardcodedNiDimension {

    public ProgramsTestDimension(String name, int depth) {
        super(name, depth);
    }

    public final static ProgramsTestDimension instance = new ProgramsTestDimension("progs", 5);

    @Override
    protected List<HNDNode> buildHardcodedElements() {
        return Arrays.asList(
        element(12, "OBJECTIFS DU MILLÉNAIRE POUR LE DÉVELOPPEMENT - OMD", 
            element(13, "OBJECTIF 1 - Réduction de l'extrême pauvreté et de la faim", 
                element(271, "Cible 1A: Réduire de moitié, entre 1990 et 2015, la proportion de la population dont le revenu est inférieur à un dollar par jour" ), 
                element(272, "Cible 1B: Assurer le plein-emploi et la possibilité pour chacun,  y compris les femmes et les jeunes de trouver  un travail décent et productif" ), 
                element(380, "Cible 1C: Réduire de moitié, entre 1990 et 2015, la proportion de la population qui souffre de la faim" ) ), 
            element(14, "OBJECTIF 2 - Assurer l'éducation primaire pour tous", 
                element(273, "Cible 2.A: D'ici à 2015, donner à tous les enfants, garçons et filles, les moyens d'achèver un cycle complet d'études primaires" ) ), 
            element(15, "OBJECTIF 3 - Promouvoir l'égalité des sexes et l'autonomisation des femmes", 
                element(390, "Cible 3A: Eliminer les disparités entre les sexes dans les enseignements primaires et secondaires d'ici à 2005 si possible et à tous les niveaux de l'enseignement en 2015 au plus tard" ) ), 
            element(16, "OBJECTIF 4 - Réduire la mortalité infantile", 
                element(382, "Cible4A.  Réduire de deux tiers, entre 1990 et 2015, le taux de mortalité des enfants de moins de 5 ans" ) ), 
            element(17, "OBJECTIF 5 - Améliorer la santé maternelle", 
                element(383, "Cible 5A.  Réduire de trois quarts, entre 1990 et 2015, le taux de mortalité maternelle" ) ), 
            element(18, "OBJECTIF 6 - Combattre le VIH/sida, le paludisme et d'autres maladies", 
                element(384, "Cible 6A.  D’ici à 2015 avoir stoppé la propagation du VIH/SIDA et commencé à inverser la tendance actuelle" ), 
                element(385, "Cible 6B. D’ici à 2015, avoir maîtrisé le paludisme et d’autres maladies, et avoir commencé à inverser la tendance actuelle" ) ), 
            element(19, "OBJECTIF 7 - Assurer un environnement durable", 
                element(386, "Cibles 7A. Intégrer les principes du développement durable dans les politiques nationales, inverser la tendance actuelle à la  déperdition de ressources environnementales" ), 
                element(387, "Cible 7B. Réduire de moitié, d’ici à 2015, le pourcentage de la population qui n’a pas accès de façon durable à un approvisionnement en eau de boisson salubre et à des services d’assainissement de base" ), 
                element(388, "Cible 7C.  Réussir, d’ici à 2020, à améliorer sensiblement la vie d’au moins 100 millions d’habitants de taudis" ) ), 
            element(20, "OBJECTIF 8 - Mettre en place un partenariat mondial pour le développement", 
                element(389, "Cible 8D. Traiter globalement le problème de la dette des pays en développement par des mesures d’ordre national et international propres à rendre leur endettement viable à long terme" ) ), 
            element(217, "Hors OMDs" ) ), 
        element(21, "PAP 2007 2008", 
            element(35, "Pilier 1. Bonne Gouvernance", 
                element(36, "Sécurité", 
                    element(50, "0a. Les rôles et les missions des institutions du secteur sécurité sont clarifiés", 
                        element(51, "1.1.1. Adoption de la loi organique définissant le rôle et la mission des institutions impliquées dans le secteur" ), 
                        element(52, "1.1.2.   Adoption des textes relatifs à la création du Conseil Supérieur de la police nationale et de l’inspectorat général des services" ) ), 
                    element(53, "0b. Les mesures visant le contrôle parlementaire, de la société civile et budgétaire du secteur sont en place" ), 
                    element(54, "1. La PNC est réformée et transformée en une structure professionnelle et unifiée, soutenue par un cadre légal cohérent", 
                        element(55, "1.1.1- Mise en place du Comité de Suivi et poursuite de travail en groupe sur la base d’un programme de travail" ), 
                        element(56, "1.2.1- Lancement du programme de formation de la police, y inclus une orientation en matière de justice" ), 
                        element(57, "1.2.2- Utilisation à 50 % de leur capacité des écoles de formation de la police" ), 
                        element(58, "1.2.3- Installation et équipement des policiers formés dans leurs unités" ), 
                        element(59, "1.2.4- Adoption de la loi organique de la police, comprenant des dispositions sur la police de proximité" ), 
                        element(60, "1.2.5- Mise en place d’une gestion transparente du budget alloué à la police" ), 
                        element(61, "1.4.1 -  Opérationnalisation des unités de la Police dans les grands centres urbains" ), 
                        element(62, "1.5.1- Finalisation du recensement de la police" ) ), 
                    element(63, "2. Les FARDC sont réformées et transformées en une structure professionnelle et unifiée, soutenue par un cadre légal cohérent afin de protéger les civils", 
                        element(64, "2.1.1- Finalisation du recensement et des audits du secteur, et  mise en œuvre des recommandations prioritaires" ), 
                        element(65, "2.1.2 Restructuration  de la chaîne de paiement" ), 
                        element(67, "2.1.3- Développement et opération-nalisation du système de fichier des salaires" ), 
                        element(68, "2.2.1- Equipement des brigades intégrées en matériels" ), 
                        element(69, "2.3.1-   Finalisation des brassages" ) ), 
                    element(66, "3. Le système judiciaire est réformé et réorganisé en concordance avec la nouvelle Constitution" ) ), 
                element(42, "Transparence et efficacité dans la gestion des finances publiques", 
                    element(73, "1. Augmentation des revenus du gouvernement et réforme de la procédure budgétaire en accord avec les normes internationales", 
                        element(76, "1.1.1. Promulgation du code minier" ), 
                        element(77, "1.2.1. Respect du cycle budgétaire" ), 
                        element(78, "1.2.2.Mise en place et opérationnalisation du fichuer  global des salaires" ), 
                        element(79, "Adoption d'un plan d'action triennal pour améliorer la préparation, l'exécution et le contrôle du budget" ) ), 
                    element(80, "Contrôle des dépenses publiques par le gouvernement et des structures indépendantes", 
                        element(81, "2.1.1. Elaboration d'un plan triennal de réofrme des finances publiques identifiants notamment" ), 
                        element(82, "2.2.1.Mise en place d'une chaîne améliorée des dépenses publiques" ), 
                        element(83, "2.2.2. Revue du système de suivi et d'élaboration de rapports des dépenses publiques" ), 
                        element(84, "2.3.1. Adoption de la loi sur la passation des marchés" ), 
                        element(85, "2.4.1. Elaboration et diffusion des différentes publication ci-après : l'audit de la banque centrale, l'étude de la cour des comptes sur l'exécution budgétaire biannuelle, les rapports trimestriels sur l'exécution du budget à soumettre au parlement" ), 
                        element(86, "2.5.1. Mise en place d'une commission anti-blanchissement d'argent" ), 
                        element(87, "2.5.2. Mise en place et opérationnalisation d'un système de contrôle des affaires de corruption, et publication des conclusions et recommandations" ), 
                        element(88, "2.5.3. Revue des dépenses publiques dans  des secteurs clés, dont les secteurs de la santé et de l'éduction" ), 
                        element(89, "2.6.1. lLancement du renforcement des capacités des services provinciaux impliqués dans l'élaboration, l'exécution et le suivi du budget" ) ) ), 
                element(44, "Gestion des ressources naturelles", 
                    element(92, "1. Les ressources naturelles sont gérées d'une manière durable sur la base des codes légaux" ) ), 
                element(45, "Réforme de l'administration publique" ), 
                element(46, "Gouvernance locale", 
                    element(102, "1.Les systèmes fiduciaires sont mis en place sur le plan local et provincial et les capacités de prestation de services sociaux sont renforcées, sur base d'un cadre juridique cohérent" ) ), 
                element(47, "Climat des investissements et réformes des entreprises publiques", 
                    element(103, "1. La législation en faveur des investissements est établie avec ses cadres de travail et les entreprises publiques sont restructurées et reformées en accord avec les standards internationaux", 
                        element(104, "1.1.1. Publication du premier rapport sur la réforme bancaire" ), 
                        element(105, "1.2.1. Adoption d'un plan d'action stratégique pour la réforme des entreprises publiques" ), 
                        element(106, "1.3.1. Signature d'un contrat/bail de gestion pour le port de matadi entre l'onatra et une entreprise privée" ), 
                        element(107, "1.3.2.Signature d'un contrat/bail de gestion pour les chemins de fer entre la SNCC et une entreprise privée" ), 
                        element(108, "1.3.3. Publication du premier rapport sur la réforme des utilités publiques (électricité et eau)" ), 
                        element(109, "1.4.1. Signature du décret présidentiel d'adhésion et l'ohada et adoption des mesures d'application de ce décret" ), 
                        element(110, "1.4.2. Développement d'une stratégie et d'un plan d'actions pour leverles obstacles et autres contraintes au développement du secteur privé, sur la base de l'évaluation du climat d'affaires (ICA) et du rapport 'doing businesss'" ), 
                        element(379, "1.4.2. Développement d'une stratégie et d'un plan d'actions pour lever les obstacles et autres contraintes au développement du secteur privé, sur la base de l'évaluation du climat d'affaires (ICA) et du rapport 'doing business'" ), 
                        element(381, "1.4.1. Signature du décret présidentiel d'adhésion à  l'OHADA et adoption des mesures d'application de ce décret" ) ) ) ), 
            element(40, "Pilier 2. Croissance Pro-Pauvre", 
                element(48, "Transport", 
                    element(111, "1.La structure de transpoprt est réhabilitée, les entreprises de transport étatiques et privées sont reformées et les investissments dans le secteur sont priorisés", 
                        element(112, "1.1.1.Adoption de la loi portant sur la protection du patrimoine routier et création d'un fonds d'entretien routier  de deuxième génération" ), 
                        element(113, "1.1.2. Réhabilitation de 1.000 Km de routes nationales bitumées sur le réseau prioritaire : likasi-lubumbashi (120 kms), kimbangu-tshela (99 kms), kengue-batshamba (344 kms), boucle-kinshasa (upn-NSELE/Pont 90 kms), matadi-kinshasa" ), 
                        element(114, "1.1.3. Réalisation des études de faisabilité pour 65 kilomètres de voirie" ), 
                        element(115, "1.1.4. Réhabilitation de 190 kilomètres de voirie" ), 
                        element(129, "1.1.5. Réhabilitation de pistes rurales (le nombre de kms de pistes rurales à réhbiliter sera précisé da,s le plan de mise en oeuvre du PAP)" ), 
                        element(130, "1.1.6. Réouverture de 2,000 kilomètres de routes en terre du réseau national prioritaire" ), 
                        element(131, "1.1.7.Reconnnecter au moins 18 villes principales (incluant les chefs lieux des provinces) à leur hinterland dans un rayon de 40 kilomètres" ), 
                        element(132, "1.1.8. Entretien  de pistes rurales (le nombre de kms de pistes rurales à entretenir sera précisé dans le plan de mise en oeuvre du PAP)" ), 
                        element(133, "1.1.9. Entretien régulier d'u moins 3.000 kilomètres de réseau national prioritaire" ), 
                        element(134, "1.1.10. Entretien de 190 kilomètres de voirie" ), 
                        element(135, "1.31. Etudes techniques pour les réhabilitation des ports fluviaux (40 ports) études bathymétriques et hydrographiques des voies fluviales navigables, acquisition de l'équipement nécessaires pour l'aménagement des 15.000 kms de voies navigables de la RDC" ), 
                        element(136, "1.4.1. Adoption du nouveau code de l'aviation civile et création constitution et financement de l'agence nationale de sécurité et surveillance de l'aviation civile         doption du nouveau" ) ) ), 
                element(70, "Agriculture", 
                    element(121, "1. La production agricole est augmentée et son évacuation assurée, permettant l'autonomie alimentaire et la relance de l'exportation" ), 
                    element(122, "2. L'amélioration de la gestion forestière" ), 
                    element(137, "1.1.1. Adoption de la stratégie sectoriell" ) ), 
                element(71, "Mines", 
                    element(123, "1. L'environnement d'affaires dans le secteur minier s'améliore" ), 
                    element(124, "2. L'exploitation informelle et artisanale est régularisée" ) ), 
                element(72, "Industrie et Services", 
                    element(125, "1. L'accès aux services financiers est accru" ), 
                    element(126, "2. La RDC est dotée d'une politique nationale cohérente de l'emploi et de la formation professionnelle" ), 
                    element(127, "3. La disponibilité de l'énergie électrique est augmentée" ) ) ), 
            element(138, "Pilier 3. Secteurs Sociaux", 
                element(146, "Education", 
                    element(147, "La gestion stratégique et opérationnelle dans le secteur de l'enseignement est améliorée" ), 
                    element(148, "Le niveau de financement du secteur public de l'éducation est augmenté et la gestion financière du  secteur est améliorée" ), 
                    element(149, "L'accès universel gratuti à l'enseignement primaire est progressivement atteint" ), 
                    element(150, "La couverture et la qualité des services de l'éducation au primaire et secondaire sont améliorées" ), 
                    element(151, "Les enseignements supérieur et professionnel sont rationalisés et révitalisés" ) ), 
                element(152, "La Santé", 
                    element(153, "Le cadre législatif et normatif pour le secteur de santé est révisé" ), 
                    element(154, "L'accès aux soins de santé et l'équité sont améliorés" ), 
                    element(155, "Une offre équilibrée de ressources humaines en santé est atteinte" ), 
                    element(156, "Une offre continue et régulière de médicaments essentiels et génériques (MEG)" ), 
                    element(157, "Des mécanismes de financement stables et ddurables pour le secteur de santé sont établis et des obstacles financiers à l'accès aux soins de santé sont séquentiellement supprimés" ) ), 
                element(158, "Eau et Assainissement", 
                    element(159, "La gestion opérationnelle et stratégique est améliorée dans le secteur de l'eau et de l'assainissement" ), 
                    element(160, "L'accès à l'eau et à l'assainissement en zone rurale est élargi" ), 
                    element(161, "La couverture des services de l'eau en zone urbaine est élargie" ), 
                    element(162, "La couverture des services urbains d'assainissement est  élargie" ) ), 
                element(163, "Protection Sociale", 
                    element(165, "Le risque parmi les populations les plus vulnérables est réduit" ), 
                    element(166, "Les populations fortement vulnérables bénéficient de mesure de sécurité" ) ) ), 
            element(139, "Pilier 4. VIH/SIDA", 
                element(167, "La prévention du VIH est accélérée et élargie particulièrement pour les femmes et les jeunes" ), 
                element(168, "L'accès universel gratuit au dépistage, au traitement et aux soins contre le VIH est assuré de façon graduelle" ), 
                element(169, "L'impact négatif du SIDA sur les personnes vivant avec le VIH et leurs familles est atténue" ), 
                element(170, "Une vision stratégique assortie d'une amélioration de la coordination et de mécanismes de financement est définie et mise en oeuvre" ) ), 
            element(140, "Pilier 5. Dynamique Communautaire", 
                element(198, "Dynamique Communautaire", 
                    element(201, "La capacité des institutions de l'Etat et des organisations des communautés de base de fournir des services sociaux de base au niveau local est accrue et les programmes de réhabilitation sont initiés dans des communautés sélectionnées" ), 
                    element(204, "Les opportunités d'emplois et des moyens de subsistances sont accrues" ), 
                    element(205, "Les infrastructuers publiques sont réhibilitées dans des communautés sélectionnées" ), 
                    element(206, "La sécurité locale est améliorée et la reconciliation est encouragée" ), 
                    element(207, "Les communautés participent efficacement aux programmes de la réduction de la pauvreté" ) ) ) ), 
        element(22, "PROGRAMMES NATIONAUX", 
            element(23, "PMURR / Programme Multisectoriel d'Urgence de Réhabilitation et Reconstruction (BM)" ), 
            element(24, "PURUS / Projet d'Urgence de Réhabilitation Urbaine et Sociale (BM)" ), 
            element(25, "PNLS / Programme National de Lutte contre le SIDA" ), 
            element(26, "FED 9 / 9e Fonds Européen de Développement (UE)" ), 
            element(27, "PARSS / Programme d'Appui de Réhabilitation du Secteur de la Santé (BM)" ), 
            element(28, "PUAACV / Projet d'Urgence d'Appui à l'Amélioration des Conditions de Vie (BM)" ), 
            element(29, "PASU / Projet d'Action Sociale d'Urgence (BM)" ), 
            element(30, "PNDDR / Programme National de Désarmement,Démobilisation et de Réinsertion (BM)" ), 
            element(31, "PUSPRES / Projet d'Urgence de Soutien au Processus de Réunification Economique et Sociale (BM)" ), 
            element(33, "SAPMP / Projet de Marché d'Electricité d'Afrique Australe (BM)" ), 
            element(172, "UNICEF / Education de base" ), 
            element(173, "UNICEF / Protection de l'enfant" ), 
            element(174, "UNICEF / Planification, Communication, Coordination VIH/SIDA" ), 
            element(175, "UNICEF / Eau, Hygiène et Assainissement" ), 
            element(178, "ESA / Etudes du Secteur Agricole (BAD)" ), 
            element(179, "PRODAP / Projet d' Appui au Programme Régional d'Aménagement Intégré du Lac Tanganyika(BAD)" ), 
            element(180, "PAPDDS / Projet d'Appui au Plan Directeur de Développement de la Santé en Province Orientale(BAD)" ), 
            element(181, "PEASU / Projet d'Alimentation en Eau Potable et d'Assainissement en Milieu Peri Urbain (BAD)" ), 
            element(182, "PASE / Projet d'Appui au Secteur de l'Education (BAD)" ), 
            element(183, "PARSE / Projet d'Appui au Redressement du Secteur de l'Education (BM)" ), 
            element(184, "PMURIS / Projet Multisectoriel de Réhabilitation des Infrastructures Sociales (BAD)" ), 
            element(185, "PAIM / Projet d'Appui Institutionnel Multisectoriel (BAD)" ), 
            element(186, "PARER / Projet d'Appui à la Relance Economique et à la Réunification" ), 
            element(187, "PARSAR / Projet d'Appui à la Réhabilitation du Secteur Agricole et Rural (BAD)" ), 
            element(188, "FAO / TCP -Technological Cooperation Programme" ), 
            element(189, "FAO / TF - Other Trust Funds" ), 
            element(190, "FAO / TF Governement Coopération Programme" ), 
            element(191, "FAO / Uniteral Trust Fund" ), 
            element(192, "FAO TeleFood Activies" ), 
            element(194, "MAP / Programme Multisectoriel de Lutte contre le Sida (BM)" ), 
            element(195, "UNFPA / Santé de la reproduction" ), 
            element(196, "UNFPA / Population et développement" ), 
            element(197, "VSGB" ), 
            element(208, "PURR / Projet d'Urgence de Redressement Rapide (BM)" ), 
            element(210, "PMEDE / Projet de Marché d'Electricité à la consommation domestique et à l'Exportation (BM)" ), 
            element(211, "PSRE / Projet de Stabilisation et de Relance Economique (BM)" ), 
            element(212, "PSEC / Projet de Soutien aux Entreprises Congolaises (BM)" ), 
            element(213, "PTM / Projet de Transport Multimodal (BM)" ), 
            element(214, "PAREC / Projet d'appui au renforcement des capacités (BM)" ), 
            element(215, "PRESEC / (BM)" ), 
            element(216, "PCDSP / Projet de Competitivité et Développement du Secteur Privé (BM)" ), 
            element(218, "UNFPA PUH / Projets d'urgence humanitaire" ), 
            element(219, "BI 2008 / Budget d'Investissement 2008" ), 
            element(220, "BI 2009 / Budget d'Investissement 2009" ), 
            element(221, "BI 2010 / Budget d'Investissement 2010" ), 
            element(222, "PPTE 2008 / Dépenses Initiative Pays Pauvres Très Endetté 2008" ), 
            element(223, "SNDS / Stratégie Nationale de Développement de la Statistique" ), 
            element(226, "PRCG / Projet de renforcement des capacités en gouvernance (BM)" ), 
            element(227, "FED 8 / 8e Fonds Européens de Développement(UE)" ), 
            element(228, "BI 2007 / Budget d'investissement 2007" ), 
            element(230, "UNDAF / UN Development Assistance Framework", 
                element(326, "Good Governance" ), 
                element(327, "Pro Poor Growth" ), 
                element(328, "Basic Social Services" ), 
                element(329, "HIV/AIDS" ), 
                element(330, "Community Dynamics" ) ), 
            element(237, "LTH / Lignes Thématiques Budgétaires (UE)" ), 
            element(238, "EPT / Education Pour Tous" ), 
            element(240, "PUAICF / Programme d'urgence d'attenuation des impacts de la crise financière (BM, BAD)" ), 
            element(249, "PEMU / Projet d'alimentation d'eau en milieu urbain (BM)" ), 
            element(254, "PFCN / Projet Forêts et Conservation de la Nature(BM)" ), 
            element(255, "STAREC / Programme de stabilisation et reconstruction des zones sortant de conflits armés" ), 
            element(257, "PARRSA / Projet d'appui à la relance et réhabilitation du secteur agricole (BM)" ), 
            element(261, "PRSF / Projet de reconstruction du secteur forestier (BM)" ), 
            element(270, "FED 10 / 10ème Fonds européen de développement" ), 
            element(276, "PRESAR / Projet de réhabilitation du secteur agricole et rural (BAD)" ), 
            element(284, "UNICEF / Survie de l'enfant" ), 
            element(285, "UNICEF / Plaidoyer our la promotion des droits" ), 
            element(286, "UNESCO / Culture" ), 
            element(287, "UNESCO / Communication et Information" ), 
            element(288, "PNUD / Gouvernance" ), 
            element(291, "Unesco /Education", 
                element(292, "Accès et équité", 
                    element(293, "Réduction des frais scolaires" ) ) ), 
            element(295, "GOUVERNANCE", 
                element(296, "Gce Economique" ), 
                element(297, "Sécuritsation" ), 
                element(298, "Elections" ), 
                element(299, "Décentralisation" ), 
                element(300, "Administrative" ), 
                element(301, "Unité d'appui au programme" ), 
                element(302, "Gce Politique" ), 
                element(303, "Sécutitaire" ), 
                element(466, "Justice" ) ), 
            element(304, "PAUVRETE", 
                element(305, "Environnement" ), 
                element(306, "Relèvemnt communautaire" ), 
                element(308, "Microfinance et emploi" ), 
                element(310, "VIH/SIDA" ), 
                element(311, "OMD/DSCRP" ), 
                element(312, "Gestion et coordination" ) ), 
            element(314, "SUPPORT AU PROGRAMME", 
                element(315, "Politiques et stratégies" ), 
                element(316, "Communication" ), 
                element(317, "Spgm Coordination" ), 
                element(318, "Renforcément des capacités" ), 
                element(320, "Genre" ), 
                element(323, "Suivi et évaluation" ) ), 
            element(325, "PRONAREC/Programme National de Renforcément des Capacités (BM)" ), 
            element(331, "Violences Sexuelles Basées sur le Genre" ), 
            element(341, "MONUSCO/ARMEE", 
                element(342, "AR/Service support trng", 
                    element(344, "Peacekeeping Ops" ), 
                    element(345, "Logistic/Supply Chain Mgmt" ), 
                    element(346, "Combat medical services" ) ), 
                element(347, "AR/Opérations", 
                    element(348, "Operational Doctrice" ), 
                    element(349, "Current Operations SOPs" ), 
                    element(350, "Task Organizations SOPs" ), 
                    element(351, "Unite Couverture" ), 
                    element(352, "Unite RR" ), 
                    element(353, "Unite DP" ), 
                    element(354, "Civil Military Affairs" ), 
                    element(355, "Mentor Program" ) ), 
                element(356, "AR/Planning" ), 
                element(365, "AR/Combat Support Training" ), 
                element(366, "AR/Combat Arms Training" ), 
                element(367, "AR/Command & Control" ), 
                element(368, "AR/Miscellaneous" ), 
                element(369, "AR/Scls & CI PRA by 2011" ), 
                element(370, "AR/Organization Strategic", 
                    element(373, "Legal Component" ), 
                    element(374, "National Military Strategy" ), 
                    element(375, "MOD Reorganization" ), 
                    element(376, "Etat Major General Reorganization" ), 
                    element(377, "Defense Budget Process" ), 
                    element(378, "Reform Harmonization" ) ), 
                element(372, "AR/Personnel Administration" ) ), 
            element(391, "BI 2011/Budget d'Investissement 2011" ), 
            element(392, "Pro routes/Projet réouverture et entretien routier (BM & RU))" ), 
            element(394, "PASU FA1/Projet daction sociale d'urgence  financement additionnels (BM)" ), 
            element(395, "PHK/Projet Himo Katanga" ), 
            element(398, "EDR/Projet enfants dits de la rue" ), 
            element(399, "BI 2012/Budget d'Investissement  2012" ), 
            element(401, "FSRDC/Fonds Social de la République Démocratique du Congo(BM)", 
                element(402, "PASU FA1/Projet d'action sociale d'urgence  financement additionnels" ), 
                element(404, "EDR/Enfants dits de la rue" ), 
                element(405, "PHKAT/Projet  Haute Intensité de la Main d'Oeuvre au Katanga" ), 
                element(406, "PASU/Projet d'action sociale d'urgence" ), 
                element(407, "PASU FA2/Projet d'action sociale d'urgence  financement additionnels" ) ), 
            element(408, "DSCRP/Document de la Stratégie de Croissance et de Réduction de la Pauvreté", 
                element(409, "PILIER 1/ Renforcer la gouvernance et la paix", 
                    element(413, "Renforcer l'autorité de l'Etat", 
                        element(420, "Renforcer les institutions politiques et démocratiques" ), 
                        element(421, "Renforcer les capacités d'intervention de l'armée et de la police pour assurer la sécurité du territoire national" ), 
                        element(422, "Accélérer la réforme du système judiciaire et promovoir les droits humains" ) ), 
                    element(414, "Accélérer le processus de la décentralisation" ), 
                    element(415, "Poursuivre la réforme des finances publiques" ), 
                    element(416, "Améliorer le cliamt des affaires et promouvoir le secteur privé", 
                        element(423, "Améliorer le climat des affaires" ), 
                        element(424, "Promouvoir le secteur privé" ), 
                        element(425, "Amélioration l'intermédition financière" ), 
                        element(426, "Reformer les entreprises du portefeuille" ), 
                        element(427, "Promouvoir une classe moyenne congolaise et utiliser le potentiel de la diaspora" ) ), 
                    element(417, "Renforcer les capacités institutionnelles et humaines et moderniser l'administration publique" ), 
                    element(418, "Appuyer le dispositif de planification et le système national des statistiques" ), 
                    element(419, "Restructurer la Banque Centrale du  Congo" ) ), 
                element(410, "PILIER 2/Diversifier l'économie,accélérer la croissance et  promouvoir l'emploi", 
                    element(428, "Relancer l'agriculture et assurer la sécurité alimentaire et le bien-être des ruraux", 
                        element(429, "Renforcer le secteur des transports" ), 
                        element(430, "Accroitre la production électrique et améliorer l'accès des populations" ), 
                        element(431, "Développer le secteur de la poste, des télécommunications et des technologies de l'information et  de la communication" ), 
                        element(433, "Promouvoir le tourisme" ), 
                        element(435, "Promouvoir les autres domaines du secteur tertiaire" ) ), 
                    element(436, "Redynamiser l'appareil de production", 
                        element(437, "Développer le secteur forestier" ), 
                        element(438, "Relancer la production minière" ), 
                        element(439, "Accroitre la production des hydrocarbures" ), 
                        element(440, "Promouvoir les industries" ) ), 
                    element(441, "Promouvoir le commerce extérieur" ), 
                    element(442, "Promouvoir l'emploi" ), 
                    element(443, "Aménager le territoire national et les villes" ), 
                    element(444, "Formaliser le secteur informel" ), 
                    element(445, "Promouvoir le développement spatial" ) ), 
                element(411, "PILIER 3/Amélioration l'accès aux services sociaux de base et renforcer le capital humain", 
                    element(446, "Renforcer le capital humain", 
                        element(451, "Améliorer l'accès à l'éducation et la formation professionnelle" ), 
                        element(452, "Améliorer l'état de santé et le statut nutritionnel" ), 
                        element(453, "Promouvoir la jeunesse et les sports" ), 
                        element(454, "Promouvoir la culture et les arts" ) ), 
                    element(447, "Lutter contre le VIH/SIDA" ), 
                    element(448, "Réduire les inégalités et la vulnérabilité", 
                        element(455, "Assurer l'égalité du genre" ), 
                        element(456, "Assurer la protection sociale" ) ), 
                    element(449, "Améliorer le cadre de vie des populations et l'accès aux services", 
                        element(457, "Poursuivre les réformes foncières, renforcer les voiries et améliorer le logement" ), 
                        element(458, "Améliorer l'accès à l'eau, à l'hygiène et assainissement" ) ), 
                    element(450, "Promouvoir la dynamique communautaire" ) ), 
                element(412, "PILIER 4/Protéger l'environnement et lutter contre le changement climatique", 
                    element(459, "Gérer et protèger l'environnement et les ressources naturelles", 
                        element(461, "Gérer et protéger durablement l'environnement" ), 
                        element(462, "Gérer et protéger durablement les ressources naturelles renouvelables" ) ), 
                    element(460, "Lutter contre les changements climatiques", 
                        element(463, "Atténuer les effets des changements climatiques" ), 
                        element(464, "S'adapter aux changements climatiques" ) ) ) ), 
            element(465, "Promines (BM)" ), 
            element(467, "BI 2013/Budget d'Investissemnt 2013" ), 
            element(468, "GPB/DG programmes géographiques (CANADA)" ), 
            element(469, "PC/Partenariats avec les Canadiens (CANADA)" ), 
            element(470, "MGPB/DG programmes multilatéraux et mondiaux (CANADA)" ), 
            element(471, "SPP/Politiques stratégiques & rendement (CANADA)" ), 
            element(472, "AIDCOM/Aide au Commerce(UE)" ), 
            element(473, "BI 2014/Bugdet d'Investissement  2014" ), 
            element(474, "PDU/Projet de développement urbain (BM)" ), 
            element(475, "PROSEB/Projet de soutien à l'éducation de base (BM)" ), 
            element(476, "PREPAN/Projet de réhabilitation du réseau des parcs nationaux (BM)" ), 
            element(477, "PMR-RH/Projet de mobilisation et de révitalisation des ressources humaines de l'administration publique (BAD)" ), 
            element(478, "PIC 2008-2010/Programme Indicatif de Coopération 2008-2010" ), 
            element(479, "PIC 2010-2013/Programme Indicatif de Coopération 2010-2013" ), 
            element(480, "PIC 2007-2007/Programme Indicatif de Coopération 2007-2007" ), 
            element(481, "PIC 1990-2006/Programme Indicatif de Coopération 1990-2006" ) ), 
        element(262, "PAP 2009 2010" ));
    }
}

