package org.dgfoundation.amp.nireports.testcases.drc.dimensions;

import org.dgfoundation.amp.nireports.testcases.HNDNode;
import org.dgfoundation.amp.nireports.testcases.HardcodedNiDimension;

import java.util.Arrays;
import java.util.List;

import static org.dgfoundation.amp.nireports.testcases.HNDNode.element;

public class SectorsTestDimension extends HardcodedNiDimension {

    public SectorsTestDimension(String name, int depth) {
        super(name, depth);
    }

    public final static SectorsTestDimension instance = new SectorsTestDimension("sectors", 3);

    @Override
    protected List<HNDNode> buildHardcodedElements() {
        return Arrays.asList(
        element(1, "EDUCATION", 
            element(2, "--Éducation, niveau non spécifié", 
                element(3, "-- --Politique de l’éducation et gestion administrative" ), 
                element(4, "-- --Bâtiments et équipements scolaires et formation" ), 
                element(5, "-- --Formation des enseignants" ), 
                element(6, "-- --Recherche en éducation" ) ), 
            element(7, "--Éducation de base", 
                element(8, "-- --Enseignement primaire" ), 
                element(9, "-- --Éducation pour une meilleure qualité de vie pour les jeunes et les adultes" ), 
                element(10, "-- --Éducation de la petite enfance" ) ), 
            element(11, "--Éducation secondaire", 
                element(12, "-- --Enseignement secondaire" ), 
                element(13, "-- --Formation professionnelle" ) ), 
            element(14, "--Éducation post-secondaire", 
                element(15, "-- --Enseignement supérieur" ), 
                element(16, "-- --Formation technique supérieure de gestion" ) ) ), 
        element(17, "SANTE", 
            element(18, "--Santé, général", 
                element(19, "-- --Politique de la santé et gestion administrative" ), 
                element(20, "-- --Éducation et formation médicales" ), 
                element(21, "-- --Recherche médicale" ), 
                element(22, "-- --Services médicaux" ) ), 
            element(23, "--Santé de base", 
                element(24, "-- --Soins et services de santé de base" ), 
                element(25, "-- --Bâtiments et équipements pour la santé de base" ), 
                element(26, "-- --Nutrition de base" ), 
                element(27, "-- --Lutte contre les maladies infectieuses" ), 
                element(28, "-- --Éducation sanitaire" ), 
                element(29, "-- --Formation de personnel de santé" ), 
                element(281, "-- --Lutte contre le paludisme" ), 
                element(282, "-- --Lutte contre la tuberculose" ) ) ), 
        element(30, "POLITIQUE EN MATIERE DE POPULATION/SANTE ET FERTILITE /VIH-SIDA", 
            element(31, "--Politique/programmes en matière de population et gestion administrative" ), 
            element(32, "--Soins en matière de fertilité" ), 
            element(33, "--Planification familiale" ), 
            element(34, "--Lutte contre les MST et VIH/sida" ), 
            element(35, "--Formation de personnel  en matière de population et de santé et fertilité" ) ), 
        element(36, "EAU ET ASSAINISSEMENT", 
            element(37, "--Politique des ressources en eau et gestion administrative" ), 
            element(38, "--Protection des ressources en eau" ), 
            element(39, "--Approvisionnement en eau et assainissement – systèmes à grande échelle", 
                element(315, "-- --Approvisionnement en eau - systèmes à grande échelle" ), 
                element(316, "-- --Assainissement - systèmes à grande échelle" ) ), 
            element(40, "--Approvisionnement en eau potable et assainissement- dispositifs de base", 
                element(313, "-- --Approvisionnement en eau potable-dispositifs de base" ), 
                element(314, "-- --Assainissement- dispositifs de base" ) ), 
            element(41, "--Aménagement de bassins fluviaux" ), 
            element(42, "--Traitement des déchets" ), 
            element(43, "--Éducation/formation dans la distribution d’eau et l’assainissement" ) ), 
        element(44, "GOUVERNANCE ET SOCIETE CIVILE", 
            element(229, "--Gouvernance et société civile, général", 
                element(45, "-- --Politiques publiques et gestion administrative" ), 
                element(46, "-- --Gestion des finances publiques" ), 
                element(47, "-- --Développement des services légaux et judiciaires" ), 
                element(48, "-- --Décentralisation et soutien aux administrations infranationales" ), 
                element(49, "-- --Participation démocratique et société civile" ), 
                element(51, "-- --Élections" ), 
                element(52, "-- --Droits de la personne et droits humains" ), 
                element(54, "-- --Médias et liberté de l'information" ), 
                element(238, "-- --Organisations et institutions pour l’égalité des femmes" ), 
                element(276, "-- --Assemblées législatives et partis politiques" ), 
                element(283, "-- --Organisations et institutions pour la lutte contre la corruption" ) ), 
            element(230, "--Paix et sécurité, prévention et règlement des conflits", 
                element(50, "-- --Maintien de la paix à l’issue d’un conflit (Nations Unies), inclus DDR" ), 
                element(55, "-- --Enlèvement des mines terrestres" ), 
                element(231, "-- --Contrôle des armes légères et de petit calibre" ), 
                element(232, "-- --Gestion et réforme des systèmes de sécurité (police, armée, milices)" ), 
                element(233, "-- --Dispositifs civils de construction de la paix, et de prévention et de règlement des conflits" ), 
                element(234, "-- --Enfants soldats (Prévention et démobilisation)" ) ) ), 
        element(56, "SERVICES SOCIAUX DIVERS", 
            element(57, "--Services sociaux" ), 
            element(58, "--Politique de l’emploi et gestion administrative" ), 
            element(59, "--Politique du logement et gestion administrative" ), 
            element(60, "--Logement à coût réduit" ), 
            element(61, "--Aide plurisectorielle pour les services sociaux de base" ), 
            element(62, "--Culture et loisirs" ), 
            element(63, "--Renforcement des capacités statistiques" ), 
            element(64, "--Lutte contre le trafic de drogues" ), 
            element(235, "--Atténuation de l’impact social du VIH/sida" ) ), 
        element(66, "TRANSPORTS ET ENTREPOSAGE", 
            element(67, "--Politique des transports et gestion administrative" ), 
            element(68, "--Transport routier", 
                element(277, "-- --Routes desserte agricole / pistes rurales" ) ), 
            element(69, "--Transport ferroviaire" ), 
            element(70, "--Transport par voies d’eau" ), 
            element(71, "--Transport aérien" ), 
            element(72, "--Stockage" ), 
            element(73, "--Éducation/formation dans les transports et le stockage" ) ), 
        element(74, "COMMUNICATIONS", 
            element(75, "--Politique des communications et gestion administrative" ), 
            element(76, "--Télécommunications" ), 
            element(77, "--Radio, télévision, presse écrite" ), 
            element(78, "--Technologies de l’information et de la communication (TIC)" ) ), 
        element(79, "ENERGIE (PRODUCTION ET DISTRIBUTION)", 
            element(80, "--Politique de l’énergie et gestion administrative" ), 
            element(81, "--Production d’énergie (sources non renouvelables)" ), 
            element(82, "--Production d’énergie (sources renouvelables)" ), 
            element(83, "--Transmission et distribution d’électricité" ), 
            element(84, "--Distribution de gaz" ), 
            element(85, "--Centrales alimentées au fuel" ), 
            element(86, "--Centrales alimentées au gaz" ), 
            element(87, "--Centrales alimentées au charbon" ), 
            element(88, "--Centrales nucléaires" ), 
            element(89, "--Centrales et barrages hydroélectriques" ), 
            element(90, "--Énergie géothermique" ), 
            element(91, "--Énergie solaire" ), 
            element(92, "--Énergie éolienne" ), 
            element(93, "--Énergie marémotrice" ), 
            element(94, "--Biomasse" ), 
            element(95, "--Éducation et formation dans le domaine de l’énergie" ), 
            element(96, "--Recherche dans le domaine de l’énergie" ) ), 
        element(97, "BANQUES ET SERVICES FINANCIERS", 
            element(98, "--Politique des finances et gestion administrative" ), 
            element(99, "--Institutions monétaires" ), 
            element(100, "--Intermédiaires financiers officiels" ), 
            element(101, "--Intermédiaires financiers du secteur informel et semi formel" ), 
            element(102, "--Education/formation dans la banque et les services financiers" ) ), 
        element(103, "ENTREPRISES ET AUTRES SERVICES", 
            element(104, "--Services et institutions de soutien commerciaux" ), 
            element(105, "--Privatisation" ) ), 
        element(106, "AGRICULTURE, ELEVAGE", 
            element(107, "--Politique agricole et gestion administrative" ), 
            element(108, "--Développement agricole" ), 
            element(109, "--Ressources en terres cultivables" ), 
            element(110, "--Ressources en eau à usage agricole" ), 
            element(111, "--Produits à usage agricole" ), 
            element(112, "--Production agricole" ), 
            element(113, "--Récoltes destinées à l’exportation" ), 
            element(114, "--Bétail" ), 
            element(115, "--Réforme agraire" ), 
            element(116, "--Développement agricole alternatif" ), 
            element(117, "--Vulgarisation agricole" ), 
            element(118, "--Éducation et formation dans le domaine agricole" ), 
            element(119, "--Recherche agronomique" ), 
            element(120, "--Services agricoles (marchés, transport et stockage)" ), 
            element(121, "--Protection des plantes et des récoltes, lutte antiacridienne" ), 
            element(122, "--Services financiers agricoles" ), 
            element(123, "--Coopératives agricoles" ), 
            element(124, "--Services vétérinaires (bétail)" ) ), 
        element(125, "SYLVICULTURE", 
            element(126, "--Politique de la sylviculture et gestion administrative" ), 
            element(127, "--Développement sylvicole" ), 
            element(128, "--Reboisement (bois  de chauffage et charbon de bois)" ), 
            element(129, "--Éducation et formation en sylviculture" ), 
            element(130, "--Recherche en sylviculture" ), 
            element(131, "--Services sylvicoles" ) ), 
        element(132, "PECHE", 
            element(133, "--Politique de la pêche et gestion administrative" ), 
            element(134, "--Développement de la pêche" ), 
            element(135, "--Education et formation dans le domaine de la pêche" ), 
            element(136, "--Recherche dans le domaine de la pêche" ), 
            element(137, "--Services dans le domaine de la pêche" ) ), 
        element(138, "INDUSTRIES MANUFACTURIERES", 
            element(139, "--Politique de l’industrie et gestion administrative" ), 
            element(140, "--Développement industriel" ), 
            element(141, "--Développement des Petites et Moyennes Entreprises(PME)" ), 
            element(142, "--Artisanat" ), 
            element(143, "--Agro-industries" ), 
            element(144, "--Industries forestières" ), 
            element(145, "--Industrie textile, cuirs et produits similaires" ), 
            element(146, "--Produits chimiques" ), 
            element(147, "--Production d’engrais chimiques" ), 
            element(148, "--Ciment, chaux et plâtre" ), 
            element(149, "--Fabrication d’énergie" ), 
            element(150, "--Produits pharmaceutiques" ), 
            element(151, "--Industrie métallurgique de base" ), 
            element(152, "--Industries des métaux non ferreux" ), 
            element(153, "--Construction mécanique et électrique" ), 
            element(154, "--Matériel de transport" ), 
            element(155, "--Recherche et développement technologiques" ) ), 
        element(156, "INDUSTRIES EXTRACTIVES", 
            element(157, "--Politique de l’industrie extractive et gestion administrative" ), 
            element(158, "--Prospection et exploration des minerais" ), 
            element(159, "--Charbon" ), 
            element(160, "--Pétrole et gaz" ), 
            element(161, "--Métaux ferreux" ), 
            element(162, "--Métaux non ferreux" ), 
            element(163, "--Métaux et minerais précieux" ), 
            element(164, "--Minerais industriels" ), 
            element(165, "--Engrais minéraux" ), 
            element(166, "--Ressources des fonds marins" ) ), 
        element(167, "POLITIQUE DE LA CONSTRUCTION" ), 
        element(169, "POLITIQUE COMMERCIALE ET REGLEMENTATIONS ET AJUSTEMENT LIES", 
            element(170, "--Politique commerciale et gestion administrative" ), 
            element(171, "--Facilitation du commerce" ), 
            element(172, "--Accords commerciaux régionaux" ), 
            element(173, "--Négociations commerciales multilatérales" ), 
            element(174, "--Éducation/formation dans le domaine du commerce" ), 
            element(284, "--Ajustement lié au commerce" ) ), 
        element(175, "TOURISME", 
            element(176, "--Politique du tourisme et gestion administrative" ) ), 
        element(177, "ENVIRONNEMENT (PROTECTION DE L')", 
            element(178, "--Politique de l'environnement et gestion administrative" ), 
            element(256, "--Protection de la biosphère" ), 
            element(257, "--Diversité biologique" ), 
            element(258, "--Protection des sites" ), 
            element(259, "--Prévention et lutte contre les inondations" ), 
            element(260, "--Éducation et formation environnementales" ), 
            element(261, "--Recherche environnementale" ) ), 
        element(195, "X3:AIDE-PROGRAMME ET AIDE SOUS FORME DE PRODUITS", 
            element(196, "--Soutien budgétaire", 
                element(197, "-- --Soutien budgétaire" ) ), 
            element(198, "--Aide alimentaire à des fins de développement/aide à la sécurité alimentaire", 
                element(199, "-- --Programmes de sécurité et d’aide alimentaire" ) ), 
            element(200, "--Aide sous forme de produits : autre", 
                element(201, "-- --Subventions à l’importation (biens d’équipement)" ), 
                element(202, "-- --Subventions à l’importation (produits)" ) ) ), 
        element(203, "X6:ACTIONS SE RAPPORTANT À LA DETTE", 
            element(204, "--Action se rapportant à la dette" ), 
            element(205, "--Annulation de la dette" ), 
            element(206, "--Allégement de la dette bi(multi)latérale" ), 
            element(207, "--Rééchelonnement d’échéances et refinancement" ), 
            element(208, "--Échange de dette à des fins de développement" ), 
            element(209, "--Autres échanges de dette" ), 
            element(210, "--Rachat de la dette" ) ), 
        element(211, "X7:AIDE HUMANITAIRE", 
            element(214, "--Intervention d’urgence", 
                element(213, "-- ---Aide alimentaire d’urgence" ), 
                element(215, "-- --Assistance matérielle et services d’urgence non spécifiés" ), 
                element(217, "-- --Coordination des secours" ), 
                element(240, "-- --Réintégration et relance communautaire" ), 
                element(241, "-- --Santé" ), 
                element(242, "-- --Nutrition" ), 
                element(243, "-- --Eau et assainissement" ), 
                element(244, "-- --Abri et biens non alimentaires" ), 
                element(245, "-- --Education" ), 
                element(246, "-- --Protection" ), 
                element(247, "-- --Télécommunications" ), 
                element(248, "-- --Logistique" ) ), 
            element(236, "--Prévention des catastrophes et préparation à leur survenue", 
                element(237, "-- --Prévention des conflits et préparation à leur survenue" ) ) ), 
        element(220, "X2:FRAIS ADMINISTRATIFS DES BAILLEURS ET AGENCES", 
            element(221, "--Frais administratifs des bailleurs" ), 
            element(269, "--Frais administratifs des agences d'exécution" ) ), 
        element(222, "X5:CONCOURS FOURNIS AUX ONGS", 
            element(223, "--En faveur des ONG nationales" ), 
            element(224, "--En faveur des ONG internationales" ), 
            element(225, "--En faveur des ONG locales et régionales" ) ), 
        element(226, "Z:NON AFFECTE/ NON SPECIFIE", 
            element(227, "--Secteur non spécifié" ), 
            element(228, "--Sensibilisation au développement" ) ), 
        element(249, "X1:MULTI-SECTEURS", 
            element(250, "--Aide plurisectorielle" ), 
            element(251, "--Développement et gestion urbaine" ), 
            element(252, "--Développement rural" ), 
            element(253, "--Développement alternatif non agricole" ), 
            element(254, "--Education et formation plurisectorielles, inclus bourses d'études" ), 
            element(255, "--Institutions scientifiques et de recherche" ) ), 
        element(262, "1. LES INFRASTRUCTURES (TRANSPORTS, AMÉNAGEMENT URBAIN, NTIC)" ), 
        element(263, "2. LA SANTÉ ET L'ÉDUCATION (INCLUT VIH/SIDA ET ASSAINISSEMENT)" ), 
        element(264, "3. L'EAU ET L'ÉLECTRICITÉ (INCLUT HYDROCARBURES)" ), 
        element(265, "4. LE LOGEMENT" ), 
        element(266, "5. LA CRÉATION D'EMPLOI (INCLUT AGRICULTURE, INDUSTRIES, TOURISME)" ), 
        element(267, "6.HORS DES CINQ CHANTIERS" ), 
        element(270, "X4:CONTRIBUTIONS VERSEES A DES FONDS COMMUNS POUR LA RDC", 
            element(271, "--Fonds humanitaires", 
                element(273, "-- --Pooled Fund" ), 
                element(274, "-- --Mécanisme de réponse rapide (MRR)" ) ), 
            element(272, "--Fonds de développement" ) ), 
        element(285, "Y" ), 
        element(286, "GOUVERNACE" ), 
        element(287, "DEFENSE,ORDRE ET SECURITE" ), 
        element(288, "INFRASTRACTURES", 
            element(295, "TRANSPORTS" ), 
            element(296, "COMMUNICATIONS", 
                element(308, "Radio" ), 
                element(309, "Télévision,médias et presse" ), 
                element(310, "Station météorologique" ), 
                element(311, "Station terrienne" ), 
                element(312, "Nouvelle technologie de l'information et communication (NTIC)" ) ), 
            element(297, "IMMOBILIERS" ), 
            element(298, "ENERGIES", 
                element(303, "Construction des barrages et centrales hydroélectriques" ), 
                element(304, "Exploitation,transport et distribution de l'électricité" ), 
                element(305, "Production,exploitation et  distribution d'eau" ), 
                element(306, "Productio,exploitation,distribution du gaz" ), 
                element(307, "Productio,exploitation,distribution d'energie solaire" ) ), 
            element(299, "EQUIPEMENTS DIVERS", 
                element(300, "Garage central STA" ), 
                element(301, "Garages provinciaux" ), 
                element(302, "Garages sécondaires" ) ) ), 
        element(289, "ACTIVITES ECONOMIQUES" ), 
        element(290, "SOCIAUX" ), 
        element(293, "ENVIRONNEMENT" ), 
        element(294, "DYNAMIQUE COMMUNAUTAIRE" ));
    }
}

