module.exports = {
   WIZARD_CLOSED_EVENT:'WIZARD_CLOSED_EVENT',
   CREATE_LAYER_EVENT: 'CREATE_LAYER_EVENT',
   UPDATE_LAYER_EVENT: 'UPDATE_LAYER_EVENT',
   OPEN_POPULATION_VIEW_EVENT: 'OPEN_POPULATION_VIEW_EVENT',
   POPULATION_VIEW_CLOSED_EVENT : 'POPULATION_VIEW_CLOSED_EVENT'
}
