module.exports = [{name:'UNKNOWN_ERROR', code: '0600', translationKey: 'amp.gis-layers-manager:validation-UnknownError', defaultMessage:'Unknown Error'},
                  {name: 'UNAUTHORIZED', code:'0601', translationKey: 'amp.gis-layers-manager:validation-Unauthorized', defaultMessage:'Unauthorized operation'},
                  {name: 'FIELD_INVALID_TYPE', code: '0602',translationKey: 'amp.gis-layers-manager:validation-InvalidType', defaultMessage:'Invalid field type'},
                  {name: 'FIELD_INVALID_VALUE', code: '0603', translationKey: 'amp.gis-layers-manager:validation-InvalidValue', defaultMessage:'Invalid field value'},
                  {name: 'INVALID_ID', code: '0604',translationKey: 'amp.gis-layers-manager:validation-InvalidID', defaultMessage:'Invalid id'},
                  {name: 'INCORRECT_CONTENT', code: '0605', translationKey: 'amp.gis-layers-manager:validation-IncorrectContent', defaultMessage:'Wrong content'},
                  {name: 'INEXISTANT_ADM_LEVEL', code: '0606', translationKey: 'amp.gis-layers-manager:validation-InexistantADMLevel', defaultMessage:'Inexistant AdmLevel'},
                  {name: 'NUMBER_NOT_MATCH', code: '0607', translationKey: 'amp.gis-layers-manager:validation-NumberMismatch', defaultMessage:'Number misMatch'},
                  {name: 'NAME_NOT_MATCH', code: '0608', translationKey: 'amp.gis-layers-manager:validation-NameMismatch', defaultMessage:'Name misMatch'},
                  {name: 'LOCATION_NOT_FOUND', code: '0609', translationKey: 'amp.gis-layers-manager:validation-LocationNotFound', defaultMessage:'Location not found'},
                  {name: 'INVALID_FIELD', code: '0610', translationKey: 'amp.gis-layers-manager:validation-InvalidField', defaultMessage:'Invalid field'},
                  {name: 'INVALID_SORT', code: '0611', translationKey: 'amp.gis-layers-manager:validation-InvalidSort', defaultMessage:'Invalid sort'},
                  {name: 'EXISTING_NAME', code: '0612', translationKey: 'amp.gis-layers-manager:validation-LayerWithNameExists', defaultMessage:'A layer with the specified name already exists. Please choose a different name'},
                  {name: 'INVALID_POPULATION_LAYERS', code: '0613', translationKey: 'amp.gis-layers-manager:validation-InvalidPopulationLayers', defaultMessage:'Invalid population layers'},
                  {name: 'INVALID_INDICATOR_TYPE', code: '0614', translationKey: 'amp.gis-layers-manager:validation-InvalidIndicatorType', defaultMessage:'Invalid Indicator Type'},
                  {name: 'INVALID_IMPORT_NO_VALUE', code: '0615', translationKey: 'amp.gis-layers-manager:validation-InvalidImport', defaultMessage:'Invalid Import: Please add at least one indicator value'},
                  {name: 'INVALID_IMPORT_INVALID_ADMIN_LEVEL', code: '0616', translationKey: 'amp.gis-layers-manager:validation-InvalidImportAdminLevel', defaultMessage:'Invalid Import: Administrative divisions in the uploaded file do not match Admin level selected in wizard'},
                ];
