---

- name: Enable and start firewalld
  service: name=firewalld state=started enabled=yes

- name: Extra open TCP ports
  firewalld: port={{ item }}/tcp permanent=true state=enabled immediate=yes
  with_items: "{{ common__extra_open_tcp_ports|default([]) }}"
  notify:
    - restart firewalld
