---

- name: Create developers group
  group: name=developers

- name: Create deployer user
  user:
    name: deployer
    comment: 'Deployer'
    group: developers
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_comment: '<deployer@$HOSTNAME>'

# @see: http://docs.ansible.com/ansible/faq.html#how-do-i-generate-crypted-passwords-for-the-user-module
- name: Create user accounts for developers
  user:
    name: "{{ item.name }}"
    comment: "{{ item.comment|default(omit) }}"
    group: "{{ item.group|default('developers') }}"
    groups: "{{ item.groups|default(omit) }}"
    password: "{{ item.password|default(omit) }}"
  with_items: "{{ common__developers|default([]) }}"

- name: Add authorized SSH keys for accounts
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.key }}"
  with_items: "{{ common__developers|default([]) }}"

- name: Configure the new user files umask.
  copy: src=profile_umask.sh dest=/etc/profile.d/custom-umask.sh
