import * as AC from './ActivityConstants';
import * as FM from  './FeatureManagerConstants';

export const ACTIVITY_FIELDS_FM_PATH = {};
ACTIVITY_FIELDS_FM_PATH[AC.MODIFIED_BY] = FM.ACTIVITY_LAST_UPDATED_BY;
ACTIVITY_FIELDS_FM_PATH[AC.UPDATE_DATE] = FM.ACTIVITY_LAST_UPDATED_ON;

ACTIVITY_FIELDS_FM_PATH[AC.COMMITMENT_RECIPIENT_ORG] = FM.ACTIVITY_COMMITMENT_ORG_ROLE_ON;
ACTIVITY_FIELDS_FM_PATH[AC.COMMITMENT_RECIPIENT_ROLE] = FM.ACTIVITY_COMMITMENT_ORG_ON;

ACTIVITY_FIELDS_FM_PATH[AC.DISBURSEMENT_RECIPIENT_ORG] = FM.ACTIVITY_DISBURSEMENT_ORG_ROLE_ON;
ACTIVITY_FIELDS_FM_PATH[AC.DISBURSEMENT_RECIPIENT_ROLE] = FM.ACTIVITY_DISBURSEMENT_ORG_ON;