CREATE OR REPLACE VIEW `v_donor_funding` AS select `f`.`amp_activity_id` AS `amp_activity_id`,`f`.`amp_funding_id` AS `amp_funding_id`,`fd`.`amp_fund_detail_id` AS `amp_fund_detail_id`,`d`.`name` AS `donor_name`,`fd`.`transaction_type` AS `transaction_type`,`fd`.`adjustment_type` AS `adjustment_type`,`fd`.`transaction_date` AS `transaction_date`,`fd`.`transaction_amount` AS `transaction_amount`,`c`.`currency_code` AS `currency_code`,`cval`.`category_value` AS `terms_assist_name`,`fd`.`fixed_exchange_rate` AS `fixed_exchange_rate`,`b`.`org_grp_name` AS `org_grp_name`,`ot`.`org_type` AS `donor_type_name`,`cval2`.`category_value` AS `financing_instrument_name`,`b`.`amp_org_grp_id` AS `org_grp_id`,`ot`.`amp_org_type_id` AS `org_type_id`,`cval2`.`id` as financing_instrument_id, `cval`.`id` AS `terms_assist_id` from (((((((`amp_funding` `f` join `amp_funding_detail` `fd`) join `amp_category_value` `cval`) join `amp_currency` `c`) join `amp_organisation` `d`) join `amp_org_group` `b`) join `amp_org_type` `ot`) join `amp_category_value` `cval2`) where ((`cval2`.`id` = `f`.`financing_instr_category_value_id`) and (`c`.`amp_currency_id` = `fd`.`amp_currency_id`) and (`f`.`amp_funding_id` = `fd`.`AMP_FUNDING_ID`) and (`cval`.`id` = `f`.`type_of_assistance_category_value_id`) and (`d`.`amp_org_id` = `f`.`amp_donor_org_id`) and (`d`.`org_grp_id` = `b`.`amp_org_grp_id`) and (`ot`.`amp_org_type_id` = `d`.`org_type_id`)) order by `f`.`amp_activity_id`;
CREATE OR REPLACE VIEW `v_contribution_funding` AS select `eu`.`amp_activity_id` AS `amp_activity_id`,`eu`.`id` AS `amp_funding_id`,`euc`.`id` AS `amp_funding_detail_id`,`o`.`name` AS `donor_name`,`euc`.`amount` AS `transaction_amount`,`euc`.`transaction_date` AS `transaction_date`,`c`.`currency_code` AS `currency_code`,`acv_term`.`category_value` AS `terms_assist_name`,`acv_mod`.`category_value` AS `financing_instrument_name`,`o`.`amp_org_id` AS `amp_org_id`,`o`.`org_grp_id` AS `org_grp_id`,`acv_term`.`id` AS `terms_assist_id` from (((((`amp_eu_activity` `eu` join `amp_eu_activity_contributions` `euc`) join `amp_currency` `c`) join `amp_category_value` `acv_term`) join `amp_category_value` `acv_mod`) join `amp_organisation` `o`) where ((`eu`.`id` = `euc`.`eu_activity_id`) and (`euc`.`amount_currency` = `c`.`amp_currency_id`) and (`acv_term`.`id` = `euc`.`financing_type_categ_val_id`) and (`acv_mod`.`id` = `euc`.`financing_instr_category_value_id`) and (`o`.`amp_org_id` = `euc`.`donor_id`)) order by `eu`.`amp_activity_id`;
CREATE OR REPLACE VIEW `v_financing_instrument` AS (select `f`.`amp_activity_id` AS `amp_activity_id`,`val`.`category_value` AS `name`,`f`.`financing_instr_category_value_id` AS `amp_modality_id` from (`amp_funding` `f` join `amp_category_value` `val`) where (`f`.`financing_instr_category_value_id` = `val`.`id`)) union (select `eu`.`amp_activity_id` AS `amp_activity_id`,`val`.`category_value` AS `category_value`,`eu_con`.`financing_instr_category_value_id` AS `financing_instr_category_value_id` from ((`amp_eu_activity` `eu` join `amp_eu_activity_contributions` `eu_con`) join `amp_category_value` `val`) where ((`eu_con`.`eu_activity_id` = `eu`.`id`) and (`eu_con`.`financing_instr_category_value_id` = `val`.`id`))) order by `amp_activity_id`,`name`;
CREATE OR REPLACE VIEW `v_regional_funding` AS select `f`.`activity_id` AS `amp_activity_id`,`f`.`amp_regional_funding_id` AS `amp_regional_funding_id`,`f`.`amp_regional_funding_id` AS `amp_fund_detail_id`,`r`.`name` AS `region_name`,`f`.`transaction_type` AS `transaction_type`,`f`.`adjustment_type` AS `adjustment_type`,`f`.`transaction_date` AS `transaction_date`,`f`.`transaction_amount` AS `transaction_amount`,`c`.`currency_code` AS `currency_code`,`f`.`region_id` AS `region_id` from ((`amp_regional_funding` `f` join `amp_region` `r`) join `amp_currency` `c`) where ((`c`.`amp_currency_id` = `f`.`currency_id`) and (`f`.`region_id` = `r`.`amp_region_id`)) order by `f`.`activity_id`;
TRUNCATE TABLE amp_columns_filters;
INSERT INTO `amp_columns_filters` VALUES (1,getReportColumnId('Primary Sector'),'selectedSecondarySectors','amp_sector_id')
,(2,getReportColumnId('National Planning Objectives'),'selectedNatPlanObj','amp_program_id')
,(3,getReportColumnId('Primary Program'),'selectedPrimaryPrograms','amp_program_id')
,(4,getReportColumnId('Secondary Program'),'selectedSecondaryPrograms','amp_program_id')
,(5,getReportColumnId('Region'),'regionSelected','region_id')
,(6,getReportColumnId('Executing Agency'),'executingAgency','amp_org_id')
,(7,getReportColumnId('Implementing Agency'),'implementingAgency','amp_org_id')
,(8,getReportColumnId('Beneficiary Agency'),'beneficiaryAgency','amp_org_id')
,(9,getReportColumnId('Financing Instrument'),'financingInstruments','amp_modality_id')
,(10,getReportColumnId('Type Of Assistance'),'typeOfAssistance','terms_assist_code')
,(11,getReportColumnId('Donor Group'),'donorGroups','amp_org_grp_id')
,(12,getReportColumnId('Donor Type'),'donorTypes','org_type_id')
,(13,getReportColumnId('Donor Agency'),'donorGroups','org_grp_id')
,(14,getReportColumnId('Donor Agency'),'donorTypes','org_type_id')
,(15,getReportColumnId('Primary Sector'),'selectedSectors','amp_sector_id');