ALTER TABLE `dg_user` DROP COLUMN `LAST_VISIT`;
ALTER TABLE `dg_user` DROP COLUMN `SECOND_TO_LAST_VISIT`;
ALTER TABLE `dg_user` DROP COLUMN `NUMBER_OF_SESSIONS`;
ALTER TABLE `dg_user` DROP COLUMN `ORGANIZATION`;
ALTER TABLE `amp_modules_visibility` DROP COLUMN `type`;
DROP VIEW IF EXISTS v_terms_assist;