// Generated by delombok at Mon Mar 24 00:10:06 EET 2014
package org.digijava.module.fundingpledges.form;

import org.digijava.module.aim.dbentity.AmpCurrency;
import org.digijava.module.aim.util.Identifiable;
import org.digijava.module.categorymanager.dbentity.AmpCategoryValue;
import org.digijava.module.fundingpledges.dbentity.FundingPledgesDetails;

public class FundingPledgesDetailsShim implements UniquelyIdentifiable {
	private Long pledgeTypeId;
	private Long typeOfAssistanceId;
	private Long aidModalityId;
	private Double amount;
	private Long currencyId;
	private Long fundingYear;
	private long uniqueId = PledgeForm.uniqueIds.getAndIncrement();
	
	public FundingPledgesDetailsShim(AmpCurrency currency) {
		this.amount = 0.0;
		this.currencyId = currency.getAmpCurrencyId();
	}
	
	public FundingPledgesDetailsShim(FundingPledgesDetails fpd) {
		this.pledgeTypeId = getIdFrom(fpd.getPledgetype());
		this.typeOfAssistanceId = getIdFrom(fpd.getTypeOfAssistance());
		this.aidModalityId = getIdFrom(fpd.getAidmodality());
		this.amount = fpd.getAmount();
		this.currencyId = getIdFrom(fpd.getCurrency());
		this.fundingYear = getLongFrom(fpd.getFundingYear());
	}
	
	public static Long getIdFrom(Identifiable id) {
		return id == null ? null : (Long)id.getIdentifier();
	}
	
	public static Long getLongFrom(String z) {
		if (z == null) return null;
		try {
			return Long.parseLong(z);
		} catch (Exception e) {
			return null;
		}
	}
	
	@java.lang.SuppressWarnings("all")
	public Long getPledgeTypeId() {
		return this.pledgeTypeId;
	}
	
	@java.lang.SuppressWarnings("all")
	public Long getTypeOfAssistanceId() {
		return this.typeOfAssistanceId;
	}
	
	@java.lang.SuppressWarnings("all")
	public Long getAidModalityId() {
		return this.aidModalityId;
	}
	
	@java.lang.SuppressWarnings("all")
	public Double getAmount() {
		return this.amount;
	}
	
	@java.lang.SuppressWarnings("all")
	public Long getCurrencyId() {
		return this.currencyId;
	}
	
	@java.lang.SuppressWarnings("all")
	public Long getFundingYear() {
		return this.fundingYear;
	}
	
	@java.lang.SuppressWarnings("all")
	public long getUniqueId() {
		return this.uniqueId;
	}
	
	@java.lang.SuppressWarnings("all")
	public void setPledgeTypeId(final Long pledgeTypeId) {
		this.pledgeTypeId = pledgeTypeId;
	}
	
	@java.lang.SuppressWarnings("all")
	public void setTypeOfAssistanceId(final Long typeOfAssistanceId) {
		this.typeOfAssistanceId = typeOfAssistanceId;
	}
	
	@java.lang.SuppressWarnings("all")
	public void setAidModalityId(final Long aidModalityId) {
		this.aidModalityId = aidModalityId;
	}
	
	@java.lang.SuppressWarnings("all")
	public void setAmount(final Double amount) {
		this.amount = amount;
	}
	
	@java.lang.SuppressWarnings("all")
	public void setCurrencyId(final Long currencyId) {
		this.currencyId = currencyId;
	}
	
	@java.lang.SuppressWarnings("all")
	public void setFundingYear(final Long fundingYear) {
		this.fundingYear = fundingYear;
	}
	
	@java.lang.SuppressWarnings("all")
	public void setUniqueId(final long uniqueId) {
		this.uniqueId = uniqueId;
	}
}