/**
 * 
 */
package org.dgfoundation.amp.ar.amp28;

import static org.dgfoundation.amp.testutils.ReportTestingUtils.MUST_BE_EMPTY;
import junit.framework.Test;
import junit.framework.TestSuite;

import org.dgfoundation.amp.testmodels.ColumnReportDataModel;
import org.dgfoundation.amp.testmodels.GroupColumnModel;
import org.dgfoundation.amp.testmodels.GroupReportModel;
import org.dgfoundation.amp.testmodels.SimpleColumnModel;
import org.dgfoundation.amp.testutils.ReportsTestCase;
import org.digijava.kernel.request.TLSUtils;


/**
 * Real Commitments and Real MTEFs reports tests
 * @author Constantin Dolghier
 */
public class RealCommitmentsAndMTEFs extends ReportsTestCase {

	private RealCommitmentsAndMTEFs(String name) {
		super(name);
	}
	
	@Override
    protected void setUp() throws Exception
    {
		TLSUtils.getThreadLocalInstance().setForcedLangCode("en");
		super.setUp();
        // do nothing now                
    }

	public static Test suite()
	{
		TestSuite suite = new TestSuite(PledgeReportsTests.class.getName());
		suite.addTest(new RealCommitmentsAndMTEFs("testRealCommsDisbsFlat"));
		suite.addTest(new RealCommitmentsAndMTEFs("testRealCommsDisbsByImpl"));
		suite.addTest(new RealCommitmentsAndMTEFs("testRealCommsDisbsByRegion"));
		
		suite.addTest(new RealCommitmentsAndMTEFs("testRealMTEFsFlat"));
		suite.addTest(new RealCommitmentsAndMTEFs("testRealMTEFsByRegion"));
		suite.addTest(new RealCommitmentsAndMTEFs("testRealMTEFsByExec"));
		suite.addTest(new RealCommitmentsAndMTEFs("testRealMTEFsByImpl"));
		return suite;
	}
	
	public void testRealMTEFsFlat() {
		GroupReportModel cor = GroupReportModel.withColumnReports("AMP-19212-real-mtefs",
				ColumnReportDataModel.withColumns("AMP-19212-real-mtefs",
						SimpleColumnModel.withContents("Project Title", "pledged 2", "pledged 2", "Activity with Directed MTEFs", "Activity with Directed MTEFs", "Eth Water", "Eth Water", "Activity With Directed Comms and Disbs", "Activity With Directed Comms and Disbs", "Second activity with directed MTEFs", "Second activity with directed MTEFs").setIsPledge(false), 
						SimpleColumnModel.withContents("Region", "pledged 2", "Cahul County", "Activity with Directed MTEFs", "Leova County", "Eth Water", "Anenii Noi County", "Second activity with directed MTEFs", "[Drochia County, Hincesti County, Telenesti County]").setIsPledge(false), 
						SimpleColumnModel.withContents("Executing Agency", "Activity with Directed MTEFs", "[Ministry of Finance, Water Org]", "Eth Water", "[UNDP, World Bank]", "Activity With Directed Comms and Disbs", "[72 Local Public Administrations from RM, Ministry of Economy]", "Second activity with directed MTEFs", "[Norway, Water Org, World Bank]").setIsPledge(false), 
						GroupColumnModel.withSubColumns("Funding",
							GroupColumnModel.withSubColumns("2011",
								GroupColumnModel.withSubColumns("Real MTEFs",
									SimpleColumnModel.withContents("DN-IMPL", "Activity with Directed MTEFs", "500 000").setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-EXEC", "Second activity with directed MTEFs", "60 000").setIsPledge(false))), 
							GroupColumnModel.withSubColumns("2012",
								GroupColumnModel.withSubColumns("Real MTEFs",
									SimpleColumnModel.withContents("DN-BENF", "Activity with Directed MTEFs", "401 606,43").setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-BENF", "Second activity with directed MTEFs", "35 000").setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-IMPL", "Second activity with directed MTEFs", "40 000").setIsPledge(false))), 
							GroupColumnModel.withSubColumns("2014",
								GroupColumnModel.withSubColumns("Real MTEFs",
									SimpleColumnModel.withContents("IMPL-DN", "Second activity with directed MTEFs", "70 000").setIsPledge(false)))), 
						GroupColumnModel.withSubColumns("Total Costs",
							GroupColumnModel.withSubColumns("Real MTEFs",
								SimpleColumnModel.withContents("DN-BENF", "Activity with Directed MTEFs", "401 606,43").setIsPledge(false), 
								SimpleColumnModel.withContents("DN-IMPL", "Activity with Directed MTEFs", "500 000").setIsPledge(false), 
								SimpleColumnModel.withContents("IMPL-BENF", "Second activity with directed MTEFs", "35 000").setIsPledge(false), 
								SimpleColumnModel.withContents("IMPL-DN", "Second activity with directed MTEFs", "70 000").setIsPledge(false), 
								SimpleColumnModel.withContents("IMPL-EXEC", "Second activity with directed MTEFs", "60 000").setIsPledge(false), 
								SimpleColumnModel.withContents("IMPL-IMPL", "Second activity with directed MTEFs", "40 000").setIsPledge(false))))
					.withTrailCells(null, null, null, "500 000", "60 000", "401 606,43", "35 000", "40 000", "70 000", "401 606,43", "500 000", "35 000", "70 000", "60 000", "40 000"))
				.withTrailCells(null, null, null, "500 000", "60 000", "401 606,43", "35 000", "40 000", "70 000", "401 606,43", "500 000", "35 000", "70 000", "60 000", "40 000")
				.withPositionDigest(true,
					"(line 0:RHLC Project Title: (startRow: 0, rowSpan: 4, totalRowSpan: 4, colStart: 0, colSpan: 1), RHLC Region: (startRow: 0, rowSpan: 4, totalRowSpan: 4, colStart: 1, colSpan: 1), RHLC Executing Agency: (startRow: 0, rowSpan: 4, totalRowSpan: 4, colStart: 2, colSpan: 1), RHLC Funding: (startRow: 0, rowSpan: 1, totalRowSpan: 4, colStart: 3, colSpan: 6), RHLC Total Costs: (startRow: 0, rowSpan: 2, totalRowSpan: 4, colStart: 9, colSpan: 6))",
					"(line 1:RHLC 2011: (startRow: 1, rowSpan: 1, totalRowSpan: 3, colStart: 3, colSpan: 2), RHLC 2012: (startRow: 1, rowSpan: 1, totalRowSpan: 3, colStart: 5, colSpan: 3), RHLC 2014: (startRow: 1, rowSpan: 1, totalRowSpan: 3, colStart: 8, colSpan: 1))",
					"(line 2:RHLC Real MTEFs: (startRow: 2, rowSpan: 1, totalRowSpan: 2, colStart: 3, colSpan: 2), RHLC Real MTEFs: (startRow: 2, rowSpan: 1, totalRowSpan: 2, colStart: 5, colSpan: 3), RHLC Real MTEFs: (startRow: 2, rowSpan: 1, totalRowSpan: 2, colStart: 8, colSpan: 1), RHLC Real MTEFs: (startRow: 2, rowSpan: 1, totalRowSpan: 2, colStart: 9, colSpan: 6))",
					"(line 3:RHLC DN-IMPL: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 3, colSpan: 1), RHLC IMPL-EXEC: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 4, colSpan: 1), RHLC DN-BENF: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 5, colSpan: 1), RHLC IMPL-BENF: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 6, colSpan: 1), RHLC IMPL-IMPL: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 7, colSpan: 1), RHLC IMPL-DN: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 8, colSpan: 1), RHLC DN-BENF: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 9, colSpan: 1), RHLC DN-IMPL: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 10, colSpan: 1), RHLC IMPL-BENF: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 11, colSpan: 1), RHLC IMPL-DN: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 12, colSpan: 1), RHLC IMPL-EXEC: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 13, colSpan: 1), RHLC IMPL-IMPL: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 14, colSpan: 1))");
		
		runReportTest("Report With Real MTEFs Flat", "AMP-19212-real-mtefs", new String[] {"Eth Water", "pledged 2", "Activity with Directed MTEFs", "Activity With Directed Comms and Disbs", "Second activity with directed MTEFs"}, 
				cor, null, "en");
	}
	
	public void testRealMTEFsByRegion() {
		GroupReportModel cor = GroupReportModel.withGroupReports("AMP-19212-real-mtefs-by-region",
				GroupReportModel.withColumnReports("AMP-19212-real-mtefs-by-region",
						ColumnReportDataModel.withColumns("Region: Drochia County",
							SimpleColumnModel.withContents("Project Title", "Second activity with directed MTEFs", "Second activity with directed MTEFs").setIsPledge(false), 
							SimpleColumnModel.withContents("Executing Agency", "Second activity with directed MTEFs", "[Norway, Water Org, World Bank]").setIsPledge(false), 
							GroupColumnModel.withSubColumns("Funding",
								GroupColumnModel.withSubColumns("2011",
									GroupColumnModel.withSubColumns("Real MTEFs",
										SimpleColumnModel.withContents("DN-IMPL", MUST_BE_EMPTY).setIsPledge(false), 
										SimpleColumnModel.withContents("IMPL-EXEC", "Second activity with directed MTEFs", "18 000").setIsPledge(false))), 
								GroupColumnModel.withSubColumns("2012",
									GroupColumnModel.withSubColumns("Real MTEFs",
										SimpleColumnModel.withContents("DN-BENF", MUST_BE_EMPTY).setIsPledge(false), 
										SimpleColumnModel.withContents("IMPL-BENF", "Second activity with directed MTEFs", "10 500").setIsPledge(false), 
										SimpleColumnModel.withContents("IMPL-IMPL", "Second activity with directed MTEFs", "12 000").setIsPledge(false))), 
								GroupColumnModel.withSubColumns("2014",
									GroupColumnModel.withSubColumns("Real MTEFs",
										SimpleColumnModel.withContents("IMPL-DN", "Second activity with directed MTEFs", "21 000").setIsPledge(false)))), 
							GroupColumnModel.withSubColumns("Total Costs",
								GroupColumnModel.withSubColumns("Real MTEFs",
									SimpleColumnModel.withContents("DN-BENF", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("DN-IMPL", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-BENF", "Second activity with directed MTEFs", "10 500").setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-DN", "Second activity with directed MTEFs", "21 000").setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-EXEC", "Second activity with directed MTEFs", "18 000").setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-IMPL", "Second activity with directed MTEFs", "12 000").setIsPledge(false))))
						.withTrailCells(null, null, "0", "18 000", "0", "10 500", "12 000", "21 000", "0", "0", "10 500", "21 000", "18 000", "12 000"),
						ColumnReportDataModel.withColumns("Region: Hincesti County",
							SimpleColumnModel.withContents("Project Title", "Second activity with directed MTEFs", "Second activity with directed MTEFs").setIsPledge(false), 
							SimpleColumnModel.withContents("Executing Agency", "Second activity with directed MTEFs", "[Norway, Water Org, World Bank]").setIsPledge(false), 
							GroupColumnModel.withSubColumns("Funding",
								GroupColumnModel.withSubColumns("2011",
									GroupColumnModel.withSubColumns("Real MTEFs",
										SimpleColumnModel.withContents("DN-IMPL", MUST_BE_EMPTY).setIsPledge(false), 
										SimpleColumnModel.withContents("IMPL-EXEC", "Second activity with directed MTEFs", "36 000").setIsPledge(false))), 
								GroupColumnModel.withSubColumns("2012",
									GroupColumnModel.withSubColumns("Real MTEFs",
										SimpleColumnModel.withContents("DN-BENF", MUST_BE_EMPTY).setIsPledge(false), 
										SimpleColumnModel.withContents("IMPL-BENF", "Second activity with directed MTEFs", "21 000").setIsPledge(false), 
										SimpleColumnModel.withContents("IMPL-IMPL", "Second activity with directed MTEFs", "24 000").setIsPledge(false))), 
								GroupColumnModel.withSubColumns("2014",
									GroupColumnModel.withSubColumns("Real MTEFs",
										SimpleColumnModel.withContents("IMPL-DN", "Second activity with directed MTEFs", "42 000").setIsPledge(false)))), 
							GroupColumnModel.withSubColumns("Total Costs",
								GroupColumnModel.withSubColumns("Real MTEFs",
									SimpleColumnModel.withContents("DN-BENF", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("DN-IMPL", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-BENF", "Second activity with directed MTEFs", "21 000").setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-DN", "Second activity with directed MTEFs", "42 000").setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-EXEC", "Second activity with directed MTEFs", "36 000").setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-IMPL", "Second activity with directed MTEFs", "24 000").setIsPledge(false))))
						.withTrailCells(null, null, "0", "36 000", "0", "21 000", "24 000", "42 000", "0", "0", "21 000", "42 000", "36 000", "24 000"),
						ColumnReportDataModel.withColumns("Region: Leova County",
							SimpleColumnModel.withContents("Project Title", "Activity with Directed MTEFs", "Activity with Directed MTEFs").setIsPledge(false), 
							SimpleColumnModel.withContents("Executing Agency", "Activity with Directed MTEFs", "[Ministry of Finance, Water Org]").setIsPledge(false), 
							GroupColumnModel.withSubColumns("Funding",
								GroupColumnModel.withSubColumns("2011",
									GroupColumnModel.withSubColumns("Real MTEFs",
										SimpleColumnModel.withContents("DN-IMPL", "Activity with Directed MTEFs", "500 000").setIsPledge(false), 
										SimpleColumnModel.withContents("IMPL-EXEC", MUST_BE_EMPTY).setIsPledge(false))), 
								GroupColumnModel.withSubColumns("2012",
									GroupColumnModel.withSubColumns("Real MTEFs",
										SimpleColumnModel.withContents("DN-BENF", "Activity with Directed MTEFs", "401 606,43").setIsPledge(false), 
										SimpleColumnModel.withContents("IMPL-BENF", MUST_BE_EMPTY).setIsPledge(false), 
										SimpleColumnModel.withContents("IMPL-IMPL", MUST_BE_EMPTY).setIsPledge(false))), 
								GroupColumnModel.withSubColumns("2014",
									GroupColumnModel.withSubColumns("Real MTEFs",
										SimpleColumnModel.withContents("IMPL-DN", MUST_BE_EMPTY).setIsPledge(false)))), 
							GroupColumnModel.withSubColumns("Total Costs",
								GroupColumnModel.withSubColumns("Real MTEFs",
									SimpleColumnModel.withContents("DN-BENF", "Activity with Directed MTEFs", "401 606,43").setIsPledge(false), 
									SimpleColumnModel.withContents("DN-IMPL", "Activity with Directed MTEFs", "500 000").setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-BENF", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-DN", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-EXEC", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-IMPL", MUST_BE_EMPTY).setIsPledge(false))))
						.withTrailCells(null, null, "500 000", "0", "401 606,43", "0", "0", "0", "401 606,43", "500 000", "0", "0", "0", "0"),
						ColumnReportDataModel.withColumns("Region: Telenesti County",
							SimpleColumnModel.withContents("Project Title", "Second activity with directed MTEFs", "Second activity with directed MTEFs").setIsPledge(false), 
							SimpleColumnModel.withContents("Executing Agency", "Second activity with directed MTEFs", "[Norway, Water Org, World Bank]").setIsPledge(false), 
							GroupColumnModel.withSubColumns("Funding",
								GroupColumnModel.withSubColumns("2011",
									GroupColumnModel.withSubColumns("Real MTEFs",
										SimpleColumnModel.withContents("DN-IMPL", MUST_BE_EMPTY).setIsPledge(false), 
										SimpleColumnModel.withContents("IMPL-EXEC", "Second activity with directed MTEFs", "6 000").setIsPledge(false))), 
								GroupColumnModel.withSubColumns("2012",
									GroupColumnModel.withSubColumns("Real MTEFs",
										SimpleColumnModel.withContents("DN-BENF", MUST_BE_EMPTY).setIsPledge(false), 
										SimpleColumnModel.withContents("IMPL-BENF", "Second activity with directed MTEFs", "3 500").setIsPledge(false), 
										SimpleColumnModel.withContents("IMPL-IMPL", "Second activity with directed MTEFs", "4 000").setIsPledge(false))), 
								GroupColumnModel.withSubColumns("2014",
									GroupColumnModel.withSubColumns("Real MTEFs",
										SimpleColumnModel.withContents("IMPL-DN", "Second activity with directed MTEFs", "7 000").setIsPledge(false)))), 
							GroupColumnModel.withSubColumns("Total Costs",
								GroupColumnModel.withSubColumns("Real MTEFs",
									SimpleColumnModel.withContents("DN-BENF", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("DN-IMPL", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-BENF", "Second activity with directed MTEFs", "3 500").setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-DN", "Second activity with directed MTEFs", "7 000").setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-EXEC", "Second activity with directed MTEFs", "6 000").setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-IMPL", "Second activity with directed MTEFs", "4 000").setIsPledge(false))))
						.withTrailCells(null, null, "0", "6 000", "0", "3 500", "4 000", "7 000", "0", "0", "3 500", "7 000", "6 000", "4 000"))
					.withTrailCells(null, null, "500 000", "60 000", "401 606,43", "35 000", "40 000", "70 000", "401 606,43", "500 000", "35 000", "70 000", "60 000", "40 000"))
				.withTrailCells(null, null, "500 000", "60 000", "401 606,43", "35 000", "40 000", "70 000", "401 606,43", "500 000", "35 000", "70 000", "60 000", "40 000")
				.withPositionDigest(true,
					"(line 0:RHLC Project Title: (startRow: 0, rowSpan: 4, totalRowSpan: 4, colStart: 0, colSpan: 1), RHLC Executing Agency: (startRow: 0, rowSpan: 4, totalRowSpan: 4, colStart: 1, colSpan: 1), RHLC Funding: (startRow: 0, rowSpan: 1, totalRowSpan: 4, colStart: 2, colSpan: 6), RHLC Total Costs: (startRow: 0, rowSpan: 2, totalRowSpan: 4, colStart: 8, colSpan: 6))",
					"(line 1:RHLC 2011: (startRow: 1, rowSpan: 1, totalRowSpan: 3, colStart: 2, colSpan: 2), RHLC 2012: (startRow: 1, rowSpan: 1, totalRowSpan: 3, colStart: 4, colSpan: 3), RHLC 2014: (startRow: 1, rowSpan: 1, totalRowSpan: 3, colStart: 7, colSpan: 1))",
					"(line 2:RHLC Real MTEFs: (startRow: 2, rowSpan: 1, totalRowSpan: 2, colStart: 2, colSpan: 2), RHLC Real MTEFs: (startRow: 2, rowSpan: 1, totalRowSpan: 2, colStart: 4, colSpan: 3), RHLC Real MTEFs: (startRow: 2, rowSpan: 1, totalRowSpan: 2, colStart: 7, colSpan: 1), RHLC Real MTEFs: (startRow: 2, rowSpan: 1, totalRowSpan: 2, colStart: 8, colSpan: 6))",
					"(line 3:RHLC DN-IMPL: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 2, colSpan: 1), RHLC IMPL-EXEC: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 3, colSpan: 1), RHLC DN-BENF: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 4, colSpan: 1), RHLC IMPL-BENF: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 5, colSpan: 1), RHLC IMPL-IMPL: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 6, colSpan: 1), RHLC IMPL-DN: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 7, colSpan: 1), RHLC DN-BENF: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 8, colSpan: 1), RHLC DN-IMPL: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 9, colSpan: 1), RHLC IMPL-BENF: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 10, colSpan: 1), RHLC IMPL-DN: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 11, colSpan: 1), RHLC IMPL-EXEC: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 12, colSpan: 1), RHLC IMPL-IMPL: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 13, colSpan: 1))");
		
		runReportTest("Report With Real MTEFs By Region", "AMP-19212-real-mtefs-by-region", new String[] {"Eth Water", "pledged 2", "Activity with Directed MTEFs", "Activity With Directed Comms and Disbs", "Second activity with directed MTEFs"}, 
				cor, null, "en");
	}

	public void testRealMTEFsByImpl() {
		GroupReportModel cor = GroupReportModel.withGroupReports("AMP-19212-real-mtefs-by-impl",
				GroupReportModel.withColumnReports("AMP-19212-real-mtefs-by-impl",
						ColumnReportDataModel.withColumns("Implementing Agency: Ministry of Finance",
							SimpleColumnModel.withContents("Project Title", "Activity with Directed MTEFs", "Activity with Directed MTEFs", "Second activity with directed MTEFs", "Second activity with directed MTEFs").setIsPledge(false), 
							SimpleColumnModel.withContents("Region", "Activity with Directed MTEFs", "Leova County", "Second activity with directed MTEFs", "[Drochia County, Hincesti County, Telenesti County]").setIsPledge(false), 
							GroupColumnModel.withSubColumns("Funding",
								GroupColumnModel.withSubColumns("2011",
									GroupColumnModel.withSubColumns("Real MTEFs",
										SimpleColumnModel.withContents("DN-IMPL", "Activity with Directed MTEFs", "500 000").setIsPledge(false), 
										SimpleColumnModel.withContents("IMPL-EXEC", "Second activity with directed MTEFs", "60 000").setIsPledge(false))), 
								GroupColumnModel.withSubColumns("2012",
									GroupColumnModel.withSubColumns("Real MTEFs",
										SimpleColumnModel.withContents("IMPL-BENF", "Second activity with directed MTEFs", "35 000").setIsPledge(false), 
										SimpleColumnModel.withContents("IMPL-IMPL", MUST_BE_EMPTY).setIsPledge(false))), 
								GroupColumnModel.withSubColumns("2014",
									GroupColumnModel.withSubColumns("Real MTEFs",
										SimpleColumnModel.withContents("IMPL-DN", MUST_BE_EMPTY).setIsPledge(false)))), 
							GroupColumnModel.withSubColumns("Total Costs",
								GroupColumnModel.withSubColumns("Real MTEFs",
									SimpleColumnModel.withContents("DN-IMPL", "Activity with Directed MTEFs", "500 000").setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-BENF", "Second activity with directed MTEFs", "35 000").setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-DN", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-EXEC", "Second activity with directed MTEFs", "60 000").setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-IMPL", MUST_BE_EMPTY).setIsPledge(false))))
						.withTrailCells(null, null, "500 000", "60 000", "35 000", "0", "0", "500 000", "35 000", "0", "60 000", "0"),
						ColumnReportDataModel.withColumns("Implementing Agency: UNDP",
							SimpleColumnModel.withContents("Project Title", "Second activity with directed MTEFs", "Second activity with directed MTEFs").setIsPledge(false), 
							SimpleColumnModel.withContents("Region", "Second activity with directed MTEFs", "[Drochia County, Hincesti County, Telenesti County]").setIsPledge(false), 
							GroupColumnModel.withSubColumns("Funding",
								GroupColumnModel.withSubColumns("2011",
									GroupColumnModel.withSubColumns("Real MTEFs",
										SimpleColumnModel.withContents("DN-IMPL", MUST_BE_EMPTY).setIsPledge(false), 
										SimpleColumnModel.withContents("IMPL-EXEC", MUST_BE_EMPTY).setIsPledge(false))), 
								GroupColumnModel.withSubColumns("2012",
									GroupColumnModel.withSubColumns("Real MTEFs",
										SimpleColumnModel.withContents("IMPL-BENF", MUST_BE_EMPTY).setIsPledge(false), 
										SimpleColumnModel.withContents("IMPL-IMPL", MUST_BE_EMPTY).setIsPledge(false))), 
								GroupColumnModel.withSubColumns("2014",
									GroupColumnModel.withSubColumns("Real MTEFs",
										SimpleColumnModel.withContents("IMPL-DN", "Second activity with directed MTEFs", "70 000").setIsPledge(false)))), 
							GroupColumnModel.withSubColumns("Total Costs",
								GroupColumnModel.withSubColumns("Real MTEFs",
									SimpleColumnModel.withContents("DN-IMPL", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-BENF", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-DN", "Second activity with directed MTEFs", "70 000").setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-EXEC", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-IMPL", MUST_BE_EMPTY).setIsPledge(false))))
						.withTrailCells(null, null, "0", "0", "0", "0", "70 000", "0", "0", "70 000", "0", "0"))
					.withTrailCells(null, null, "500 000", "60 000", "35 000", "0", "70 000", "500 000", "35 000", "70 000", "60 000", "0"))
				.withTrailCells(null, null, "500 000", "60 000", "35 000", "0", "70 000", "500 000", "35 000", "70 000", "60 000", "0")
				.withPositionDigest(true,
					"(line 0:RHLC Project Title: (startRow: 0, rowSpan: 4, totalRowSpan: 4, colStart: 0, colSpan: 1), RHLC Region: (startRow: 0, rowSpan: 4, totalRowSpan: 4, colStart: 1, colSpan: 1), RHLC Funding: (startRow: 0, rowSpan: 1, totalRowSpan: 4, colStart: 2, colSpan: 5), RHLC Total Costs: (startRow: 0, rowSpan: 2, totalRowSpan: 4, colStart: 7, colSpan: 5))",
					"(line 1:RHLC 2011: (startRow: 1, rowSpan: 1, totalRowSpan: 3, colStart: 2, colSpan: 2), RHLC 2012: (startRow: 1, rowSpan: 1, totalRowSpan: 3, colStart: 4, colSpan: 2), RHLC 2014: (startRow: 1, rowSpan: 1, totalRowSpan: 3, colStart: 6, colSpan: 1))",
					"(line 2:RHLC Real MTEFs: (startRow: 2, rowSpan: 1, totalRowSpan: 2, colStart: 2, colSpan: 2), RHLC Real MTEFs: (startRow: 2, rowSpan: 1, totalRowSpan: 2, colStart: 4, colSpan: 2), RHLC Real MTEFs: (startRow: 2, rowSpan: 1, totalRowSpan: 2, colStart: 6, colSpan: 1), RHLC Real MTEFs: (startRow: 2, rowSpan: 1, totalRowSpan: 2, colStart: 7, colSpan: 5))",
					"(line 3:RHLC DN-IMPL: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 2, colSpan: 1), RHLC IMPL-EXEC: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 3, colSpan: 1), RHLC IMPL-BENF: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 4, colSpan: 1), RHLC IMPL-IMPL: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 5, colSpan: 1), RHLC IMPL-DN: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 6, colSpan: 1), RHLC DN-IMPL: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 7, colSpan: 1), RHLC IMPL-BENF: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 8, colSpan: 1), RHLC IMPL-DN: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 9, colSpan: 1), RHLC IMPL-EXEC: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 10, colSpan: 1), RHLC IMPL-IMPL: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 11, colSpan: 1))");
		
		runReportTest("Report With Real MTEFs By Impl", "AMP-19212-real-mtefs-by-impl", new String[] {"Eth Water", "pledged 2", "Activity with Directed MTEFs", "Activity With Directed Comms and Disbs", "Second activity with directed MTEFs"}, 
				cor, null, "en");
	}

	public void testRealMTEFsByExec() {
		GroupReportModel cor = GroupReportModel.withGroupReports("AMP-19212-real-mtefs-by-executing",
				GroupReportModel.withColumnReports("AMP-19212-real-mtefs-by-executing",
						ColumnReportDataModel.withColumns("Executing Agency: Water Org",
							SimpleColumnModel.withContents("Project Title", "Second activity with directed MTEFs", "Second activity with directed MTEFs").setIsPledge(false), 
							SimpleColumnModel.withContents("Region", "Second activity with directed MTEFs", "[Drochia County, Hincesti County, Telenesti County]").setIsPledge(false), 
							GroupColumnModel.withSubColumns("Funding",
								GroupColumnModel.withSubColumns("2011",
									GroupColumnModel.withSubColumns("Real MTEFs",
										SimpleColumnModel.withContents("IMPL-EXEC", "Second activity with directed MTEFs", "60 000").setIsPledge(false)))), 
							GroupColumnModel.withSubColumns("Total Costs",
								GroupColumnModel.withSubColumns("Real MTEFs",
									SimpleColumnModel.withContents("IMPL-EXEC", "Second activity with directed MTEFs", "60 000").setIsPledge(false))))
						.withTrailCells(null, null, "60 000", "60 000"))
					.withTrailCells(null, null, "60 000", "60 000"))
				.withTrailCells(null, null, "60 000", "60 000")
				.withPositionDigest(true,
					"(line 0:RHLC Project Title: (startRow: 0, rowSpan: 4, totalRowSpan: 4, colStart: 0, colSpan: 1), RHLC Region: (startRow: 0, rowSpan: 4, totalRowSpan: 4, colStart: 1, colSpan: 1), RHLC Funding: (startRow: 0, rowSpan: 1, totalRowSpan: 4, colStart: 2, colSpan: 1), RHLC Total Costs: (startRow: 0, rowSpan: 2, totalRowSpan: 4, colStart: 3, colSpan: 1))",
					"(line 1:RHLC 2011: (startRow: 1, rowSpan: 1, totalRowSpan: 3, colStart: 2, colSpan: 1))",
					"(line 2:RHLC Real MTEFs: (startRow: 2, rowSpan: 1, totalRowSpan: 2, colStart: 2, colSpan: 1), RHLC Real MTEFs: (startRow: 2, rowSpan: 1, totalRowSpan: 2, colStart: 3, colSpan: 1))",
					"(line 3:RHLC IMPL-EXEC: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 2, colSpan: 1), RHLC IMPL-EXEC: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 3, colSpan: 1))");
		
		runReportTest("Report With Real MTEFs By Exec", "AMP-19212-real-mtefs-by-executing", new String[] {"Eth Water", "pledged 2", "Activity with Directed MTEFs", "Activity With Directed Comms and Disbs", "Second activity with directed MTEFs"}, 
				cor, null, "en");
	}

	
	public void testRealCommsDisbsFlat() {
		GroupReportModel summaryTotalsOnly = GroupReportModel.withColumnReports("AMP-19212-Actual-Real-Commitments",
				ColumnReportDataModel.withColumns("AMP-19212-Actual-Real-Commitments",
						SimpleColumnModel.withContents("Project Title", "pledged 2", "pledged 2", "Activity with Directed MTEFs", "Activity with Directed MTEFs", "Eth Water", "Eth Water", "Activity With Directed Comms and Disbs", "Activity With Directed Comms and Disbs").setIsPledge(false), 
						SimpleColumnModel.withContents("Region", "pledged 2", "Cahul County", "Activity with Directed MTEFs", "Leova County", "Eth Water", "Anenii Noi County").setIsPledge(false), 
						GroupColumnModel.withSubColumns("Funding",
							GroupColumnModel.withSubColumns("2013",
								SimpleColumnModel.withContents("Actual Commitments", "pledged 2", "2 670 000").setIsPledge(false), 
								GroupColumnModel.withSubColumns("Real Commitments",
									SimpleColumnModel.withContents("IMPL-EXEC", "Activity With Directed Comms and Disbs", "20 000").setIsPledge(false)), 
								SimpleColumnModel.withContents("Actual Disbursements", "Eth Water", "545 000").setIsPledge(false), 
								GroupColumnModel.withSubColumns("Real Disbursements",
									SimpleColumnModel.withContents("DN-EXEC", "Eth Water", "545 000").setIsPledge(false), 
									SimpleColumnModel.withContents("EXEC-IMPL", "Eth Water", "100 000").setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-BENF", "Eth Water", "15 000").setIsPledge(false))), 
							GroupColumnModel.withSubColumns("2014",
								SimpleColumnModel.withContents("Actual Commitments", "pledged 2", "4 400 000").setIsPledge(false), 
								GroupColumnModel.withSubColumns("Real Commitments",
									SimpleColumnModel.withContents("IMPL-EXEC", "Activity With Directed Comms and Disbs", "20 000").setIsPledge(false)), 
								SimpleColumnModel.withContents("Actual Disbursements", "pledged 2", "450 000").setIsPledge(false), 
								SimpleColumnModel.withContents("Real Disbursements", MUST_BE_EMPTY).setIsPledge(false)), 
							GroupColumnModel.withSubColumns("2015",
								SimpleColumnModel.withContents("Actual Commitments", "Activity with Directed MTEFs", "1 200 000", "Activity With Directed Comms and Disbs", "40 000").setIsPledge(false), 
								GroupColumnModel.withSubColumns("Real Commitments",
									SimpleColumnModel.withContents("DN-IMPL", "Activity With Directed Comms and Disbs", "40 000").setIsPledge(false)), 
								SimpleColumnModel.withContents("Actual Disbursements", "Activity With Directed Comms and Disbs", "40 000").setIsPledge(false), 
								GroupColumnModel.withSubColumns("Real Disbursements",
									SimpleColumnModel.withContents("DN-IMPL", "Activity With Directed Comms and Disbs", "40 000").setIsPledge(false)))), 
						GroupColumnModel.withSubColumns("Total Costs",
							SimpleColumnModel.withContents("Actual Commitments", "pledged 2", "7 070 000", "Activity with Directed MTEFs", "1 200 000", "Activity With Directed Comms and Disbs", "40 000").setIsPledge(false), 
							GroupColumnModel.withSubColumns("Real Commitments",
								SimpleColumnModel.withContents("DN-IMPL", "Activity With Directed Comms and Disbs", "40 000").setIsPledge(false), 
								SimpleColumnModel.withContents("IMPL-EXEC", "Activity With Directed Comms and Disbs", "40 000").setIsPledge(false)), 
							SimpleColumnModel.withContents("Actual Disbursements", "pledged 2", "450 000", "Eth Water", "545 000", "Activity With Directed Comms and Disbs", "40 000").setIsPledge(false), 
							GroupColumnModel.withSubColumns("Real Disbursements",
								SimpleColumnModel.withContents("DN-EXEC", "Eth Water", "545 000").setIsPledge(false), 
								SimpleColumnModel.withContents("DN-IMPL", "Activity With Directed Comms and Disbs", "40 000").setIsPledge(false), 
								SimpleColumnModel.withContents("EXEC-IMPL", "Eth Water", "100 000").setIsPledge(false), 
								SimpleColumnModel.withContents("IMPL-BENF", "Eth Water", "15 000").setIsPledge(false))))
					.withTrailCells(null, null, "2 670 000", "20 000", "545 000", "545 000", "100 000", "15 000", "4 400 000", "20 000", "450 000", "0", "1 240 000", "40 000", "40 000", "40 000", "8 310 000", "40 000", "40 000", "1 035 000", "545 000", "40 000", "100 000", "15 000"))
				.withTrailCells(null, null, "2 670 000", "20 000", "545 000", "545 000", "100 000", "15 000", "4 400 000", "20 000", "450 000", "0", "1 240 000", "40 000", "40 000", "40 000", "8 310 000", "40 000", "40 000", "1 035 000", "545 000", "40 000", "100 000", "15 000")
				.withPositionDigest(true,
					"(line 0:RHLC Project Title: (startRow: 0, rowSpan: 4, totalRowSpan: 4, colStart: 0, colSpan: 1), RHLC Region: (startRow: 0, rowSpan: 4, totalRowSpan: 4, colStart: 1, colSpan: 1), RHLC Funding: (startRow: 0, rowSpan: 1, totalRowSpan: 4, colStart: 2, colSpan: 14), RHLC Total Costs: (startRow: 0, rowSpan: 2, totalRowSpan: 4, colStart: 16, colSpan: 8))",
					"(line 1:RHLC 2013: (startRow: 1, rowSpan: 1, totalRowSpan: 3, colStart: 2, colSpan: 6), RHLC 2014: (startRow: 1, rowSpan: 1, totalRowSpan: 3, colStart: 8, colSpan: 4), RHLC 2015: (startRow: 1, rowSpan: 1, totalRowSpan: 3, colStart: 12, colSpan: 4))",
					"(line 2:RHLC Actual Commitments: (startRow: 2, rowSpan: 2, totalRowSpan: 2, colStart: 2, colSpan: 1), RHLC Real Commitments: (startRow: 2, rowSpan: 1, totalRowSpan: 2, colStart: 3, colSpan: 1), RHLC Actual Disbursements: (startRow: 2, rowSpan: 2, totalRowSpan: 2, colStart: 4, colSpan: 1), RHLC Real Disbursements: (startRow: 2, rowSpan: 1, totalRowSpan: 2, colStart: 5, colSpan: 3), RHLC Actual Commitments: (startRow: 2, rowSpan: 2, totalRowSpan: 2, colStart: 8, colSpan: 1), RHLC Real Commitments: (startRow: 2, rowSpan: 1, totalRowSpan: 2, colStart: 9, colSpan: 1), RHLC Actual Disbursements: (startRow: 2, rowSpan: 2, totalRowSpan: 2, colStart: 10, colSpan: 1), RHLC Real Disbursements: (startRow: 2, rowSpan: 2, totalRowSpan: 2, colStart: 11, colSpan: 1), RHLC Actual Commitments: (startRow: 2, rowSpan: 2, totalRowSpan: 2, colStart: 12, colSpan: 1), RHLC Real Commitments: (startRow: 2, rowSpan: 1, totalRowSpan: 2, colStart: 13, colSpan: 1), RHLC Actual Disbursements: (startRow: 2, rowSpan: 2, totalRowSpan: 2, colStart: 14, colSpan: 1), RHLC Real Disbursements: (startRow: 2, rowSpan: 1, totalRowSpan: 2, colStart: 15, colSpan: 1), RHLC Actual Commitments: (startRow: 2, rowSpan: 2, totalRowSpan: 2, colStart: 16, colSpan: 1), RHLC Real Commitments: (startRow: 2, rowSpan: 1, totalRowSpan: 2, colStart: 17, colSpan: 2), RHLC Actual Disbursements: (startRow: 2, rowSpan: 2, totalRowSpan: 2, colStart: 19, colSpan: 1), RHLC Real Disbursements: (startRow: 2, rowSpan: 1, totalRowSpan: 2, colStart: 20, colSpan: 4))",
					"(line 3:RHLC IMPL-EXEC: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 3, colSpan: 1), RHLC DN-EXEC: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 5, colSpan: 1), RHLC EXEC-IMPL: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 6, colSpan: 1), RHLC IMPL-BENF: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 7, colSpan: 1), RHLC IMPL-EXEC: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 9, colSpan: 1), RHLC DN-IMPL: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 13, colSpan: 1), RHLC DN-IMPL: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 15, colSpan: 1), RHLC DN-IMPL: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 17, colSpan: 1), RHLC IMPL-EXEC: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 18, colSpan: 1), RHLC DN-EXEC: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 20, colSpan: 1), RHLC DN-IMPL: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 21, colSpan: 1), RHLC EXEC-IMPL: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 22, colSpan: 1), RHLC IMPL-BENF: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 23, colSpan: 1))");
		
		runReportTest("Report With Real Comms and Real Disbs Flat", "AMP-19212-Actual-Real-Commitments", new String[] {"Eth Water", "pledged 2", "Activity with Directed MTEFs", "Activity With Directed Comms and Disbs"}, 
				summaryTotalsOnly, null, "en");
	}

	public void testRealCommsDisbsByImpl() {
		GroupReportModel summaryTotalsOnly = GroupReportModel.withGroupReports("AMP-19212-Actual-Real-Commitments-by-impl",
				GroupReportModel.withColumnReports("AMP-19212-Actual-Real-Commitments-by-impl",
						ColumnReportDataModel.withColumns("Implementing Agency: Implementing Agency Unallocated",
							SimpleColumnModel.withContents("Project Title", "pledged 2", "pledged 2").setIsPledge(false), 
							SimpleColumnModel.withContents("Region", "pledged 2", "Cahul County").setIsPledge(false), 
							GroupColumnModel.withSubColumns("Funding",
								GroupColumnModel.withSubColumns("2013",
									SimpleColumnModel.withContents("Actual Commitments", "pledged 2", "2 670 000").setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Commitments",
										SimpleColumnModel.withContents("IMPL-EXEC", MUST_BE_EMPTY).setIsPledge(false)), 
									SimpleColumnModel.withContents("Actual Disbursements", MUST_BE_EMPTY).setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Disbursements",
										SimpleColumnModel.withContents("EXEC-IMPL", MUST_BE_EMPTY).setIsPledge(false), 
										SimpleColumnModel.withContents("IMPL-BENF", MUST_BE_EMPTY).setIsPledge(false))), 
								GroupColumnModel.withSubColumns("2014",
									SimpleColumnModel.withContents("Actual Commitments", "pledged 2", "4 400 000").setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Commitments",
										SimpleColumnModel.withContents("IMPL-EXEC", MUST_BE_EMPTY).setIsPledge(false)), 
									SimpleColumnModel.withContents("Actual Disbursements", "pledged 2", "450 000").setIsPledge(false), 
									SimpleColumnModel.withContents("Real Disbursements", MUST_BE_EMPTY).setIsPledge(false)), 
								GroupColumnModel.withSubColumns("2015",
									SimpleColumnModel.withContents("Actual Commitments", MUST_BE_EMPTY).setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Commitments",
										SimpleColumnModel.withContents("DN-IMPL", MUST_BE_EMPTY).setIsPledge(false)), 
									SimpleColumnModel.withContents("Actual Disbursements", MUST_BE_EMPTY).setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Disbursements",
										SimpleColumnModel.withContents("DN-IMPL", MUST_BE_EMPTY).setIsPledge(false)))), 
							GroupColumnModel.withSubColumns("Total Costs",
								SimpleColumnModel.withContents("Actual Commitments", "pledged 2", "7 070 000").setIsPledge(false), 
								GroupColumnModel.withSubColumns("Real Commitments",
									SimpleColumnModel.withContents("DN-IMPL", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-EXEC", MUST_BE_EMPTY).setIsPledge(false)), 
								SimpleColumnModel.withContents("Actual Disbursements", "pledged 2", "450 000").setIsPledge(false), 
								GroupColumnModel.withSubColumns("Real Disbursements",
									SimpleColumnModel.withContents("DN-IMPL", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("EXEC-IMPL", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-BENF", MUST_BE_EMPTY).setIsPledge(false))))
						.withTrailCells(null, null, "2 670 000", "0", "0", "0", "0", "4 400 000", "0", "450 000", "0", "0", "0", "0", "0", "7 070 000", "0", "0", "450 000", "0", "0", "0"),
						ColumnReportDataModel.withColumns("Implementing Agency: Ministry of Economy",
							SimpleColumnModel.withContents("Project Title", "Eth Water", "Eth Water").setIsPledge(false), 
							SimpleColumnModel.withContents("Region", "Eth Water", "Anenii Noi County").setIsPledge(false), 
							GroupColumnModel.withSubColumns("Funding",
								GroupColumnModel.withSubColumns("2013",
									SimpleColumnModel.withContents("Actual Commitments", MUST_BE_EMPTY).setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Commitments",
										SimpleColumnModel.withContents("IMPL-EXEC", MUST_BE_EMPTY).setIsPledge(false)), 
									SimpleColumnModel.withContents("Actual Disbursements", "Eth Water", "272 500").setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Disbursements",
										SimpleColumnModel.withContents("EXEC-IMPL", "Eth Water", "50 000").setIsPledge(false), 
										SimpleColumnModel.withContents("IMPL-BENF", "Eth Water", "5 000").setIsPledge(false))), 
								GroupColumnModel.withSubColumns("2014",
									SimpleColumnModel.withContents("Actual Commitments", MUST_BE_EMPTY).setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Commitments",
										SimpleColumnModel.withContents("IMPL-EXEC", MUST_BE_EMPTY).setIsPledge(false)), 
									SimpleColumnModel.withContents("Actual Disbursements", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("Real Disbursements", MUST_BE_EMPTY).setIsPledge(false)), 
								GroupColumnModel.withSubColumns("2015",
									SimpleColumnModel.withContents("Actual Commitments", MUST_BE_EMPTY).setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Commitments",
										SimpleColumnModel.withContents("DN-IMPL", MUST_BE_EMPTY).setIsPledge(false)), 
									SimpleColumnModel.withContents("Actual Disbursements", MUST_BE_EMPTY).setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Disbursements",
										SimpleColumnModel.withContents("DN-IMPL", MUST_BE_EMPTY).setIsPledge(false)))), 
							GroupColumnModel.withSubColumns("Total Costs",
								SimpleColumnModel.withContents("Actual Commitments", MUST_BE_EMPTY).setIsPledge(false), 
								GroupColumnModel.withSubColumns("Real Commitments",
									SimpleColumnModel.withContents("DN-IMPL", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-EXEC", MUST_BE_EMPTY).setIsPledge(false)), 
								SimpleColumnModel.withContents("Actual Disbursements", "Eth Water", "272 500").setIsPledge(false), 
								GroupColumnModel.withSubColumns("Real Disbursements",
									SimpleColumnModel.withContents("DN-IMPL", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("EXEC-IMPL", "Eth Water", "50 000").setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-BENF", "Eth Water", "5 000").setIsPledge(false))))
						.withTrailCells(null, null, "0", "0", "272 500", "50 000", "5 000", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "272 500", "0", "50 000", "5 000"),
						ColumnReportDataModel.withColumns("Implementing Agency: Ministry of Finance",
							SimpleColumnModel.withContents("Project Title", "Activity with Directed MTEFs", "Activity with Directed MTEFs", "Eth Water", "Eth Water").setIsPledge(false), 
							SimpleColumnModel.withContents("Region", "Activity with Directed MTEFs", "Leova County", "Eth Water", "Anenii Noi County").setIsPledge(false), 
							GroupColumnModel.withSubColumns("Funding",
								GroupColumnModel.withSubColumns("2013",
									SimpleColumnModel.withContents("Actual Commitments", MUST_BE_EMPTY).setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Commitments",
										SimpleColumnModel.withContents("IMPL-EXEC", MUST_BE_EMPTY).setIsPledge(false)), 
									SimpleColumnModel.withContents("Actual Disbursements", "Eth Water", "272 500").setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Disbursements",
										SimpleColumnModel.withContents("EXEC-IMPL", "Eth Water", "50 000").setIsPledge(false), 
										SimpleColumnModel.withContents("IMPL-BENF", "Eth Water", "10 000").setIsPledge(false))), 
								GroupColumnModel.withSubColumns("2014",
									SimpleColumnModel.withContents("Actual Commitments", MUST_BE_EMPTY).setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Commitments",
										SimpleColumnModel.withContents("IMPL-EXEC", MUST_BE_EMPTY).setIsPledge(false)), 
									SimpleColumnModel.withContents("Actual Disbursements", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("Real Disbursements", MUST_BE_EMPTY).setIsPledge(false)), 
								GroupColumnModel.withSubColumns("2015",
									SimpleColumnModel.withContents("Actual Commitments", "Activity with Directed MTEFs", "792 000").setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Commitments",
										SimpleColumnModel.withContents("DN-IMPL", MUST_BE_EMPTY).setIsPledge(false)), 
									SimpleColumnModel.withContents("Actual Disbursements", MUST_BE_EMPTY).setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Disbursements",
										SimpleColumnModel.withContents("DN-IMPL", MUST_BE_EMPTY).setIsPledge(false)))), 
							GroupColumnModel.withSubColumns("Total Costs",
								SimpleColumnModel.withContents("Actual Commitments", "Activity with Directed MTEFs", "792 000").setIsPledge(false), 
								GroupColumnModel.withSubColumns("Real Commitments",
									SimpleColumnModel.withContents("DN-IMPL", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-EXEC", MUST_BE_EMPTY).setIsPledge(false)), 
								SimpleColumnModel.withContents("Actual Disbursements", "Eth Water", "272 500").setIsPledge(false), 
								GroupColumnModel.withSubColumns("Real Disbursements",
									SimpleColumnModel.withContents("DN-IMPL", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("EXEC-IMPL", "Eth Water", "50 000").setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-BENF", "Eth Water", "10 000").setIsPledge(false))))
						.withTrailCells(null, null, "0", "0", "272 500", "50 000", "10 000", "0", "0", "0", "0", "792 000", "0", "0", "0", "792 000", "0", "0", "272 500", "0", "50 000", "10 000"),
						ColumnReportDataModel.withColumns("Implementing Agency: USAID",
							SimpleColumnModel.withContents("Project Title", "Activity with Directed MTEFs", "Activity with Directed MTEFs").setIsPledge(false), 
							SimpleColumnModel.withContents("Region", "Activity with Directed MTEFs", "Leova County").setIsPledge(false), 
							GroupColumnModel.withSubColumns("Funding",
								GroupColumnModel.withSubColumns("2013",
									SimpleColumnModel.withContents("Actual Commitments", MUST_BE_EMPTY).setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Commitments",
										SimpleColumnModel.withContents("IMPL-EXEC", MUST_BE_EMPTY).setIsPledge(false)), 
									SimpleColumnModel.withContents("Actual Disbursements", MUST_BE_EMPTY).setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Disbursements",
										SimpleColumnModel.withContents("EXEC-IMPL", MUST_BE_EMPTY).setIsPledge(false), 
										SimpleColumnModel.withContents("IMPL-BENF", MUST_BE_EMPTY).setIsPledge(false))), 
								GroupColumnModel.withSubColumns("2014",
									SimpleColumnModel.withContents("Actual Commitments", MUST_BE_EMPTY).setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Commitments",
										SimpleColumnModel.withContents("IMPL-EXEC", MUST_BE_EMPTY).setIsPledge(false)), 
									SimpleColumnModel.withContents("Actual Disbursements", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("Real Disbursements", MUST_BE_EMPTY).setIsPledge(false)), 
								GroupColumnModel.withSubColumns("2015",
									SimpleColumnModel.withContents("Actual Commitments", "Activity with Directed MTEFs", "408 000").setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Commitments",
										SimpleColumnModel.withContents("DN-IMPL", MUST_BE_EMPTY).setIsPledge(false)), 
									SimpleColumnModel.withContents("Actual Disbursements", MUST_BE_EMPTY).setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Disbursements",
										SimpleColumnModel.withContents("DN-IMPL", MUST_BE_EMPTY).setIsPledge(false)))), 
							GroupColumnModel.withSubColumns("Total Costs",
								SimpleColumnModel.withContents("Actual Commitments", "Activity with Directed MTEFs", "408 000").setIsPledge(false), 
								GroupColumnModel.withSubColumns("Real Commitments",
									SimpleColumnModel.withContents("DN-IMPL", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-EXEC", MUST_BE_EMPTY).setIsPledge(false)), 
								SimpleColumnModel.withContents("Actual Disbursements", MUST_BE_EMPTY).setIsPledge(false), 
								GroupColumnModel.withSubColumns("Real Disbursements",
									SimpleColumnModel.withContents("DN-IMPL", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("EXEC-IMPL", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-BENF", MUST_BE_EMPTY).setIsPledge(false))))
						.withTrailCells(null, null, "0", "0", "0", "0", "0", "0", "0", "0", "0", "408 000", "0", "0", "0", "408 000", "0", "0", "0", "0", "0", "0"),
						ColumnReportDataModel.withColumns("Implementing Agency: Water Foundation",
							SimpleColumnModel.withContents("Project Title", "Activity With Directed Comms and Disbs", "Activity With Directed Comms and Disbs").setIsPledge(false), 
							SimpleColumnModel.withContents("Region", MUST_BE_EMPTY).setIsPledge(false), 
							GroupColumnModel.withSubColumns("Funding",
								GroupColumnModel.withSubColumns("2013",
									SimpleColumnModel.withContents("Actual Commitments", MUST_BE_EMPTY).setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Commitments",
										SimpleColumnModel.withContents("IMPL-EXEC", "Activity With Directed Comms and Disbs", "20 000").setIsPledge(false)), 
									SimpleColumnModel.withContents("Actual Disbursements", MUST_BE_EMPTY).setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Disbursements",
										SimpleColumnModel.withContents("EXEC-IMPL", MUST_BE_EMPTY).setIsPledge(false), 
										SimpleColumnModel.withContents("IMPL-BENF", MUST_BE_EMPTY).setIsPledge(false))), 
								GroupColumnModel.withSubColumns("2014",
									SimpleColumnModel.withContents("Actual Commitments", MUST_BE_EMPTY).setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Commitments",
										SimpleColumnModel.withContents("IMPL-EXEC", "Activity With Directed Comms and Disbs", "5 000").setIsPledge(false)), 
									SimpleColumnModel.withContents("Actual Disbursements", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("Real Disbursements", MUST_BE_EMPTY).setIsPledge(false)), 
								GroupColumnModel.withSubColumns("2015",
									SimpleColumnModel.withContents("Actual Commitments", "Activity With Directed Comms and Disbs", "26 800").setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Commitments",
										SimpleColumnModel.withContents("DN-IMPL", "Activity With Directed Comms and Disbs", "25 000").setIsPledge(false)), 
									SimpleColumnModel.withContents("Actual Disbursements", "Activity With Directed Comms and Disbs", "26 800").setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Disbursements",
										SimpleColumnModel.withContents("DN-IMPL", "Activity With Directed Comms and Disbs", "25 000").setIsPledge(false)))), 
							GroupColumnModel.withSubColumns("Total Costs",
								SimpleColumnModel.withContents("Actual Commitments", "Activity With Directed Comms and Disbs", "26 800").setIsPledge(false), 
								GroupColumnModel.withSubColumns("Real Commitments",
									SimpleColumnModel.withContents("DN-IMPL", "Activity With Directed Comms and Disbs", "25 000").setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-EXEC", "Activity With Directed Comms and Disbs", "25 000").setIsPledge(false)), 
								SimpleColumnModel.withContents("Actual Disbursements", "Activity With Directed Comms and Disbs", "26 800").setIsPledge(false), 
								GroupColumnModel.withSubColumns("Real Disbursements",
									SimpleColumnModel.withContents("DN-IMPL", "Activity With Directed Comms and Disbs", "25 000").setIsPledge(false), 
									SimpleColumnModel.withContents("EXEC-IMPL", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-BENF", MUST_BE_EMPTY).setIsPledge(false))))
						.withTrailCells(null, null, "0", "20 000", "0", "0", "0", "0", "5 000", "0", "0", "26 800", "25 000", "26 800", "25 000", "26 800", "25 000", "25 000", "26 800", "25 000", "0", "0"),
						ColumnReportDataModel.withColumns("Implementing Agency: Water Org",
							SimpleColumnModel.withContents("Project Title", "Activity With Directed Comms and Disbs", "Activity With Directed Comms and Disbs").setIsPledge(false), 
							SimpleColumnModel.withContents("Region", MUST_BE_EMPTY).setIsPledge(false), 
							GroupColumnModel.withSubColumns("Funding",
								GroupColumnModel.withSubColumns("2013",
									SimpleColumnModel.withContents("Actual Commitments", MUST_BE_EMPTY).setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Commitments",
										SimpleColumnModel.withContents("IMPL-EXEC", MUST_BE_EMPTY).setIsPledge(false)), 
									SimpleColumnModel.withContents("Actual Disbursements", MUST_BE_EMPTY).setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Disbursements",
										SimpleColumnModel.withContents("EXEC-IMPL", MUST_BE_EMPTY).setIsPledge(false), 
										SimpleColumnModel.withContents("IMPL-BENF", MUST_BE_EMPTY).setIsPledge(false))), 
								GroupColumnModel.withSubColumns("2014",
									SimpleColumnModel.withContents("Actual Commitments", MUST_BE_EMPTY).setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Commitments",
										SimpleColumnModel.withContents("IMPL-EXEC", "Activity With Directed Comms and Disbs", "15 000").setIsPledge(false)), 
									SimpleColumnModel.withContents("Actual Disbursements", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("Real Disbursements", MUST_BE_EMPTY).setIsPledge(false)), 
								GroupColumnModel.withSubColumns("2015",
									SimpleColumnModel.withContents("Actual Commitments", "Activity With Directed Comms and Disbs", "13 200").setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Commitments",
										SimpleColumnModel.withContents("DN-IMPL", "Activity With Directed Comms and Disbs", "15 000").setIsPledge(false)), 
									SimpleColumnModel.withContents("Actual Disbursements", "Activity With Directed Comms and Disbs", "13 200").setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Disbursements",
										SimpleColumnModel.withContents("DN-IMPL", "Activity With Directed Comms and Disbs", "15 000").setIsPledge(false)))), 
							GroupColumnModel.withSubColumns("Total Costs",
								SimpleColumnModel.withContents("Actual Commitments", "Activity With Directed Comms and Disbs", "13 200").setIsPledge(false), 
								GroupColumnModel.withSubColumns("Real Commitments",
									SimpleColumnModel.withContents("DN-IMPL", "Activity With Directed Comms and Disbs", "15 000").setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-EXEC", "Activity With Directed Comms and Disbs", "15 000").setIsPledge(false)), 
								SimpleColumnModel.withContents("Actual Disbursements", "Activity With Directed Comms and Disbs", "13 200").setIsPledge(false), 
								GroupColumnModel.withSubColumns("Real Disbursements",
									SimpleColumnModel.withContents("DN-IMPL", "Activity With Directed Comms and Disbs", "15 000").setIsPledge(false), 
									SimpleColumnModel.withContents("EXEC-IMPL", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-BENF", MUST_BE_EMPTY).setIsPledge(false))))
						.withTrailCells(null, null, "0", "0", "0", "0", "0", "0", "15 000", "0", "0", "13 200", "15 000", "13 200", "15 000", "13 200", "15 000", "15 000", "13 200", "15 000", "0", "0"))
					.withTrailCells(null, null, "2 670 000", "20 000", "545 000", "100 000", "15 000", "4 400 000", "20 000", "450 000", "0", "1 240 000", "40 000", "40 000", "40 000", "8 310 000", "40 000", "40 000", "1 035 000", "40 000", "100 000", "15 000"))
				.withTrailCells(null, null, "2 670 000", "20 000", "545 000", "100 000", "15 000", "4 400 000", "20 000", "450 000", "0", "1 240 000", "40 000", "40 000", "40 000", "8 310 000", "40 000", "40 000", "1 035 000", "40 000", "100 000", "15 000")
				.withPositionDigest(true,
					"(line 0:RHLC Project Title: (startRow: 0, rowSpan: 4, totalRowSpan: 4, colStart: 0, colSpan: 1), RHLC Region: (startRow: 0, rowSpan: 4, totalRowSpan: 4, colStart: 1, colSpan: 1), RHLC Funding: (startRow: 0, rowSpan: 1, totalRowSpan: 4, colStart: 2, colSpan: 13), RHLC Total Costs: (startRow: 0, rowSpan: 2, totalRowSpan: 4, colStart: 15, colSpan: 7))",
					"(line 1:RHLC 2013: (startRow: 1, rowSpan: 1, totalRowSpan: 3, colStart: 2, colSpan: 5), RHLC 2014: (startRow: 1, rowSpan: 1, totalRowSpan: 3, colStart: 7, colSpan: 4), RHLC 2015: (startRow: 1, rowSpan: 1, totalRowSpan: 3, colStart: 11, colSpan: 4))",
					"(line 2:RHLC Actual Commitments: (startRow: 2, rowSpan: 2, totalRowSpan: 2, colStart: 2, colSpan: 1), RHLC Real Commitments: (startRow: 2, rowSpan: 1, totalRowSpan: 2, colStart: 3, colSpan: 1), RHLC Actual Disbursements: (startRow: 2, rowSpan: 2, totalRowSpan: 2, colStart: 4, colSpan: 1), RHLC Real Disbursements: (startRow: 2, rowSpan: 1, totalRowSpan: 2, colStart: 5, colSpan: 2), RHLC Actual Commitments: (startRow: 2, rowSpan: 2, totalRowSpan: 2, colStart: 7, colSpan: 1), RHLC Real Commitments: (startRow: 2, rowSpan: 1, totalRowSpan: 2, colStart: 8, colSpan: 1), RHLC Actual Disbursements: (startRow: 2, rowSpan: 2, totalRowSpan: 2, colStart: 9, colSpan: 1), RHLC Real Disbursements: (startRow: 2, rowSpan: 2, totalRowSpan: 2, colStart: 10, colSpan: 1), RHLC Actual Commitments: (startRow: 2, rowSpan: 2, totalRowSpan: 2, colStart: 11, colSpan: 1), RHLC Real Commitments: (startRow: 2, rowSpan: 1, totalRowSpan: 2, colStart: 12, colSpan: 1), RHLC Actual Disbursements: (startRow: 2, rowSpan: 2, totalRowSpan: 2, colStart: 13, colSpan: 1), RHLC Real Disbursements: (startRow: 2, rowSpan: 1, totalRowSpan: 2, colStart: 14, colSpan: 1), RHLC Actual Commitments: (startRow: 2, rowSpan: 2, totalRowSpan: 2, colStart: 15, colSpan: 1), RHLC Real Commitments: (startRow: 2, rowSpan: 1, totalRowSpan: 2, colStart: 16, colSpan: 2), RHLC Actual Disbursements: (startRow: 2, rowSpan: 2, totalRowSpan: 2, colStart: 18, colSpan: 1), RHLC Real Disbursements: (startRow: 2, rowSpan: 1, totalRowSpan: 2, colStart: 19, colSpan: 3))",
					"(line 3:RHLC IMPL-EXEC: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 3, colSpan: 1), RHLC EXEC-IMPL: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 5, colSpan: 1), RHLC IMPL-BENF: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 6, colSpan: 1), RHLC IMPL-EXEC: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 8, colSpan: 1), RHLC DN-IMPL: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 12, colSpan: 1), RHLC DN-IMPL: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 14, colSpan: 1), RHLC DN-IMPL: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 16, colSpan: 1), RHLC IMPL-EXEC: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 17, colSpan: 1), RHLC DN-IMPL: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 19, colSpan: 1), RHLC EXEC-IMPL: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 20, colSpan: 1), RHLC IMPL-BENF: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 21, colSpan: 1))");
		
		runReportTest("Report With Real Comms and Real Disbs By Impl", "AMP-19212-Actual-Real-Commitments-by-impl", new String[] {"Eth Water", "pledged 2", "Activity with Directed MTEFs", "Activity With Directed Comms and Disbs"}, 
				summaryTotalsOnly, null, "en");
	}

	public void testRealCommsDisbsByRegion() {
		GroupReportModel summaryTotalsOnly = GroupReportModel.withGroupReports("AMP-19212-Actual-Real-Commitments-by-region",
				GroupReportModel.withColumnReports("AMP-19212-Actual-Real-Commitments-by-region",
						ColumnReportDataModel.withColumns("Region: Anenii Noi County",
							SimpleColumnModel.withContents("Project Title", "Eth Water", "Eth Water").setIsPledge(false), 
							GroupColumnModel.withSubColumns("Funding",
								GroupColumnModel.withSubColumns("2013",
									SimpleColumnModel.withContents("Actual Commitments", MUST_BE_EMPTY).setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Commitments",
										SimpleColumnModel.withContents("IMPL-EXEC", MUST_BE_EMPTY).setIsPledge(false)), 
									SimpleColumnModel.withContents("Actual Disbursements", "Eth Water", "545 000").setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Disbursements",
										SimpleColumnModel.withContents("DN-EXEC", "Eth Water", "545 000").setIsPledge(false), 
										SimpleColumnModel.withContents("EXEC-IMPL", "Eth Water", "100 000").setIsPledge(false), 
										SimpleColumnModel.withContents("IMPL-BENF", "Eth Water", "15 000").setIsPledge(false))), 
								GroupColumnModel.withSubColumns("2014",
									SimpleColumnModel.withContents("Actual Commitments", MUST_BE_EMPTY).setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Commitments",
										SimpleColumnModel.withContents("IMPL-EXEC", MUST_BE_EMPTY).setIsPledge(false)), 
									SimpleColumnModel.withContents("Actual Disbursements", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("Real Disbursements", MUST_BE_EMPTY).setIsPledge(false)), 
								GroupColumnModel.withSubColumns("2015",
									SimpleColumnModel.withContents("Actual Commitments", MUST_BE_EMPTY).setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Commitments",
										SimpleColumnModel.withContents("DN-IMPL", MUST_BE_EMPTY).setIsPledge(false)), 
									SimpleColumnModel.withContents("Actual Disbursements", MUST_BE_EMPTY).setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Disbursements",
										SimpleColumnModel.withContents("DN-IMPL", MUST_BE_EMPTY).setIsPledge(false)))), 
							GroupColumnModel.withSubColumns("Total Costs",
								SimpleColumnModel.withContents("Actual Commitments", MUST_BE_EMPTY).setIsPledge(false), 
								GroupColumnModel.withSubColumns("Real Commitments",
									SimpleColumnModel.withContents("DN-IMPL", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-EXEC", MUST_BE_EMPTY).setIsPledge(false)), 
								SimpleColumnModel.withContents("Actual Disbursements", "Eth Water", "545 000").setIsPledge(false), 
								GroupColumnModel.withSubColumns("Real Disbursements",
									SimpleColumnModel.withContents("DN-EXEC", "Eth Water", "545 000").setIsPledge(false), 
									SimpleColumnModel.withContents("DN-IMPL", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("EXEC-IMPL", "Eth Water", "100 000").setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-BENF", "Eth Water", "15 000").setIsPledge(false))))
						.withTrailCells(null, "0", "0", "545 000", "545 000", "100 000", "15 000", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "545 000", "545 000", "0", "100 000", "15 000"),
						ColumnReportDataModel.withColumns("Region: Cahul County",
							SimpleColumnModel.withContents("Project Title", "pledged 2", "pledged 2").setIsPledge(false), 
							GroupColumnModel.withSubColumns("Funding",
								GroupColumnModel.withSubColumns("2013",
									SimpleColumnModel.withContents("Actual Commitments", "pledged 2", "2 670 000").setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Commitments",
										SimpleColumnModel.withContents("IMPL-EXEC", MUST_BE_EMPTY).setIsPledge(false)), 
									SimpleColumnModel.withContents("Actual Disbursements", MUST_BE_EMPTY).setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Disbursements",
										SimpleColumnModel.withContents("DN-EXEC", MUST_BE_EMPTY).setIsPledge(false), 
										SimpleColumnModel.withContents("EXEC-IMPL", MUST_BE_EMPTY).setIsPledge(false), 
										SimpleColumnModel.withContents("IMPL-BENF", MUST_BE_EMPTY).setIsPledge(false))), 
								GroupColumnModel.withSubColumns("2014",
									SimpleColumnModel.withContents("Actual Commitments", "pledged 2", "4 400 000").setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Commitments",
										SimpleColumnModel.withContents("IMPL-EXEC", MUST_BE_EMPTY).setIsPledge(false)), 
									SimpleColumnModel.withContents("Actual Disbursements", "pledged 2", "450 000").setIsPledge(false), 
									SimpleColumnModel.withContents("Real Disbursements", MUST_BE_EMPTY).setIsPledge(false)), 
								GroupColumnModel.withSubColumns("2015",
									SimpleColumnModel.withContents("Actual Commitments", MUST_BE_EMPTY).setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Commitments",
										SimpleColumnModel.withContents("DN-IMPL", MUST_BE_EMPTY).setIsPledge(false)), 
									SimpleColumnModel.withContents("Actual Disbursements", MUST_BE_EMPTY).setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Disbursements",
										SimpleColumnModel.withContents("DN-IMPL", MUST_BE_EMPTY).setIsPledge(false)))), 
							GroupColumnModel.withSubColumns("Total Costs",
								SimpleColumnModel.withContents("Actual Commitments", "pledged 2", "7 070 000").setIsPledge(false), 
								GroupColumnModel.withSubColumns("Real Commitments",
									SimpleColumnModel.withContents("DN-IMPL", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-EXEC", MUST_BE_EMPTY).setIsPledge(false)), 
								SimpleColumnModel.withContents("Actual Disbursements", "pledged 2", "450 000").setIsPledge(false), 
								GroupColumnModel.withSubColumns("Real Disbursements",
									SimpleColumnModel.withContents("DN-EXEC", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("DN-IMPL", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("EXEC-IMPL", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-BENF", MUST_BE_EMPTY).setIsPledge(false))))
						.withTrailCells(null, "2 670 000", "0", "0", "0", "0", "0", "4 400 000", "0", "450 000", "0", "0", "0", "0", "0", "7 070 000", "0", "0", "450 000", "0", "0", "0", "0"),
						ColumnReportDataModel.withColumns("Region: Leova County",
							SimpleColumnModel.withContents("Project Title", "Activity with Directed MTEFs", "Activity with Directed MTEFs").setIsPledge(false), 
							GroupColumnModel.withSubColumns("Funding",
								GroupColumnModel.withSubColumns("2013",
									SimpleColumnModel.withContents("Actual Commitments", MUST_BE_EMPTY).setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Commitments",
										SimpleColumnModel.withContents("IMPL-EXEC", MUST_BE_EMPTY).setIsPledge(false)), 
									SimpleColumnModel.withContents("Actual Disbursements", MUST_BE_EMPTY).setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Disbursements",
										SimpleColumnModel.withContents("DN-EXEC", MUST_BE_EMPTY).setIsPledge(false), 
										SimpleColumnModel.withContents("EXEC-IMPL", MUST_BE_EMPTY).setIsPledge(false), 
										SimpleColumnModel.withContents("IMPL-BENF", MUST_BE_EMPTY).setIsPledge(false))), 
								GroupColumnModel.withSubColumns("2014",
									SimpleColumnModel.withContents("Actual Commitments", MUST_BE_EMPTY).setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Commitments",
										SimpleColumnModel.withContents("IMPL-EXEC", MUST_BE_EMPTY).setIsPledge(false)), 
									SimpleColumnModel.withContents("Actual Disbursements", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("Real Disbursements", MUST_BE_EMPTY).setIsPledge(false)), 
								GroupColumnModel.withSubColumns("2015",
									SimpleColumnModel.withContents("Actual Commitments", "Activity with Directed MTEFs", "1 200 000").setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Commitments",
										SimpleColumnModel.withContents("DN-IMPL", MUST_BE_EMPTY).setIsPledge(false)), 
									SimpleColumnModel.withContents("Actual Disbursements", MUST_BE_EMPTY).setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Disbursements",
										SimpleColumnModel.withContents("DN-IMPL", MUST_BE_EMPTY).setIsPledge(false)))), 
							GroupColumnModel.withSubColumns("Total Costs",
								SimpleColumnModel.withContents("Actual Commitments", "Activity with Directed MTEFs", "1 200 000").setIsPledge(false), 
								GroupColumnModel.withSubColumns("Real Commitments",
									SimpleColumnModel.withContents("DN-IMPL", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-EXEC", MUST_BE_EMPTY).setIsPledge(false)), 
								SimpleColumnModel.withContents("Actual Disbursements", MUST_BE_EMPTY).setIsPledge(false), 
								GroupColumnModel.withSubColumns("Real Disbursements",
									SimpleColumnModel.withContents("DN-EXEC", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("DN-IMPL", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("EXEC-IMPL", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-BENF", MUST_BE_EMPTY).setIsPledge(false))))
						.withTrailCells(null, "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "1 200 000", "0", "0", "0", "1 200 000", "0", "0", "0", "0", "0", "0", "0"),
						ColumnReportDataModel.withColumns("Region: Region Unallocated",
							SimpleColumnModel.withContents("Project Title", "Activity With Directed Comms and Disbs", "Activity With Directed Comms and Disbs").setIsPledge(false), 
							GroupColumnModel.withSubColumns("Funding",
								GroupColumnModel.withSubColumns("2013",
									SimpleColumnModel.withContents("Actual Commitments", MUST_BE_EMPTY).setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Commitments",
										SimpleColumnModel.withContents("IMPL-EXEC", "Activity With Directed Comms and Disbs", "20 000").setIsPledge(false)), 
									SimpleColumnModel.withContents("Actual Disbursements", MUST_BE_EMPTY).setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Disbursements",
										SimpleColumnModel.withContents("DN-EXEC", MUST_BE_EMPTY).setIsPledge(false), 
										SimpleColumnModel.withContents("EXEC-IMPL", MUST_BE_EMPTY).setIsPledge(false), 
										SimpleColumnModel.withContents("IMPL-BENF", MUST_BE_EMPTY).setIsPledge(false))), 
								GroupColumnModel.withSubColumns("2014",
									SimpleColumnModel.withContents("Actual Commitments", MUST_BE_EMPTY).setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Commitments",
										SimpleColumnModel.withContents("IMPL-EXEC", "Activity With Directed Comms and Disbs", "20 000").setIsPledge(false)), 
									SimpleColumnModel.withContents("Actual Disbursements", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("Real Disbursements", MUST_BE_EMPTY).setIsPledge(false)), 
								GroupColumnModel.withSubColumns("2015",
									SimpleColumnModel.withContents("Actual Commitments", "Activity With Directed Comms and Disbs", "40 000").setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Commitments",
										SimpleColumnModel.withContents("DN-IMPL", "Activity With Directed Comms and Disbs", "40 000").setIsPledge(false)), 
									SimpleColumnModel.withContents("Actual Disbursements", "Activity With Directed Comms and Disbs", "40 000").setIsPledge(false), 
									GroupColumnModel.withSubColumns("Real Disbursements",
										SimpleColumnModel.withContents("DN-IMPL", "Activity With Directed Comms and Disbs", "40 000").setIsPledge(false)))), 
							GroupColumnModel.withSubColumns("Total Costs",
								SimpleColumnModel.withContents("Actual Commitments", "Activity With Directed Comms and Disbs", "40 000").setIsPledge(false), 
								GroupColumnModel.withSubColumns("Real Commitments",
									SimpleColumnModel.withContents("DN-IMPL", "Activity With Directed Comms and Disbs", "40 000").setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-EXEC", "Activity With Directed Comms and Disbs", "40 000").setIsPledge(false)), 
								SimpleColumnModel.withContents("Actual Disbursements", "Activity With Directed Comms and Disbs", "40 000").setIsPledge(false), 
								GroupColumnModel.withSubColumns("Real Disbursements",
									SimpleColumnModel.withContents("DN-EXEC", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("DN-IMPL", "Activity With Directed Comms and Disbs", "40 000").setIsPledge(false), 
									SimpleColumnModel.withContents("EXEC-IMPL", MUST_BE_EMPTY).setIsPledge(false), 
									SimpleColumnModel.withContents("IMPL-BENF", MUST_BE_EMPTY).setIsPledge(false))))
						.withTrailCells(null, "0", "20 000", "0", "0", "0", "0", "0", "20 000", "0", "0", "40 000", "40 000", "40 000", "40 000", "40 000", "40 000", "40 000", "40 000", "0", "40 000", "0", "0"))
					.withTrailCells(null, "2 670 000", "20 000", "545 000", "545 000", "100 000", "15 000", "4 400 000", "20 000", "450 000", "0", "1 240 000", "40 000", "40 000", "40 000", "8 310 000", "40 000", "40 000", "1 035 000", "545 000", "40 000", "100 000", "15 000"))
				.withTrailCells(null, "2 670 000", "20 000", "545 000", "545 000", "100 000", "15 000", "4 400 000", "20 000", "450 000", "0", "1 240 000", "40 000", "40 000", "40 000", "8 310 000", "40 000", "40 000", "1 035 000", "545 000", "40 000", "100 000", "15 000")
				.withPositionDigest(true,
					"(line 0:RHLC Project Title: (startRow: 0, rowSpan: 4, totalRowSpan: 4, colStart: 0, colSpan: 1), RHLC Funding: (startRow: 0, rowSpan: 1, totalRowSpan: 4, colStart: 1, colSpan: 14), RHLC Total Costs: (startRow: 0, rowSpan: 2, totalRowSpan: 4, colStart: 15, colSpan: 8))",
					"(line 1:RHLC 2013: (startRow: 1, rowSpan: 1, totalRowSpan: 3, colStart: 1, colSpan: 6), RHLC 2014: (startRow: 1, rowSpan: 1, totalRowSpan: 3, colStart: 7, colSpan: 4), RHLC 2015: (startRow: 1, rowSpan: 1, totalRowSpan: 3, colStart: 11, colSpan: 4))",
					"(line 2:RHLC Actual Commitments: (startRow: 2, rowSpan: 2, totalRowSpan: 2, colStart: 1, colSpan: 1), RHLC Real Commitments: (startRow: 2, rowSpan: 1, totalRowSpan: 2, colStart: 2, colSpan: 1), RHLC Actual Disbursements: (startRow: 2, rowSpan: 2, totalRowSpan: 2, colStart: 3, colSpan: 1), RHLC Real Disbursements: (startRow: 2, rowSpan: 1, totalRowSpan: 2, colStart: 4, colSpan: 3), RHLC Actual Commitments: (startRow: 2, rowSpan: 2, totalRowSpan: 2, colStart: 7, colSpan: 1), RHLC Real Commitments: (startRow: 2, rowSpan: 1, totalRowSpan: 2, colStart: 8, colSpan: 1), RHLC Actual Disbursements: (startRow: 2, rowSpan: 2, totalRowSpan: 2, colStart: 9, colSpan: 1), RHLC Real Disbursements: (startRow: 2, rowSpan: 2, totalRowSpan: 2, colStart: 10, colSpan: 1), RHLC Actual Commitments: (startRow: 2, rowSpan: 2, totalRowSpan: 2, colStart: 11, colSpan: 1), RHLC Real Commitments: (startRow: 2, rowSpan: 1, totalRowSpan: 2, colStart: 12, colSpan: 1), RHLC Actual Disbursements: (startRow: 2, rowSpan: 2, totalRowSpan: 2, colStart: 13, colSpan: 1), RHLC Real Disbursements: (startRow: 2, rowSpan: 1, totalRowSpan: 2, colStart: 14, colSpan: 1), RHLC Actual Commitments: (startRow: 2, rowSpan: 2, totalRowSpan: 2, colStart: 15, colSpan: 1), RHLC Real Commitments: (startRow: 2, rowSpan: 1, totalRowSpan: 2, colStart: 16, colSpan: 2), RHLC Actual Disbursements: (startRow: 2, rowSpan: 2, totalRowSpan: 2, colStart: 18, colSpan: 1), RHLC Real Disbursements: (startRow: 2, rowSpan: 1, totalRowSpan: 2, colStart: 19, colSpan: 4))",
					"(line 3:RHLC IMPL-EXEC: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 2, colSpan: 1), RHLC DN-EXEC: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 4, colSpan: 1), RHLC EXEC-IMPL: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 5, colSpan: 1), RHLC IMPL-BENF: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 6, colSpan: 1), RHLC IMPL-EXEC: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 8, colSpan: 1), RHLC DN-IMPL: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 12, colSpan: 1), RHLC DN-IMPL: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 14, colSpan: 1), RHLC DN-IMPL: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 16, colSpan: 1), RHLC IMPL-EXEC: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 17, colSpan: 1), RHLC DN-EXEC: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 19, colSpan: 1), RHLC DN-IMPL: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 20, colSpan: 1), RHLC EXEC-IMPL: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 21, colSpan: 1), RHLC IMPL-BENF: (startRow: 3, rowSpan: 1, totalRowSpan: 1, colStart: 22, colSpan: 1))");
	
		runReportTest("Report With Real Comms and Real Disbs by Region", "AMP-19212-Actual-Real-Commitments-by-region", new String[] {"Eth Water", "pledged 2", "Activity with Directed MTEFs", "Activity With Directed Comms and Disbs"}, 
				summaryTotalsOnly, null, "en");
	}

}
