/**
 * This is a helper class for checking FM configuration status,
 * base taken from AMP-offline FeatureManajger.js
 * revision 6567ae13218497a51c028ec90b0f4f281db20341
 * Its simplified just to check if a full path is enabled in amp
 * since so far is the only thing needed in activity preview. For this said simplicity we are just creating the full
 * list of entries
 * @author from offline : Nadejda Mandrescu
 *
 */
const ACTIVITY_FORM_FM_ENTRY = 'ACTIVITY FORM';

export default class FeatureManager {

    constructor(fmConfig) {
        //change it to be loaded from the api
        const FM_TREE = {
            "ACTIVITY FORM": [
                "/Activity Form/Cancel Reject activity",
                "/Activity Form/FM Mode",
                "/Activity Form/Funding/Add Executing Agency",
                "/Activity Form/Funding/Funding Group/Funding Item/Add Executing Agency",
                "/Activity Form/Funding/Funding Group/Funding Item/Change Funding Organisation",
                "/Activity Form/Funding/Funding Group/Funding Item/Change Org",
                "/Activity Form/Funding/Funding Group/Funding Item/Commitments/Add Commitment",
                "/Activity Form/Funding/Funding Group/Funding Item/Commitments/Commitments Table/Adjustment Type",
                "/Activity Form/Funding/Funding Group/Funding Item/Commitments/Commitments Table/Amount",
                "/Activity Form/Funding/Funding Group/Funding Item/Commitments/Commitments Table/Currency",
                "/Activity Form/Funding/Funding Group/Funding Item/Commitments/Commitments Table/Delete Commitment",
                "/Activity Form/Funding/Funding Group/Funding Item/Commitments/Commitments Table/Required Validator for Disaster Response",
                "/Activity Form/Funding/Funding Group/Funding Item/Commitments/Commitments Table/Transaction Date/Same As ",
                "/Activity Form/Funding/Funding Group/Funding Item/Conditions",
                "/Activity Form/Funding/Funding Group/Funding Item/Delete Funding Item",
                "/Activity Form/Funding/Funding Group/Funding Item/Disbursements/Add Disbursement",
                "/Activity Form/Funding/Funding Group/Funding Item/Disbursements/Disbursements/Actual Disbursements",
                "/Activity Form/Funding/Funding Group/Funding Item/Disbursements/Disbursements/Planned Disbursements",
                "/Activity Form/Funding/Funding Group/Funding Item/Disbursements/Disbursements Table/Adjustment Type",
                "/Activity Form/Funding/Funding Group/Funding Item/Disbursements/Disbursements Table/Amount",
                "/Activity Form/Funding/Funding Group/Funding Item/Disbursements/Disbursements Table/Currency",
                "/Activity Form/Funding/Funding Group/Funding Item/Disbursements/Disbursements Table/Delete Disbursement",
                "/Activity Form/Funding/Funding Group/Funding Item/Disbursements/Disbursements Table/Funding Flows OrgRole Selector/Add Executing Agency",
                "/Activity Form/Funding/Funding Group/Funding Item/Disbursements/Disbursements Table/Funding Flows OrgRole Selector/Add Implementing Agency",
                "/Activity Form/Funding/Funding Group/Funding Item/Disbursements/Disbursements Table/Funding Flows OrgRole Selector/Recipient Org Role",
                "/Activity Form/Funding/Funding Group/Funding Item/Disbursements/Disbursements Table/Funding Flows OrgRole Selector/Recipient Organization",
                "/Activity Form/Funding/Funding Group/Funding Item/Disbursements/Disbursements Table/Required Validator for Disaster Response",
                "/Activity Form/Funding/Funding Group/Funding Item/Disbursements/Disbursements Table/Transaction Date/Same As ",
                "/Activity Form/Funding/Funding Group/Funding Item/Donor Organisation",
                "/Activity Form/Funding/Funding Group/Funding Item/Funding Classification/Financing Instrument",
                "/Activity Form/Funding/Funding Group/Funding Item/Funding Classification/Funding Organization Id",
                "/Activity Form/Funding/Funding Group/Funding Item/Funding Classification/Required Validator for Funding Status",
                "/Activity Form/Funding/Funding Group/Funding Item/Funding Classification/Show Financing Instrument in summary",
                "/Activity Form/Funding/Funding Group/Funding Item/Funding Classification/Show Financing id in summary",
                "/Activity Form/Funding/Funding Group/Funding Item/Funding Classification/Show Type of Assistence in summary",
                "/Activity Form/Funding/Funding Group/Funding Item/Funding Classification/Type of Assistence",
                "/Activity Form/Funding/Funding Group/Funding Item/Funding Section Summary",
                "/Activity Form/Funding/Funding Group/Funding Item/MTEF Projections/Add Projection",
                "/Activity Form/Funding/Funding Group/Funding Item/MTEF Projections/MTEF Projections Table/Amount",
                "/Activity Form/Funding/Funding Group/Funding Item/MTEF Projections/MTEF Projections Table/Currency",
                "/Activity Form/Funding/Funding Group/Funding Item/MTEF Projections/MTEF Projections Table/Delete MTEF Projection",
                "/Activity Form/Funding/Funding Group/Funding Item/MTEF Projections/MTEF Projections Table/Disaster Response",
                "/Activity Form/Funding/Funding Group/Funding Item/MTEF Projections/MTEF Projections Table/MTEF Projection",
                "/Activity Form/Funding/Funding Group/Funding Item/MTEF Projections/MTEF Projections Table/Projection Date",
                "/Activity Form/Funding/Funding Group/Funding Item/Org Role",
                "/Activity Form/Funding/Funding Group/Funding Item/Organization",
                "/Activity Form/Funding/Funding Group/Funding Item/Replace Funding Organizations/Search Organizations",
                "/Activity Form/Funding/Funding Group/Funding Item/Replace Funding Organizations/Select Organization Type",
                "/Activity Form/Funding/Funding Group/New Funding Item",
                "/Activity Form/Funding/Modalities",
                "/Activity Form/Funding/New Funding Group",
                "/Activity Form/Funding/Overview Section/Overall Funding Totals/Total Actual Commitments",
                "/Activity Form/Funding/Overview Section/Overall Funding Totals/Total Actual Disbursement",
                "/Activity Form/Funding/Overview Section/Overall Funding Totals/Total Planned Disbursement",
                "/Activity Form/Funding/Search Funding Organizations",
                "/Activity Form/Funding/Total Number of Funding Sources",
                "/Activity Form/GPI/GPI Item/GPI Questions List/Does the project use national auditing procedures?",
                "/Activity Form/GPI/GPI Item/GPI Questions List/Does the project use national budget execution procedures?",
                "/Activity Form/GPI/GPI Item/GPI Questions List/Does the project use national financial reporting procedures?",
                "/Activity Form/GPI/GPI Item/GPI Questions List/Does the project use national procurement systems?",
                "/Activity Form/GPI/GPI Item/GPI Questions List/Does this project use the country results framework?",
                "/Activity Form/GPI/GPI Item/GPI Questions List/Has this project been formally agreed upon (i.e. memorandum of understanding, project agreement, etc.) with a Government entity?",
                "/Activity Form/GPI/GPI Item/GPI Questions List/Is this project on budget and subject to parliamentary scrutiny?",
                "/Activity Form/Identification/A.C. Chapter",
                "/Activity Form/Identification/Activity Budget",
                "/Activity Form/Identification/Activity Status",
                "/Activity Form/Identification/Activity Updated On",
                "/Activity Form/Identification/Government Agreement Number",
                "/Activity Form/Identification/Government Approval Procedures",
                "/Activity Form/Identification/Humanitarian Aid",
                "/Activity Form/Identification/Joint Criteria",
                "/Activity Form/Identification/Objective",
                "/Activity Form/Identification/Project Title",
                "/Activity Form/Identification/Project Title Similarity Warning",
                "/Activity Form/Identification/Required Validator for Activity Budget",
                "/Activity Form/Identification/Required Validator for Description",
                "/Activity Form/Identification/Required Validator for Humanitarian Aid",
                "/Activity Form/Identification/Status Reason",
                "/Activity Form/Location/Implementation Level",
                "/Activity Form/Location/Implementation Location",
                "/Activity Form/Location/Locations/Divide Percentage",
                "/Activity Form/Location/Locations/Location percentage required",
                "/Activity Form/Location/Locations/Location required validator",
                "/Activity Form/Location/Locations/Search Locations",
                "/Activity Form/Location/Locations/Tree Validator",
                "/Activity Form/Location/Locations/locationPercentageTotal",
                "/Activity Form/Location/Locations/uniqueLocationsValidator",
                "/Activity Form/Logframe",
                "/Activity Form/Organizations/Donor Organization/Add Funding Item Automatically",
                "/Activity Form/Organizations/Donor Organization/Delete Related Organisation",
                "/Activity Form/Organizations/Donor Organization/Required Validator",
                "/Activity Form/Organizations/Donor Organization/Search Organizations/Search Organizations",
                "/Activity Form/Organizations/Donor Organization/Search Organizations/Select Organization Type",
                "/Activity Form/Organizations/Executing Agency/Add Funding Item Automatically",
                "/Activity Form/Organizations/Executing Agency/Delete Related Organisation",
                "/Activity Form/Organizations/Executing Agency/Search Organizations/Search Organizations",
                "/Activity Form/Organizations/Executing Agency/Search Organizations/Select Organization Type",
                "/Activity Form/Organizations/Executing Agency/relOrgPercentageTotal",
                "/Activity Form/Organizations/Implementing Agency/Delete Related Organisation",
                "/Activity Form/Organizations/Implementing Agency/Search Organizations/Search Organizations",
                "/Activity Form/Organizations/Implementing Agency/Search Organizations/Select Organization Type",
                "/Activity Form/Organizations/Implementing Agency/relOrgPercentageTotal",
                "/Activity Form/Organizations/Responsible Organization/Add New Budget",
                "/Activity Form/Organizations/Responsible Organization/Delete Related Organisation",
                "/Activity Form/Organizations/Responsible Organization/Divide Percentage",
                "/Activity Form/Organizations/Responsible Organization/Search Organizations/Search Organizations",
                "/Activity Form/Organizations/Responsible Organization/Search Organizations/Select Organization Type",
                "/Activity Form/Organizations/Responsible Organization/Unique Orgs Validator",
                "/Activity Form/Organizations/Responsible Organization/percentage",
                "/Activity Form/Organizations/Responsible Organization/relOrgPercentageTotal",
                "/Activity Form/Planning/Actual Approval Date",
                "/Activity Form/Planning/Actual Completion Date/Same As ",
                "/Activity Form/Planning/Actual Start Date",
                "/Activity Form/Planning/Proposed Approval Date/Same As ",
                "/Activity Form/Planning/Proposed Completion Date/Same As ",
                "/Activity Form/Planning/Required Validator for Original Completion Date",
                "/Activity Form/Planning/Required Validator for Proposed Start Date",
                "/Activity Form/Preview",
                "/Activity Form/Program/National Plan Objective/Add Program",
                "/Activity Form/Program/National Plan Objective/Delete Program",
                "/Activity Form/Program/National Plan Objective/Divide Percentage",
                "/Activity Form/Program/National Plan Objective/Program",
                "/Activity Form/Program/National Plan Objective/Themes",
                "/Activity Form/Program/National Plan Objective/Tree Validator",
                "/Activity Form/Program/National Plan Objective/max Size Program Validator",
                "/Activity Form/Program/National Plan Objective/minSizeProgramValidator",
                "/Activity Form/Program/National Plan Objective/programPercentage",
                "/Activity Form/Program/National Plan Objective/programPercentageTotal",
                "/Activity Form/Program/National Plan Objective/uniqueProgramsValidator",
                "/Activity Form/Reject Activity",
                "/Activity Form/Reject Message",
                "/Activity Form/Related Documents/Add New Document/Add",
                "/Activity Form/Related Documents/Add New Document/Cancel",
                "/Activity Form/Related Documents/Add New Document/Description",
                "/Activity Form/Related Documents/Add New Document/Note",
                "/Activity Form/Related Documents/Add New Document/Title",
                "/Activity Form/Related Documents/Add New Document/Type",
                "/Activity Form/Related Documents/Add New Document/Web Link",
                "/Activity Form/Related Documents/Add New Web Link/Add",
                "/Activity Form/Related Documents/Add New Web Link/Cancel",
                "/Activity Form/Related Documents/Add New Web Link/Description",
                "/Activity Form/Related Documents/Add New Web Link/Note",
                "/Activity Form/Related Documents/Add New Web Link/Title",
                "/Activity Form/Related Documents/Add New Web Link/Type",
                "/Activity Form/Related Documents/Add New Web Link/Web Link",
                "/Activity Form/Related Documents/Resource List/Delete Resource",
                "/Activity Form/Related Documents/Resource List/Document Date",
                "/Activity Form/Related Documents/Resource List/Document Size",
                "/Activity Form/Related Documents/Resource List/Document Type",
                "/Activity Form/Related Documents/Resource List/Document Year",
                "/Activity Form/Related Documents/Resource List/Title",
                "/Activity Form/Related Documents/Search Resources/Resources Field",
                "/Activity Form/Save and Submit",
                "/Activity Form/Save as Draft",
                "/Activity Form/Sectors/Primary Sectors/Delete Sector",
                "/Activity Form/Sectors/Primary Sectors/Divide Percentage",
                "/Activity Form/Sectors/Primary Sectors/Search Primary Sectors",
                "/Activity Form/Sectors/Primary Sectors/minSizeSectorsValidator",
                "/Activity Form/Sectors/Primary Sectors/sectorPercentage",
                "/Activity Form/Sectors/Primary Sectors/sectorPercentageTotal",
                "/Activity Form/Sectors/Primary Sectors/treeSectorsValidator",
                "/Activity Form/Sectors/Primary Sectors/uniqueSectorsValidator",
                "/Activity Form/Sectors/Secondary Sectors/Delete Sector",
                "/Activity Form/Sectors/Secondary Sectors/Search Secondary Sectors",
                "/Activity Form/Structures/Add Structure",
                "/Activity Form/Structures/Delete Structure",
                "/Activity Form/Structures/Map",
                "/Activity Form/Structures/Structure Description",
                "/Activity Form/Structures/Structure Latitude",
                "/Activity Form/Structures/Structure Longitude",
                "/Activity Form/Structures/Structure Shape",
                "/Activity Form/Structures/Structure Title",
                "/Activity Form/Structures/Structure Type"
            ]
        }
        this._fmConfig = FM_TREE[ACTIVITY_FORM_FM_ENTRY];
    }
    isFMSettingEnabled(fmPath) {
        return this._fmConfig.includes(fmPath);
    }
}
//temp to come from API

