[ ] 
[-] testcase Test1 () appstate DefaultBaseState
	[ ] login("atl@amp.org", "atl")
	[ ] AMPMyDesktop.AddActivity.Click()
	[ ] AMPAddActivityStep1.ProjectTitle.SetText("Full Activity Silk Test")
	[ ] AMPAddActivityStep1.Objective.Click()
	[ ] EditData.SetActive()
	[ ] EditData.Click(1,100,100)
	[ ] EditData.TypeKeys("Test Objective")
	[ ] EditData.SaveNow.Click()
	[ ] 
	[ ] AMPAddActivityStep1.ObjAddEditObjectivelyVerifIndicators.Click ()
	[ ] CommentDetail.AddYourCommentHere.SetText("Obj Verf Indicators")
	[ ] CommentDetail.Save.Click()
	[ ] Sleep(1)
	[ ] CommentDetail.Close.Click()
	[ ] AMPAddActivityStep1.ObjAddEditAssumption.Click()
	[ ] CommentDetail.AddYourCommentHere.SetText("Assumption")
	[ ] CommentDetail.Save.Click()
	[ ] Sleep(1)
	[ ] CommentDetail.Close.Click()
	[ ] 
	[ ] AMPAddActivityStep1.ObjAddEditVerification.Click()
	[ ] CommentDetail.AddYourCommentHere.SetText("Verification")
	[ ] CommentDetail.Save.Click()
	[ ] Sleep(1)
	[ ] CommentDetail.Close.Click()
	[ ] 
	[ ] AMPAddActivityStep1.Description.Click()
	[ ] EditData.SetActive()
	[ ] EditData.Click(1,100,100)
	[ ] EditData.TypeKeys("Test Description")
	[ ] EditData.SaveNow.Click()
	[ ] 
	[ ] AMPAddActivityStep1.Purpose.Click()
	[ ] EditData.SetActive()
	[ ] EditData.Click(1,100,100)
	[ ] EditData.TypeKeys("Test Purpose")
	[ ] EditData.SaveNow.Click()
	[ ] 
	[ ] AMPAddActivityStep1.PurpAddEditObjectivelyVerifIndicators.Click ()
	[ ] CommentDetail.AddYourCommentHere.SetText("Purp Verf Indicators")
	[ ] CommentDetail.Save.Click()
	[ ] Sleep(1)
	[ ] CommentDetail.Close.Click()
	[ ] 
	[ ] AMPAddActivityStep1.PurpAddEditAssumption.Click()
	[ ] CommentDetail.AddYourCommentHere.SetText("Assumption")
	[ ] CommentDetail.Save.Click()
	[ ] Sleep(1)
	[ ] CommentDetail.Close.Click()
	[ ] 
	[ ] AMPAddActivityStep1.PurpAddEditVerification.Click()
	[ ] CommentDetail.AddYourCommentHere.SetText("Verification")
	[ ] CommentDetail.Save.Click()
	[ ] Sleep(1)
	[ ] CommentDetail.Close.Click()
	[ ] 
	[ ] AMPAddActivityStep1.Results.Click()
	[ ] EditData.SetActive()
	[ ] EditData.Click(1,100,100)
	[ ] EditData.TypeKeys("Test Results")
	[ ] EditData.SaveNow.Click()
	[ ] 
	[ ] AMPAddActivityStep1.ResultsAddEditObjectivelyVerifIndicators.Click ()
	[ ] CommentDetail.AddYourCommentHere.SetText("Purp Verf Indicators")
	[ ] CommentDetail.Save.Click()
	[ ] Sleep(1)
	[ ] CommentDetail.Close.Click()
	[ ] 
	[ ] AMPAddActivityStep1.ResultsAddEditAssumption.Click()
	[ ] CommentDetail.AddYourCommentHere.SetText("Assumption")
	[ ] CommentDetail.Save.Click()
	[ ] Sleep(1)
	[ ] CommentDetail.Close.Click()
	[ ] 
	[ ] AMPAddActivityStep1.ResultsAddEditVerification.Click()
	[ ] CommentDetail.AddYourCommentHere.SetText("Verification")
	[ ] CommentDetail.Save.Click()
	[ ] Sleep(1)
	[ ] CommentDetail.Close.Click()
	[ ] 
	[ ] AMPAddActivityStep1.Lesson.Click()
	[ ] EditData.SetActive()
	[ ] EditData.Click(1,100,100)
	[ ] EditData.TypeKeys("Test Lesson")
	[ ] EditData.SaveNow.Click()
	[ ] 
	[ ] AMPAddActivityStep1.AccessionInstrument.Select (2)
	[ ] AMPAddActivityStep1.ACChapter.Select (2)
	[ ] AMPAddActivityStep1.ActivityIsOnBudget.Check ()
	[ ] 
	[ ] AMPAddActivityStep1.FY.SetText("1")
	[ ] AMPAddActivityStep1.Vote.SetText("2")
	[ ] AMPAddActivityStep1.SubVote.SetText("3")
	[ ] AMPAddActivityStep1.SubProgram.SetText("4")
	[ ] AMPAddActivityStep1.ProjectCode.SetText("5")
	[ ] AMPAddActivityStep1.FinancialInstrument.Select (1)
	[ ] AMPAddActivityStep1.GovApprovalProc.Select(1)
	[ ] AMPAddActivityStep1.JointCriteria.Select(1)
	[ ] 
	[ ] AMPAddActivityStep1.AddOrganizations.Click ()
	[ ] AMPSelectOrganizations.SetActive( )
	[ ] AMPSelectOrganizations.Search.Click ()
	[ ] AMPSelectOrganizations.ResultsCheckBox1.Check ()
	[ ] AMPSelectOrganizations.Add.Click ()
	[ ] AMPAddActivityStep1.SetActive( )
	[ ] AMPAddActivityStep1.Org1Id.SetText("123")
	[ ] AMPAddActivityStep1.LineMinistryRank.Select (2)
	[ ] AMPAddActivityStep1.MinistryOfPlanningRank.Select (2)
	[ ] DATETIME today
	[ ] STRING date1
	[ ] today = GetDateTime()
	[ ] date1 = FormatDateTime(today,"dd/mm/yyyy")
	[ ] BrowserPage.ExecLine ('document.getElementById("originalAppDate").value = "'+date1+'"', TRUE)
	[ ] AMPAddActivityStep1.SameAsProposedApprovalDate.Check ()
	[+] AMPAddActivityStep1.ActualApprovalDate.VerifyProperties ({...})
		[ ] ""
		[-] {...}
			[ ] {"Exists",               TRUE}
			[ ] {"Text",                 date1}
	[ ] AMPAddActivityStep1.SameAsProposedApprovalDate.Uncheck ()
	[ ] BrowserPage.ExecLine('document.getElementById("revisedAppDate").value = "'+date1+'"', TRUE)
	[ ] BrowserPage.ExecLine('document.getElementById("originalStartDate").value = "'+date1+'"', TRUE)
	[ ] AMPAddActivityStep1.SameAsProposedStartDate.Check ()
	[+] AMPAddActivityStep1.ProposedStartDate.VerifyProperties ({...})
		[ ] ""
		[-] {...}
			[ ] {"Exists",               TRUE}
			[ ] {"Text",                 date1}
	[ ] AMPAddActivityStep1.SameAsProposedStartDate.Uncheck ()
	[ ] BrowserPage.ExecLine('document.getElementById("revisedStartDate").value = "'+date1+'"', TRUE)
	[ ] BrowserPage.ExecLine('document.getElementById("contractingDate").value = "'+date1+'"', TRUE)
	[ ] BrowserPage.ExecLine('document.getElementById("disbursementsDate").value = "'+date1+'"', TRUE)
	[ ] AMPAddActivityStep1.Comment1.Click ()
	[ ] CommentDetail.SetActive( )
	[ ] //CommentDetail.AddYourCommentHere.Click( 1, 100,100)
	[ ] CommentDetail.AddYourCommentHere.TypeKeys ("comentezi ? bla bla bla scriem caractere ")
	[ ] CommentDetail.Save.Click ()
	[ ] CommentDetail.Close.Click ()
	[ ] 
	[ ] AMPAddActivityStep1.SetActive()
	[ ] AMPAddActivityStep1.StatusId.Select(2)
	[ ] AMPAddActivityStep1.IfThereHaveBeenSomeChange.TypeKeys("reason for changing status")
	[ ] 
	[ ] AMPAddActivityStep1.References.Click()
	[ ] AMPAddActivityStep2.Location.Click()
	[ ] AMPAddActivityStep3.SetActive()
	[ ] 
	[ ] 
	[ ] AMPAddActivityStep3.ImplementationLevel.Select (2)
	[ ] AMPAddActivityStep3.SelectTheAppropriateRegion.Select ("District")
	[ ] AMPAddActivityStep3.AddLocation.Click ()
	[ ] //AMPAddActivityStep3.SetActive( )
	[ ] //no regions in the database
	[ ] 
	[ ] //AMPSelectLocation.Region.Select (1)
	[ ] //AMPSelectLocation.Zone.Select(1)
	[ ] //AMPSelectLocation.District.Select(1)
	[ ] 
	[ ] AMPSelectLocation.Add.Click ()
	[ ] AMPAddActivityStep3.AddSectors.Click ()
	[ ] AMPAddSectors.SelectSectors.Select(2)
	[ ] Sleep(3)
	[ ] AMPAddSectors.Sector.Select(2)
	[ ] Sleep(3)
	[ ] AMPAddSectors.SubSectorLevel1.Select(1)
	[ ] Sleep(3)
	[ ] AMPAddSectors.Add.Click()
	[ ] Sleep(3)
	[ ] //have not selected option from sub sector level 2
	[ ] AMPAddActivityStep3.SetActive()
	[ ] AMPAddActivityStep3.Description.TypeKeys("Description")
	[ ] AMPAddActivityStep3.CrossCuttingIssues.Edit.Edit1.Click()
	[ ] EditData.SetActive()
	[ ] EditData.Click(1,100,100)
	[ ] EditData.Text.TypeKeys("Equal Opportunity")
	[ ] EditData.SaveNow.Click()
	[ ] AMPAddActivityStep3.CrossCuttingIssues.Edit.Edit2.Click()
	[ ] EditData.SetActive()
	[ ] EditData.Click(1,100,100)
	[ ] EditData.Text.TypeKeys("Environment")
	[ ] EditData.SaveNow.Click()
	[ ] AMPAddActivityStep3.CrossCuttingIssues.Edit.Edit3.Click()
	[ ] EditData.SetActive()
	[ ] EditData.Click(1,100,100)
	[ ] EditData.Text.TypeKeys("Minorities")
	[ ] EditData.SaveNow.Click()
	[ ] AMPAddActivityStep3.Funding.Click()
	[ ] 
	[ ] 
	[ ] AMPAddActivityStep4.AddOrganizations.Click()
	[ ] AMPSelectOrganizations.SetActive()
	[ ] AMPSelectOrganizations.Search.Click ()
	[ ] AMPSelectOrganizations.ResultsCheckBox1.Check()
	[ ] AMPSelectOrganizations.Add.Click()
	[ ] AMPAddActivityStep4.AddFunding.Click()
	[ ] AMPAddFunding.SetActive()
	[ ] AMPAddFunding.AssistanceType.Select(2)
	[ ] AMPAddFunding.Modality.Select(2)
	[ ] AMPAddFunding.FundingOrganizationId.SetText("123")
	[-] if (AMPAddFunding.AddProjection.Exists())
		[ ] AMPAddFunding.AddProjection.Click ()
		[ ] AMPAddFunding.Pipeline1.SetText("123")
		[ ] AMPAddFunding.Currency.Select(1)
	[-] if (AMPAddFunding.AddCommitment.Exists())
		[ ] AMPAddFunding.AddCommitment.Click()
		[ ] AMPAddFunding.PlannedActual.Select(1)
		[ ] AMPAddFunding.Planned.SetText("23")
		[ ] AMPAddFunding.Currency2.Select(1)
		[ ] BrowserPage.ExecLine('document.getElementById("trans3Date0").value = "'+date1+'"', TRUE)
	[-] if (AMPAddFunding.AddDisbursement.Exists())
		[ ] AMPAddFunding.AddDisbursement.Click()
		[ ] AMPAddFunding.PlannedActual2.Select(1)
		[ ] AMPAddFunding.Planned2.SetText("12")
		[ ] AMPAddFunding.Currency3.Select(1)
		[ ] BrowserPage.ExecLine('document.getElementById("transDate1").value = "'+date1+'"', TRUE)
	[-] //if (AMPAddFunding.AddExpenditure.Exists())
		[ ] //AMPAddFunding.AddExpenditure.Click()
		[ ] //AMPAddFunding.PlannedActual3.Select(1)
		[ ] //AMPAddFunding.Planned3.SetText("14")
		[ ] //AMPAddFunding.Currency4.Select(1)
		[ ] //BrowserPage.ExecLine('document.getElementById("trans6Date3").value = "'+date1+'"', TRUE)
		[ ] //AMPAddFunding.Classification.SetText("classification")
	[ ] AMPAddFunding.Conditions.SetText("conditions")
	[ ] AMPAddFunding.Save.Click()
	[ ] AMPAddActivityStep4.Components.Click()
	[ ] AMPAddActivityStep5.AddComponent.Click()
	[ ] 
	[ ] AMPAddComponents.Component.Select(2)
	[ ] AMPAddComponents.AddCommitments.Click()
	[ ] AMPAddComponents.PlannedActual1.Select(1)
	[ ] AMPAddComponents.Planned.SetText("3")
	[ ] AMPAddComponents.Currency.Select(1)
	[ ] BrowserPage.ExecLine('document.getElementById("date1comm_0_4").value = "'+date1+'"', TRUE)
	[ ] AMPAddComponents.AddDisbursement.Click()
	[ ] AMPAddComponents.PlannedActual2.Select(1)
	[ ] AMPAddComponents.Planned2.SetText("4")
	[ ] AMPAddComponents.Currency2.Select(1)
	[ ] BrowserPage.ExecLine('document.getElementById("date1disb_0_4").value = "'+date1+'"', TRUE)
	[ ] AMPAddComponents.AddExpenditure.Click()
	[ ] AMPAddComponents.PlannedActual3.Select(1)
	[ ] AMPAddComponents.Planned.SetText("4")
	[ ] AMPAddComponents.Currency3.Select(1)
	[ ] BrowserPage.ExecLine('document.getElementById("date1expn_0_4").value = "'+date1+'"', TRUE)
	[ ] AMPAddComponents.Save.Click()
	[ ] AMPAddActivityStep5.AddPhysicalProgress.Click()
	[ ] AMPAddPhysicalProgress.Title.SetText("progress")
	[ ] AMPAddPhysicalProgress.Description.SetText("description")
	[ ] BrowserPage.ExecLine('document.getElementById("date1").value = "'+date1+'"', TRUE)
	[ ] AMPAddPhysicalProgress.Add.Click()
	[ ] 
	[ ] AMPAddActivityStep5.AddIssues.Click()
	[ ] AMPAddIssue.Issue.SetText("issue")
	[ ] AMPAddIssue.Add.Click()
	[ ] AMPAddActivityStep5.AddMeasures.Click()
	[ ] AMPAddMeasure.Measure.SetText("measure")
	[ ] AMPAddMeasure.Add.Click()
	[ ] 
	[ ] AMPAddActivityStep5.RelatedDocuments.Click ()
	[ ] AMPAddActivityStep6.AddDocumentsFromRepository.Click ()
	[ ] AMPAddDocumentsFromRepository.HtmlTable1.SelectSelectDocumen.Select.Click ()
	[ ] AMPAddDocumentsFromRepository.Empty.TeamDocuments.Click ()
	[ ] AMPAddDocumentsFromRepository.HtmlTable1.SelectSelectDocumen.Examen_krDoc.Click ()
	[ ] AMPAddDocumentsFromRepository.Submit.Click ()
	[ ] AMPAddActivityStep6.AddDocuments.Click ()
	[ ] AMPAddDocuments.Title.SetText("title")
	[ ] AMPAddDocuments.Description.TypeKeys ("description")
	[ ] AMPAddDocuments.Comments.TypeKeys ("comments")
	[ ] BrowserPage.ExecLine('document.getElementById("date1").value = "'+date1+'"', TRUE)
	[ ] AMPAddDocuments.Browse.Click()
	[ ] ChooseFile.SetActive ()
	[ ] ChooseFile.ListView1.Select (1)
	[ ] ChooseFile.Open.Click ()
	[ ] AMPAddActivityStep6.AddWebResources.Click ()
	[ ] AMPAddDocuments.Title.SetText("title")
	[ ] AMPAddDocuments.Description.SetText("description")
	[ ] AMPAddDocuments.Comments.SetText("comment")
	[ ] AMPAddDocuments.WebResources.SetText("http://google.com")
	[ ] AMPAddDocuments.Add.Click ()
	[ ] AMPAddActivityStep6.RelatedOrganizations.Click()
	[ ] AMPAddActivityStep7.AddOrganizations1.Click ()
	[ ] AMPSelectOrganizations.SetActive( )
	[ ] AMPSelectOrganizations.Search.Click ()
	[ ] AMPSelectOrganizations.ResultsCheckBox1.Check ()
	[ ] AMPSelectOrganizations.Add.Click ()
	[ ] AMPAddActivityStep7.AddOrganizations2.Click ()
	[ ] AMPSelectOrganizations.SetActive ()
	[ ] AMPSelectOrganizations.Search.Click ()
	[ ] AMPSelectOrganizations.ResultsCheckBox1.Check ()
	[ ] AMPSelectOrganizations.Add.Click ()
	[ ] AMPAddActivityStep7.AddOrganizations3.Click ()
	[ ] AMPSelectOrganizations.SetActive ()
	[ ] AMPSelectOrganizations.Search.Click ()
	[ ] AMPSelectOrganizations.ResultsCheckBox1.Check ()
	[ ] AMPSelectOrganizations.Add.Click ()
	[ ] AMPAddActivityStep7.AddOrganizations4.Click ()
	[ ] AMPSelectOrganizations.SetActive ()
	[ ] AMPSelectOrganizations.Search.Click ()
	[ ] AMPSelectOrganizations.ResultsCheckBox1.Check ()
	[ ] AMPSelectOrganizations.Add.Click ()
	[ ] AMPAddActivityStep7.AddOrganizations5.Click ()
	[ ] AMPSelectOrganizations.SetActive ()
	[ ] AMPSelectOrganizations.Search.Click ()
	[ ] AMPSelectOrganizations.ResultsCheckBox1.Check ()
	[ ] AMPSelectOrganizations.Add.Click ()
	[ ] AMPAddActivityStep7.AddOrganizations6.Click ()
	[ ] AMPSelectOrganizations.SetActive ()
	[ ] AMPSelectOrganizations.Search.Click ()
	[ ] AMPSelectOrganizations.ResultsCheckBox1.Check ()
	[ ] AMPSelectOrganizations.Add.Click ()
	[ ] AMPAddActivityStep7.RelatedOrganizations.Click ()
	[ ] AMPAddActivityStep9.FirstName1.SetText("John")
	[ ] AMPAddActivityStep9.LastName1.SetText("Nash")
	[ ] AMPAddActivityStep9.Email1.SetText("j@n.com")
	[ ] AMPAddActivityStep9.Title1.SetText("ceo")
	[ ] AMPAddActivityStep9.Organization1.SetText("organization")
	[ ] AMPAddActivityStep9.PhoneNumber1.SetText("0987654")
	[ ] AMPAddActivityStep9.FaxNumber1.SetText("123345")
	[ ] AMPAddActivityStep9.FirstName2.SetText("David")
	[ ] AMPAddActivityStep9.LastName2.SetText("Jones")
	[ ] AMPAddActivityStep9.Email2.SetText("d@j.com")
	[ ] AMPAddActivityStep9.Title2.SetText("ceo")
	[ ] AMPAddActivityStep9.Organization2.SetText("org2")
	[ ] AMPAddActivityStep9.PhoneNumber2.SetText("123456")
	[ ] AMPAddActivityStep9.FaxNumber2.SetText("654321")
	[ ] AMPAddActivityStep9.ME.Click ()
	[ ] AMPAddActivityStep10.IND004.Click ()
	[ ] AMPAddActivityStep10.BaseValue.SetText("6")
	[ ] BrowserPage.ExecLine('document.getElementById("date1").value = "'+date1+'"', TRUE)
	[ ] AMPAddActivityStep10.Comments1.TypeKeys ("comment")
	[ ] AMPAddActivityStep10.TargetVal.SetText("8")
	[ ] BrowserPage.ExecLine('document.getElementById("date2").value = "'+date1+'"', TRUE)
	[ ] AMPAddActivityStep10.Comments2.TypeKeys ("comment")
	[ ] AMPAddActivityStep10.CurrentValue.SetText("4")
	[ ] AMPAddActivityStep10.Comments3.TypeKeys ("comment")
	[ ] AMPAddActivityStep10.SetValues.Click ()
	[ ] AMPAddActivityStep10.Costing.Click ()
	[ ] AMPAddActivityStep10.Costing.Click ()
	[ ] AMPAddActivityStep11.AddActivity.Click ()
	[ ] AMPAddEditActivity.SetActive()
	[ ] AMPAddEditActivity.ActivityName.SetText("activity")
	[ ] AMPAddEditActivity.ActivityID.SetText("10")
	[ ] AMPAddEditActivity.Inputs.SetPosition( 1, 1)
	[ ] AMPAddEditActivity.Inputs.TypeKeys ("input")
	[ ] AMPAddEditActivity.TotalCost.SetText("4")
	[ ] AMPAddEditActivity.ActivityID1.Select ("Canadian Dollar")
	[ ] AMPAddEditActivity.Contributions.SetText("4")
	[ ] AMPAddEditActivity.Pop1.Select (2)
	[ ] AMPAddEditActivity.Pop2.Select (2)
	[ ] AMPAddEditActivity.Pop3.Select (2)
	[ ] AMPAddEditActivity.Pop4.Select (2)
	[ ] AMPAddEditActivity.Assumptions.TypeKeys ("asumptions")
	[ ] AMPAddEditActivity.Progress.TypeKeys ("progress")
	[ ] AMPAddEditActivity.PickDate.Click ()
	[ ] AMPAddEditActivity.OK.Click ()
	[ ] 
	[ ] 
