[-] testcase Test1 () appstate none
	[-] recording
		[ ] AMPMyDesktop.SetActive( )
		[ ] AMPDesktopLinks.TopMenu.REPORTS.Click ()
		[ ] AMPPublicTeamReports.ReportGenerator.Click ()
		[ ] AMPReportGeneratorStep1.N5ReportDetails.Select ("Donor Report (Donor Funding)")
		[ ] AMPReportGeneratorStep1.Next.Click ()
		[ ] AMPReportGeneratorStep2.AMP.Check ()
		[ ] AMPReportGeneratorStep2.Add.Click ()
		[ ] AMPReportGeneratorStep2.Next1.Click ()
		[ ] AMPDesktopLinks.AccessionInstrument.Check ()
		[ ] AMPDesktopLinks.DonorAgency.Check ()
		[ ] AMPDesktopLinks.DonorGroup.Check ()
		[ ] AMPDesktopLinks.Add.Click ()
		[ ] AMPDesktopLinks.Next1.Click ()
		[ ] AMPDesktopLinks.ActualCommitments.Check ()
		[ ] AMPDesktopLinks.Add.Click ()
		[ ] AMPDesktopLinks.Next1.Click ()
		[ ] AMPReportGeneratorStep5.N5ReportDetails1.ReportTitle.HtmlTextField1.SetPosition( 1, 1)
		[ ] AMPReportGeneratorStep5.N5ReportDetails1.ReportTitle.HtmlTextField1.TypeKeys ("test reprt")
		[ ] AMPReportGeneratorStep5.N5ReportDetails1.ReportTitle.HtmlTextField1.TypeKeys ("<Backspace>")
		[ ] AMPReportGeneratorStep5.N5ReportDetails1.ReportTitle.HtmlTextField1.TypeKeys ("<Backspace>")
		[ ] AMPReportGeneratorStep5.N5ReportDetails1.ReportTitle.HtmlTextField1.TypeKeys ("ort")
		[ ] AMPReportGeneratorStep5.SaveReport.Click ()
		[ ] AMPDesktopLinks.TopMenu.REPORTS.Click ()
[ ] 
