[-] testcase Test1_1() appstate DefaultBaseState
	[ ] login("atl@amp.org", "atl")
	[ ] AMPMyDesktop.SetActive( )
	[ ] AMPDesktopLinks.TopMenu.REPORTS.Click ()
	[ ] AMPPublicTeamReports.ReportGenerator.Click ()
	[ ] AMPReportGeneratorStep1.N5ReportDetails.Select (1)
	[ ] AMPReportGeneratorStep1.Next.Click ()
	[ ] AMPReportGeneratorStep2.AMP.Check ()
	[ ] AMPReportGeneratorStep2.Add.Click ()
	[ ] AMPReportGeneratorStep2.Next1.Click ()
	[ ] AMPReportGeneratorStep3.CheckBox1.Check ()
	[ ] AMPReportGeneratorStep3.CheckBox2.Check ()
	[ ] AMPReportGeneratorStep3.CheckBox3.Check ()
	[ ] AMPReportGeneratorStep3.Add.Click()
	[ ] AMPReportGeneratorStep3.Next.Click()
	[ ] AMPReportGeneratorStep4.CheckAll.Click()
	[ ] AMPReportGeneratorStep4.Add.Click()
	[ ] AMPReportGeneratorStep4.Next.Click()
	[ ] AMPReportGeneratorStep5.N5ReportDetails1.ReportTitle.HtmlTextField1.SetText ("test report")
	[ ] AMPReportGeneratorStep5.SaveReport.Click ()
	[ ] AMPDesktopLinks.TopMenu.REPORTS.Click ()
	[ ] 
	[ ] 
[-] testcase Test1_2() appstate DefaultBaseState
	[ ] login("atl@amp.org", "atl")
	[ ] AMPMyDesktop.SetActive( )
	[ ] AMPDesktopLinks.TopMenu.REPORTS.Click ()
	[ ] AMPPublicTeamReports.ReportGenerator.Click ()
	[ ] AMPReportGeneratorStep1.N5ReportDetails.Select (1)
	[ ] AMPReportGeneratorStep1.Next.Click ()
	[ ] AMPReportGeneratorStep2.SelectAll.AMP.Identification.Check ()
	[ ] AMPReportGeneratorStep2.Add.Click ()
	[ ] AMPReportGeneratorStep2.SelectAll.AMP.Location.ImplementationLevel.Check ()
	[ ] AMPReportGeneratorStep2.Add.Click ()
	[ ] AMPReportGeneratorStep2.Next1.Click ()
	[ ] AMPReportGeneratorStep3.Next.Click ()
	[ ] AMPReportGeneratorStep4.CheckBox1.Click()
	[ ] AMPReportGeneratorStep4.CheckBox2.Click()
	[ ] AMPReportGeneratorStep4.Add.Click ()
	[ ] AMPReportGeneratorStep4.Next.Click ()
	[ ] AMPReportGeneratorStep5.N5ReportDetails1.ReportTitle.HtmlTextField1.SetText("test some columns report")
	[ ] AMPReportGeneratorStep5.SaveReport.Click ()
	[ ] AMPDesktopLinks.TopMenu.REPORTS.Click ()
	[ ] 
[-] testcase Test1_3() appstate DefaultBaseState
	[ ] login("atl@amp.org", "atl")
	[ ] AMPMyDesktop.SetActive( )
	[ ] AMPDesktopLinks.TopMenu.REPORTS.Click ()
	[ ] AMPPublicTeamReports.ReportGenerator.Click ()
	[ ] AMPReportGeneratorStep1.N5ReportDetails.Select (1)
	[ ] AMPReportGeneratorStep1.Next.Click ()
	[ ] AMPReportGeneratorStep2.SelectAll.AMP.Identification.Check ()
	[ ] AMPReportGeneratorStep2.Add.Click ()
	[ ] AMPReportGeneratorStep2.Next1.Click()
	[ ] AMPReportGeneratorStep3.CheckBox1.Check ()
	[ ] AMPReportGeneratorStep3.CheckBox2.Check ()
	[ ] AMPReportGeneratorStep3.Add.Click()
	[ ] AMPReportGeneratorStep3.MoveUp2.Click ()
	[ ] AMPReportGeneratorStep3.Next.Click ()
	[ ] AMPReportGeneratorStep4.CheckBox1.Check ()
	[ ] AMPReportGeneratorStep4.CheckBox2.Check ()
	[ ] AMPReportGeneratorStep4.Add.Click ()
	[ ] AMPReportGeneratorStep4.Next.Click ()
	[ ] AMPReportGeneratorStep5.N5ReportDetails1.ReportTitle.HtmlTextField1.SetText("test hierarchy report")
	[ ] AMPReportGeneratorStep5.SaveReport.Click ()
	[ ] AMPDesktopLinks.TopMenu.REPORTS.Click ()
	[ ] 
[-] testcase Test1_4() appstate DefaultBaseState
	[ ] login("atl@amp.org", "atl")
	[ ] AMPMyDesktop.SetActive( )
	[ ] AMPDesktopLinks.TopMenu.REPORTS.Click ()
	[ ] AMPPublicTeamReports.ReportGenerator.Click ()
	[ ] AMPReportGeneratorStep1.N5ReportDetails.Select (1)
	[ ] AMPReportGeneratorStep1.Next.Click ()
	[ ] AMPReportGeneratorStep2.SelectAll.AMP.Identification.Check ()
	[ ] AMPReportGeneratorStep2.Add.Click ()
	[ ] AMPReportGeneratorStep2.SetActive( )
	[ ] AMPDesktopLinks.AccessionInstrument.Check ()
	[ ] AMPReportGeneratorStep2.Remove.Click ()
	[ ] AMPReportGeneratorStep2.Next1.Click ()
	[ ] AMPReportGeneratorStep3.CheckBox1.Check ()
	[ ] AMPReportGeneratorStep3.CheckBox2.Check ()
	[ ] AMPReportGeneratorStep3.Add.Click ()
	[ ] AMPReportGeneratorStep3.ProjectTitle.Check ()
	[ ] AMPReportGeneratorStep3.Remove.Click ()
	[ ] AMPReportGeneratorStep3.Next.Click ()
	[ ] AMPReportGeneratorStep4.CheckBox1.Check ()
	[ ] AMPReportGeneratorStep4.CheckBox2.Check ()
	[ ] AMPReportGeneratorStep4.Add.Click ()
	[ ] AMPReportGeneratorStep4.ActualDisbursements.Check ()
	[ ] AMPReportGeneratorStep4.Remove.Click ()
	[ ] AMPReportGeneratorStep4.Next.Click ()
	[ ] AMPReportGeneratorStep5.N5ReportDetails1.ReportTitle.HtmlTextField1.SetText("test add/remove")
	[ ] AMPReportGeneratorStep5.SaveReport.Click ()
	[ ] AMPDesktopLinks.TopMenu.REPORTS.Click ()
	[ ] 
[-] testcase Test1_5() appstate DefaultBaseState
	[ ] login("atl@amp.org", "atl")
	[ ] AMPMyDesktop.SetActive( )
	[ ] AMPDesktopLinks.TopMenu.REPORTS.Click ()
	[ ] AMPPublicTeamReports.ReportGenerator.Click ()
	[ ] AMPReportGeneratorStep1.N5ReportDetails.Select (1)
	[ ] AMPReportGeneratorStep1.Next.Click ()
	[ ] AMPReportGeneratorStep2.SelectAll.AMP.Identification.Check ()
	[ ] AMPReportGeneratorStep2.Add.Click ()
	[ ] AMPReportGeneratorStep2.SelectAll.AMP.Location.ImplementationLevel.Check ()
	[ ] AMPReportGeneratorStep2.Add.Click ()
	[ ] AMPReportGeneratorStep2.Next1.Click ()
	[ ] AMPReportGeneratorStep3.CheckBox1.Check ()
	[ ] AMPReportGeneratorStep3.CheckBox2.Check ()
	[ ] AMPReportGeneratorStep3.Add.Click ()
	[ ] AMPReportGeneratorStep3.Next.Click ()
	[ ] AMPReportGeneratorStep4.CheckBox1.Check ()
	[ ] AMPReportGeneratorStep4.CheckBox2.Check ()
	[ ] AMPReportGeneratorStep4.Add.Click ()
	[ ] AMPReportGeneratorStep4.Next.Click ()
	[ ] AMPReportGeneratorStep5.N5ReportDetails1.ReportTitle.HtmlTextField1.SetText("test donor report")
	[ ] AMPReportGeneratorStep5.SaveReport.Click ()
	[ ] AMPDesktopLinks.TopMenu.REPORTS.Click ()
	[ ] 
[-] testcase Test1_6() appstate DefaultBaseState
	[ ] login("atl@amp.org", "atl")
	[ ] AMPMyDesktop.SetActive( )
	[ ] AMPDesktopLinks.TopMenu.REPORTS.Click ()
	[ ] AMPPublicTeamReports.ReportGenerator.Click ()
	[ ] AMPReportGeneratorStep1.N5ReportDetails.Select (2)
	[ ] AMPReportGeneratorStep1.Next.Click ()
	[ ] AMPReportGeneratorStep2.SelectAll.AMP.Identification.Check ()
	[ ] AMPReportGeneratorStep2.Add.Click ()
	[ ] AMPReportGeneratorStep2.SelectAll.AMP.Location.ImplementationLevel.Check ()
	[ ] AMPReportGeneratorStep2.Add.Click ()
	[ ] AMPReportGeneratorStep2.Next1.Click ()
	[ ] AMPReportGeneratorStep3.CheckBox1.Check ()
	[ ] AMPReportGeneratorStep3.CheckBox2.Check ()
	[ ] AMPReportGeneratorStep3.Add.Click ()
	[ ] AMPReportGeneratorStep3.Next.Click ()
	[ ] AMPReportGeneratorStep4.CheckBox1.Check ()
	[ ] AMPReportGeneratorStep4.CheckBox2.Check ()
	[ ] AMPReportGeneratorStep4.Add.Click ()
	[ ] AMPReportGeneratorStep4.Next.Click ()
	[ ] AMPReportGeneratorStep5.N5ReportDetails1.ReportTitle.HtmlTextField1.SetText("test regional report")
	[ ] AMPReportGeneratorStep5.SaveReport.Click ()
	[ ] 
	[ ] 
