export const DEFAULT_UI_DATE_FORMAT = 'DD/MMM/YYYY';
export const DATE_FORMAT_SETTING = 'default-date-format';
export const CALENDAR_SETTING = 'calendar-id';
export const ETH_BASE_CALENDAR = 'ETH-CAL';
export const GREG_BASE_CALENDAR = 'GREG-CAL';
export const EP_DATE_FORMAT =  'YYYY-MM-DD';
export const CALENDAR_IS_FISCAL = 'is-fiscal';

export const NATIONAL_BUDGET_EXECUTION_PROCEDURES = 'National Budget Execution Procedures';
export const NATIONAL_FINANCIAL_REPORTING_PROCEDURES = 'National Financial Reporting Procedures';
export const NATIONAL_AUDITING_PROCEDURES = 'National Auditing Procedures';
export const NATIONAL_PROCUREMENT_EXECUTION_PROCEDURES = 'National Procurement Systems';
export const YEAR = 'Year';
export const FY = 'FY';
export const DONOR_GROUP = 'Donor Group';
export const DONOR_AGENCY = 'Donor Agency';
export const ACTIVITY_ID = 'Activity Id';
export const DONOR_ID = 'Donor Id';
export const PLANNED_DISBURSEMENTS = 'Planned Disbursements';
export const ANNUAL_GOVERNMENT_BUDGET = 'Funds Recorded in Government Annual Budget';
export const PERCENTAGE_OF_PLANNED_ON_BUDGET = '% of planned on budget';
export const INDICATOR_5B = 'Indicator 5b';
export const TOTAL_ACTUAL_DISBURSEMENTS = 'Total Actual Disbursements';
export const CONCESSIONAL = 'Concessional';
export const ACTUAL_DISBURSEMENTS = 'Actual Disbursements';
export const DISBURSEMENTS_THROUGH_OTHER_PROVIDERS = 'Disbursements through other providers';
export const DISBURSEMENTS_AS_SCHEDULED = 'Disbursed as Scheduled';
export const OVER_DISBURSED = 'Over Disbursed';
export const USE_OF_COUNTRY_SYSTEMS = 'Use of country systems';
export const NATIONAL_LEVEL = '(National Level)';
export const REMARK = 'Remark';
export const NUMBER_OF_REMARKS = 'Number of Remarks';
export const INDICATOR_1_CODE = '1';
export const INDICATOR_1_1_CODE = '1_1';
export const INDICATOR_5A_CODE = '5a';
export const INDICATOR_5B_CODE = '5b';
export const INDICATOR_6_CODE = '6';
export const INDICATOR_9B_CODE = '9b';
export const INDICATOR_CODE_LIST = [INDICATOR_1_CODE, INDICATOR_5A_CODE, INDICATOR_5B_CODE,INDICATOR_6_CODE, INDICATOR_9B_CODE];

//Indicator 1 constants
export const Q1 = 'Q1';
export const Q2 = 'Q2';
export const Q3 = 'Q3';
export const Q4 = 'Q4';
export const Q5 = 'Q5';
export const Q6 = 'Q6';
export const Q7 = 'Q7';
export const Q8 = 'Q8';
export const Q9 = 'Q9';
export const Q10 = 'Q10';
export const Q11 = 'Q11';
export const PROJECT_TITLE = 'Project Title';
export const RESULT = 'Result';
export const M_E = 'M&E';
export const ACTUAL_COMMITMENTS = 'Actual Commitments';//
export const ACTUAL_APPROVAL_DATE = 'Actual Approval Date';
export const FINANCING_INSTRUMENT = 'Financing Instrument';
export const IMPLEMENTING_AGENCY = 'Implementing Agency';
export const PRIMARY_SECTOR = 'Primary Sector';
export const Q6_DESCRIPTION = 'Q6 Description';
export const Q10_DESCRIPTION = 'Q10 Description';
export const OUTPUT_1 = '1';
export const OUTPUT_2 = '2';
export const DELIMETER = '###';

export const XLS = 'xls';
export const PDF = 'pdf';

export const IMG_INFO = 'IMG_INFO';
export const IMG_VALUE = 'IMG_INFO';

export const OPTION_YES = 'Yes';
export const OPTION_NO = 'No';
