<?php

/**
 * @file
 * Exposes cached_amp_activity table to Drupal.
 */

/**
 * The DB key for the AMP database.
 */
define('AMP_DATABASE', 'amp_projects');

/**
 * Define some of the AMP trasaction type constants.
 */
define('AMP_TRANSACTION_TYPE_COMMITMENT', 0); // Commitment.
define('AMP_TRANSACTION_TYPE_DISBURSEMENT', 1); // Disbursement.
define('AMP_TRANSACTION_TYPE_EXPENDITURE', 2); // Expenditure.

/**
 * Implements hook_views_api().
 */
function amp_activity_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'amp_activity') . '/views',
  );
}

/**
 * Returns...
 *
 * @TODO: Add more cache, the cached_amp_activity table is updated rarely.
 */
function amp_activity_get_amp_activities() {
  $activities_list = &drupal_static(__FUNCTION__, NULL);

  if (isset($activities_list)) {
    return $activities_list;
  }

  db_set_active(AMP_DATABASE);

  $query = db_select('cached_amp_activity', 'cached_amp_activity');
  $query->addField('cached_amp_activity', 'amp_activity_id');

  $query->where('cached_amp_activity.draft <> TRUE');
  $query->where('cached_amp_activity.amp_team_id IS NOT NULL');
  $query->where('cached_amp_activity.approval_status IN (\'approved\', \'startedapproved\')');

  // Get Activities which have one parent of type "Management"? I guess!?!
  $case_one_sub = "SELECT amp_team_id FROM amp_team WHERE access_type = 'Management'";
  $case_one = "SELECT amp_team_id FROM amp_team WHERE parent_team_id IN ($case_one_sub)";
  $snippets[] = $case_one;

  // It sure does something... but I don't know what to name it.
  $case_two_sub = "SELECT amp_org_id FROM amp_team_orgs WHERE amp_team_id IN ($case_one)";
  $case_two = "SELECT DISTINCT(activity) FROM amp_org_role WHERE organisation IN ($case_two_sub)";
  $snippets[] = $case_two;

  $db_or = db_or();
  foreach ($snippets as $case) {
    $db_or->where("cached_amp_activity.amp_activity_id IN (${case})");
  }
  $query->condition($db_or);

  $results = $query->execute()->fetchCol();
  db_set_active();

  if (!empty($results) && is_array($results)) {
    $activities_list = $results;
  }

  return $activities_list;
}

/**
 * Returns an array of 'Activity Budget' options.
 */
function _amp_activity_get_onoff_budget_ids() {
  $options = &drupal_static(__FUNCTION__);
  if (isset($options)) {
    return $options;
  }

  db_set_active(AMP_DATABASE);

  // Get the amp_category_class_id.
  $subquery = db_select('amp_category_class')
    ->fields('amp_category_class', array('id'))
    ->condition('amp_category_class.keyname', 'activity_budget', '=');

  // Get category values for 'Activity Budget'.
  $query = db_select('amp_category_value')
    ->distinct()
    ->fields('amp_category_value', array('id', 'category_value'))
    ->orderBy('amp_category_value.index_column')
    ->condition('amp_category_value.amp_category_class_id', $subquery, 'IN');

  $result = $query->execute();
  db_set_active();

  foreach ($result as $record) {
    switch ($record->category_value) {
      case 'Off Budget':
        $options['off'] = $record->id;
        break;
      case 'On Budget':
        $options['on'] = $record->id;
        break;
    }
  }

  return $options;
}

/**
 * Returns a 'date_year_range' string for the date_popup widget.
 */
function _amp_activity_activities_period_range_limits() {
  $date_year_range = &drupal_static(__FUNCTION__);

  if (isset($date_year_range)) {
    return $date_year_range;
  }

  $this_year = date('Y');

  // By default display a decent amount of years.
  $default = '-30:+30';

  db_set_active('amp_projects');

  try {
    // Get the started date for the oldest activity.
    $query = db_select('cached_amp_activity', 'activity')
      ->fields('activity', array('actual_start_date'))
      ->condition('actual_start_date', '1900-01-01 00:00:00', '!=')
      ->orderby('actual_start_date', 'ASC')
      ->range(0, 1);
    $min_year = $query->execute()->fetchField();

    // Get the completion date for the most recently completed activity.
    $query = db_select('cached_amp_activity', 'activity')
      ->fields('activity', array('actual_completion_date'))
      ->isNotNull('actual_completion_date')
      ->orderby('actual_completion_date', 'DESC')
      ->range(0, 1);
    $max_year = $query->execute()->fetchField();

  }
  catch (Exception $e) {
    drupal_set_message($e->getMessage(), 'error');
    return $default;
  }

  db_set_active();

  if (empty($min_year) || empty($max_year)) {
    return $default;
  }

  // Extract the year.
  $min_year = date('Y', strtotime($min_year));
  $max_year = date('Y', strtotime($max_year));

  if ($min_year - $this_year < 0) {
    $range_start = (string) ($min_year - $this_year);
  }
  else {
    $range_start = '-0';
  }

  if ($max_year - $this_year > 0) {
    $range_end = '+' . ($max_year - $this_year);
  }
  else {
    $range_end = (string) ($max_year - $this_year);
  }

  // Create a 'date_year_range' string for the date_popup widget.
  $date_year_range = implode(':', array($range_start, $range_end));

  return $date_year_range;
}

/**
 * Returns the children of a sector ID.
 */
function _amp_activity_get_child_sector_ids($parent_sector_id) {
  $child_sector_ids = array();

  db_set_active(AMP_DATABASE);

  $child_ids = db_select('amp_sector', 'amps')
    ->fields('amps', array('amp_sector_id'))
    ->condition('amps.parent_sector_id', $parent_sector_id, '=')->execute()
    ->fetchCol();
  db_set_active();

  foreach ($child_ids as $child_id) {
    $child_sector_ids[] = $child_id;
    $child_sector_ids = array_merge($child_sector_ids, _amp_activity_get_child_sector_ids($child_id));
  }

  return $child_sector_ids;
}

/**
 * Returns the parents of a location ID.
 */
function _amp_activity_get_location_parent_ids($location_id) {
  $include_country_level_projects = &drupal_static('_amp_activity_get_location_parent_ids', FALSE);

  if (empty($include_country_level_projects)) {
    return array();
  }

  db_set_active(AMP_DATABASE);

  $parent_ids = db_select('amp_category_value_location', 'acvl')
    ->fields('acvl', array('parent_location'))
    ->condition('acvl.id', $location_id, '=')
    ->isNotNull('acvl.parent_location')
    ->execute()
    ->fetchCol();
  db_set_active();

  $parent_location_ids = array();
  foreach ($parent_ids as $parent_id) {
    $parent_location_ids[] = $parent_id;

    $parent_location_ids = array_merge($parent_location_ids, _amp_activity_get_location_parent_ids($parent_id));
  }

  return $parent_location_ids;
}

/**
 * Returns the children of a program ID.
 */
function _amp_activity_get_child_program_ids($program_id) {
  $child_program_ids = array();

  db_set_active(AMP_DATABASE);

  $child_ids = db_select('amp_team', 'amp_team')
    ->fields('amp_team', array('amp_team_id'))
    ->condition('amp_team.parent_team_id', $program_id, '=')
    ->execute()
    ->fetchCol();
  db_set_active();

  foreach ($child_ids as $child_id) {
    $child_program_ids[] = $child_id;
    $child_program_ids = array_merge($child_program_ids, _amp_activity_get_child_program_ids($child_id));
  }

  return $child_program_ids;
}
