insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('af', '87081', 'Afghanistan', 'AFG', 't', 't', 't', 'cn:af', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('al', '87084', 'Albania', 'ALB', 't', 't', 't', 'cn:al', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('dz', '87136', 'Algeria', 'DZA', 'f', 't', 't', 'cn:dz', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('as', '87090', 'American Samoa', 'ASM', 't', 't', 't', 'cn:as', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ad', '87079', 'Andorra', 'AND', 't', 't', 'f', 'cn:ad', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ao', '87087', 'Angola', 'AGO', 'f', 'f', 't', 'cn:ao', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ai', '87083', 'Anguilla', 'AIA', 't', 't', 'f', 'cn:ai', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('aq', '87088', 'Antarctica', '', 't', 't', 'f', 'cn:aq', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ag', '87082', 'Antigua and Barbuda', 'ATG', 't', 't', 't', 'cn:ag', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ar', '87089', 'Argentina', 'ARG', 't', 't', 't', 'cn:ar', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('am', '87085', 'Armenia', 'ARM', 't', 't', 't', 'cn:am', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('aw', '87093', 'Aruba', 'ABW', 't', 't', 't', 'cn:aw', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('au', '87092', 'Australia', 'AUS', 't', 't', 't', 'cn:au', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('at', '87091', 'Austria', 'AUT', 't', 't', 't', 'cn:at', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('az', '87094', 'Azerbaijan', 'AZE', 't', 't', 't', 'cn:az', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('bs', '87108', 'Bahamas', 'BHS', 't', 't', 't', 'cn:bs', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('bh', '87101', 'Bahrain', 'BHR', 'f', 't', 't', 'cn:bh', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('bd', '87097', 'Bangladesh', 'BGD', 't', 't', 't', 'cn:bd', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ps', '112008', 'Palestinian Territory, Occupied', 'PSE', 't', 't', 'f', 'cn:ps', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('bb', '87096', 'Barbados', 'BRB', 't', 't', 't', 'cn:bb', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('by', '87112', 'Belarus', 'BLR', 't', 't', 't', 'cn:by', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('be', '87098', 'Belgium', 'BEL', 't', 't', 't', 'cn:be', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('bz', '87113', 'Belize', 'BLZ', 't', 't', 't', 'cn:bz', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('bj', '87103', 'Benin', 'BEN', 't', 't', 't', 'cn:bj', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('bm', '87104', 'Bermuda', 'BMU', 't', 't', 't', 'cn:bm', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('bt', '87109', 'Bhutan', 'BTN', 't', 't', 't', 'cn:bt', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('bo', '87106', 'Bolivia', 'BOL', 't', 't', 't', 'cn:bo', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ba', '87095', 'Bosnia and Herzegovina', 'BIH', 't', 't', 't', 'cn:ba', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('bw', '87111', 'Botswana', 'BWA', 't', 't', 't', 'cn:bw', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('bv', '87110', 'Bouvet Island', '', 't', 't', 'f', 'cn:bv', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('br', '87107', 'Brazil', 'BRA', 't', 't', 't', 'cn:br', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('io', '87179', 'British Indian Ocean Territory', '', 't', 't', 'f', 'cn:io', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('bn', '87105', 'Brunei Darussalam', 'BRN', 't', 't', 't', 'cn:bn', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('bg', '87100', 'Bulgaria', 'BGR', 't', 't', 't', 'cn:bg', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('bf', '87099', 'Burkina Faso', 'BFA', 't', 't', 't', 'cn:bf', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('bi', '87102', 'Burundi', 'BDI', 't', 't', 't', 'cn:bi', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('kh', '87189', 'Cambodia', 'KHM', 't', 't', 't', 'cn:kh', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('cm', '87121', 'Cameroon', 'CMR', 't', 't', 't', 'cn:cm', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ca', '87114', 'Canada', 'CAN', 't', 't', 't', 'cn:ca', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('cv', '87127', 'Cape Verde', 'CPV', 't', 't', 't', 'cn:cv', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ky', '87196', 'Cayman Islands', 'CYM', 't', 't', 't', 'cn:ky', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('cf', '87116', 'Central African Republic', 'CAF', 't', 't', 't', 'cn:cf', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('td', '87283', 'Chad', 'TCD', 't', 't', 't', 'cn:td', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('cl', '87120', 'Chile', 'CHL', 't', 't', 't', 'cn:cl', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('cn', '87122', 'China', 'CHN', 't', 't', 't', 'cn:cn', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('cx', '87128', 'Christmas Island', '', 't', 't', 'f', 'cn:cx', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('cc', '87115', 'Cocos (Keeling) Islands', '', 't', 't', 'f', 'cn:cc', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('co', '87123', 'Colombia', 'COL', 't', 't', 't', 'cn:co', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('km', '87191', 'Comoros', 'COM', 't', 't', 't', 'cn:km', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('cg', '87117', 'Congo', 'COG', 't', 't', 't', 'cn:cg', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('cd', '112009', 'Congo, Democratic Republic Of', 'COD', 't', 't', 'f', 'cn:cd', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ck', '87119', 'Cook Islands', 'COK', 't', 't', 'f', 'cn:ck', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('cr', '87124', 'Costa Rica', 'CRI', 't', 't', 't', 'cn:cr', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ci', '112007', 'Cote d`Ivoire', 'CIV', 't', 't', 't', 'cn:ci', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('hr', '87172', 'Croatia (Hrvatska)', 'HRV', 't', 't', 't', 'cn:hr', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('cu', '87126', 'Cuba', 'CUB', 't', 't', 't', 'cn:cu', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('cy', '87129', 'Cyprus', 'CYP', 't', 't', 't', 'cn:cy', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('cz', '87130', 'Czech Republic', 'CZE', 't', 't', 't', 'cn:cz', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('dk', '87133', 'Denmark', 'DNK', 't', 't', 't', 'cn:dk', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('dj', '87132', 'Djibouti', 'DJI', 't', 't', 't', 'cn:dj', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('dm', '87134', 'Dominica', 'DMA', 't', 't', 't', 'cn:dm', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('do', '87135', 'Dominican Republic', 'DOM', 't', 't', 't', 'cn:do', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('tp', '87292', 'East Timor', 'TMP', 't', 't', 'f', 'cn:tp', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ec', '87137', 'Ecuador', 'ECU', 't', 't', 't', 'cn:ec', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('eg', '87139', 'Egypt', 'EGY', 't', 't', 't', 'cn:eg', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('sv', '87279', 'El Salvador', 'SLV', 't', 't', 't', 'cn:sv', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('gq', '87162', 'Equatorial Guinea', 'GNQ', 't', 't', 't', 'cn:gq', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('er', '87141', 'Eritrea', 'ERI', 't', 't', 't', 'cn:er', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ee', '87138', 'Estonia', 'EST', 't', 't', 't', 'cn:ee', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('et', '87143', 'Ethiopia', 'ETH', 't', 't', 't', 'cn:et', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('fk', '87146', 'Falkland Islands (Malvinas)', 'FLK', 't', 't', 'f', 'cn:fk', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('fo', '87148', 'Faroe Islands', 'FRO', 't', 't', 't', 'cn:fo', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('fj', '87145', 'Fiji', 'FJI', 't', 't', 't', 'cn:fj', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('fi', '87144', 'Finland', 'FIN', 't', 't', 't', 'cn:fi', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('fr', '87149', 'France', 'FRA', 't', 't', 't', 'cn:fr', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('gf', '87155', 'French Guiana', 'GUF', 't', 't', 'f', 'cn:gf', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('pf', '87246', 'French Polynesia', 'PYF', 't', 't', 't', 'cn:pf', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('tf', '87284', 'French Southern Territories', '', 't', 't', 'f', 'cn:tf', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ga', '87151', 'Gabon', 'GAB', 't', 't', 't', 'cn:ga', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('gm', '87159', 'Gambia', 'GMB', 't', 't', 't', 'cn:gm', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ge', '87154', 'Georgia', 'GEO', 't', 't', 't', 'cn:ge', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('de', '87131', 'Germany', 'DEU', 't', 't', 't', 'cn:de', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('gh', '87156', 'Ghana', 'GHA', 't', 't', 't', 'cn:gh', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('gi', '87157', 'Gibraltar', 'GIB', 't', 't', 'f', 'cn:gi', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('gr', '87163', 'Greece', 'GRC', 't', 't', 't', 'cn:gr', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('gl', '87158', 'Greenland', 'GRL', 't', 't', 't', 'cn:gl', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('gd', '87153', 'Grenada', 'GRD', 't', 't', 't', 'cn:gd', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('gp', '87161', 'Guadeloupe', 'GLP', 't', 't', 'f', 'cn:gp', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('gu', '87166', 'Guam', 'GUM', 't', 't', 't', 'cn:gu', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('gt', '87165', 'Guatemala', 'GTM', 't', 't', 't', 'cn:gt', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('gn', '87160', 'Guinea', 'GIN', 't', 't', 't', 'cn:gn', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('gw', '87167', 'Guinea-Bissau', 'GNB', 't', 't', 't', 'cn:gw', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('gy', '87168', 'Guyana', 'GUY', 't', 't', 't', 'cn:gy', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ht', '87173', 'Haiti', 'HTI', 't', 't', 't', 'cn:ht', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('hm', '87170', 'Heard and McDonald Islands', '', 't', 't', 'f', 'cn:hm', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('va', '87305', 'Vatican City State (Holy See)', 'VAT', 't', 't', 'f', 'cn:va', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('hn', '87171', 'Honduras', 'HND', 't', 't', 't', 'cn:hn', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('hk', '87169', 'Hong Kong', 'HKG', 't', 't', 't', 'cn:hk', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('hu', '87174', 'Hungary', 'HUN', 't', 't', 't', 'cn:hu', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('is', '87182', 'Iceland', 'ISL', 't', 't', 't', 'cn:is', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('in', '87178', 'India', 'IND', 't', 't', 't', 'cn:in', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('id', '87175', 'Indonesia', 'IDN', 't', 't', 't', 'cn:id', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ir', '87181', 'Iran', 'IRN', 't', 't', 't', 'cn:ir', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('iq', '87180', 'Iraq', 'IRQ', 't', 't', 't', 'cn:iq', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ie', '87176', 'Ireland', 'IRL', 't', 't', 't', 'cn:ie', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('il', '87177', 'Israel', 'ISR', 't', 't', 't', 'cn:il', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('it', '87183', 'Italy', 'ITA', 't', 't', 't', 'cn:it', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('jm', '87184', 'Jamaica', 'JAM', 't', 't', 't', 'cn:jm', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('jp', '87186', 'Japan', 'JPN', 't', 't', 't', 'cn:jp', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('jo', '87185', 'Jordan', 'JOR', 't', 't', 't', 'cn:jo', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('kz', '87197', 'Kazakhstan', 'KAZ', 't', 't', 't', 'cn:kz', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ke', '87187', 'Kenya', 'KEN', 't', 't', 't', 'cn:ke', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ki', '87190', 'Kiribati', 'KIR', 't', 't', 't', 'cn:ki', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('kp', '87193', 'Korea (North)', 'PRK', 't', 't', 't', 'cn:kp', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('kr', '87194', 'Korea (South)', 'KOR', 't', 't', 't', 'cn:kr', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('kw', '87195', 'Kuwait', 'KWT', 't', 't', 't', 'cn:kw', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('kg', '87188', 'Kyrgyzstan', 'KGZ', 't', 't', 't', 'cn:kg', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ua', '87298', 'Ukraine', 'UKR', 't', 't', 't', 'cn:ua', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('la', '87198', 'Laos', 'LAO', 't', 't', 't', 'cn:la', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('lv', '87207', 'Latvia', 'LVA', 't', 't', 't', 'cn:lv', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ma', '87209', 'Morocco', 'MAR', 't', 't', 't', 'cn:ma', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('pk', '87249', 'Pakistan', 'PAK', 't', 't', 't', 'cn:pk', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('lb', '87199', 'Lebanon', 'LBN', 't', 't', 't', 'cn:lb', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ls', '87204', 'Lesotho', 'LSO', 't', 't', 't', 'cn:ls', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('lr', '87203', 'Liberia', 'LBR', 't', 't', 't', 'cn:lr', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ly', '87208', 'Libya', 'LBY', 't', 't', 't', 'cn:ly', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('li', '87201', 'Liechtenstein', 'LIE', 't', 't', 't', 'cn:li', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('lt', '87205', 'Lithuania', 'LTU', 't', 't', 't', 'cn:lt', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('lu', '87206', 'Luxembourg', 'LUX', 't', 't', 't', 'cn:lu', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('mo', '87218', 'Macau', 'MAC', 't', 't', 't', 'cn:mo', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('mk', '87214', 'Macedonia', 'MKD', 't', 't', 't', 'cn:mk', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('mg', '87212', 'Madagascar', 'MDG', 't', 't', 't', 'cn:mg', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('mw', '87226', 'Malawi', 'MWI', 't', 't', 't', 'cn:mw', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('my', '87228', 'Malaysia', 'MYS', 't', 't', 't', 'cn:my', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('mv', '87225', 'Maldives', 'MDV', 't', 't', 't', 'cn:mv', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ml', '87215', 'Mali', 'MLI', 't', 't', 't', 'cn:ml', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('mt', '87223', 'Malta', 'MLT', 't', 't', 't', 'cn:mt', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('mh', '87213', 'Marshall Islands', 'MHL', 't', 't', 't', 'cn:mh', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('mq', '87220', 'Martinique', 'MTQ', 't', 't', 'f', 'cn:mq', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('mr', '87221', 'Mauritania', 'MRT', 't', 't', 't', 'cn:mr', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('mu', '87224', 'Mauritius', 'MUS', 't', 't', 't', 'cn:mu', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('yt', '87315', 'Mayotte', '', 't', 't', 'f', 'cn:yt', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('mx', '87227', 'Mexico', 'MEX', 't', 't', 't', 'cn:mx', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('fm', '87147', 'Micronesia', 'FSM', 't', 't', 't', 'cn:fm', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('md', '87211', 'Moldova', 'MDA', 't', 't', 't', 'cn:md', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('mc', '87210', 'Monaco', 'MCO', 't', 't', 't', 'cn:mc', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('mn', '87217', 'Mongolia', 'MNG', 't', 't', 't', 'cn:mn', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ms', '87222', 'Montserrat', 'MSR', 't', 't', 'f', 'cn:ms', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('mz', '87229', 'Mozambique', 'MOZ', 't', 't', 't', 'cn:mz', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('mm', '87216', 'Myanmar', 'MMR', 't', 't', 't', 'cn:mm', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('na', '87230', 'Namibia', 'NAM', 't', 't', 't', 'cn:na', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('nr', '87239', 'Nauru', 'NRU', 't', 't', 'f', 'cn:nr', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('np', '87238', 'Nepal', 'NPL', 't', 't', 't', 'cn:np', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('nl', '87236', 'Netherlands', 'NLD', 't', 't', 't', 'cn:nl', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('an', '87086', 'Netherlands Antilles', 'ANT', 't', 't', 't', 'cn:an', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('nc', '87231', 'New Caledonia', 'NCL', 't', 't', 't', 'cn:nc', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('nz', '87242', 'New Zealand (Aotearoa)', 'NZL', 't', 't', 't', 'cn:nz', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ni', '87235', 'Nicaragua', 'NIC', 't', 't', 't', 'cn:ni', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ne', '87232', 'Niger', 'NER', 't', 't', 't', 'cn:ne', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ng', '87234', 'Nigeria', 'NGA', 't', 't', 't', 'cn:ng', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('nu', '87241', 'Niue', 'NIU', 't', 't', 'f', 'cn:nu', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('nf', '87233', 'Norfolk Island', 'NFK', 't', 't', 'f', 'cn:nf', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('mp', '87219', 'Northern Mariana Islands', 'MNP', 't', 't', 't', 'cn:mp', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('no', '87237', 'Norway', 'NOR', 't', 't', 't', 'cn:no', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('om', '87243', 'Oman', 'OMN', 't', 't', 't', 'cn:om', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('pw', '87255', 'Palau', 'PLW', 't', 't', 't', 'cn:pw', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('pa', '87244', 'Panama', 'PAN', 't', 't', 't', 'cn:pa', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('pg', '87247', 'Papua New Guinea', 'PNG', 't', 't', 't', 'cn:pg', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('py', '87256', 'Paraguay', 'PRY', 't', 't', 't', 'cn:py', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('pe', '87245', 'Peru', 'PER', 't', 't', 't', 'cn:pe', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ph', '87248', 'Philippines', 'PHL', 't', 't', 't', 'cn:ph', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('pn', '87252', 'Pitcairn', 'PCN', 't', 't', 'f', 'cn:pn', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('pl', '87250', 'Poland', 'POL', 't', 't', 't', 'cn:pl', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('pt', '87254', 'Portugal', 'PRT', 't', 't', 't', 'cn:pt', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('pr', '87253', 'Puerto Rico', 'PRI', 't', 't', 't', 'cn:pr', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('qa', '87257', 'Qatar', 'QAT', 't', 't', 't', 'cn:qa', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('re', '87258', 'Reunion', 'REU', 't', 't', 'f', 'cn:re', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ru', '87260', 'Russian Federation', 'RUS', 't', 't', 't', 'cn:ru', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('rw', '87261', 'Rwanda', 'RWA', 't', 't', 't', 'cn:rw', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('sh', '87268', 'St. Helena', 'SHN', 't', 't', 'f', 'cn:sh', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('kn', '87192', 'Saint Kitts and Nevis', 'KNA', 't', 't', 't', 'cn:kn', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('lc', '87200', 'Saint Lucia', 'LCA', 't', 't', 't', 'cn:lc', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('pm', '87251', 'St. Pierre and Miquelon', 'SPM', 't', 't', 'f', 'cn:pm', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('vc', '87306', 'Saint Vincent and the Grenadines', 'VCT', 't', 't', 't', 'cn:vc', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ws', '87313', 'Samoa', 'WSM', 't', 't', 't', 'cn:ws', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('sm', '87273', 'San Marino', 'SMR', 't', 't', 't', 'cn:sm', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('st', '87277', 'Sao Tome and Principe', 'STP', 't', 't', 't', 'cn:st', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('sa', '87262', 'Saudi Arabia', 'SAU', 't', 't', 't', 'cn:sa', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('sn', '87274', 'Senegal', 'SEN', 't', 't', 't', 'cn:sn', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('sc', '87264', 'Seychelles', 'SYC', 't', 't', 't', 'cn:sc', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('sl', '87272', 'Sierra Leone', 'SLE', 't', 't', 't', 'cn:sl', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('sg', '87267', 'Singapore', 'SGP', 't', 't', 't', 'cn:sg', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('sk', '87271', 'Slovak Republic', 'SVK', 't', 't', 't', 'cn:sk', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('si', '87269', 'Slovenia', 'SVN', 't', 't', 't', 'cn:si', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('sb', '87263', 'Solomon Islands', 'SLB', 't', 't', 't', 'cn:sb', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('so', '87275', 'Somalia', 'SOM', 't', 't', 't', 'cn:so', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('za', '87317', 'South Africa', 'ZAF', 't', 't', 't', 'cn:za', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('gs', '87164', 'S. Georgia and S. Sandwich Isls.', '', 't', 't', 'f', 'cn:gs', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('es', '87142', 'Spain', 'ESP', 't', 't', 't', 'cn:es', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('lk', '87202', 'Sri Lanka', 'LKA', 't', 't', 't', 'cn:lk', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('sd', '87265', 'Sudan', 'SDN', 't', 't', 't', 'cn:sd', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('sr', '87276', 'Suriname', 'SUR', 't', 't', 't', 'cn:sr', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('sj', '87270', 'Svalbard and Jan Mayen Islands', 'SJM', 't', 't', 'f', 'cn:sj', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('sz', '87281', 'Swaziland', 'SWZ', 't', 't', 't', 'cn:sz', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('se', '87266', 'Sweden', 'SWE', 't', 't', 't', 'cn:se', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ch', '87118', 'Switzerland', 'CHE', 't', 't', 't', 'cn:ch', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('sy', '87280', 'Syria', 'SYR', 't', 't', 't', 'cn:sy', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('tw', '87296', 'Taiwan', 'TWN', 't', 't', 'f', 'cn:tw', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('tj', '87287', 'Tajikistan', 'TJK', 't', 't', 't', 'cn:tj', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('tz', '87297', 'Tanzania', 'TZA', 't', 't', 't', 'cn:tz', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('th', '87286', 'Thailand', 'THA', 't', 't', 't', 'cn:th', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('tg', '87285', 'Togo', 'TGO', 't', 't', 't', 'cn:tg', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('tk', '87288', 'Tokelau', 'TKL', 't', 't', 'f', 'cn:tk', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('to', '87291', 'Tonga', 'TON', 't', 't', 't', 'cn:to', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('tt', '87294', 'Trinidad and Tobago', 'TTO', 't', 't', 't', 'cn:tt', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('tn', '87290', 'Tunisia', 'TUN', 't', 't', 't', 'cn:tn', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('tr', '87293', 'Turkey', 'TUR', 't', 't', 't', 'cn:tr', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('tm', '87289', 'Turkmenistan', 'TKM', 't', 't', 't', 'cn:tm', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('tc', '87282', 'Turks and Caicos Islands', 'TCA', 't', 't', 'f', 'cn:tc', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('tv', '87295', 'Tuvalu', 'TUV', 't', 't', 'f', 'cn:tv', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ug', '87299', 'Uganda', 'UGA', 't', 't', 't', 'cn:ug', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ae', '87080', 'United Arab Emirates', 'ARE', 't', 't', 't', 'cn:ae', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('gb', '87300', 'United Kingdom', '', 't', 't', 'f', 'cn:gb', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('us', '87302', 'United States', 'USA', 't', 't', 't', 'cn:us', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('um', '87301', 'US Minor Outlying Islands', '', 't', 't', 'f', 'cn:um', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('uy', '87303', 'Uruguay', 'URY', 't', 't', 't', 'cn:uy', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('uz', '87304', 'Uzbekistan', 'UZB', 't', 't', 't', 'cn:uz', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('vu', '87311', 'Vanuatu', 'VUT', 't', 't', 't', 'cn:vu', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ve', '87307', 'Venezuela', 'VEN', 't', 't', 't', 'cn:ve', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('vn', '87310', 'Viet Nam', 'VNM', 't', 't', 't', 'cn:vn', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('vg', '87308', 'Virgin Islands (British)', 'VIR', 't', 't', 't', 'cn:vg', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('vi', '87309', 'Virgin Islands (U.S.)', 'VGB', 't', 't', 'f', 'cn:vi', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('wf', '87312', 'Wallis and Futuna Islands', 'WLF', 't', 't', 'f', 'cn:wf', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('eh', '87140', 'Western Sahara', 'ESH', 't', 't', 'f', 'cn:eh', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ye', '87314', 'Yemen', 'YEM', 't', 't', 't', 'cn:ye', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('yu', '87316', 'Yugoslavia', 'YUG', 't', 't', 't', 'cn:yu', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('zm', '87318', 'Zambia', 'ZMB', 't', 't', 't', 'cn:zm', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('zw', '87320', 'Zimbabwe', 'ZWE', 't', 't', 't', 'cn:zw', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('ro', '87259', 'Romania', 'ROM', 't', 't', 't', 'cn:ro', '1');
insert into DG_COUNTRIES (iso, country_id, country_name, iso3, stat, show_ctry, dec_ctry, message_lang_key, available) values('  ', '98975', 'Multi-country', '   ', 't', 't', 't', 'cn:  ', '1');
commit;
