require "csv"

# Load Rails environment
ENV['RAILS_ENV'] = ARGV.first || ENV['RAILS_ENV'] || 'development'
require File.expand_path(File.dirname(__FILE__) + "/../config/environment")

CSV.parse(DATA.read) do |l|
  if l[0]
    # Save last sector
    if @current_main_sector
      @current_main_sector.save!
    end
      
    code = l[0].to_i
    # This is a DAC three digit code!
    @current_main_sector = DacSector.create(:code => code, :name => l[2].upcase, :description => l[3])
    print "\nAdding section #{code.to_s + '    ' + l[2]}"
  else
    # This is a CRS five digit code!
    code = l[1].to_i
    new_sect = CrsSector.create(:code => code, :name => l[2], :description => l[3])
    @current_main_sector.crs_sectors << new_sect
    
    # Print a dot to show progress.. flush statement is necessary to print it unbuffered!
    print "."
    $stdout.flush
  end
  
  # Finally save the last sector
  @current_main_sector.save!
end

puts "\ndone."

__END__
111,,"Education, level unspecified",The codes in this category are to be used only when level of education is unspecified or unknown (e.g. training of primary school teachers should be coded under 11220).,
,11110,Education policy and administrative management,"Education sector policy, planning and programmes; aid to education ministries, administration and management systems; institution capacity building and advice; school management and governance; curriculum and materials development; unspecified education activities.",
,11120,Education facilities and training,"Educational buildings, equipment, materials; subsidiary services to education (boarding facilities, staff housing); language training; colloquia, seminars, lectures, etc.",
,11130,Teacher training,Teacher education (where the level of education is unspecified); in-service and pre-service training; materials development.,
,11182,Educational research,"Research and studies on education effectiveness, relevance and quality; systematic evaluation and monitoring.",
112,,Basic education,,
,11220,Primary education,Formal and non-formal primary education for children; all elementary and first cycle systematic instruction; provision of learning materials.,
,11230,Basic life skills for youth and adults ,Formal and non-formal education for basic life skills for young people and adults (adults education); literacy and numeracy training.,
,11240,Early childhood education,Formal and non-formal pre-school education.,
113,,Secondary education,,
,11320,Secondary education,Second cycle systematic instruction at both junior and senior levels.,
,11330,Vocational training,Elementary vocational training and secondary level technical education; on-the job training; apprenticeships; including informal vocational training.,
114,,Post-secondary education,,
,11420,Higher education,"Degree and diploma programmes at universities, colleges and polytechnics; scholarships.",
,11430,Advanced technical and managerial training,Professional-level vocational training programmes and in-service training.,
121,,"Health, general",,
,12110,Health policy and administrative management,"Health sector policy, planning and programmes; aid to health ministries, public health administration; institution capacity building and advice; medical insurance programmes; unspecified health activities.",
,12181,Medical education/training,Medical education and training for tertiary level services.,
,12182,Medical research,General medical research (excluding basic health research).,
,12191,Medical services,"Laboratories, specialised clinics and hospitals (including equipment and supplies); ambulances; dental services; mental health care; medical rehabilitation; control of non-infectious diseases; drug and substance abuse control [excluding narcotics traffic control (16063)].",
122,,Basic health,,
,12220,Basic health care,"Basic and primary health care programmes; paramedical and nursing care programmes; supply of drugs, medicines and vaccines related to basic health care.",
,12230,Basic health infrastructure,"District-level hospitals, clinics and dispensaries and related medical equipment; excluding specialised hospitals and clinics (12191).",
,12240,Basic nutrition,"Direct feeding programmes (maternal feeding, breastfeeding and weaning foods, child feeding, school feeding); determination of micro-nutrient deficiencies; provision of vitamin A, iodine, iron etc.; monitoring of nutritional status; nutrition and food hygiene education; household food security.",
,12250,Infectious disease control,"Immunisation; prevention and control of infectious and parasite diseases, except malaria (12262), tuberculosis (12263), HIV/AIDS and other STDs (13040). It includes diarrheal diseases, vector-borne diseases (e.g. river blindness and guinea worm), viral diseases, mycosis, helminthiasis, zoonosis, diseases by other bacteria and viruses, pediculosis, etc.",
,12261,Health education,"Information, education and training of the population for improving health knowledge and practices; public health and awareness campaigns. ",
,12262,Malaria control,Prevention and control of malaria.,
,12263,Tuberculosis control,"Immunisation, prevention and control of tuberculosis.",
,12281,Health personnel development,Training of health staff for basic health care services.,
130,,POPULATION POLICIES/PROGRAMMES AND REPRODUCTIVE HEALTH,,
,13010,Population policy and administrative management,"Population/development policies; census work, vital registration; migration data; demographic research/analysis; reproductive health research; unspecified population activities.",
,13020,Reproductive health care,Promotion of reproductive health; prenatal and postnatal care including delivery; prevention and treatment of infertility; prevention and management of consequences of abortion; safe motherhood activities.,
,13030,Family planning,"Family planning services including counselling; information, education and communication (IEC) activities; delivery of contraceptives; capacity building and training.",
,13040,STD control including HIV/AIDS,"All activities related to sexually transmitted diseases and HIV/AIDS control e.g. information, education and communication; testing; prevention; treatment, care.",
,13081,Personnel development for population and reproductive health,Education and training of health staff for population and reproductive health care services.,
140,,WATER SUPPLY AND SANITATION,,
,14010,Water resources policy and administrative management,"Water sector policy, planning and programmes; water legislation and management; institution capacity building and advice; water supply assessments and studies; groundwater, water quality and watershed studies; hydrogeology; excluding agricultural water resources (31140).",
,14015,Water resources protection,"Inland surface waters (rivers, lakes, etc.); conservation and rehabilitation of ground water; prevention of water contamination from agro-chemicals, industrial effluents.",
,14020,Water supply and sanitation - large systems,"Water desalination plants; intakes, storage, treatment, pumping stations, conveyance and distribution systems; sewerage; domestic and industrial waste water treatment plants. ",
,14030,Basic drinking water supply and basic sanitation,"Water supply and sanitation through low-cost technologies such as handpumps, spring catchment, gravity-fed systems, rain water collection, storage tanks, small distribution systems; latrines, small-bore sewers, on-site disposal (septic tanks).",
,14040,River development,Integrated river basin projects; river flow control; dams and reservoirs [excluding dams primarily for irrigation (31140) and hydropower (23065) and activities related to river transport (21040)]. ,
,14050,Waste management/disposal,"Municipal and industrial solid waste management, including hazardous and toxic waste; collection, disposal and treatment; landfill areas; composting and reuse.",
,14081,Education and training in water supply and sanitation ,,
151,,"Government and civil society, general",,
,15110,Economic and development policy/planning,"Macro-economic, fiscal and monetary policy and planning; social planning; economic and social analysis and forecasting; development planning and preparation of structural reforms; organisational development; support to ministries involved in aid co-ordination; other ministries and government departments when sector cannot be specified.  (Use code 51010 for budget support to macroeconomic reforms.)",
,15120,Public sector financial management,"Strengthening financial and managerial accountability; public expenditure management; improving financial management systems; tax assessment procedures; budget drafting; field auditing; measures against waste, fraud and corruption.",
,15130,Legal and judicial development,"Constitutional development, legal drafting; institutional strengthening of legal and judicial systems; legal training and education; legal advice and services; crime prevention.",
,15140,Government administration ,"Systems of government including parliament, local government, decentralisation; civil service and civil service reform.  Including general services by government (or commissioned by government) not elsewhere specified e.g. police, fire protection; cartography, meteorology, legal metrology, aerial surveys and remote sensing; administrative buildings. ",
,15150,Strengthening civil society,"Community participation and development; co-operatives; grassroots organisations; development of other participatory planning and decision making procedures and institutions (see code 15220 for civilian peace-building, conflict prevention and resolution).",
,15161,Elections,"Electoral assistance and monitoring, voters’ education [other than in connection with UN peace building (15230)].",
,15162,Human rights,"Monitoring of human rights performance; support for national and regional human rights bodies; protection of ethnic, religious and cultural minorities [other than in connection with UN peace building (15230)].",
,15163,Free flow of information,"Uncensored flow of information on public issues, including activities that increase the professionalism, skills and integrity of the print and broadcast media (e.g. training of journalists).",
,15164,Women’s equality organisations and institutions,Support for institutions and organisations (governmental and non-governmental) working for gender equality and women’s empowerment.,
152,,"Conflict prevention and resolution, peace and security","N.B.  Further notes on ODA eligibility (and exclusions) of conflict, peace and security related activities are given in paragraph 39 of the DAC Statistical Reporting Directives.",
,15210,Security system management and reform,"Technical co-operation provided to parliament, government ministries, law enforcement agencies and the judiciary to assist review and reform of the security system to improve democratic governance and civilian control; technical co-operation provided to government to improve civilian oversight and democratic control of budgeting, management, accountability and auditing of security expenditure, including military budgets, as part of a public expenditure management programme; assistance to civil society to enhance its competence and capacity to scrutinise the security system so that it is managed in accordance with democratic norms and principles of accountability, transparency and good governance.",
,15220,"Civilian peace-building, conflict prevention and resolution","Support for civilian activities related to peace building, conflict prevention and resolution, including capacity building, monitoring, dialogue and information exchange.",
,15230,Post-conflict peace-building (UN),"Participation in the post-conflict peace-building phase of United Nations peace operations (activities such as human rights and elections monitoring, rehabilitation of demobilised soldiers, rehabilitation of basic national infrastructure,  monitoring or retraining of civil administrators and police forces, training in customs and border control procedures, advice or training in fiscal or macroeconomic stabilisation policy, repatriation and demobilisation of armed factions, and disposal of their weapons; support for landmine removal).  Direct contributions to the UN peacekeeping budget are excluded from bilateral ODA (they are reportable in part as multilateral ODA).",
,15240,Reintegration and SALW control,"Reintegration of demobilised military personnel into the economy; conversion of production facilities from military to civilian outputs; technical co-operation to control, prevent and/or reduce the proliferation of small arms and light weapons (SALW) – see para. 39 of the DAC Statistical Reporting Directives for definition of SALW activities covered. [Other than in connection with UN peace-building (15230) or child soldiers (15261)].",
,15250,Land mine clearance,Explosive mine removal for developmental purposes [other than in connection with UN peace-building (15230)].,
,15261,Child soldiers (Prevention and demobilisation) ,"Technical co-operation provided to government – and assistance to civil society organisations – to support and apply legislation designed to prevent the recruitment of child soldiers, and to demobilise, disarm, reintegrate, repatriate and resettle (DDR) child soldiers.",
160,,OTHER SOCIAL INFRASTRUCTURE AND SERVICES,,
,16010,Social/ welfare services,"Social legislation and administration; institution capacity building and advice; social security and other social schemes; special programmes for the elderly, orphans, the disabled, street children; social dimensions of structural adjustment; unspecified social infrastructure and services, including consumer protection.",
,16020,Employment policy and administrative management,Employment policy and planning; labour law; labour unions; institution capacity building and advice; support programmes for unemployed; employment creation and income generation programmes; occupational safety and health; combating child labour.,
,16030,Housing policy and administrative management,"Housing sector policy, planning and programmes;  excluding low-cost housing and slum clearance (16040).",
,16040,Low-cost housing,Including slum clearance.,
,16050,Multisector aid for basic social services ,"Basic social services are defined to include basic education, basic health, basic nutrition, population/reproductive health and basic drinking water supply and basic sanitation.",
,16061,Culture and recreation,Including libraries and museums.,
,16062,Statistical capacity building,Both in national statistical offices and any other government ministries.,
,16063,Narcotics control,In-country and customs controls including training of the police; educational programmes and awareness campaigns to restrict narcotics traffic and in-country distribution.,
,16064,Social mitigation of HIV/AIDS,"Special programmes to address the consequences of HIV/AIDS, e.g. social, legal and economic assistance to people living with HIV/AIDS including food security and employment; support to vulnerable groups and children orphaned by HIV/AIDS; human rights of HIV/AIDS affected people. ",
210,,TRANSPORT AND STORAGE,Note: Manufacturing of transport equipment should be included under code 32172.,
,21010,Transport policy and administrative management,"Transport sector policy, planning and programmes; aid to transport ministries; institution capacity building and advice; unspecified transport; activities that combine road, rail, water and/or air transport.",
,21020,Road transport,"Road infrastructure, road vehicles; passenger road transport, motor passenger cars.",
,21030,Rail transport,"Rail infrastructure, rail equipment, locomotives, other rolling stock; including light rail (tram) and underground systems.",
,21040,Water transport,"Harbours and docks, harbour guidance systems, ships and boats; river and other inland water transport, inland barges and vessels.",
,21050,Air transport,"Airports, airport guidance systems, aeroplanes, aeroplane maintenance equipment.",
,21061,Storage,Whether or not related to transportation.,
,21081,Education and training in transport and storage,,
,22010,Communications policy and administrative management,"Communications sector policy, planning and programmes; institution capacity building and advice; including postal services development; unspecified communications activities.",
,22020,Telecommunications,"Telephone networks, telecommunication satellites, earth stations.",
,22030,Radio/television/print media,"Radio and TV links, equipment; newspapers; printing and publishing.",
,22040,Information and communication technology (ICT),Computer hardware and software; internet access; IT training.  When sector cannot be specified.  ,
230,,ENERGY GENERATION AND SUPPLY,,
,23010,Energy policy and administrative management,"Energy sector policy, planning and programmes; aid to energy ministries; institution capacity building and advice; unspecified energy activities including energy conservation.",
,23020,Power generation/non-renewable sources ,Thermal power plants including when heat source cannot be determined; combined gas-coal power plants.,
,23030,Power generation/renewable sources ,"Including policy, planning, development programmes, surveys and incentives. Fuelwood/ charcoal production should be included under forestry (31261).",
,23040,Electrical transmission/ distribution,Distribution from power source to end user; transmission lines.,
,23050,Gas distribution,Delivery for use by ultimate consumer.,
,23061,Oil-fired power plants,Including diesel power plants.,
,23062,Gas-fired power plants,,
,23063,Coal-fired power plants,,
,23064,Nuclear power plants,Including nuclear safety.,
,23065,Hydro-electric power plants,Including power-generating river barges.,
,23066,Geothermal energy,,
,23067,Solar energy,"Including photo-voltaic cells, solar thermal applications and solar heating.",
,23068,Wind power,Wind energy for water lifting and electric power generation.,
,23069,Ocean power,"Including ocean thermal energy conversion, tidal and wave power.",
,23070,Biomass,"Densification technologies and use of biomass for direct power generation including biogas, gas obtained from sugar cane and other plant residues, anaerobic digesters.",
,23081,Energy education/training,Applies to all energy sub-sectors; all levels of training.,
,23082,Energy research,"Including general inventories, surveys.",
240,,BANKING AND FINANCIAL SERVICES,,
,24010,Financial policy and administrative management,"Finance sector policy, planning and programmes; institution capacity building and advice; financial markets and systems.",
,24020,Monetary institutions,Central banks.,
,24030,Formal sector financial intermediaries,"All formal sector financial intermediaries; credit lines; insurance, leasing, venture capital, etc. (except when focused on only one sector).",
,24040,Informal/semi-formal financial intermediaries,"Micro credit, savings and credit co-operatives etc.",
,24081,Education/training in banking and financial services,,
250,,BUSINESS AND OTHER SERVICES,,
,25010,Business support services and institutions,"Support to trade and business associations, chambers of commerce; legal and regulatory reform aimed at improving business and investment climate; private sector institution capacity building and advice; trade information; public-private sector networking including trade fairs; e‑commerce.  Where sector cannot be specified: general support to private sector enterprises (in particular, use code 32130 for enterprises in the industrial sector).",
,25020,Privatisation,"When sector cannot be specified.  Including general state enterprise restructuring or demonopolisation programmes; planning, programming, advice.",
311,,AGRICULTURE,,
,31110,Agricultural policy and administrative management,"Agricultural sector policy, planning and programmes; aid to agricultural ministries;  institution capacity building and advice; unspecified agriculture.",
,31120,Agricultural development,Integrated projects; farm development.,
,31130,Agricultural land resources,"Including soil degradation control; soil improvement; drainage of water logged areas; soil desalination; agricultural land surveys; land reclamation; erosion control, desertification control.",
,31140,Agricultural water resources,"Irrigation, reservoirs, hydraulic structures, ground water exploitation for agricultural use.",
,,,,
,31150,Agricultural inputs,"Supply of seeds, fertilizers, agricultural machinery/equipment.",
,31161,Food crop production,"Including grains (wheat, rice, barley, maize, rye, oats, millet, sorghum); horticulture; vegetables; fruit and berries; other annual and perennial crops. [Use code 32161 for agro-industries.]",
,31162,Industrial crops/export crops,"Including sugar; coffee, cocoa, tea; oil seeds, nuts, kernels; fibre crops; tobacco; rubber.  [Use code 32161 for agro-industries.]",
,31163,Livestock,Animal husbandry; animal feed aid.,
,31164,Agrarian reform,Including agricultural sector adjustment.,
,31165,Agricultural alternative development,Projects to reduce illicit drug cultivation through other agricultural marketing and production opportunities (see code 43050 for non-agricultural alternative development).,
,31166,Agricultural extension,Non-formal training in agriculture.,
,31181,Agricultural education/training,,
,31182,Agricultural research,"Plant breeding, physiology, genetic resources, ecology, taxonomy, disease control, agricultural bio-technology; including livestock research (animal health, breeding and genetics, nutrition, physiology).",
,31191,Agricultural services,"Marketing policies & organisation; storage and transportation, creation of strategic reserves.",
,31192,Plant and post-harvest protection and pest control,"Including integrated plant protection, biological plant protection activities, supply and management of agrochemicals, supply of pesticides, plant protection policy and legislation.",
,31193,Agricultural financial services,Financial intermediaries for the agricultural sector including credit schemes; crop insurance.,
,31194,Agricultural co-operatives,Including farmers’ organisations.,
,31195,Livestock/veterinary services,"Animal health and management, genetic resources, feed resources.",
312,,FORESTRY,,
,31210,Forestry policy and administrative management,"Forestry sector policy, planning and programmes; institution capacity building and advice; forest surveys; unspecified forestry and agro-forestry activities.",
,31220,Forestry development,"Afforestation for industrial and rural consumption; exploitation and utilisation; erosion control, desertification control; integrated forestry projects.",
,31261,Fuelwood/charcoal,Forestry development whose primary purpose is production of fuelwood and charcoal.,
,31281,Forestry education/training,,
,31282,Forestry research,"Including artificial regeneration, genetic improvement, production methods, fertilizer, harvesting.",
,31291,Forestry services,,
313,,FISHING,,
,31310,Fishing policy and administrative management,"Fishing sector policy, planning and programmes; institution capacity building and advice; ocean and coastal fishing; marine and freshwater fish surveys and prospecting; fishing boats/equipment; unspecified fishing activities.",
,31320,Fishery development,Exploitation and utilisation of fisheries; fish stock protection; aquaculture; integrated fishery projects.,
,31381,Fishery education/training,,
,31382,Fishery research,Pilot fish culture; marine/freshwater biological research.,
,31391,Fishery services,Fishing harbours; fish markets; fishery transport and cold storage.,
321,,INDUSTRY,,
,32110,Industrial policy and administrative management,"Industrial sector policy, planning and programmes; institution capacity building and advice; unspecified industrial activities; manufacturing of goods not specified below.",
,32120,Industrial development,,
,32130,Small and medium-sized enterprises (SME) development,"Direct support to the development of small and medium-sized enterprises in the industrial sector, including accounting, auditing and advisory services.",
,32140,Cottage industries and handicraft,,
,32161,Agro-industries,"Staple food processing, dairy products, slaughter houses and equipment, meat and fish processing and preserving, oils/fats, sugar refineries, beverages/tobacco, animal feeds production.",
,32162,Forest industries,"Wood production, pulp/paper production.",
,32163,"Textiles, leather and substitutes",Including knitting factories. ,
,32164,Chemicals ,Industrial and non-industrial production facilities; includes pesticides production.,
,32165,Fertilizer plants,,
,32166,Cement/lime/plaster,,
,32167,Energy manufacturing,Including gas liquefaction; petroleum refineries.,
,32168,Pharmaceutical production,"Medical equipment/supplies; drugs, medicines, vaccines; hygienic products.",
,32169,Basic metal industries,"Iron and steel, structural metal production.",
,32170,Non-ferrous metal industries,,
,32171,Engineering,"Manufacturing of electrical and non-electrical machinery, engines/turbines.",
,32172,Transport equipment industry,"Shipbuilding, fishing boats building; railroad equipment; motor vehicles and motor passenger cars; aircraft; navigation/guidance systems.",
,32182,Technological research and development,Including industrial standards; quality management; metrology;  testing;  accreditation;  certification.,
322,,MINERAL RESOURCES AND MINING,,
,32210,Mineral/mining policy and administrative management,"Mineral and mining sector policy, planning and programmes;  mining legislation, mining cadastre, mineral resources inventory, information systems, institution capacity building and advice;  unspecified mineral resources exploitation.",
,32220,Mineral prospection and exploration,"Geology, geophysics, geochemistry;  excluding hydrogeology (14010) and environmental geology (41010), mineral extraction and processing, infrastructure, technology, economics, safety and environment management.",
,32261,Coal,Including lignite and peat.,
,32262,Oil and gas,"Petroleum, natural gas, condensates, liquefied petroleum gas (LPG), liquefied natural gas (LNG);  including drilling and production.",
,32263,Ferrous metals,Iron and ferro-alloy metals.,
,32264,Nonferrous metals,"Aluminium, copper, lead, nickel, tin, zinc.",
,32265,Precious metals/materials,"Gold, silver, platinum, diamonds, gemstones.",
,32266,Industrial minerals,"Baryte, limestone, feldspar, kaolin, sand, gypsym, gravel, ornamental stones.",
,32267,Fertilizer minerals,"Phosphates, potash.",
,32268,Offshore minerals,"Polymetallic nodules, phosphorites, marine placer deposits.",
323,,CONSTRUCTION,,
,32310,Construction policy and administrative management,"Construction sector policy and planning; excluding construction activities within specific sectors (e.g., hospital or school construction).",
331,,TRADE POLICY AND REGULATIONS,,
,33110,Trade policy and administrative management,Trade policy and planning; support to ministries and departments responsible for trade policy; trade-related legislation and regulatory reforms; policy analysis and implementation of multilateral trade agreements e.g. technical barriers to trade and sanitary and phytosanitary measures (TBT/SPS) except at regional level (see 33130); mainstreaming trade in national development strategies (e.g. poverty reduction strategy papers); wholesale/retail trade; unspecified trade and trade promotion activities.,
,33120,Trade facilitation,"Simplification and harmonisation of international import and export procedures (e.g. customs valuation, licensing procedures, transport formalities, payments, insurance); support to customs departments; tariff reforms.",
,33130,Regional trade agreements (RTAs),"Support to regional trade arrangements [e.g. Southern African Development Community (SADC), Association of Southeast Asian Nations (ASEAN), Free Trade Area of the Americas (FTAA), African Caribbean Pacific/European Union (ACP/EU)], including work on technical barriers to trade and sanitary and phytosanitary measures (TBT/SPS) at regional level; elaboration of rules of origin and introduction of special and differential treatment in RTAs.",
,33140,Multilateral trade negotiations,"Support developing countries’ effective participation in multilateral trade negotiations, including training of negotiators, assessing impacts of negotiations; accession to the World Trade Organisation (WTO) and other multilateral trade-related organisations.",
,33150,Trade-related adjustment,Contributions to the government budget to assist the implementation of recipients' own trade reforms and adjustments to trade policy measures by other countries; assistance to manage shortfalls in the balance of payments due to changes in the world trading environment. ,
,33181,Trade education/training,Human resources development in trade not included under any of the above codes.  Includes university programmes in trade.,
332,,TOURISM,,
,33210,Tourism policy and administrative management,,
410,,General environmental protection,Non-sector specific.,
,41010,Environmental policy and administrative management,"Environmental policy, laws, regulations and economic instruments; administrational institutions and practices; environmental and land use planning and decision-making procedures; seminars, meetings; miscellaneous conservation and protection measures not specified below.",
,41020,Biosphere protection,"Air pollution control, ozone layer preservation; marine pollution control.",
,41030,Bio-diversity,Including natural reserves and actions in the surrounding areas; other measures to protect endangered or vulnerable species and their habitats (e.g. wetlands preservation).,
,41040,Site preservation,"Applies to unique cultural landscape; including sites/objects of historical, archeological, aesthetic, scientific or educational value.",
,41050,Flood prevention/control,Floods from rivers or the sea; including sea water intrusion control and sea level rise related activities.,
,41081,Environmental education/ training,,
,41082,Environmental research,"Including establishment of databases, inventories/accounts of physical and natural resources; environmental profiles and impact studies if not sector specific.",
420,,Women in development,,
,42010,Women in development,"Including multisectoral WID projects and programmes; promotion of and support to WID groups and networks; conferences, seminars, etc.",
430,,Other multisector,,
,43010,Multisector aid,,
,43030,Urban development and management,Integrated urban development projects; local development and urban management; urban infrastructure and services; municipal finances; urban environmental management; urban development and planning; urban renewal and urban housing; land information systems.,
,43040,Rural development,"Integrated rural development projects;  e.g. regional development planning;  promotion of decentralised and multi-sectoral competence for planning, co-ordination and management;  implementation of regional development and measures (including natural reserve management);  land management;  land use planning; land settlement and resettlement activities [excluding resettlement of refugees and internally displaced persons (72010)]; functional integration of rural and urban areas;  geographical information systems.",
,43050,Non-agricultural alternative development,"Projects to reduce illicit drug cultivation through, for example, non-agricultural income opportunities, social and physical infrastructure (see code 31165 for agricultural alternative development).",
,43081,Multisector education/training,Including scholarships.,
,43082,Research/scientific institutions,When sector cannot be identified.,
510,,General budget support,Budget support in the form of sector-wide approaches (SWAps) should be included in the respective sectors. ,
,51010,General budget support,"Unearmarked contributions to the government budget; support for the implementation of macroeconomic reforms (structural adjustment programmes, poverty reduction strategies); general programme assistance (when not allocable by sector).",
520,,Developmental food aid/Food security assistance,,
,52010,Food aid/Food security programmes,Supply of edible human food under national or international programmes including transport costs; cash payments made for food supplies; project food aid and food aid for market sales when benefiting sector not specified; excluding emergency food aid.,
530,,Other commodity assistance,Non-food commodity assistance (when benefiting sector not specified).,
,53030,Import support (capital goods),Capital goods and services; lines of credit.,
,53040,Import support (commodities),"Commodities, general goods and services, oil imports.",
600,,ACTION RELATING TO DEBT,,
,60010,Action relating to debt,Actions falling outside the code headings below; training in debt management.,
,60020,Debt forgiveness ,,
,60030,Relief of multilateral debt,Grants or credits to cover debt owed to multilateral financial institutions; including contributions to Heavily Indebted Poor Countries (HIPC) Trust Fund.,
,60040,Rescheduling and refinancing,,
,60061,Debt for development swap,"Allocation of debt claims to use for development (e.g., debt for education, debt for environment).",
,60062,Other debt swap,Where the debt swap benefits an external agent i.e. is not specifically for development purposes.,
,60063,Debt buy-back,Purchase of debt for the purpose of cancellation.,
720,,Emergency Response,An emergency is a situation which results from man made crises and/or natural disasters.,
,72010,Material relief assistance and services ,"Shelter, water, sanitation and health services, supply of medicines and other non-food relief items; assistance to refugees and  internally displaced people in developing countries other than for food (72040) or protection (72050).  ",
,72040,Emergency food aid,Food aid normally for general free distribution or special supplementary feeding programmes; short-term relief to targeted population groups affected by emergency situations.  Excludes non-emergency food security assistance programmes/food aid (52010).,
,72050,Relief co-ordination; protection and support services ,"Measures to co-ordinate delivery of humanitarian aid, including logistics and communications systems;  measures to promote and protect the safety, well-being, dignity and integrity of civilians and those no longer taking part in hostilities.  (Activities designed to protect the security of persons or property through the use or display of force are not reportable as ODA.)                                                                                                                                                ",
730,,Reconstruction relief and rehabilitation,This relates to activities during and in the aftermath of an emergency situation.  Longer-term activities to improve the level of infrastructure or social services should be reported under the relevant economic and social sector codes. See also guideline on distinguishing humanitarian from sector-allocable aid. ,
,73010,Reconstruction relief and rehabilitation,"Short-term reconstruction work after emergency or conflict limited to restoring pre-existing infrastructure (e.g. repair or construction of roads, bridges and ports, restoration of essential facilities, such as water and sanitation, shelter, health care services); social and economic rehabilitation in the aftermath of emergencies to facilitate transition and enable populations to return to their previous livelihood or develop a new livelihood in the wake of an emergency situation (e.g. trauma counselling and treatment, employment programmes). ",
740,,Disaster prevention and preparedness,See codes 41050 and 15220 for prevention of floods and conflicts.,
,74010,Disaster prevention and preparedness,"Disaster risk reduction activities (e.g. developing knowledge, natural risks cartography, legal norms for construction); early warning systems; emergency contingency stocks and contingency planning including preparations for forced displacement. ",
910,,ADMINISTRATIVE COSTS OF DONORS,,
,91010,Administrative costs,,
920,,SUPPORT TO NON- GOVERNMENTAL ORGANISATIONS (NGOs),Official funds to be paid over to national and international private voluntary agencies for use at the latters’ discretion.,
,92010,Support to national NGOs,In the donor country.,
,92020,Support to international NGOs,,
,92030,Support to local and regional NGOs,In the recipient country or region.,
930,,REFUGEES IN DONOR COUNTRIES,,
,93010,Refugees in donor countries,,
998,,UNALLOCATED / UNSPECIFIED,,
,99810,Sectors not specified,Contributions to general development of the recipient should be included under programme assistance (51010).,
,99820,Promotion of development awareness,"Spending in donor country for heightened awareness/interest in development co-operation (brochures, lectures, special research projects, etc.).",