<?php

/**
 * @file
 *   Provides an input filter that replaces URLs with a shortened version.
 */

/**
 * Implements hook_init().
 */
function shortener_init() {
  // Although this is wasteful on pages that don't need it, it is generally
  // more efficient than disabling caching for input formats using this filter.
  $path = drupal_get_path('module', 'shortener');
  drupal_add_css($path . '/shortener.css');
  drupal_add_js($path . '/shortener.js');
}

/**
 * Implements hook_filter_info().
 */
function shortener_filter_info() {
  $filters = array();
  $filters['shortener'] = array(
    'title' => t('URL shortener'),
    'description' => t('Replaces URLs with a shortened version.'),
    'process callback' => '_shortener_filter_url',
    'settings callback' => '_shortener_url_settings',
    'default settings' => array(
      'shortener_url_behavior' => 'short',
      'shortener_url_length' => 72,
    ),
  );
  return $filters;
}

/**
 * Replaces URLs with the shortened version.
 *
 * Unlike the core URL filter, this only matches HTTP and HTTPS addresses,
 * because those are the only ones accepted by most URL shortening services.
 */
function _shortener_filter_url($text, $filter, $format) {
  $format = $format->format;
  $length = $filter->settings['shortener_url_length'];
  // Pass length to regexp callback.
  _filter_url_trim('', $length);
  // Pass behavior to regexp callback.
  _shortener_url_behavior(NULL, FALSE, $filter->settings['shortener_url_behavior'], $length);

  $text = ' ' . $text . ' ';

  // Match absolute URLs.
  $text = preg_replace_callback("`(<p>|<li>|<br\s*/?>|[ \n\r\t\(])((http://|https://)([a-zA-Z0-9@:%_+*~#?&=.,/;-]*[a-zA-Z0-9@:%_+*~#&=/;-]))([.,?!]*?)(?=(</p>|</li>|<br\s*/?>|[ \n\r\t\)]))`i", '_shortener_url_behavior', $text);

  // Match www domains/addresses.
  $text = preg_replace_callback("`(<p>|<li>|[ \n\r\t\(])(www\.[a-zA-Z0-9@:%_+*~#?&=.,/;-]*[a-zA-Z0-9@:%_+~#\&=/;-])([.,?!]*?)(?=(</p>|</li>|<br\s*/?>|[ \n\r\t\)]))`i", '_shortener_url_parse_partial_links', $text);
  $text = substr($text, 1, -1);

  return $text;
}

/**
 * Processes matches on partial URLs and returns the "fixed" version.
 */
function _shortener_url_parse_partial_links($match) {
  return _shortener_url_behavior($match, TRUE);
}

/**
 * Determines the link caption based on the filter behavior setting.
 */
function _shortener_url_behavior($match, $partial = FALSE, $behavior = NULL, $max_length = NULL) {
  static $_behavior;
  if ($behavior !== NULL) {
    $_behavior = $behavior;
  }
  static $_max_length;
  if ($max_length !== NULL) {
    $_max_length = $max_length;
  }

  if (!empty($match)) {
    $match[2] = decode_entities($match[2]);
    $caption = '';
    $href = $match[2];
    $title = check_url($match[2]);
    if ($_behavior == 'short' || $_behavior == 'strict') {
      $caption = shorten_url($match[2]);
      $href = $caption;
    }
    else {
      $caption = check_plain(_filter_url_trim($match[2]));
      if ($partial) {
        $href = 'http://' . check_url($match[2]);
      }
      $title = shorten_url($match[2]);
    }
    return $match[1] . '<a href="' . $href . '" title="' . $title . '" class="shortener-length-' . $_max_length . ' shortener-link shortener-' . $_behavior . '">' . $caption . '</a>' . $match[$partial ? 3 : 5];
  }
  return '';
}

/**
 * Builds the settings form for the input filter.
 */
function _shortener_url_settings($orig_form, &$form_state, $filter, $format, $defaults, $filters) {
  $filter->settings += $defaults;
  $form = array();
  $form['shortener_url_behavior'] = array(
    '#type' => 'radios',
    '#title' => t('Behavior'),
    '#default_value' => $filter->settings['shortener_url_behavior'],
    '#options' => array(
      'short' => t('Display the shortened URL by default, and add an "(expand)"/"(shorten)" link'),
      'strict' => t('Display the shortened URL by default, and do not allow expanding it'),
      'long' => t('Display the full URL by default, and add a "(shorten)"/"(expand)" link'),
    ),
  );
  $form['shortener_url_length'] = array(
    '#type' => 'textfield',
    '#title' => t('Maximum link text length'),
    '#default_value' => $filter->settings['shortener_url_length'],
    '#maxlength' => 4,
    '#description' => t('URLs longer than this number of characters will be truncated to prevent long strings that break formatting. The link itself will be retained; just the text portion of the link will be truncated.'),
  );
  return $form;
}
