---

- name: Import the amp and amp-cms DB and files
  command: /usr/local/bin/amp-import
  when: amp__import_and_build

- name: Build amp
  command: /usr/local/bin/amp-build
  args:
    chdir: /opt/devgateway/amp212-local/
    #creates: /path/to/database
  notify:
    - service tomcat7 restart

- name: Prepare amp-cms
  command: make prepare-local
  args:
    chdir: /var/www/amp212-cms-local
    #creates: /path/to/database
