package org.dgfoundation.amp.nireports.testcases.generic;

import org.dgfoundation.amp.nireports.TextCell;
import org.dgfoundation.amp.nireports.schema.NiDimension.LevelColumn;

import java.util.Arrays;
import java.util.List;
import java.util.Map;


public class DonorAgencyCells extends HardcodedCells<TextCell>{

    public DonorAgencyCells(Map<String, Long> activityNames, Map<String, Long> entityNames, LevelColumn lc) {
        super(activityNames, entityNames, lc);
    }

    @Override
    protected List<TextCell> populateCells() {
        return  Arrays.asList(
                cell("activity 1 with agreement", "Finland", 21698,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, 1),
                                entry("funding", "Funding Id", 0, 77),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Activity 2 with multiple agreements", "Ministry of Finance", 21699,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21699),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("Activity 2 with multiple agreements", "UNDP", 21695,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21695),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, 2),
                                entry("funding", "Funding Id", 0, 79),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("Activity 2 with multiple agreements", "USAID", 21696,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21696),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, 1),
                                entry("funding", "Funding Id", 0, 78),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Activity Linked With Pledge", "Finland", 21698,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 53),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Activity with both MTEFs and Act.Comms", "Finland", 21698,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2094),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 84),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("Activity with both MTEFs and Act.Comms", "Ministry of Finance", 21699,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21699),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("activity with capital spending", "Finland", 21698,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2124),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 62),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("activity with components", "Finland", 21698,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("activity with contracting agency", "Finland", 21698,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 64),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("activity with contracting agency", "Ministry of Finance", 21699,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21699),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("activity with directed MTEFs", "Ministry of Economy", 21700,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2094),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 88),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("activity with funded components", "UNDP", 21695,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21695),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 75),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("activity with funded components", "Water Foundation", 21702,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21702),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("activity with funded components", "World Bank", 21697,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21697),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("activity with funded components 2", "Finland", 21698,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("activity with incomplete agreement", "Finland", 21698,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, 3),
                                entry("funding", "Funding Id", 0, 81),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("activity with many MTEFs", "Finland", 21698,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 96),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("activity with many MTEFs", "Norway", 21694,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21694),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("activity with many MTEFs", "USAID", 21696,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21696),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 95),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("activity with pipeline MTEFs and act. disb", "Norway", 21694,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21694),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("activity with pipeline MTEFs and act. disb", "UNDP", 21695,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2094),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21695),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 93),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("Activity with planned disbursements", "Norway", 21694,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21694),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 82),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Activity with planned disbursements", "USAID", 21696,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21696),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 83),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("activity with primary_program", "World Bank", 21697,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21697),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 56),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Activity with primary_tertiary_program", "UNDP", 21695,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2093),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21695),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 55),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("activity with tertiary_program", "Ministry of Economy", 21700,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 57),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Activity with Zones", "Finland", 21698,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 41),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Activity With Zones and Percentages", "Norway", 21694,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21694),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 44),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("activity-weird-funding", "Ministry of Finance", 21699,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2095),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21699),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 102),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("activity-with-unfunded-components", "Finland", 21698,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2124),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 73),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("activity-with-unfunded-components", "Ministry of Economy", 21700,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("activity_with_disaster_response", "Finland", 21698,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2094),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 85),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("activity_with_disaster_response", "Ministry of Finance", 21699,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21699),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("arrears test", "Finland", 21698,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 98),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("crazy funding 1", "Finland", 21698,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2094),
                                entry("cats", "Type Of Assistance", 1, 2124),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 40),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("crazy funding 1", "Finland", 21698,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2093),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 39),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("date-filters-activity", "Ministry of Finance", 21699,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21699),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 33),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("department/division", "Finland", 21698,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 107),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Eth Water", "Finland", 21698,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 27),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Eth Water", "Norway", 21694,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21694),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 29),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Eth Water", "USAID", 21696,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21696),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 26),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("execution rate activity", "Ministry of Finance", 21699,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21699),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 94),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("execution rate activity", "UNDP", 21695,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21695),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("expenditure class", "Ministry of Economy", 21700,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 100),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("expenditure class", "Norway", 21694,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21694),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("mtef activity 1", "UNDP", 21695,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21695),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 32),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("mtef activity 2", "Finland", 21698,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2094),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 34),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("new activity with contracting", "Finland", 21698,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 65),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("PID: original", "Ministry of Economy", 21700,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("PID: original > actual", "Ministry of Economy", 21700,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("PID: original, actual", "Ministry of Economy", 21700,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("PID: original, proposed", "Ministry of Economy", 21700,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("PID: original, proposed, actual", "Ministry of Economy", 21700,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("pledged 2", "Finland", 21698,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("pledged 2", "USAID", 21696,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2124),
                                entry("orgs", "DN", 2, 21696),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 60),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("pledged education activity 1", "USAID", 21696,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21696),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 58),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Project with documents", "USAID", 21696,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21696),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("Proposed Project Cost 1 - USD", "Finland", 21698,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("Proposed Project Cost 2 - EUR", "Ministry of Economy", 21700,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("ptc activity 1", "Finland", 21698,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2097),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 35),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("ptc activity 2", "USAID", 21696,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2095),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21696),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 36),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Pure MTEF Project", "Ministry of Economy", 21700,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("Pure MTEF Project", "Ministry of Finance", 21699,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21699),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 24),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Real SSC Activity 1", "Finland", 21698,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 50),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Real SSC Activity 1", "USAID", 21696,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21696),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 51),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Real SSC Activity 1", "World Bank", 21697,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21697),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 49),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Real SSC Activity 2", "Norway", 21694,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21694),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 48),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("regional funding activity 1", "Finland", 21698,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 112),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("regional funding activity 2", "Norway", 21694,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21694),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 113),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("regional funding activity 3", "World Bank", 21697,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21697),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 114),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("second with disaster response", "Norway", 21694,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21694),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 109),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("SSC Project 1", "Finland", 21698,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2094),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 37),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("SSC Project 2", "Water Org", 21701,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2094),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21701),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 38),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("SubNational no percentages", "Ministry of Economy", 21700,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2094),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 52),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("TAC_activity_1", "World Bank", 21697,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21697),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 18),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("TAC_activity_2", "Water Foundation", 21702,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21702),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 19),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Test MTEF directed", "Ministry of Economy", 21700,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2093),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 22),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Test MTEF directed", "USAID", 21696,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21696),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("third activity with agreements", "Finland", 21698,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("third activity with agreements", "Ministry of Finance", 21699,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21699),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, 2),
                                entry("funding", "Funding Id", 0, 80),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Unvalidated activity", "UNDP", 21695,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21695),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 76),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("with annual ppc and actual comm", "Finland", 21698,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 111),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("with weird currencies", "Finland", 21698,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("with weird currencies", "Ministry of Finance", 21699,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2094),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21699),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 97),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("with weird currencies", "Norway", 21694,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21694),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))));
    }

}
