package org.dgfoundation.amp.nireports.testcases.generic;

import java.util.Arrays;
import java.util.List;
import java.util.Map;
import org.dgfoundation.amp.nireports.schema.NiDimension.LevelColumn;

import org.dgfoundation.amp.nireports.TextCell;


public class DonorTypeCells extends HardcodedCells<TextCell>{

    public DonorTypeCells(Map<String, Long> activityNames, Map<String, Long> entityNames, LevelColumn lc) {
        super(activityNames, entityNames, lc);
    }

    @Override
    protected List<TextCell> populateCells() {
        return  Arrays.asList(
            cell("activity 1 with agreement", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, 1),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Activity 2 with multiple agreements", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, 1),
                    entry("orgs", "DN", 2, 21696),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Activity 2 with multiple agreements", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, 2),
                    entry("orgs", "DN", 2, 21695),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Activity Linked With Pledge", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Activity with both MTEFs and Act.Comms", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, 2094),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity with capital spending", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2124))),
            cell("activity with contracting agency", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity with directed MTEFs", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, 2094),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21700),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity with funded components", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21695),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity with incomplete agreement", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, 3),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity with many MTEFs", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21696),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity with many MTEFs", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity with pipeline MTEFs and act. disb", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, 2094),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21695),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Activity with planned disbursements", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21694),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Activity with planned disbursements", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21696),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity with primary_program", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21697),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Activity with primary_tertiary_program", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, 2093),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21695),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity with tertiary_program", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21700),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Activity with Zones", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Activity With Zones and Percentages", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21694),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity-weird-funding", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, 2095),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21699),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity-with-unfunded-components", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2124))),
            cell("activity_with_disaster_response", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, 2094),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("arrears test", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("crazy funding 1", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, 2093),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("crazy funding 1", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, 2094),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2124))),
            cell("date-filters-activity", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21699),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("department/division", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Eth Water", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21696),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Eth Water", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Eth Water", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21694),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("execution rate activity", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21699),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("expenditure class", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21700),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("mtef activity 1", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21695),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("mtef activity 2", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, 2094),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("new activity with contracting", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("pledged 2", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21696),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2124))),
            cell("pledged education activity 1", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21696),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("ptc activity 1", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, 2097),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("ptc activity 2", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, 2095),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21696),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Pure MTEF Project", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21699),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Real SSC Activity 1", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21697),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Real SSC Activity 1", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Real SSC Activity 1", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21696),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Real SSC Activity 2", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21694),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("second with disaster response", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21694),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("SSC Project 1", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, 2094),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("SSC Project 2", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, 2094),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21701),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("SubNational no percentages", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, 2094),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21700),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("TAC_activity_1", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21697),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("TAC_activity_2", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21702),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Test MTEF directed", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, 2093),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21700),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("third activity with agreements", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, 2),
                    entry("orgs", "DN", 2, 21699),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Unvalidated activity", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21695),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("with annual ppc and actual comm", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("with weird currencies", "Default", 38,
                coos(
                    entry("cats", "Mode of Payment", 1, 2094),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21699),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))));
    }

}
