package org.dgfoundation.amp.nireports.testcases.generic;

import org.dgfoundation.amp.nireports.TextCell;
import org.dgfoundation.amp.nireports.schema.NiDimension.LevelColumn;

import java.util.Arrays;
import java.util.List;
import java.util.Map;


public class DonorTypeCells extends HardcodedCells<TextCell>{

    public DonorTypeCells(Map<String, Long> activityNames, Map<String, Long> entityNames, LevelColumn lc) {
        super(activityNames, entityNames, lc);
    }

    @Override
    protected List<TextCell> populateCells() {
        return  Arrays.asList(
                cell("activity 1 with agreement", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, 1),
                                entry("funding", "Funding Id", 0, 77),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Activity 2 with multiple agreements", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21699),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("Activity 2 with multiple agreements", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21696),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, 1),
                                entry("funding", "Funding Id", 0, 78),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Activity 2 with multiple agreements", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21695),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, 2),
                                entry("funding", "Funding Id", 0, 79),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("Activity Linked With Pledge", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 53),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Activity with both MTEFs and Act.Comms", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21699),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("Activity with both MTEFs and Act.Comms", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2094),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 84),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("activity with capital spending", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2124),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 62),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("activity with components", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("activity with contracting agency", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21699),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("activity with contracting agency", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 64),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("activity with directed MTEFs", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2094),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 88),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("activity with funded components", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21695),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 75),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("activity with funded components", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21697),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("activity with funded components", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21702),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("activity with funded components 2", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("activity with incomplete agreement", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, 3),
                                entry("funding", "Funding Id", 0, 81),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("activity with many MTEFs", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 96),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("activity with many MTEFs", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21694),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("activity with many MTEFs", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21696),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 95),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("activity with pipeline MTEFs and act. disb", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2094),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21695),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 93),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("activity with pipeline MTEFs and act. disb", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21694),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("Activity with planned disbursements", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21694),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 82),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Activity with planned disbursements", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21696),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 83),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("activity with primary_program", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21697),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 56),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Activity with primary_tertiary_program", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2093),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21695),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 55),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("activity with tertiary_program", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 57),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Activity with Zones", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 41),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Activity With Zones and Percentages", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21694),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 44),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("activity-weird-funding", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2095),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21699),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 102),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("activity-with-unfunded-components", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("activity-with-unfunded-components", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2124),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 73),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("activity_with_disaster_response", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21699),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("activity_with_disaster_response", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2094),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 85),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("arrears test", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 98),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("crazy funding 1", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2094),
                                entry("cats", "Type Of Assistance", 1, 2124),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 40),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("crazy funding 1", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2093),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 39),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("date-filters-activity", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21699),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 33),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("department/division", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 107),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Eth Water", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21694),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 29),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Eth Water", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21696),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 26),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Eth Water", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 27),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("execution rate activity", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21699),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 94),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("execution rate activity", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21695),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("expenditure class", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 100),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("expenditure class", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21694),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("mtef activity 1", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21695),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 32),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("mtef activity 2", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2094),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 34),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("new activity with contracting", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 65),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("PID: original", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("PID: original > actual", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("PID: original, actual", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("PID: original, proposed", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("PID: original, proposed, actual", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("pledged 2", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("pledged 2", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2124),
                                entry("orgs", "DN", 2, 21696),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 60),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("pledged education activity 1", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21696),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 58),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Project with documents", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21696),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("Proposed Project Cost 1 - USD", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("Proposed Project Cost 2 - EUR", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("ptc activity 1", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2097),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 35),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("ptc activity 2", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2095),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21696),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 36),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Pure MTEF Project", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21699),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 24),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Pure MTEF Project", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("Real SSC Activity 1", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21697),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 49),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Real SSC Activity 1", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 50),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Real SSC Activity 1", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21696),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 51),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Real SSC Activity 2", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21694),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 48),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("regional funding activity 1", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 112),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("regional funding activity 2", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21694),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 113),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("regional funding activity 3", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21697),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 114),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("second with disaster response", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21694),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 109),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("SSC Project 1", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2094),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 37),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("SSC Project 2", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2094),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21701),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 38),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("SubNational no percentages", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2094),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 52),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("TAC_activity_1", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21697),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 18),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("TAC_activity_2", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21702),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 19),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Test MTEF directed", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2093),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 22),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Test MTEF directed", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21696),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("third activity with agreements", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("third activity with agreements", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21699),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, 2),
                                entry("funding", "Funding Id", 0, 80),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Unvalidated activity", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21695),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 76),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("with annual ppc and actual comm", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 111),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("with weird currencies", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2094),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21699),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 97),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("with weird currencies", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21694),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("with weird currencies", "Default", 38,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))));
    }

}
