package org.dgfoundation.amp.nireports.testcases.generic;

import org.dgfoundation.amp.nireports.TextCell;
import org.dgfoundation.amp.nireports.schema.NiDimension.LevelColumn;

import java.util.Arrays;
import java.util.List;
import java.util.Map;


public class DonorGroupCells extends HardcodedCells<TextCell>{

    public DonorGroupCells(Map<String, Long> activityNames, Map<String, Long> entityNames, LevelColumn lc) {
        super(activityNames, entityNames, lc);
    }

    @Override
    protected List<TextCell> populateCells() {
        return  Arrays.asList(
                cell("activity 1 with agreement", "Default Group", 17,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, 1),
                                entry("funding", "Funding Id", 0, 77),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Activity 2 with multiple agreements", "American", 19,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21696),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, 1),
                                entry("funding", "Funding Id", 0, 78),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Activity 2 with multiple agreements", "International", 20,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21695),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, 2),
                                entry("funding", "Funding Id", 0, 79),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("Activity 2 with multiple agreements", "National", 21,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21699),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("Activity Linked With Pledge", "Default Group", 17,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 53),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Activity with both MTEFs and Act.Comms", "Default Group", 17,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2094),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 84),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("Activity with both MTEFs and Act.Comms", "National", 21,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21699),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("activity with capital spending", "Default Group", 17,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2124),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 62),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("activity with components", "Default Group", 17,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("activity with contracting agency", "Default Group", 17,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 64),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("activity with contracting agency", "National", 21,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21699),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("activity with directed MTEFs", "National", 21,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2094),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 88),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("activity with funded components", "American", 19,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21702),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("activity with funded components", "International", 20,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21695),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 75),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("activity with funded components", "International", 20,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21697),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("activity with funded components 2", "Default Group", 17,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("activity with incomplete agreement", "Default Group", 17,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, 3),
                                entry("funding", "Funding Id", 0, 81),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("activity with many MTEFs", "American", 19,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21696),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 95),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("activity with many MTEFs", "Default Group", 17,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 96),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("activity with many MTEFs", "European", 18,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21694),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("activity with pipeline MTEFs and act. disb", "European", 18,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21694),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("activity with pipeline MTEFs and act. disb", "International", 20,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2094),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21695),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 93),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("Activity with planned disbursements", "American", 19,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21696),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 83),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Activity with planned disbursements", "European", 18,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21694),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 82),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("activity with primary_program", "International", 20,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21697),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 56),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Activity with primary_tertiary_program", "International", 20,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2093),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21695),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 55),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("activity with tertiary_program", "National", 21,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 57),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Activity with Zones", "Default Group", 17,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 41),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Activity With Zones and Percentages", "European", 18,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21694),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 44),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("activity-weird-funding", "National", 21,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2095),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21699),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 102),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("activity-with-unfunded-components", "Default Group", 17,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2124),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 73),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("activity-with-unfunded-components", "National", 21,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("activity_with_disaster_response", "Default Group", 17,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2094),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 85),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("activity_with_disaster_response", "National", 21,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21699),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("arrears test", "Default Group", 17,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 98),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("crazy funding 1", "Default Group", 17,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2094),
                                entry("cats", "Type Of Assistance", 1, 2124),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 40),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("crazy funding 1", "Default Group", 17,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2093),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 39),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("date-filters-activity", "National", 21,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21699),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 33),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("department/division", "Default Group", 17,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 107),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Eth Water", "American", 19,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21696),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 26),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Eth Water", "Default Group", 17,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 27),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Eth Water", "European", 18,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21694),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 29),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("execution rate activity", "International", 20,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21695),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("execution rate activity", "National", 21,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21699),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 94),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("expenditure class", "European", 18,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21694),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("expenditure class", "National", 21,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 100),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("mtef activity 1", "International", 20,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21695),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 32),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("mtef activity 2", "Default Group", 17,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2094),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 34),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("new activity with contracting", "Default Group", 17,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 65),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("PID: original", "National", 21,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("PID: original > actual", "National", 21,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("PID: original, actual", "National", 21,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("PID: original, proposed", "National", 21,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("PID: original, proposed, actual", "National", 21,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("pledged 2", "American", 19,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2124),
                                entry("orgs", "DN", 2, 21696),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 60),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("pledged 2", "Default Group", 17,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("pledged education activity 1", "American", 19,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21696),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 58),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Project with documents", "American", 19,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21696),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("Proposed Project Cost 1 - USD", "Default Group", 17,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("Proposed Project Cost 2 - EUR", "National", 21,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("ptc activity 1", "Default Group", 17,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2097),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 35),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("ptc activity 2", "American", 19,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2095),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21696),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 36),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Pure MTEF Project", "National", 21,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21699),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 24),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Pure MTEF Project", "National", 21,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("Real SSC Activity 1", "American", 19,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21696),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 51),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Real SSC Activity 1", "Default Group", 17,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 50),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Real SSC Activity 1", "International", 20,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21697),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 49),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Real SSC Activity 2", "European", 18,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21694),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 48),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("regional funding activity 1", "Default Group", 17,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 112),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("regional funding activity 2", "European", 18,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21694),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 113),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("regional funding activity 3", "International", 20,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21697),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 114),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("second with disaster response", "European", 18,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21694),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 109),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("SSC Project 1", "Default Group", 17,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2094),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 37),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("SSC Project 2", "American", 19,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2094),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21701),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 38),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("SubNational no percentages", "National", 21,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2094),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 52),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("TAC_activity_1", "International", 20,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21697),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 18),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("TAC_activity_2", "American", 19,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21702),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 19),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Test MTEF directed", "American", 19,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21696),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("Test MTEF directed", "National", 21,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2093),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21700),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 22),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("third activity with agreements", "Default Group", 17,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("third activity with agreements", "National", 21,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21699),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, 2),
                                entry("funding", "Funding Id", 0, 80),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("Unvalidated activity", "International", 20,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21695),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 76),
                                entry("cats", "Financing Instrument", 1, 2125))),
                cell("with annual ppc and actual comm", "Default Group", 17,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 111),
                                entry("cats", "Financing Instrument", 1, 2120))),
                cell("with weird currencies", "Default Group", 17,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21698),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("with weird currencies", "European", 18,
                        coos(
                                entry("cats", "Mode of Payment", 1, -999999999),
                                entry("cats", "Type Of Assistance", 1, -999999999),
                                entry("orgs", "DN", 2, 21694),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, -999999999),
                                entry("cats", "Financing Instrument", 1, -999999999))),
                cell("with weird currencies", "National", 21,
                        coos(
                                entry("cats", "Mode of Payment", 1, 2094),
                                entry("cats", "Type Of Assistance", 1, 2119),
                                entry("orgs", "DN", 2, 21699),
                                entry("cats", "Funding Status", 1, -999999999),
                                entry("agrs", "agr", 0, -999999999),
                                entry("funding", "Funding Id", 0, 97),
                                entry("cats", "Financing Instrument", 1, 2125))));
    }

}
