package org.dgfoundation.amp.nireports.testcases.generic;

import org.dgfoundation.amp.nireports.TextCell;
import org.dgfoundation.amp.nireports.schema.NiDimension.LevelColumn;

import java.util.Arrays;
import java.util.List;
import java.util.Map;


public class FinancingInstrumentCells extends HardcodedCells<TextCell>{

    public FinancingInstrumentCells(Map<String, Long> activityNames, Map<String, Long> entityNames, LevelColumn lc) {
        super(activityNames, entityNames, lc);
    }

    @Override
    protected List<TextCell> populateCells() {
        return  Arrays.asList(
            cell("activity 1 with agreement", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, 1),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Activity 2 with multiple agreements", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, 1),
                    entry("orgs", "DN", 2, 21696),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Activity 2 with multiple agreements", "second financing instrument", 2125,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, 2),
                    entry("orgs", "DN", 2, 21695),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Activity Linked With Pledge", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Activity with both MTEFs and Act.Comms", "second financing instrument", 2125,
                coos(
                    entry("cats", "Mode of Payment", 1, 2094),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity with capital spending", "second financing instrument", 2125,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2124))),
            cell("activity with contracting agency", "second financing instrument", 2125,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity with directed MTEFs", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, 2096),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21696),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2124))),
            cell("activity with directed MTEFs", "second financing instrument", 2125,
                coos(
                    entry("cats", "Mode of Payment", 1, 2094),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity with directed MTEFs", "second financing instrument", 2125,
                coos(
                    entry("cats", "Mode of Payment", 1, 2094),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21700),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity with funded components", "second financing instrument", 2125,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21695),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity with incomplete agreement", "second financing instrument", 2125,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, 3),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity with many MTEFs", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21696),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity with many MTEFs", "second financing instrument", 2125,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity with pipeline MTEFs and act. disb", "second financing instrument", 2125,
                coos(
                    entry("cats", "Mode of Payment", 1, 2094),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21695),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Activity with planned disbursements", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21696),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Activity with planned disbursements", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21694),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity with primary_program", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21697),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Activity with primary_tertiary_program", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, 2093),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21695),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity with tertiary_program", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21700),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Activity with Zones", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Activity With Zones and Percentages", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21694),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity-weird-funding", "second financing instrument", 2125,
                coos(
                    entry("cats", "Mode of Payment", 1, 2095),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21699),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity-weird-funding", "second financing instrument", 2125,
                coos(
                    entry("cats", "Mode of Payment", 1, 2096),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21695),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity-weird-funding", "second financing instrument", 2125,
                coos(
                    entry("cats", "Mode of Payment", 1, 2094),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21701),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity-with-unfunded-components", "second financing instrument", 2125,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2124))),
            cell("activity_with_disaster_response", "second financing instrument", 2125,
                coos(
                    entry("cats", "Mode of Payment", 1, 2094),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("arrears test", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("crazy funding 1", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, 2093),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("crazy funding 1", "second financing instrument", 2125,
                coos(
                    entry("cats", "Mode of Payment", 1, 2094),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2124))),
            cell("date-filters-activity", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21699),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("department/division", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("department/division", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21694),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Eth Water", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21695),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Eth Water", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21700),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Eth Water", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Eth Water", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21697),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Eth Water", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21694),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Eth Water", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21696),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Eth Water", "second financing instrument", 2125,
                coos(
                    entry("cats", "Mode of Payment", 1, 2094),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21699),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2124))),
            cell("execution rate activity", "second financing instrument", 2125,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21699),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("expenditure class", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21700),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("mtef activity 1", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21695),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("mtef activity 2", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, 2094),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("new activity with contracting", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("pledged 2", "second financing instrument", 2125,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21696),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2124))),
            cell("pledged education activity 1", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21696),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("ptc activity 1", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, 2097),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("ptc activity 2", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, 2095),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21696),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Pure MTEF Project", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21699),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Pure MTEF Project", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21700),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Real SSC Activity 1", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21697),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Real SSC Activity 1", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21696),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Real SSC Activity 1", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Real SSC Activity 2", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21694),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("second with disaster response", "second financing instrument", 2125,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21694),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("SSC Project 1", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, 2094),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("SSC Project 2", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, 2094),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21701),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("SubNational no percentages", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, 2094),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21700),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("TAC_activity_1", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21697),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("TAC_activity_2", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21702),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Test MTEF directed", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21696),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Test MTEF directed", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, 2093),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21700),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("third activity with agreements", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, 2),
                    entry("orgs", "DN", 2, 21699),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Unvalidated activity", "second financing instrument", 2125,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21695),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("with annual ppc and actual comm", "default financing instrument", 2120,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("with weird currencies", "second financing instrument", 2125,
                coos(
                    entry("cats", "Mode of Payment", 1, 2094),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21699),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))));
    }

}
