package org.dgfoundation.amp.nireports.testcases.generic;

import org.dgfoundation.amp.nireports.TextCell;
import org.dgfoundation.amp.nireports.schema.NiDimension.LevelColumn;

import java.util.Arrays;
import java.util.List;
import java.util.Map;


public class TypeOfAssistanceCells extends HardcodedCells<TextCell>{

    public TypeOfAssistanceCells(Map<String, Long> activityNames, Map<String, Long> entityNames, LevelColumn lc) {
        super(activityNames, entityNames, lc);
    }

    @Override
    protected List<TextCell> populateCells() {
        return  Arrays.asList(
            cell("activity 1 with agreement", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, 1),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Activity 2 with multiple agreements", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, 2),
                    entry("orgs", "DN", 2, 21695),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Activity 2 with multiple agreements", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, 1),
                    entry("orgs", "DN", 2, 21696),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Activity Linked With Pledge", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Activity with both MTEFs and Act.Comms", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, 2094),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity with capital spending", "second type of assistance", 2124,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2124))),
            cell("activity with contracting agency", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity with directed MTEFs", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, 2094),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21700),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity with directed MTEFs", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, 2094),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity with directed MTEFs", "second type of assistance", 2124,
                coos(
                    entry("cats", "Mode of Payment", 1, 2096),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21696),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2124))),
            cell("activity with funded components", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21695),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity with incomplete agreement", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, 3),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity with many MTEFs", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21696),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity with many MTEFs", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity with pipeline MTEFs and act. disb", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, 2094),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21695),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Activity with planned disbursements", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21696),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Activity with planned disbursements", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21694),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity with primary_program", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21697),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Activity with primary_tertiary_program", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, 2093),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21695),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity with tertiary_program", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21700),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Activity with Zones", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Activity With Zones and Percentages", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21694),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity-weird-funding", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, 2096),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21695),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity-weird-funding", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, 2095),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21699),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity-weird-funding", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, 2094),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21701),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("activity-with-unfunded-components", "second type of assistance", 2124,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2124))),
            cell("activity_with_disaster_response", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, 2094),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("arrears test", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("crazy funding 1", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, 2093),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("crazy funding 1", "second type of assistance", 2124,
                coos(
                    entry("cats", "Mode of Payment", 1, 2094),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2124))),
            cell("date-filters-activity", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21699),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("department/division", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21694),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("department/division", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Eth Water", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21694),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Eth Water", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21696),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Eth Water", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Eth Water", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21695),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Eth Water", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21697),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Eth Water", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21700),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Eth Water", "second type of assistance", 2124,
                coos(
                    entry("cats", "Mode of Payment", 1, 2094),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21699),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2124))),
            cell("execution rate activity", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21699),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("expenditure class", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21700),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("mtef activity 1", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21695),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("mtef activity 2", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, 2094),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("new activity with contracting", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("pledged 2", "second type of assistance", 2124,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21696),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2124))),
            cell("pledged education activity 1", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21696),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("ptc activity 1", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, 2097),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("ptc activity 2", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, 2095),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21696),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Pure MTEF Project", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21700),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Pure MTEF Project", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21699),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Real SSC Activity 1", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21697),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Real SSC Activity 1", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21696),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Real SSC Activity 1", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Real SSC Activity 2", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21694),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("second with disaster response", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21694),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("SSC Project 1", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, 2094),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("SSC Project 2", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, 2094),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21701),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("SubNational no percentages", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, 2094),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21700),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("TAC_activity_1", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21697),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("TAC_activity_2", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21702),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Test MTEF directed", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, 2093),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21700),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Test MTEF directed", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21696),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("third activity with agreements", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, 2),
                    entry("orgs", "DN", 2, 21699),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("Unvalidated activity", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21695),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("with annual ppc and actual comm", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, -999999999),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21698),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2120),
                    entry("cats", "Type Of Assistance", 1, 2119))),
            cell("with weird currencies", "default type of assistance", 2119,
                coos(
                    entry("cats", "Mode of Payment", 1, 2094),
                    entry("agrs", "agr", 0, -999999999),
                    entry("orgs", "DN", 2, 21699),
                    entry("cats", "Funding Status", 1, -999999999),
                    entry("cats", "Financing Instrument", 1, 2125),
                    entry("cats", "Type Of Assistance", 1, 2119))));
    }

}
