//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.03 at 11:07:52 PM EEST 
//


package org.digijava.module.gateperm.feed.schema.impl;

public class CompositePermTypeImpl implements org.digijava.module.gateperm.feed.schema.CompositePermType, com.sun.xml.bind.JAXBObject, org.digijava.module.gateperm.feed.schema.impl.runtime.UnmarshallableObject, org.digijava.module.gateperm.feed.schema.impl.runtime.XMLSerializable, org.digijava.module.gateperm.feed.schema.impl.runtime.ValidatableObject
{

    protected java.lang.String _Description;
    protected com.sun.xml.bind.util.ListImpl _CompositePerm;
    protected com.sun.xml.bind.util.ListImpl _GatePerm;
    protected com.sun.xml.bind.util.ListImpl _AssignedObjId;
    protected java.lang.String _Name;
    protected boolean has_Dedicated;
    protected boolean _Dedicated;
    protected boolean has_Intersection;
    protected boolean _Intersection;
    public final static java.lang.Class version = (org.digijava.module.gateperm.feed.schema.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (org.digijava.module.gateperm.feed.schema.CompositePermType.class);
    }

    public java.lang.String getDescription() {
        return _Description;
    }

    public void setDescription(java.lang.String value) {
        _Description = value;
    }

    protected com.sun.xml.bind.util.ListImpl _getCompositePerm() {
        if (_CompositePerm == null) {
            _CompositePerm = new com.sun.xml.bind.util.ListImpl(new java.util.ArrayList());
        }
        return _CompositePerm;
    }

    public java.util.List getCompositePerm() {
        return _getCompositePerm();
    }

    protected com.sun.xml.bind.util.ListImpl _getGatePerm() {
        if (_GatePerm == null) {
            _GatePerm = new com.sun.xml.bind.util.ListImpl(new java.util.ArrayList());
        }
        return _GatePerm;
    }

    public java.util.List getGatePerm() {
        return _getGatePerm();
    }

    protected com.sun.xml.bind.util.ListImpl _getAssignedObjId() {
        if (_AssignedObjId == null) {
            _AssignedObjId = new com.sun.xml.bind.util.ListImpl(new java.util.ArrayList());
        }
        return _AssignedObjId;
    }

    public java.util.List getAssignedObjId() {
        return _getAssignedObjId();
    }

    public java.lang.String getName() {
        return _Name;
    }

    public void setName(java.lang.String value) {
        _Name = value;
    }

    public boolean isDedicated() {
        return _Dedicated;
    }

    public void setDedicated(boolean value) {
        _Dedicated = value;
        has_Dedicated = true;
    }

    public boolean isIntersection() {
        return _Intersection;
    }

    public void setIntersection(boolean value) {
        _Intersection = value;
        has_Intersection = true;
    }

    public org.digijava.module.gateperm.feed.schema.impl.runtime.UnmarshallingEventHandler createUnmarshaller(org.digijava.module.gateperm.feed.schema.impl.runtime.UnmarshallingContext context) {
        return new org.digijava.module.gateperm.feed.schema.impl.CompositePermTypeImpl.Unmarshaller(context);
    }

    public void serializeBody(org.digijava.module.gateperm.feed.schema.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx2 = 0;
        final int len2 = ((_CompositePerm == null)? 0 :_CompositePerm.size());
        int idx3 = 0;
        final int len3 = ((_GatePerm == null)? 0 :_GatePerm.size());
        int idx4 = 0;
        final int len4 = ((_AssignedObjId == null)? 0 :_AssignedObjId.size());
        while (idx4 != len4) {
            context.startElement("http://digijava.org/module/gateperm/feed/schema.xml", "assignedObjId");
            int idx_0 = idx4;
            if (_AssignedObjId.get(idx_0) == null) {
                context.getNamespaceContext().declareNamespace("http://www.w3.org/2001/XMLSchema-instance", null, true);
                try {
                    idx_0 += 1;
                } catch (java.lang.Exception e) {
                    org.digijava.module.gateperm.feed.schema.impl.runtime.Util.handlePrintConversionException(this, e, context);
                }
            } else {
                if (_AssignedObjId.get(idx_0) instanceof org.digijava.module.gateperm.feed.schema.AssignedObjIdType) {
                    context.childAsURIs(((com.sun.xml.bind.JAXBObject) _AssignedObjId.get(idx_0 ++)), "AssignedObjId");
                } else {
                    org.digijava.module.gateperm.feed.schema.impl.runtime.Util.handleTypeMismatchError(context, this, "AssignedObjId", _AssignedObjId.get(idx_0));
                }
            }
            context.endNamespaceDecls();
            int idx_1 = idx4;
            if (_AssignedObjId.get(idx_1) == null) {
                context.startAttribute("http://www.w3.org/2001/XMLSchema-instance", "nil");
                try {
                    context.text("true", "AssignedObjId");
                } catch (java.lang.Exception e) {
                    org.digijava.module.gateperm.feed.schema.impl.runtime.Util.handlePrintConversionException(this, e, context);
                }
                context.endAttribute();
            } else {
                if (_AssignedObjId.get(idx_1) instanceof org.digijava.module.gateperm.feed.schema.AssignedObjIdType) {
                    context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _AssignedObjId.get(idx_1 ++)), "AssignedObjId");
                } else {
                    org.digijava.module.gateperm.feed.schema.impl.runtime.Util.handleTypeMismatchError(context, this, "AssignedObjId", _AssignedObjId.get(idx_1));
                }
            }
            context.endAttributes();
            if (!(_AssignedObjId.get(idx4) == null)) {
                if (_AssignedObjId.get(idx4) instanceof org.digijava.module.gateperm.feed.schema.AssignedObjIdType) {
                    context.childAsBody(((com.sun.xml.bind.JAXBObject) _AssignedObjId.get(idx4 ++)), "AssignedObjId");
                } else {
                    org.digijava.module.gateperm.feed.schema.impl.runtime.Util.handleTypeMismatchError(context, this, "AssignedObjId", _AssignedObjId.get(idx4));
                }
            }
            context.endElement();
        }
        while (idx3 != len3) {
            context.startElement("http://digijava.org/module/gateperm/feed/schema.xml", "gatePerm");
            int idx_2 = idx3;
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _GatePerm.get(idx_2 ++)), "GatePerm");
            context.endNamespaceDecls();
            int idx_3 = idx3;
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _GatePerm.get(idx_3 ++)), "GatePerm");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _GatePerm.get(idx3 ++)), "GatePerm");
            context.endElement();
        }
        while (idx2 != len2) {
            context.startElement("http://digijava.org/module/gateperm/feed/schema.xml", "compositePerm");
            int idx_4 = idx2;
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _CompositePerm.get(idx_4 ++)), "CompositePerm");
            context.endNamespaceDecls();
            int idx_5 = idx2;
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _CompositePerm.get(idx_5 ++)), "CompositePerm");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _CompositePerm.get(idx2 ++)), "CompositePerm");
            context.endElement();
        }
        if (_Description!= null) {
            context.startElement("http://digijava.org/module/gateperm/feed/schema.xml", "description");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _Description), "Description");
            } catch (java.lang.Exception e) {
                org.digijava.module.gateperm.feed.schema.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
    }

    public void serializeAttributes(org.digijava.module.gateperm.feed.schema.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx2 = 0;
        final int len2 = ((_CompositePerm == null)? 0 :_CompositePerm.size());
        int idx3 = 0;
        final int len3 = ((_GatePerm == null)? 0 :_GatePerm.size());
        int idx4 = 0;
        final int len4 = ((_AssignedObjId == null)? 0 :_AssignedObjId.size());
        if (has_Dedicated) {
            context.startAttribute("", "dedicated");
            try {
                context.text(javax.xml.bind.DatatypeConverter.printBoolean(((boolean) _Dedicated)), "Dedicated");
            } catch (java.lang.Exception e) {
                org.digijava.module.gateperm.feed.schema.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endAttribute();
        }
        if (has_Intersection) {
            context.startAttribute("", "intersection");
            try {
                context.text(javax.xml.bind.DatatypeConverter.printBoolean(((boolean) _Intersection)), "Intersection");
            } catch (java.lang.Exception e) {
                org.digijava.module.gateperm.feed.schema.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endAttribute();
        }
        context.startAttribute("", "name");
        try {
            context.text(((java.lang.String) _Name), "Name");
        } catch (java.lang.Exception e) {
            org.digijava.module.gateperm.feed.schema.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endAttribute();
        while (idx4 != len4) {
            if (_AssignedObjId.get(idx4) == null) {
                try {
                    idx4 += 1;
                } catch (java.lang.Exception e) {
                    org.digijava.module.gateperm.feed.schema.impl.runtime.Util.handlePrintConversionException(this, e, context);
                }
            } else {
                if (_AssignedObjId.get(idx4) instanceof org.digijava.module.gateperm.feed.schema.AssignedObjIdType) {
                    idx4 += 1;
                } else {
                    org.digijava.module.gateperm.feed.schema.impl.runtime.Util.handleTypeMismatchError(context, this, "AssignedObjId", _AssignedObjId.get(idx4));
                }
            }
        }
        while (idx3 != len3) {
            idx3 += 1;
        }
        while (idx2 != len2) {
            idx2 += 1;
        }
    }

    public void serializeURIs(org.digijava.module.gateperm.feed.schema.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx2 = 0;
        final int len2 = ((_CompositePerm == null)? 0 :_CompositePerm.size());
        int idx3 = 0;
        final int len3 = ((_GatePerm == null)? 0 :_GatePerm.size());
        int idx4 = 0;
        final int len4 = ((_AssignedObjId == null)? 0 :_AssignedObjId.size());
        while (idx4 != len4) {
            if (_AssignedObjId.get(idx4) == null) {
                try {
                    idx4 += 1;
                } catch (java.lang.Exception e) {
                    org.digijava.module.gateperm.feed.schema.impl.runtime.Util.handlePrintConversionException(this, e, context);
                }
            } else {
                if (_AssignedObjId.get(idx4) instanceof org.digijava.module.gateperm.feed.schema.AssignedObjIdType) {
                    idx4 += 1;
                } else {
                    org.digijava.module.gateperm.feed.schema.impl.runtime.Util.handleTypeMismatchError(context, this, "AssignedObjId", _AssignedObjId.get(idx4));
                }
            }
        }
        while (idx3 != len3) {
            idx3 += 1;
        }
        while (idx2 != len2) {
            idx2 += 1;
        }
    }

    public java.lang.Class getPrimaryInterface() {
        return (org.digijava.module.gateperm.feed.schema.CompositePermType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000b"
+"expandedExpq\u0000~\u0000\u0002xpppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000pp"
+"sr\u0000\u001dcom.sun.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001ppsr\u0000 com."
+"sun.msv.grammar.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.sun.msv.gramm"
+"ar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0002xq\u0000~\u0000\u0003sr\u0000\u0011java.lang.Boolean"
+"\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psr\u0000\'com.sun.msv.grammar.trex.ElementP"
+"attern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001fLcom/sun/msv/grammar/NameCla"
+"ss;xr\u0000\u001ecom.sun.msv.grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUnd"
+"eclaredAttributesL\u0000\fcontentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003q\u0000~\u0000\u0011p\u0000sq\u0000~\u0000\u000bppsr"
+"\u0000 com.sun.msv.grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tn"
+"ameClassq\u0000~\u0000\u0013xq\u0000~\u0000\u0003ppsr\u0000\u001ccom.sun.msv.grammar.ValueExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype/Datatype;L\u0000\u0004namet\u0000\u001dLcom/su"
+"n/msv/util/StringPair;L\u0000\u0005valuet\u0000\u0012Ljava/lang/Object;xq\u0000~\u0000\u0003pps"
+"r\u0000$com.sun.msv.datatype.xsd.BooleanType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000*com.su"
+"n.msv.datatype.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.m"
+"sv.datatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datat"
+"ype.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUrit\u0000\u0012Ljava/lan"
+"g/String;L\u0000\btypeNameq\u0000~\u0000\"L\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/dataty"
+"pe/xsd/WhiteSpaceProcessor;xpt\u0000 http://www.w3.org/2001/XMLSc"
+"hemat\u0000\u0007booleansr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcess"
+"or$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd.WhiteSpac"
+"eProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u0000\u001bcom.sun.msv.util.StringPair\u00d0t\u001ejB\u008f"
+"\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\"L\u0000\fnamespaceURIq\u0000~\u0000\"xpq\u0000~\u0000&t\u0000\u0000sq\u0000~\u0000\u0010\u0001s"
+"r\u0000#com.sun.msv.grammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNam"
+"eq\u0000~\u0000\"L\u0000\fnamespaceURIq\u0000~\u0000\"xr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u0003nilt\u0000)http://www.w3.org/2001/XMLSchema-instan"
+"cesq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0012pp\u0000sq\u0000~\u0000\u000bppsq\u0000~\u0000\rq\u0000~\u0000\u0011psq\u0000~\u0000\u0017q\u0000~\u0000\u0011psr\u00002com.s"
+"un.msv.grammar.Expression$AnyStringExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~"
+"\u0000\u0003q\u0000~\u0000-psr\u0000 com.sun.msv.grammar.AnyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000"
+"/sr\u00000com.sun.msv.grammar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003q\u0000~\u0000-psq\u0000~\u0000.t\u0000:org.digijava.module.gateperm.feed.s"
+"chema.AssignedObjIdTypet\u0000+http://java.sun.com/jaxb/xjc/dummy"
+"-elementssq\u0000~\u0000\u000bppsq\u0000~\u0000\u0017q\u0000~\u0000\u0011psr\u0000\u001bcom.sun.msv.grammar.DataExp"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtq\u0000~\u0000\u001aL\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004nameq\u0000~\u0000\u001bxq\u0000~\u0000\u0003ppsr\u0000\"c"
+"om.sun.msv.datatype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u001fq\u0000~\u0000%t\u0000\u0005QN"
+"ameq\u0000~\u0000)sr\u00000com.sun.msv.grammar.Expression$NullSetExpression"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003ppsq\u0000~\u0000*q\u0000~\u0000Gq\u0000~\u0000%sq\u0000~\u0000.t\u0000\u0004typeq\u0000~\u00002q\u0000~\u0000=sq"
+"\u0000~\u0000.t\u0000\rassignedObjIdt\u00003http://digijava.org/module/gateperm/f"
+"eed/schema.xmlq\u0000~\u0000=sq\u0000~\u0000\u000bppsq\u0000~\u0000\rq\u0000~\u0000\u0011psq\u0000~\u0000\u0012q\u0000~\u0000\u0011p\u0000sq\u0000~\u0000\u0000pp"
+"sq\u0000~\u0000\u0012pp\u0000sq\u0000~\u0000\u000bppsq\u0000~\u0000\rq\u0000~\u0000\u0011psq\u0000~\u0000\u0017q\u0000~\u0000\u0011pq\u0000~\u00009q\u0000~\u0000;q\u0000~\u0000=sq\u0000~"
+"\u0000.t\u00005org.digijava.module.gateperm.feed.schema.GatePermTypeq\u0000"
+"~\u0000@sq\u0000~\u0000\u000bppsq\u0000~\u0000\u0017q\u0000~\u0000\u0011pq\u0000~\u0000Dq\u0000~\u0000Kq\u0000~\u0000=sq\u0000~\u0000.t\u0000\bgatePermq\u0000~\u0000O"
+"q\u0000~\u0000=sq\u0000~\u0000\u000bppsq\u0000~\u0000\rq\u0000~\u0000\u0011psq\u0000~\u0000\u0012q\u0000~\u0000\u0011p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0012pp\u0000sq\u0000~\u0000"
+"\u000bppsq\u0000~\u0000\rq\u0000~\u0000\u0011psq\u0000~\u0000\u0017q\u0000~\u0000\u0011pq\u0000~\u00009q\u0000~\u0000;q\u0000~\u0000=sq\u0000~\u0000.t\u0000:org.digij"
+"ava.module.gateperm.feed.schema.CompositePermTypeq\u0000~\u0000@sq\u0000~\u0000\u000b"
+"ppsq\u0000~\u0000\u0017q\u0000~\u0000\u0011pq\u0000~\u0000Dq\u0000~\u0000Kq\u0000~\u0000=sq\u0000~\u0000.t\u0000\rcompositePermq\u0000~\u0000Oq\u0000~\u0000"
+"=sq\u0000~\u0000\u000bppsq\u0000~\u0000\u0012q\u0000~\u0000\u0011p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000Cppsr\u0000#com.sun.msv.dataty"
+"pe.xsd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxq\u0000~\u0000\u001fq\u0000~\u0000%t\u0000\u0006st"
+"ringsr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Preserv"
+"e\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000(\u0001q\u0000~\u0000Isq\u0000~\u0000*q\u0000~\u0000rq\u0000~\u0000%sq\u0000~\u0000\u000bppsq\u0000~\u0000\u0017q\u0000~\u0000\u0011p"
+"q\u0000~\u0000Dq\u0000~\u0000Kq\u0000~\u0000=sq\u0000~\u0000.t\u0000\u000bdescriptionq\u0000~\u0000Oq\u0000~\u0000=sq\u0000~\u0000\u000bppsq\u0000~\u0000\u0017q"
+"\u0000~\u0000\u0011psq\u0000~\u0000Cppq\u0000~\u0000$q\u0000~\u0000Isq\u0000~\u0000*q\u0000~\u0000&q\u0000~\u0000%sq\u0000~\u0000.t\u0000\tdedicatedq\u0000~"
+"\u0000,q\u0000~\u0000=sq\u0000~\u0000\u000bppsq\u0000~\u0000\u0017q\u0000~\u0000\u0011pq\u0000~\u0000|sq\u0000~\u0000.t\u0000\fintersectionq\u0000~\u0000,q\u0000"
+"~\u0000=sq\u0000~\u0000\u0017ppq\u0000~\u0000osq\u0000~\u0000.t\u0000\u0004nameq\u0000~\u0000,sr\u0000\"com.sun.msv.grammar.Ex"
+"pressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/grammar/Ex"
+"pressionPool$ClosedHash;xpsr\u0000-com.sun.msv.grammar.Expression"
+"Pool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rstreamVersionL\u0000\u0006parentt"
+"\u0000$Lcom/sun/msv/grammar/ExpressionPool;xp\u0000\u0000\u0000\u001e\u0001pq\u0000~\u0000\u0016q\u0000~\u0000lq\u0000~\u0000"
+"nq\u0000~\u00003q\u0000~\u0000Sq\u0000~\u0000Qq\u0000~\u0000aq\u0000~\u0000_q\u0000~\u0000\nq\u0000~\u0000zq\u0000~\u00006q\u0000~\u0000Vq\u0000~\u0000dq\u0000~\u0000\fq\u0000~\u0000"
+"5q\u0000~\u0000Uq\u0000~\u0000cq\u0000~\u0000\tq\u0000~\u0000\bq\u0000~\u0000\u0080q\u0000~\u0000\u0006q\u0000~\u0000\u000fq\u0000~\u0000Aq\u0000~\u0000Zq\u0000~\u0000hq\u0000~\u0000vq\u0000~\u0000"
+"\u0007q\u0000~\u0000\u0005q\u0000~\u0000Pq\u0000~\u0000^x"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends org.digijava.module.gateperm.feed.schema.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(org.digijava.module.gateperm.feed.schema.impl.runtime.UnmarshallingContext context) {
            super(context, "------------------------");
        }

        protected Unmarshaller(org.digijava.module.gateperm.feed.schema.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return org.digijava.module.gateperm.feed.schema.impl.CompositePermTypeImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  18 :
                        attIdx = context.getAttribute("", "dedicated");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        attIdx = context.getAttribute("", "intersection");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        attIdx = context.getAttribute("", "name");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        break;
                    case  3 :
                        attIdx = context.getAttribute("", "intersection");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 6;
                            eatText1(v);
                            continue outer;
                        }
                        state = 6;
                        continue outer;
                    case  10 :
                        attIdx = context.getAttribute("http://www.w3.org/2001/XMLSchema-instance", "nil");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 13;
                            eatText2(v);
                            continue outer;
                        }
                        attIdx = context.getAttribute("", "permissibleClass");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        break;
                    case  14 :
                        if (("assignedObjId" == ___local)&&("http://digijava.org/module/gateperm/feed/schema.xml" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 10;
                            return ;
                        }
                        if (("gatePerm" == ___local)&&("http://digijava.org/module/gateperm/feed/schema.xml" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 15;
                            return ;
                        }
                        state = 17;
                        continue outer;
                    case  0 :
                        attIdx = context.getAttribute("", "dedicated");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 3;
                            eatText3(v);
                            continue outer;
                        }
                        state = 3;
                        continue outer;
                    case  23 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  15 :
                        attIdx = context.getAttribute("", "dedicated");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        attIdx = context.getAttribute("", "gateClass");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        break;
                    case  9 :
                        if (("assignedObjId" == ___local)&&("http://digijava.org/module/gateperm/feed/schema.xml" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 10;
                            return ;
                        }
                        state = 14;
                        continue outer;
                    case  20 :
                        if (("compositePerm" == ___local)&&("http://digijava.org/module/gateperm/feed/schema.xml" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 18;
                            return ;
                        }
                        if (("description" == ___local)&&("http://digijava.org/module/gateperm/feed/schema.xml" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 21;
                            return ;
                        }
                        state = 23;
                        continue outer;
                    case  17 :
                        if (("gatePerm" == ___local)&&("http://digijava.org/module/gateperm/feed/schema.xml" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 15;
                            return ;
                        }
                        if (("compositePerm" == ___local)&&("http://digijava.org/module/gateperm/feed/schema.xml" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 18;
                            return ;
                        }
                        state = 20;
                        continue outer;
                    case  6 :
                        attIdx = context.getAttribute("", "name");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 9;
                            eatText4(v);
                            continue outer;
                        }
                        break;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        private void eatText1(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Intersection = javax.xml.bind.DatatypeConverter.parseBoolean(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
                has_Intersection = true;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText2(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _getAssignedObjId().add(null);
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText3(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Dedicated = javax.xml.bind.DatatypeConverter.parseBoolean(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
                has_Dedicated = true;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText4(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Name = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  18 :
                        attIdx = context.getAttribute("", "dedicated");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "intersection");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "name");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                    case  3 :
                        attIdx = context.getAttribute("", "intersection");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 6;
                            eatText1(v);
                            continue outer;
                        }
                        state = 6;
                        continue outer;
                    case  10 :
                        attIdx = context.getAttribute("http://www.w3.org/2001/XMLSchema-instance", "nil");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 13;
                            eatText2(v);
                            continue outer;
                        }
                        attIdx = context.getAttribute("", "permissibleClass");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                    case  14 :
                        state = 17;
                        continue outer;
                    case  19 :
                        if (("compositePerm" == ___local)&&("http://digijava.org/module/gateperm/feed/schema.xml" == ___uri)) {
                            context.popAttributes();
                            state = 20;
                            return ;
                        }
                        break;
                    case  0 :
                        attIdx = context.getAttribute("", "dedicated");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 3;
                            eatText3(v);
                            continue outer;
                        }
                        state = 3;
                        continue outer;
                    case  23 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  15 :
                        attIdx = context.getAttribute("", "dedicated");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "gateClass");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                    case  13 :
                        if (("assignedObjId" == ___local)&&("http://digijava.org/module/gateperm/feed/schema.xml" == ___uri)) {
                            context.popAttributes();
                            state = 14;
                            return ;
                        }
                        break;
                    case  9 :
                        state = 14;
                        continue outer;
                    case  22 :
                        if (("description" == ___local)&&("http://digijava.org/module/gateperm/feed/schema.xml" == ___uri)) {
                            context.popAttributes();
                            state = 23;
                            return ;
                        }
                        break;
                    case  20 :
                        state = 23;
                        continue outer;
                    case  17 :
                        state = 20;
                        continue outer;
                    case  6 :
                        attIdx = context.getAttribute("", "name");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 9;
                            eatText4(v);
                            continue outer;
                        }
                        break;
                    case  16 :
                        if (("gatePerm" == ___local)&&("http://digijava.org/module/gateperm/feed/schema.xml" == ___uri)) {
                            context.popAttributes();
                            state = 17;
                            return ;
                        }
                        break;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  18 :
                        if (("dedicated" == ___local)&&("" == ___uri)) {
                            _getCompositePerm().add(((org.digijava.module.gateperm.feed.schema.impl.CompositePermTypeImpl) spawnChildFromEnterAttribute((org.digijava.module.gateperm.feed.schema.impl.CompositePermTypeImpl.class), 19, ___uri, ___local, ___qname)));
                            return ;
                        }
                        if (("intersection" == ___local)&&("" == ___uri)) {
                            _getCompositePerm().add(((org.digijava.module.gateperm.feed.schema.impl.CompositePermTypeImpl) spawnChildFromEnterAttribute((org.digijava.module.gateperm.feed.schema.impl.CompositePermTypeImpl.class), 19, ___uri, ___local, ___qname)));
                            return ;
                        }
                        if (("name" == ___local)&&("" == ___uri)) {
                            _getCompositePerm().add(((org.digijava.module.gateperm.feed.schema.impl.CompositePermTypeImpl) spawnChildFromEnterAttribute((org.digijava.module.gateperm.feed.schema.impl.CompositePermTypeImpl.class), 19, ___uri, ___local, ___qname)));
                            return ;
                        }
                        break;
                    case  3 :
                        if (("intersection" == ___local)&&("" == ___uri)) {
                            state = 4;
                            return ;
                        }
                        state = 6;
                        continue outer;
                    case  10 :
                        if (("nil" == ___local)&&("http://www.w3.org/2001/XMLSchema-instance" == ___uri)) {
                            state = 11;
                            return ;
                        }
                        if (("permissibleClass" == ___local)&&("" == ___uri)) {
                            _getAssignedObjId().add(((org.digijava.module.gateperm.feed.schema.impl.AssignedObjIdTypeImpl) spawnChildFromEnterAttribute((org.digijava.module.gateperm.feed.schema.impl.AssignedObjIdTypeImpl.class), 13, ___uri, ___local, ___qname)));
                            return ;
                        }
                        break;
                    case  14 :
                        state = 17;
                        continue outer;
                    case  0 :
                        if (("dedicated" == ___local)&&("" == ___uri)) {
                            state = 1;
                            return ;
                        }
                        state = 3;
                        continue outer;
                    case  23 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  15 :
                        if (("dedicated" == ___local)&&("" == ___uri)) {
                            _getGatePerm().add(((org.digijava.module.gateperm.feed.schema.impl.GatePermTypeImpl) spawnChildFromEnterAttribute((org.digijava.module.gateperm.feed.schema.impl.GatePermTypeImpl.class), 16, ___uri, ___local, ___qname)));
                            return ;
                        }
                        if (("gateClass" == ___local)&&("" == ___uri)) {
                            _getGatePerm().add(((org.digijava.module.gateperm.feed.schema.impl.GatePermTypeImpl) spawnChildFromEnterAttribute((org.digijava.module.gateperm.feed.schema.impl.GatePermTypeImpl.class), 16, ___uri, ___local, ___qname)));
                            return ;
                        }
                        break;
                    case  9 :
                        state = 14;
                        continue outer;
                    case  20 :
                        state = 23;
                        continue outer;
                    case  17 :
                        state = 20;
                        continue outer;
                    case  6 :
                        if (("name" == ___local)&&("" == ___uri)) {
                            state = 7;
                            return ;
                        }
                        break;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  18 :
                        attIdx = context.getAttribute("", "dedicated");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "intersection");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "name");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                    case  5 :
                        if (("intersection" == ___local)&&("" == ___uri)) {
                            state = 6;
                            return ;
                        }
                        break;
                    case  3 :
                        attIdx = context.getAttribute("", "intersection");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 6;
                            eatText1(v);
                            continue outer;
                        }
                        state = 6;
                        continue outer;
                    case  12 :
                        if (("nil" == ___local)&&("http://www.w3.org/2001/XMLSchema-instance" == ___uri)) {
                            state = 13;
                            return ;
                        }
                        break;
                    case  2 :
                        if (("dedicated" == ___local)&&("" == ___uri)) {
                            state = 3;
                            return ;
                        }
                        break;
                    case  10 :
                        attIdx = context.getAttribute("http://www.w3.org/2001/XMLSchema-instance", "nil");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 13;
                            eatText2(v);
                            continue outer;
                        }
                        attIdx = context.getAttribute("", "permissibleClass");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                    case  14 :
                        state = 17;
                        continue outer;
                    case  8 :
                        if (("name" == ___local)&&("" == ___uri)) {
                            state = 9;
                            return ;
                        }
                        break;
                    case  0 :
                        attIdx = context.getAttribute("", "dedicated");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 3;
                            eatText3(v);
                            continue outer;
                        }
                        state = 3;
                        continue outer;
                    case  23 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  15 :
                        attIdx = context.getAttribute("", "dedicated");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "gateClass");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                    case  9 :
                        state = 14;
                        continue outer;
                    case  20 :
                        state = 23;
                        continue outer;
                    case  17 :
                        state = 20;
                        continue outer;
                    case  6 :
                        attIdx = context.getAttribute("", "name");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 9;
                            eatText4(v);
                            continue outer;
                        }
                        break;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  18 :
                            attIdx = context.getAttribute("", "dedicated");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            attIdx = context.getAttribute("", "intersection");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            attIdx = context.getAttribute("", "name");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            break;
                        case  4 :
                            state = 5;
                            eatText1(value);
                            return ;
                        case  3 :
                            attIdx = context.getAttribute("", "intersection");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                state = 6;
                                eatText1(v);
                                continue outer;
                            }
                            state = 6;
                            continue outer;
                        case  10 :
                            attIdx = context.getAttribute("http://www.w3.org/2001/XMLSchema-instance", "nil");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                state = 13;
                                eatText2(v);
                                continue outer;
                            }
                            attIdx = context.getAttribute("", "permissibleClass");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            break;
                        case  14 :
                            state = 17;
                            continue outer;
                        case  7 :
                            state = 8;
                            eatText4(value);
                            return ;
                        case  0 :
                            attIdx = context.getAttribute("", "dedicated");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                state = 3;
                                eatText3(v);
                                continue outer;
                            }
                            state = 3;
                            continue outer;
                        case  1 :
                            state = 2;
                            eatText3(value);
                            return ;
                        case  23 :
                            revertToParentFromText(value);
                            return ;
                        case  15 :
                            attIdx = context.getAttribute("", "dedicated");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            attIdx = context.getAttribute("", "gateClass");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            break;
                        case  9 :
                            state = 14;
                            continue outer;
                        case  21 :
                            state = 22;
                            eatText5(value);
                            return ;
                        case  20 :
                            state = 23;
                            continue outer;
                        case  11 :
                            state = 12;
                            eatText2(value);
                            return ;
                        case  17 :
                            state = 20;
                            continue outer;
                        case  6 :
                            attIdx = context.getAttribute("", "name");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                state = 9;
                                eatText4(v);
                                continue outer;
                            }
                            break;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

        private void eatText5(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Description = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

    }

}
