//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.04.22 at 06:29:37 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://dgfoundation.org/2009/ReportMetadata", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.digijava.module.aim.ar.impexp.data;
