//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.03.12 at 05:17:55 PM EET 
//


package org.dgfoundation.amp.te.ampte;


/**
 * Java content class for anonymous complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/dan/programs/jdsp-1.6/TEMP/jaxb/bin/ampte.xsd line 18)
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="trn" type="{http://dgfoundation.org/amp/te/ampte.xsd}trn" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="src" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface TranslationsType {


    /**
     * Gets the value of the src property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getSrc();

    /**
     * Sets the value of the src property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setSrc(java.lang.String value);

    /**
     * Gets the value of the Trn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the Trn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.dgfoundation.amp.te.ampte.Trn}
     * 
     */
    java.util.List getTrn();

}
