---
- name: Configure LAMP
  hosts: "{{ hosts|default('localhost') }}"
  become: true
  become_user: root

  vars_files:
    - ["DeployerSettings.{{ project_environment|default('local') }}.yml", "DeployerSettings.yml"]

  tasks:
    - hostname: name={{ hostname }}
      when: hostname is defined

  roles:
    - common
    - httpd_php56
    - postgresql
    - memcached
    - amp
