---

- name: Create "/opt/apache/" directory
  file:
    path: "/opt/apache/"
    state: directory

- name: Download Tomcat
  get_url:
    url: "{{_tomcat__download_url}}"
    checksum: "{{tomcat__download_checksum}}"
    dest: "/opt/apache/"
  register: archive_info

- name: Extract downloaded archive
  unarchive:
    src: "{{archive_info.dest}}"
    dest: "/opt/apache/"
    copy: no
    list_files: yes
    owner: "{{common__deployer_user}}"
    group: "{{common__deployer_group}}"
    #exclude:
    # - "./webapps/ROOT"
  register: archive_files_info

- name: Set directory owner and group
  file:
    path: "/opt/apache/{{_tomcat__package}}"
    owner: "{{common__deployer_user}}"
    group: "{{common__deployer_group}}"
    mode: "u=rwx,g=rwx,o=rx"

#- name: Delete downloaded archive
#  file:
#    path: "{{archive_info.dest}}"
#    state: absent

- name: Create simbolic link for release directory
  file:
    dest: "/opt/apache/apache-tomcat"
    src: "{{_tomcat__package}}"
    state: link
    force: yes
    owner: "{{common__deployer_user}}"
    group: "{{common__deployer_group}}"
    mode: "u=rw,g=rw,o=r"
    directory_mode: "u=rwx,g=rwx,o=rx"

- name: Delete default webapp
  file:
    path: "/opt/apache/apache-tomcat/webapps/ROOT"
    src: "{{_tomcat__package}}"
    state: absent
    force: yes

- name: Configure Tomcat
  template:
    src: setenv.sh.j2
    dest: /opt/apache/apache-tomcat/bin/setenv.sh
    owner: "{{common__deployer_user}}"
    group: "{{common__deployer_group}}"
    mode: "u=rwx,g=rwx,o=rx"

# TODO: Switch to SystemD
# @see: https://www.archlinux.org/packages/extra/any/tomcat7/
- name: Configure Tomcat service
  template:
    src: tomcat7.j2
    dest: /etc/init.d/tomcat7
    mode: "u=rwx,g=rx,o=rx"
