//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-20070223-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.02 at 01:58:56 PM GMT+04:00 
//


package org.digijava.module.help.jaxb.impl;

public class HelpTypeImpl implements org.digijava.module.help.jaxb.HelpType, com.sun.xml.bind.JAXBObject, org.digijava.module.help.jaxb.impl.runtime.UnmarshallableObject, org.digijava.module.help.jaxb.impl.runtime.XMLSerializable, org.digijava.module.help.jaxb.impl.runtime.ValidatableObject
{

    protected java.lang.String _KeywordsTrnKey;
    protected boolean has_ParentId;
    protected long _ParentId;
    protected java.lang.String _TitleTrnKey;
    protected boolean has_TopicId;
    protected long _TopicId;
    protected java.lang.String _Body;
    protected java.lang.String _TopicKey;
    protected java.lang.String _Leng;
    protected java.util.Calendar _LastModDate;
    protected java.lang.String _ModuleInstance;
    protected java.lang.String _EditorKey;
    public final static java.lang.Class version = (org.digijava.module.help.jaxb.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (org.digijava.module.help.jaxb.HelpType.class);
    }

    public java.lang.String getKeywordsTrnKey() {
        return _KeywordsTrnKey;
    }

    public void setKeywordsTrnKey(java.lang.String value) {
        _KeywordsTrnKey = value;
    }

    public long getParentId() {
        return _ParentId;
    }

    public void setParentId(long value) {
        _ParentId = value;
        has_ParentId = true;
    }

    public java.lang.String getTitleTrnKey() {
        return _TitleTrnKey;
    }

    public void setTitleTrnKey(java.lang.String value) {
        _TitleTrnKey = value;
    }

    public long getTopicId() {
        return _TopicId;
    }

    public void setTopicId(long value) {
        _TopicId = value;
        has_TopicId = true;
    }

    public java.lang.String getBody() {
        return _Body;
    }

    public void setBody(java.lang.String value) {
        _Body = value;
    }

    public java.lang.String getTopicKey() {
        return _TopicKey;
    }

    public void setTopicKey(java.lang.String value) {
        _TopicKey = value;
    }

    public java.lang.String getLeng() {
        return _Leng;
    }

    public void setLeng(java.lang.String value) {
        _Leng = value;
    }

    public java.util.Calendar getLastModDate() {
        return _LastModDate;
    }

    public void setLastModDate(java.util.Calendar value) {
        _LastModDate = value;
    }

    public java.lang.String getModuleInstance() {
        return _ModuleInstance;
    }

    public void setModuleInstance(java.lang.String value) {
        _ModuleInstance = value;
    }

    public java.lang.String getEditorKey() {
        return _EditorKey;
    }

    public void setEditorKey(java.lang.String value) {
        _EditorKey = value;
    }

    public org.digijava.module.help.jaxb.impl.runtime.UnmarshallingEventHandler createUnmarshaller(org.digijava.module.help.jaxb.impl.runtime.UnmarshallingContext context) {
        return new org.digijava.module.help.jaxb.impl.HelpTypeImpl.Unmarshaller(context);
    }

    public void serializeBody(org.digijava.module.help.jaxb.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public void serializeAttributes(org.digijava.module.help.jaxb.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        if (_Body!= null) {
            context.startAttribute("", "body");
            try {
                context.text(((java.lang.String) _Body), "Body");
            } catch (java.lang.Exception e) {
                org.digijava.module.help.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endAttribute();
        }
        if (_EditorKey!= null) {
            context.startAttribute("", "editorKey");
            try {
                context.text(((java.lang.String) _EditorKey), "EditorKey");
            } catch (java.lang.Exception e) {
                org.digijava.module.help.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endAttribute();
        }
        if (_KeywordsTrnKey!= null) {
            context.startAttribute("", "keywordsTrnKey");
            try {
                context.text(((java.lang.String) _KeywordsTrnKey), "KeywordsTrnKey");
            } catch (java.lang.Exception e) {
                org.digijava.module.help.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endAttribute();
        }
        if (_LastModDate!= null) {
            context.startAttribute("", "lastModDate");
            try {
                context.text(javax.xml.bind.DatatypeConverter.printDate(((java.util.Calendar) _LastModDate)), "LastModDate");
            } catch (java.lang.Exception e) {
                org.digijava.module.help.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endAttribute();
        }
        if (_Leng!= null) {
            context.startAttribute("", "leng");
            try {
                context.text(((java.lang.String) _Leng), "Leng");
            } catch (java.lang.Exception e) {
                org.digijava.module.help.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endAttribute();
        }
        if (_ModuleInstance!= null) {
            context.startAttribute("", "moduleInstance");
            try {
                context.text(((java.lang.String) _ModuleInstance), "ModuleInstance");
            } catch (java.lang.Exception e) {
                org.digijava.module.help.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endAttribute();
        }
        if (has_ParentId) {
            context.startAttribute("", "parentId");
            try {
                context.text(javax.xml.bind.DatatypeConverter.printLong(((long) _ParentId)), "ParentId");
            } catch (java.lang.Exception e) {
                org.digijava.module.help.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endAttribute();
        }
        if (_TitleTrnKey!= null) {
            context.startAttribute("", "titleTrnKey");
            try {
                context.text(((java.lang.String) _TitleTrnKey), "TitleTrnKey");
            } catch (java.lang.Exception e) {
                org.digijava.module.help.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endAttribute();
        }
        if (has_TopicId) {
            context.startAttribute("", "topicId");
            try {
                context.text(javax.xml.bind.DatatypeConverter.printLong(((long) _TopicId)), "TopicId");
            } catch (java.lang.Exception e) {
                org.digijava.module.help.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endAttribute();
        }
        if (_TopicKey!= null) {
            context.startAttribute("", "topicKey");
            try {
                context.text(((java.lang.String) _TopicKey), "TopicKey");
            } catch (java.lang.Exception e) {
                org.digijava.module.help.jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endAttribute();
        }
    }

    public void serializeURIs(org.digijava.module.help.jaxb.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public java.lang.Class getPrimaryInterface() {
        return (org.digijava.module.help.jaxb.HelpType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000b"
+"expandedExpq\u0000~\u0000\u0002xpppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000pp"
+"sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsr\u0000\u001dcom.sun.msv.grammar.ChoiceExp\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001ppsr\u0000 com.sun.msv.grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001"
+"\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameClasst\u0000\u001fLcom/sun/msv/grammar/NameClass;"
+"xq\u0000~\u0000\u0003sr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psr\u0000\u001bcom.su"
+"n.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatyp"
+"e/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004namet\u0000\u001dLcom/sun/msv/util/StringP"
+"air;xq\u0000~\u0000\u0003ppsr\u0000#com.sun.msv.datatype.xsd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002"
+"\u0000\u0001Z\u0000\risAlwaysValidxr\u0000*com.sun.msv.datatype.xsd.BuiltinAtomic"
+"Type\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.xsd.ConcreteType\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000"
+"\u0003L\u0000\fnamespaceUrit\u0000\u0012Ljava/lang/String;L\u0000\btypeNameq\u0000~\u0000\u001dL\u0000\nwhit"
+"eSpacet\u0000.Lcom/sun/msv/datatype/xsd/WhiteSpaceProcessor;xpt\u0000 "
+"http://www.w3.org/2001/XMLSchemat\u0000\u0006stringsr\u00005com.sun.msv.dat"
+"atype.xsd.WhiteSpaceProcessor$Preserve\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun"
+".msv.datatype.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xp\u0001sr\u00000com.s"
+"un.msv.grammar.Expression$NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003"
+"ppsr\u0000\u001bcom.sun.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000"
+"\u001dL\u0000\fnamespaceURIq\u0000~\u0000\u001dxpq\u0000~\u0000!q\u0000~\u0000 sr\u0000#com.sun.msv.grammar.Sim"
+"pleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u001dL\u0000\fnamespaceURIq\u0000~\u0000\u001d"
+"xr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u0004bodyt\u0000\u0000sr\u00000"
+"com.sun.msv.grammar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000x"
+"q\u0000~\u0000\u0003sq\u0000~\u0000\u0013\u0001psq\u0000~\u0000\u000eppsq\u0000~\u0000\u0010q\u0000~\u0000\u0014pq\u0000~\u0000\u0018sq\u0000~\u0000)t\u0000\teditorKeyq\u0000~\u0000"
+"-q\u0000~\u0000/sq\u0000~\u0000\u000eppsq\u0000~\u0000\u0010q\u0000~\u0000\u0014pq\u0000~\u0000\u0018sq\u0000~\u0000)t\u0000\u000ekeywordsTrnKeyq\u0000~\u0000-q"
+"\u0000~\u0000/sq\u0000~\u0000\u000eppsq\u0000~\u0000\u0010q\u0000~\u0000\u0014psq\u0000~\u0000\u0015ppsr\u0000!com.sun.msv.datatype.xsd"
+".DateType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000)com.sun.msv.datatype.xsd.DateTimeBas"
+"eType\u0014W\u001a@3\u00a5\u00b4\u00e5\u0002\u0000\u0000xq\u0000~\u0000\u001aq\u0000~\u0000 t\u0000\u0004datesr\u00005com.sun.msv.datatype.x"
+"sd.WhiteSpaceProcessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000#q\u0000~\u0000&sq\u0000~\u0000\'q"
+"\u0000~\u0000?q\u0000~\u0000 sq\u0000~\u0000)t\u0000\u000blastModDateq\u0000~\u0000-q\u0000~\u0000/sq\u0000~\u0000\u000eppsq\u0000~\u0000\u0010q\u0000~\u0000\u0014pq"
+"\u0000~\u0000\u0018sq\u0000~\u0000)t\u0000\u0004lengq\u0000~\u0000-q\u0000~\u0000/sq\u0000~\u0000\u000eppsq\u0000~\u0000\u0010q\u0000~\u0000\u0014pq\u0000~\u0000\u0018sq\u0000~\u0000)t\u0000"
+"\u000emoduleInstanceq\u0000~\u0000-q\u0000~\u0000/sq\u0000~\u0000\u000eppsq\u0000~\u0000\u0010q\u0000~\u0000\u0014psq\u0000~\u0000\u0015ppsr\u0000!com"
+".sun.msv.datatype.xsd.LongType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000+com.sun.msv.dat"
+"atype.xsd.IntegerDerivedType\u0099\u00f1]\u0090&6k\u00be\u0002\u0000\u0001L\u0000\nbaseFacetst\u0000)Lcom/"
+"sun/msv/datatype/xsd/XSDatatypeImpl;xq\u0000~\u0000\u001aq\u0000~\u0000 t\u0000\u0004longq\u0000~\u0000As"
+"r\u0000*com.sun.msv.datatype.xsd.MaxInclusiveFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000#"
+"com.sun.msv.datatype.xsd.RangeFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\nlimitValuet"
+"\u0000\u0012Ljava/lang/Object;xr\u00009com.sun.msv.datatype.xsd.DataTypeWit"
+"hValueConstraintFacet\"\u00a7Ro\u00ca\u00c7\u008aT\u0002\u0000\u0000xr\u0000*com.sun.msv.datatype.xsd"
+".DataTypeWithFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0005Z\u0000\fisFacetFixedZ\u0000\u0012needValueChec"
+"kFlagL\u0000\bbaseTypeq\u0000~\u0000RL\u0000\fconcreteTypet\u0000\'Lcom/sun/msv/datatype"
+"/xsd/ConcreteType;L\u0000\tfacetNameq\u0000~\u0000\u001dxq\u0000~\u0000\u001cppq\u0000~\u0000A\u0000\u0001sr\u0000*com.su"
+"n.msv.datatype.xsd.MinInclusiveFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000Vppq\u0000~\u0000A"
+"\u0000\u0000sr\u0000$com.sun.msv.datatype.xsd.IntegerType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000Qq"
+"\u0000~\u0000 t\u0000\u0007integerq\u0000~\u0000Asr\u0000,com.sun.msv.datatype.xsd.FractionDigi"
+"tsFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001I\u0000\u0005scalexr\u0000;com.sun.msv.datatype.xsd.DataT"
+"ypeWithLexicalConstraintFacetT\u0090\u001c>\u001azb\u00ea\u0002\u0000\u0000xq\u0000~\u0000Yppq\u0000~\u0000A\u0001\u0000sr\u0000#c"
+"om.sun.msv.datatype.xsd.NumberType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u001aq\u0000~\u0000 t\u0000\u0007d"
+"ecimalq\u0000~\u0000Aq\u0000~\u0000et\u0000\u000efractionDigits\u0000\u0000\u0000\u0000q\u0000~\u0000_t\u0000\fminInclusivesr\u0000"
+"\u000ejava.lang.Long;\u008b\u00e4\u0090\u00cc\u008f#\u00df\u0002\u0000\u0001J\u0000\u0005valuexr\u0000\u0010java.lang.Number\u0086\u00ac\u0095\u001d\u000b\u0094"
+"\u00e0\u008b\u0002\u0000\u0000xp\u0080\u0000\u0000\u0000\u0000\u0000\u0000\u0000q\u0000~\u0000_t\u0000\fmaxInclusivesq\u0000~\u0000i\u007f\u00ff\u00ff\u00ff\u00ff\u00ff\u00ff\u00ffq\u0000~\u0000&sq\u0000~\u0000\'"
+"q\u0000~\u0000Tq\u0000~\u0000 sq\u0000~\u0000)t\u0000\bparentIdq\u0000~\u0000-q\u0000~\u0000/sq\u0000~\u0000\u000eppsq\u0000~\u0000\u0010q\u0000~\u0000\u0014pq\u0000~"
+"\u0000\u0018sq\u0000~\u0000)t\u0000\u000btitleTrnKeyq\u0000~\u0000-q\u0000~\u0000/sq\u0000~\u0000\u000eppsq\u0000~\u0000\u0010q\u0000~\u0000\u0014pq\u0000~\u0000Osq\u0000"
+"~\u0000)t\u0000\u0007topicIdq\u0000~\u0000-q\u0000~\u0000/sq\u0000~\u0000\u000eppsq\u0000~\u0000\u0010q\u0000~\u0000\u0014pq\u0000~\u0000\u0018sq\u0000~\u0000)t\u0000\btop"
+"icKeyq\u0000~\u0000-q\u0000~\u0000/sr\u0000\"com.sun.msv.grammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/grammar/ExpressionPool$Closed"
+"Hash;xpsr\u0000-com.sun.msv.grammar.ExpressionPool$ClosedHash\u00d7j\u00d0N"
+"\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rstreamVersionL\u0000\u0006parentt\u0000$Lcom/sun/msv/gram"
+"mar/ExpressionPool;xp\u0000\u0000\u0000\u0013\u0001pq\u0000~\u0000\fq\u0000~\u0000qq\u0000~\u00009q\u0000~\u0000\u0005q\u0000~\u0000\u0007q\u0000~\u0000\nq\u0000~"
+"\u0000\rq\u0000~\u0000\bq\u0000~\u0000Iq\u0000~\u00001q\u0000~\u0000\u0006q\u0000~\u0000\u000fq\u0000~\u0000\u000bq\u0000~\u0000uq\u0000~\u0000Mq\u0000~\u00005q\u0000~\u0000Eq\u0000~\u0000yq\u0000~"
+"\u0000\tx"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends org.digijava.module.help.jaxb.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(org.digijava.module.help.jaxb.impl.runtime.UnmarshallingContext context) {
            super(context, "-------------------------------");
        }

        protected Unmarshaller(org.digijava.module.help.jaxb.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return org.digijava.module.help.jaxb.impl.HelpTypeImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  9 :
                        attIdx = context.getAttribute("", "lastModDate");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 12;
                            eatText1(v);
                            continue outer;
                        }
                        state = 12;
                        continue outer;
                    case  27 :
                        attIdx = context.getAttribute("", "topicKey");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 30;
                            eatText2(v);
                            continue outer;
                        }
                        state = 30;
                        continue outer;
                    case  30 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  3 :
                        attIdx = context.getAttribute("", "editorKey");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 6;
                            eatText3(v);
                            continue outer;
                        }
                        state = 6;
                        continue outer;
                    case  21 :
                        attIdx = context.getAttribute("", "titleTrnKey");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 24;
                            eatText4(v);
                            continue outer;
                        }
                        state = 24;
                        continue outer;
                    case  18 :
                        attIdx = context.getAttribute("", "parentId");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 21;
                            eatText5(v);
                            continue outer;
                        }
                        state = 21;
                        continue outer;
                    case  6 :
                        attIdx = context.getAttribute("", "keywordsTrnKey");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 9;
                            eatText6(v);
                            continue outer;
                        }
                        state = 9;
                        continue outer;
                    case  12 :
                        attIdx = context.getAttribute("", "leng");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 15;
                            eatText7(v);
                            continue outer;
                        }
                        state = 15;
                        continue outer;
                    case  15 :
                        attIdx = context.getAttribute("", "moduleInstance");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 18;
                            eatText8(v);
                            continue outer;
                        }
                        state = 18;
                        continue outer;
                    case  0 :
                        attIdx = context.getAttribute("", "body");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 3;
                            eatText9(v);
                            continue outer;
                        }
                        state = 3;
                        continue outer;
                    case  24 :
                        attIdx = context.getAttribute("", "topicId");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 27;
                            eatText10(v);
                            continue outer;
                        }
                        state = 27;
                        continue outer;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        private void eatText1(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _LastModDate = javax.xml.bind.DatatypeConverter.parseDate(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText2(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _TopicKey = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText3(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _EditorKey = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText4(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _TitleTrnKey = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText5(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _ParentId = javax.xml.bind.DatatypeConverter.parseLong(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
                has_ParentId = true;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText6(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _KeywordsTrnKey = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText7(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Leng = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText8(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _ModuleInstance = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText9(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Body = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText10(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _TopicId = javax.xml.bind.DatatypeConverter.parseLong(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
                has_TopicId = true;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  9 :
                        attIdx = context.getAttribute("", "lastModDate");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 12;
                            eatText1(v);
                            continue outer;
                        }
                        state = 12;
                        continue outer;
                    case  27 :
                        attIdx = context.getAttribute("", "topicKey");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 30;
                            eatText2(v);
                            continue outer;
                        }
                        state = 30;
                        continue outer;
                    case  30 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  3 :
                        attIdx = context.getAttribute("", "editorKey");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 6;
                            eatText3(v);
                            continue outer;
                        }
                        state = 6;
                        continue outer;
                    case  21 :
                        attIdx = context.getAttribute("", "titleTrnKey");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 24;
                            eatText4(v);
                            continue outer;
                        }
                        state = 24;
                        continue outer;
                    case  18 :
                        attIdx = context.getAttribute("", "parentId");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 21;
                            eatText5(v);
                            continue outer;
                        }
                        state = 21;
                        continue outer;
                    case  6 :
                        attIdx = context.getAttribute("", "keywordsTrnKey");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 9;
                            eatText6(v);
                            continue outer;
                        }
                        state = 9;
                        continue outer;
                    case  12 :
                        attIdx = context.getAttribute("", "leng");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 15;
                            eatText7(v);
                            continue outer;
                        }
                        state = 15;
                        continue outer;
                    case  15 :
                        attIdx = context.getAttribute("", "moduleInstance");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 18;
                            eatText8(v);
                            continue outer;
                        }
                        state = 18;
                        continue outer;
                    case  0 :
                        attIdx = context.getAttribute("", "body");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 3;
                            eatText9(v);
                            continue outer;
                        }
                        state = 3;
                        continue outer;
                    case  24 :
                        attIdx = context.getAttribute("", "topicId");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 27;
                            eatText10(v);
                            continue outer;
                        }
                        state = 27;
                        continue outer;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  9 :
                        if (("lastModDate" == ___local)&&("" == ___uri)) {
                            state = 10;
                            return ;
                        }
                        state = 12;
                        continue outer;
                    case  27 :
                        if (("topicKey" == ___local)&&("" == ___uri)) {
                            state = 28;
                            return ;
                        }
                        state = 30;
                        continue outer;
                    case  30 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  3 :
                        if (("editorKey" == ___local)&&("" == ___uri)) {
                            state = 4;
                            return ;
                        }
                        state = 6;
                        continue outer;
                    case  21 :
                        if (("titleTrnKey" == ___local)&&("" == ___uri)) {
                            state = 22;
                            return ;
                        }
                        state = 24;
                        continue outer;
                    case  18 :
                        if (("parentId" == ___local)&&("" == ___uri)) {
                            state = 19;
                            return ;
                        }
                        state = 21;
                        continue outer;
                    case  6 :
                        if (("keywordsTrnKey" == ___local)&&("" == ___uri)) {
                            state = 7;
                            return ;
                        }
                        state = 9;
                        continue outer;
                    case  12 :
                        if (("leng" == ___local)&&("" == ___uri)) {
                            state = 13;
                            return ;
                        }
                        state = 15;
                        continue outer;
                    case  15 :
                        if (("moduleInstance" == ___local)&&("" == ___uri)) {
                            state = 16;
                            return ;
                        }
                        state = 18;
                        continue outer;
                    case  0 :
                        if (("body" == ___local)&&("" == ___uri)) {
                            state = 1;
                            return ;
                        }
                        state = 3;
                        continue outer;
                    case  24 :
                        if (("topicId" == ___local)&&("" == ___uri)) {
                            state = 25;
                            return ;
                        }
                        state = 27;
                        continue outer;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  29 :
                        if (("topicKey" == ___local)&&("" == ___uri)) {
                            state = 30;
                            return ;
                        }
                        break;
                    case  9 :
                        attIdx = context.getAttribute("", "lastModDate");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 12;
                            eatText1(v);
                            continue outer;
                        }
                        state = 12;
                        continue outer;
                    case  27 :
                        attIdx = context.getAttribute("", "topicKey");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 30;
                            eatText2(v);
                            continue outer;
                        }
                        state = 30;
                        continue outer;
                    case  8 :
                        if (("keywordsTrnKey" == ___local)&&("" == ___uri)) {
                            state = 9;
                            return ;
                        }
                        break;
                    case  11 :
                        if (("lastModDate" == ___local)&&("" == ___uri)) {
                            state = 12;
                            return ;
                        }
                        break;
                    case  20 :
                        if (("parentId" == ___local)&&("" == ___uri)) {
                            state = 21;
                            return ;
                        }
                        break;
                    case  30 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  3 :
                        attIdx = context.getAttribute("", "editorKey");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 6;
                            eatText3(v);
                            continue outer;
                        }
                        state = 6;
                        continue outer;
                    case  17 :
                        if (("moduleInstance" == ___local)&&("" == ___uri)) {
                            state = 18;
                            return ;
                        }
                        break;
                    case  21 :
                        attIdx = context.getAttribute("", "titleTrnKey");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 24;
                            eatText4(v);
                            continue outer;
                        }
                        state = 24;
                        continue outer;
                    case  18 :
                        attIdx = context.getAttribute("", "parentId");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 21;
                            eatText5(v);
                            continue outer;
                        }
                        state = 21;
                        continue outer;
                    case  26 :
                        if (("topicId" == ___local)&&("" == ___uri)) {
                            state = 27;
                            return ;
                        }
                        break;
                    case  23 :
                        if (("titleTrnKey" == ___local)&&("" == ___uri)) {
                            state = 24;
                            return ;
                        }
                        break;
                    case  6 :
                        attIdx = context.getAttribute("", "keywordsTrnKey");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 9;
                            eatText6(v);
                            continue outer;
                        }
                        state = 9;
                        continue outer;
                    case  2 :
                        if (("body" == ___local)&&("" == ___uri)) {
                            state = 3;
                            return ;
                        }
                        break;
                    case  14 :
                        if (("leng" == ___local)&&("" == ___uri)) {
                            state = 15;
                            return ;
                        }
                        break;
                    case  12 :
                        attIdx = context.getAttribute("", "leng");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 15;
                            eatText7(v);
                            continue outer;
                        }
                        state = 15;
                        continue outer;
                    case  5 :
                        if (("editorKey" == ___local)&&("" == ___uri)) {
                            state = 6;
                            return ;
                        }
                        break;
                    case  15 :
                        attIdx = context.getAttribute("", "moduleInstance");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 18;
                            eatText8(v);
                            continue outer;
                        }
                        state = 18;
                        continue outer;
                    case  0 :
                        attIdx = context.getAttribute("", "body");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 3;
                            eatText9(v);
                            continue outer;
                        }
                        state = 3;
                        continue outer;
                    case  24 :
                        attIdx = context.getAttribute("", "topicId");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 27;
                            eatText10(v);
                            continue outer;
                        }
                        state = 27;
                        continue outer;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  22 :
                            state = 23;
                            eatText4(value);
                            return ;
                        case  9 :
                            attIdx = context.getAttribute("", "lastModDate");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                state = 12;
                                eatText1(v);
                                continue outer;
                            }
                            state = 12;
                            continue outer;
                        case  19 :
                            state = 20;
                            eatText5(value);
                            return ;
                        case  27 :
                            attIdx = context.getAttribute("", "topicKey");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                state = 30;
                                eatText2(v);
                                continue outer;
                            }
                            state = 30;
                            continue outer;
                        case  1 :
                            state = 2;
                            eatText9(value);
                            return ;
                        case  30 :
                            revertToParentFromText(value);
                            return ;
                        case  25 :
                            state = 26;
                            eatText10(value);
                            return ;
                        case  3 :
                            attIdx = context.getAttribute("", "editorKey");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                state = 6;
                                eatText3(v);
                                continue outer;
                            }
                            state = 6;
                            continue outer;
                        case  4 :
                            state = 5;
                            eatText3(value);
                            return ;
                        case  7 :
                            state = 8;
                            eatText6(value);
                            return ;
                        case  13 :
                            state = 14;
                            eatText7(value);
                            return ;
                        case  21 :
                            attIdx = context.getAttribute("", "titleTrnKey");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                state = 24;
                                eatText4(v);
                                continue outer;
                            }
                            state = 24;
                            continue outer;
                        case  18 :
                            attIdx = context.getAttribute("", "parentId");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                state = 21;
                                eatText5(v);
                                continue outer;
                            }
                            state = 21;
                            continue outer;
                        case  28 :
                            state = 29;
                            eatText2(value);
                            return ;
                        case  10 :
                            state = 11;
                            eatText1(value);
                            return ;
                        case  6 :
                            attIdx = context.getAttribute("", "keywordsTrnKey");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                state = 9;
                                eatText6(v);
                                continue outer;
                            }
                            state = 9;
                            continue outer;
                        case  12 :
                            attIdx = context.getAttribute("", "leng");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                state = 15;
                                eatText7(v);
                                continue outer;
                            }
                            state = 15;
                            continue outer;
                        case  16 :
                            state = 17;
                            eatText8(value);
                            return ;
                        case  15 :
                            attIdx = context.getAttribute("", "moduleInstance");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                state = 18;
                                eatText8(v);
                                continue outer;
                            }
                            state = 18;
                            continue outer;
                        case  0 :
                            attIdx = context.getAttribute("", "body");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                state = 3;
                                eatText9(v);
                                continue outer;
                            }
                            state = 3;
                            continue outer;
                        case  24 :
                            attIdx = context.getAttribute("", "topicId");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                state = 27;
                                eatText10(v);
                                continue outer;
                            }
                            state = 27;
                            continue outer;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

    }

}
