package org.dgfoundation.amp.nireports.testcases.drc;

import org.dgfoundation.amp.nireports.testcases.IHardcodedNames;

import java.util.Arrays;

/**
 * Contains the hardcoded mapping of some funding categories and columns, used by hardcoded funding cells.
 * See {@link FundingIdsMapper} for the way those are generated.
 * @author acartaleanu
 *
 */
public class DRCHardcodedFundingNames extends IHardcodedNames {
            
    @Override
    protected void populateMaps() {
        category("donor_org_id", Arrays.asList(
            param("S.G. Anciens Combattants", 3257),
            param("Investissement privé swazilandais", 3626),
            param("Fonds Forestiers pour le Bassin du Congo", 3897),
            param("MINES ADVISORY GROUP", 3971),
            param("International Rescue Committee", 3334),
            param("Bandundu", 3916),
            param("Ministère de la Santé Publique", 3369),
            param("Innovative Recourses Management", 3780),
            param("University of Guelph", 3903),
            param("S.G. Urbanisme et Habitat", 3154),
            param("Heal Africa", 3472),
            param("Goal Ireland", 3467),
            param("Comité Provincial Bandundu", 3152),
            param("Ministère des Affaires Etrangères", 3182),
            param("Atlas Logistique", 3776),
            param("Médécin Sans Frontière", 3651),
            param("11.11.11", 3783),
            param("Malteser International", 3490),
            param("Vlaams Internationaal Centrum", 4105),
            param("Investissement privé mauricien", 3629),
            param("Care Canada", 3680),
            param("GOVERNMENT OF SWITZERLAND", 3956),
            param("Search For Common Ground", 3517),
            param("IFPRODUCTIONS", 3905),
            param("POPULATION MEDIA CENTER", 3436),
            param("ACCC", 3687),
            param("Association des Rotary clubs belges pour la coopération au développement", 4096),
            param("CANADIAN INTERNATIONAL DEVELOP", 4035),
            param("S.G. Condition Féminine et Famille", 3200),
            param("FOLECO", 3864),
            param("DGD", 4129),
            param("AIDE MEDICALE INTERNATIONALE", 3423),
            param("Groupe d'Etude de Transports", 3215),
            param("Comité pour le Développement de l'Afrique Australe", 3332),
            param("Agence Française de Développement", 3343),
            param("Banque Africaine de Développement", 3381),
            param("Conférence des Nations Unies sur le commerce et le développement", 3603),
            param("Investissement privé italien", 3620),
            param("African Wildlife Foudation", 3801),
            param("Ministère des Affaires Etrangères Allemande", 3893),
            param("Commission épiscopale", 3912),
            param("Commission Européenne", 3328),
            param("Cellule d'appui à l'Ordonnateur  Fonds Européen pour le Développement", 3344),
            param("Solidarité aide humanitaire d'urgence", 3519),
            param("CEBA", 3678),
            param("The National Democratic Institute for International Affairs", 3523),
            param("COD-PROGRAMME PROMOTION SOINS", 3973),
            param("RENAPI", 3269),
            param("BD", 3784),
            param("UN Dept of Economic and Social", 3947),
            param("Office National des Transports du Congo", 3225),
            param("Volontaires des Nations Unies (admin PNUD)", 3604),
            param("PRESIDENCE DE LA REPUBLIQUE", 3358),
            param("Action Aid International DRC", 4026),
            param("Université de Bercelona", 3703),
            param("CARITAS INTERNATIONALIS", 3439),
            param("S.G. Senat", 3361),
            param("CIF Santé", 3704),
            param("Investissement privé canadien", 3613),
            param("COLLABORATION SANTE INTERNATIONAL", 3966),
            param("Frères des Hommes", 4104),
            param("Province du Nord Kivu", 4198),
            param("Fonds mondial malaria (à supprimer)", 4216),
            param("SLCD", 3782),
            param("Adventist Develop&amp;Relief Agenc", 3960),
            param("Service National", 4374),
            param("Pooled Fund Humanitaire", 3416),
            param("Fundation IEPALA", 3698),
            param("Ambassade de Turquie", 3581),
            param("S.G. Petites et Moyennes Entreprises", 3370),
            param("UNITED NATIONS VOLUNTEERS", 3926),
            param("Vision Environnement et Développement Communautaire", 3527),
            param("Département des opérations de maintien de la paix", 3605),
            param("Komyuniti cons", 3713),
            param("Institut Saint Joseph", 4014),
            param("Direction Générale  des Douanes et Assises", 3163),
            param("Comité Pilote de Réforme des Entreprises Publiques", 3591),
            param("Multi Action d' Assistances au", 4012),
            param("Medical Emergency Relief International", 3498),
            param("CREDES", 3572),
            param("Education Développement Center, Inc", 3757),
            param("S.G. Affaires Foncières", 3187),
            param("PNUD TRAC1.1.1 ", 3385),
            param("Ministère des Affaires Etrangères de Danmark", 3639),
            param("Research Triangle Institute", 4040),
            param("Renatelsat", 3245),
            param("Itineras cons", 3725),
            param("AGRO ACTION ALLEMANDE", 3422),
            param("Jesuit Refugee Service", 3978),
            param("International Labour Organisat", 3933),
            param("NGO-FONDATION FEMMES PLUS", 3999),
            param("S.G. Plan", 3205),
            param("SHC", 3717),
            param("S.G. Défense Nationale", 3256),
            param("Université de Lubumbashi", 4379),
            param("Ministère de l'Economie Nationale et Commerce", 3186),
            param("Investissement privé luxembourgois", 4177),
            param("Ambassade d'Italie", 3290),
            param("Ambassade d'Allemagne", 3276),
            param("Oxfam-Solidarité Belgique", 3508),
            param("CHAKA (ADG Gembloux - CODEART - ISF) - CHAKA", 4094),
            param("Vereniging voor Technische Samenwerking - TRIAS", 4099),
            param("Université Protestante du Congo", 3992),
            param("Commission Episcopale Nationale Congolaise", 4377),
            param("PNUD country co financing CS 11888", 3391),
            param("Various", 3738),
            param("Investissemnt privé béninois", 3611),
            param("Ministère de l'Industrie", 3240),
            param("Avocats sans frontières", 3763),
            param("Fonds Mondial", 4223),
            param("UN INDUSTRIAL DEVELOPMENT ORGA", 3928),
            param("MEDAIR", 3573),
            param("Msaada et Solidarité Internationale pour la Promotiondes Energies Renouvelables dans le tiers Monde", 3814),
            param("Réfugiés politiques", 4056),
            param("CARITAS DEVELOPPEMENT", 3440),
            param("Investissement privé belge", 3610),
            param("PNUD Programme Cost Sharing 30000", 3397),
            param("Development alternatives incorporated", 3983),
            param("Ministère des Affaires Etrangères d'Irlande", 3636),
            param("International Trade Centre", 3936),
            param("Ambassade des Pays-Bas", 3296),
            param("S.G. Industrie", 3372),
            param("Ministère de la Défense Nationale et Anciens Combattants", 3183),
            param("Enfance Tiers Monde", 3712),
            param("Investissement privé néerlandais", 4185),
            param("Matres Mundi", 3657),
            param("UNDP", 3948),
            param("S.G. Finances", 3162),
            param("Careas", 3787),
            param("GOVERNMENT OF JAPAN", 3942),
            param("Inspection Générale des Finances", 3166),
            param("Catholic Relief Services", 3442),
            param("Bureau de Coordination des Marchés des Infrastructures", 3413),
            param("Fonds d'équipement des Nations Unies (admin PNUD)", 3321),
            param("Comité Provincial Kinshasa", 3147),
            param("Investissement privé ukrainien", 4179),
            param("Agence Norvégienne de Développement", 10),
            param("ALBOAN", 3705),
            param("SOS Faim", 3719),
            param("Eximbank of India", 3594),
            param("Fonds monétaire international", 3325),
            param("Johanniter", 3920),
            param("Medecins du Monde-Belgique", 3491),
            param("SPAIN MDG FUND", 4044),
            param("S.G. Environnement et Conservation de la Nature", 3364),
            param("Unité d'Exécution du Programme National de Désarmement, Démobilisation et Réinsertion", 3866),
            param("Comité Provincial Nord-Kivu", 3149),
            param("Cabinet du Premier Ministre", 3159),
            param("OXFAM", 3336),
            param("Fonds Africain de Développement", 3357),
            param("University, college or other teaching institution, research institute or think-tank", 4369),
            param("Cooperazione Intermazionale", 3957),
            param("Associazione Volntarin Per  Il Servizio Internazionale", 3430),
            param("WSM", 3722),
            param("Tearfund", 3521),
            param("SFI/Société financière internationale", 3349),
            param("Canadian Catholic Organization for Development and Peace", 3558),
            param("Ministère des Affaires Etrangères de Pologne", 3914),
            param("Handicap International/Atlas Logistique", 3471),
            param("Programme International de Conservation des Gorilles", 3515),
            param("Ministère des Infrastructures,Travaux Publics et Reconstruction", 3246),
            param("Direction des Voies de Desserte Agricole", 3247),
            param("University of North Carolina", 4005),
            param("Action Bio", 4091),
            param("Vrijwilligers voor het Onderwijs - VRIJOND", 4114),
            param("PRIMATURE", 3363),
            param("RCN Justice&Démocratie", 3516),
            param("Institut National de Préparation Professionnelle", 3212),
            param("Organisation internationale du travail", 3308),
            param("Bureau d'Etudes d'Aménagement et 'Urbanisme", 3238),
            param("Trust Found (Banque Mondiale)", 4193),
            param("Ministère du Budget", 3172),
            param("Croix Rouge Belge", 3709),
            param("Mission  des Nations Unies pour la Stabilisation et Consolidation de la paix", 3314),
            param("Le Centre Carter", 3906),
            param("Institut National d'Etudes et des Recherches Agronomiques", 3195),
            param("Finlande", 3637),
            param("KOREA INTERNATIONAL VOLUNTEER ORGANIZATION", 4078),
            param("Consortuin CCICD-CHUM", 3931),
            param("EQUILIBRE", 4006),
            param("S.G. Justice", 3266),
            param("Chancellerie des Ordres Nationaux", 4375),
            param("S.G. Santé", 3374),
            param("UNEP", 3691),
            param("CCISD/USI", 3989),
            param("Ambassade de Belgique", 3278),
            param("Population Service International", 3745),
            param("Investissement privé nigérian", 4181),
            param("Programme National Mutlisectoriel de Lutte contre le SIDA", 3855),
            param("Institut National de Statistiques", 3922),
            param("Ambassade des Etats-Unis d'Amérique", 3285),
            param("VZW / civ.mij  : onbepaald", 4095),
            param("COD-Conseil National des ONGs", 3962),
            param("INTERACTIONS", 4017),
            param("Bureau des Nations Unies pour les services d'Appui aux Projets", 3315),
            param("United Nations Mine Action Service", 3690),
            param("Commission Electorale Indépendante", 3686),
            param("War Child Canada", 4013),
            param("United Nations Children’s Fund", 4364),
            param("GOVERNMENT OF NETHERLANDS", 3944),
            param("Programme des Nations Unies pour le Développement", 3302),
            param("Investissement privé togolais", 3627),
            param("Investissement privé hellenique", 4178),
            param("Jane Goodall Institute for Wildlife Research, Education and Conservation", 3988),
            param("Action pour le Développement et la Paix Endogènes", 3541),
            param("Agence espagnole de coopération internationale et développement", 3915),
            param("Action contre la faim USA", 3335),
            param("MONTREAL PROTOCOL", 4039),
            param("S.G. Commerce Extérieur", 3174),
            param("Cellule d'exécution des projets-Eau", 3918),
            param("CARITAS INTERNATIONAL-BELGIQUE", 3438),
            param("Port de Bruxelles", 3715),
            param("Asociacion Ayuda a Los Desempleados Del Tercer Mundo", 3702),
            param("Ministère du Genre,Famille et Enfant", 3229),
            param("Ministère du Portefeuille", 3270),
            param("The mines advisory group", 3907),
            param("Kinderen Derde Wereld - KDW/ETM", 4107),
            param("S.G. Assemblée Nationale", 3359),
            param("COOPERA", 3655),
            param("SERVICE D' APPUI AU DEVELOPPME", 4011),
            param("Ambassade de l'Inde", 3288),
            param("ORG. INTERNATIONALE DE LA FRAN", 4043),
            param("Medecins du Monde -France", 3492),
            param("Ministère des Affaires Etrangères d'Albanie", 3884),
            param("Direction de Gestion de la Dette Publique", 3171),
            param("Bureau de coordination des affaires humanitaires des Nations Unies", 3312),
            param("World Vision Canada", 3688),
            param("Agence Coréenne de Coopération Internationale", 3882),
            param("Fonds Social de la République Démocratique du Congo", 3327),
            param("Georgetown Unversity", 3748),
            param("Engender heath", 4025),
            param("Population Services International", 4352),
            param("DOCTORS ON CALL FOR SERVICE", 3456),
            param("Investissement privé américain", 3608),
            param("Armée du Salut", 3800),
            param("Protos", 3802),
            param("Pouvoir Judiciaire", 4376),
            param("COD-GROUP ETUDE ACTION DEVELOP", 4008),
            param("Danchurchaid", 3648),
            param("GOVERNMENT OF LUXEMBOURG", 3943),
            param("CROIX ROUGE BELGIQUE", 4031),
            param("Pesonnes âgées", 4054),
            param("CENTRES SOCIAUX SANITAIRES -CONGO", 3444),
            param("GOVERNMENT OF BELGIUM", 3932),
            param("Investissement privé bahaméen", 4176),
            param("Commission justice et paix belge", 3708),
            param("Paul Carlson Partnership", 4167),
            param("Koninklijk Museum voor Midden-Afrika in Tervuren", 4102),
            param("Ambassade de Royaume Uni", 3649),
            param("UNITED NATIONS DEVELOPMENT PRO", 3927),
            param("Ministère de la Recherche Scientifique", 3729),
            param("Save the Children UK", 3333),
            param("Fonds Mondial HIV/SIDA (à supprimer)", 3402),
            param("NGO Solidarité Socialiste - FCD", 3723),
            param("Cellule infrastructure", 3844),
            param("COMITATO INTERNAZIONALE PER DE SVILUPPO DEI POPULI", 3448),
            param("GROUPE ONE", 4116),
            param("Ministère du Développement Rural", 3732),
            param("Organisation Internationale pour les Migrations", 3593),
            param("Don Bosco", 3701),
            param("Bureau local RDC", 3845),
            param("Ministère de l'Energie", 3192),
            param("AIDES", 3544),
            param("Province de Kinshasa", 4197),
            param("Investssement privé autrichien", 3609),
            param("Régie de Distribution d'Eau", 3231),
            param("Commission d' Encadrement pour", 4022),
            param("Ministère des Droits Humains", 3260),
            param("Ambassade de Suède", 3660),
            param("Association pour la Protection", 4016),
            param("001981", 4045),
            param("Cellule d'Exécution des Projets PMR RH", 4190),
            param("Investissement privé congolais", 3630),
            param("Ambassade du Canada", 3677),
            param("Coopération Technique Suisse", 3913),
            param("Congolaise des Hydrocarbures", 3273),
            param("Organisation de Cooperation etde Développement Economique", 3986),
            param("Education", 3378),
            param("Avenir Congo", 4092),
            param("Central Emergency Reponse Fund (CERF)", 3854),
            param("ANES-Congo", 3871),
            param("PNUD Cost Sharing WB1 30011", 3398),
            param("UNCODED", 3727),
            param("Ministère des Affaires Etrangères Luxembourg", 3643),
            param("S.G. Agriculture, Pêche et Elevage", 3250),
            param("Ministère des Affaires Etrangères de Finlande", 3638),
            param("Province du Katanga", 4205),
            param("Entraide prot. Suisse", 3910),
            param("UNAIDS", 3984),
            param("CHRISTIAN AID", 3445),
            param("Groupe de Recherche et d'Echanges Technologiques", 3468),
            param("Ambassade de Russie", 4191),
            param("Programme alimentaire mondial", 3303),
            param("Joint United Nations Programme on HIV/AIDS", 4345),
            param("Vlaamse Interuniversitaire Raad", 3987),
            param("Investissement privé gambien", 3617),
            param("Véterinaire Sans Frontières", 3653),
            param("UNICEF Fonds d'urgence", 3578),
            param("APEFE - Association pour la Promotion de l'Education et de la Formation à l'Etranger - APEFE", 4120),
            param("Administration centrale", 4208),
            param("Ministère des Mines", 3262),
            param("Ministère des Affaires Etrangères de la République Tchèque", 3641),
            param("Search Common Ground", 3747),
            param("BUREAU INTERNATIONAL CATHOLIQUE POUR L'ENFANCE", 3435),
            param("FOODS FOR HUNGRY INTERNATIONAL", 3970),
            param("S.G. Coopération Internationale", 3180),
            param("Caritas  Uvira", 4034),
            param("New York University", 4021),
            param("BROEDERLIJK DELEN", 3818),
            param("Investissement privé turque", 4175),
            param("South-East Consortiun for International Développement", 3761),
            param("SECID", 3741),
            param("Action Agro Allemande", 3993),
            param("GT8 Groupe agriculture et développement rural", 3669),
            param("Unité de Coordinnation du Projet/PARSE", 4196),
            param("Organisation des Nations Unies", 3301),
            param("OCCDP", 3685),
            param("Non-Governmental Organisations (NGOs) and Civil Society", 4349),
            param("Japan International Cooperation System", 4165),
            param("NGO-Org Catholique d'Aide et d", 4001),
            param("Radio Télévision Nationale Congolaise", 3243),
            param("Cabinet du Président de la République", 3263),
            param("Pact Building Capacity Worldwide", 3509),
            param("S.G. Economie", 3173),
            param("Avenir Meilleur pour les Orphelins du Congo", 3568),
            param("MEDICUS MUNDI BIZKAIA", 3756),
            param("Haute Autorité des Médias", 3241),
            param("Chemin de Fer des Uélés", 3222),
            param("Center for Disease Control And Prevention", 3894),
            param("S.G. Budget", 3268),
            param("World Food Programme", 3951),
            param("Intrenational  Resources Group lt", 4168),
            param("Winrock international", 3954),
            param("Action Contre la Pauvrete", 4018),
            param("Ministère de l'Enseignement Supérieur et Universitaire", 3201),
            param("UICN", 3692),
            param("Ministère de l'Agriculture", 3160),
            param("Ministère des Affaires Entragères", 3161),
            param("Commission Nationale de Prévention Routière", 3224),
            param("Mission de police de l'Union européenne à Kinshasa", 3595),
            param("Ministère des Petites et Moyennnes Entreprises", 3730),
            param("S.G. Recherche Scientifique", 3194),
            param("Ministère des Affaires Etrangères,Commerce et Développement ", 4383),
            param("Collaboration Santé Internationale", 4015),
            param("Ministère de l'Enseignement Primaire,Secondaire et Professionnel", 3199),
            param("Institut National de Sécurité Sociale", 3209),
            param("Commission Internationale du Bassin Congo-Oubangi-Sangha", 3707),
            param("Unité Nationale de Coordination de Projet", 4210),
            param("Petits Pas", 4109),
            param("Ambassade du Brésil", 3279),
            param("Investissemement privé tanzanien", 4189),
            param("Bureau Diocesain des Oeuvres Médicales", 3785),
            param("Régie des Voies Maritimes", 3220),
            param("Groupe contre les mines", 3502),
            param("S.G. Transports et voies de communication", 3214),
            param("Missionnaires Claretiennes", 3696),
            param("Abt Associates", 3822),
            param("SOS Kinderdorp - België help de wereld", 4103),
            param("Department for International Development", 3),
            param("Police Nationale Congolaise", 4186),
            param("Unité de Coordinnation du Projet/PARSS", 4195),
            param("Investissement privé britanique", 3612),
            param("Comité Provincial Sud-Kivu", 3151),
            param("Fonds International pour le Développement Agricole", 3382),
            param("Investissement privé israëlien", 3619),
            param("Banque Centrale du Congo", 3170),
            param("Investissement privé allemand", 3615),
            param("Ministère de Coopération Economique et du Développement", 3892),
            param("Ambassade de Chine", 3281),
            param("CDI BWAMANDA", 3877),
            param("Ministère des Affaires Sociales,Action Humanitaire et Solidarité Nationale", 3158),
            param("Global rights", 3466),
            param("Investissement privé chinois", 3614),
            param("Direction Générale de la Coopération au Développement Belge", 2),
            param("Organization Navarra de Ayuda entre los Pueblos", 3693),
            param("International Centre for Transitional Justice", 4137),
            param("UniverSud Liège (ex-ACDLg/ACDST)", 4101),
            param("Unité de Coordinnation du Projet PFCN", 4192),
            param("Groupe de Recherche et d'action sur le développement durable et le développement économique durable", 3469),
            param("COD-Bureua Diocesain de Develo", 3991),
            param("Union Africaine", 4209),
            param("Direction Générale des Recettes Administratives et Domaniales", 3165),
            param("Ministère de l'Intérieur et Sécurité", 3253),
            param("Africa Parks", 3706),
            param("Province Administration Centrale", 4224),
            param("Norwegian Refugee Council", 3505),
            param("Trias", 3720),
            param("Province Orientale", 4202),
            param("UN DEMOCRACY FUND (UNDEF)", 4042),
            param("CENTRE SCIENTIFIQUE ET MEDICAL DE L'UNIVERSITE LIBRE DE BRUXELLES POUR SES ACTIVITES DE COOPERATION", 3443),
            param("ACTION CONTRE LA FAIM", 3976),
            param("Société Nationale d'Electricité", 3232),
            param("Avocats Sans Frontières Belgique", 3794),
            param("UN Development Programme", 3952),
            param("Agence Congolaise de Presse", 3244),
            param("Fonds des Nations Unies pour la population", 3310),
            param("Université de Kisangani", 4380),
            param("Fonds de Développement des Nations Unies pour la femme", 3316),
            param("Commission Electorale Nationale  Indépendante", 3362),
            param("Widelife Conservation Society", 3529),
            param("Caritas allemagne", 3891),
            param("Investissement privé indien", 3618),
            param("Banque Européenne d'Investissement", 9),
            param("Association de Sante Familiale", 3963),
            param("Ministère de la Communication et Médias", 3242),
            param("Federacion de Asociaciones Meddicus Mundi en Espagne", 3700),
            param("Investissement privé portugais", 3622),
            param("Oxfam-Quebec", 3507),
            param("Aviation sans frontière Française", 3434),
            param("Association africaine de défense des Droits de l'Homme ", 4028),
            param("Organisation mondiale de la santé", 3307),
            param("Deutsche Gesellschaft Technische Zusammenarbeit", 3454),
            param("MALTESER", 3968),
            param("Office National du Tourisme", 3368),
            param("Agence Européenne pour le Développement", 3421),
            param("Ambassade de Suisse", 3299),
            param("Other.", 4350),
            param("Cellule pour la Décentralisation", 3851),
            param("Méteorologie et Télecommunication par Satellite", 3228),
            param("FEDECAME", 3575),
            param("AFRICA CONSERVATION FUND", 3419),
            param("Investissement privé zambien", 3628),
            param("World Vision International", 3531),
            param("PMU InterLife", 3587),
            param("OXFAM SOLIDARITES BELGIQUE", 4010),
            param("Damiaanactie", 3711),
            param("Internews Network", 3798),
            param("GT5 Groupe infrastructures et transport", 3666),
            param("Solidarité Socialiste", 3774),
            param("Action contre la pauvreté", 3534),
            param("Terre sans Frontière", 3682),
            param("Mission de conseil et d’assistance en matière de réforme du secteur de la sécurité en RDC", 3596),
            param("Centre Congolais de Culture , de Formation et de Développement", 3659),
            param("NGO-DAN CHURCH AID", 3997),
            param("S.G. Affaires Humanitaires", 3176),
            param("EUROPEAN UNION", 3967),
            param("Province de l'Equateur", 4201),
            param("United Nations agency, fund or commission (UN)", 4363),
            param("Action pour la Paix, l'éducation et le Développement", 3538),
            param("S.G. Cour des Comptes", 3360),
            param("Woman for women International", 3530),
            param("Medecins sans Frontières-France", 3495),
            param("Conseil Interuniversitaire de la Communauté française de Belgique", 4128),
            param("Régie des Voies Aériennes", 3218),
            param("Fonds Médical Tropical", 3463),
            param("Ministère de la Décentralisation et Aménagement du Territoire", 3731),
            param("ICRAF International Council for Research in Agro-Forestry - CGIAR - PRT", 4133),
            param("Ministère des Postes, Téléphones et Télécommunications", 3274),
            param("Program for Apporpriate Technology in Health (PATH)", 4170),
            param("World Health Organisation", 3739),
            param("Province du Bas-Congo", 4199),
            param("GTM-FUNDACION SOLAR", 4007),
            param("GOVERNMENT OF SPAIN", 3953),
            param("DRC - CARJTAS MANIEMA", 4003),
            param("Province de Maniema", 4206),
            param("Comité International de la Croix Rouge", 3633),
            param("Rotary Belgique", 3716),
            param("Aviation sans frontière Belgique", 3433),
            param("Action contre la faim", 3803),
            param("Action pour le Bien-Etre Commun", 4019),
            param("Société Nationale des Chemins de Fer du Congo", 3217),
            param("Missionnaires du Divin Maitre", 3995),
            param("Fonds mondial tuberculose (à supprimer)", 4217),
            param("Third Country Government (Delegated co-operation)", 4359),
            param("Medecins sans Frontières-Belgique", 3493),
            param("CRC Sogema", 3975),
            param("Diakonie", 3348),
            param("EQUILIBRE DE L'AIDE D'URGENCE AU DEVELOPPEMENT COMMUNAUTAIRE", 3458),
            param("Ministère de l'Emploi,Travail et Prévoyance Sociale", 3188),
            param("Ministère des Affaires Etrangères de la Grèce", 3640),
            param("Institut Congolais pour la Conservation de la Nature", 3856),
            param("Ministère des Affaires Entragères Thailandaise", 3853),
            param("Comité Provincial Oriental", 3150),
            param("Fundacion Albihar", 3658),
            param("Electoral Institule of Southeren Africa", 3772),
            param("Haut Commissariat des Nations Unies pour les droits humains", 3317),
            param("Norway Red Cross", 3453),
            param("Organisation des Nations Unies pour l'alimentation et l'agriculture", 3306),
            param("Investissement privé sud africain", 3624),
            param("Agence d'aide à la Coopération Tecnhique et au Développement", 3749),
            param("Caritate Aegrorum Servi", 4112),
            param("PAGE", 3744),
            param("Ministère des Transports et Voies de Communication", 3373),
            param("Intenational Org for Migration", 3935),
            param("Service National d'Hydraulique Rurale", 3248),
            param("Family Health International", 3459),
            param("Caritas Allemagne", 4023),
            param("Lutheran World Federation", 3489),
            param("TEARFUNND", 4027),
            param("Service Laïque de Coopération au Développement", 4147),
            param("Accompagnement Technique pour", 4024),
            param("Ecole Nationale des Finances", 3168),
            param("VZW CAP SANTE", 4160),
            param("Norwegian Chruch Aid", 3980),
            param("Commission Diocesaine Justice", 4020),
            param("Ministère des Affaires Etrangères de la Norvège", 3635),
            param("Agence Suèdoise Internationale de Développement (ASDI)", 3867),
            param("ACDLg", 3576),
            param("Food for The Hungry International", 3793),
            param("Stichting Vluchteling", 3908),
            param("John Snow inc", 3964),
            param("A spécifier", 4049),
            param("Coopération italienne", 3601),
            param("S.G. Communications et Médias", 3807),
            param("Conseil Permanent de la Comptabilite au Congo", 3167),
            param("Province du Sud Kivu", 4200),
            param("Mercy Corps", 3501),
            param("Kredistanst FW", 3380),
            param("SNV Organisation Néerlandaise de Développement", 3754),
            param("S.G. Hydrocarbures", 3271),
            param("Staff Member", 4355),
            param("German Agro Action", 3764),
            param("Ambassade de France", 3286),
            param("Healthnet International", 3779),
            param("Investissement privé centrafricain", 4182),
            param("S.G. Energie", 3230),
            param("NGO-CRAFOD", 4000),
            param("Européenne à suprimer", 3562),
            param("International Federation of Red Cross and Red Crescent Societies", 3646),
            param("NGO-GOAL IRELAND", 3998),
            param("Compagnie Maritime du Congo", 3227),
            param("Conférence épiscopale", 3710),
            param("Centre Bethanie", 3797),
            param("ACGT/Agence Congolaise des Grands Travaux", 4194),
            param("Ambassade de Norvège", 3295),
            param("Norwegian Church Aid", 3504),
            param("Municipalité métropolitaine d'Istanbul", 3582),
            param("UN Office for Project Services", 3950),
            param("UNICEF Autres Ressources", 3917),
            param("S.G. Mines", 3189),
            param("Action pour Enfants Oubliés", 3537),
            param("PARLEMENT", 3264),
            param("Banque internationale pour la reconstruction et le développement", 3350),
            param("Province Nationale", 4211),
            param("AEDES", 3571),
            param("ASSOCIATION POUR LA SANTE FAMILIALE", 3428),
            param("GT4 Groupe gouvernance économique", 3665),
            param("Unité de Coordination des Projets", 3570),
            param("Association de Coopération et de Recherches pour le Développement", 3789),
            param("Association Régionale d'Approvisionnement en Médicaments Essentiels", 3567),
            param("Service National des Energies Nouvelles", 3249),
            param("World Hope International", 3965),
            param("A préciser", 4062),
            param("International Foundation for Education and Self-Help", 3478),
            param("Louvain Développement", 3488),
            param("CONCERN WORLD WIDE", 3450),
            param("S.G. Travail", 3208),
            param("GOVERNMENT OF ITALY", 3941),
            param("Development & training service", 3958),
            param("Ambassade d'Autriche", 3277),
            param("Office de Voiries et Drainage", 3236),
            param("Investissemement privé camerounais", 4188),
            param("DRC-National Execution", 3940),
            param("PNUD PAF - UNAIDS Fund 11940", 3392),
            param("PNUD cost sharing Gouv 30071", 3401),
            param("Interchurch Medical Assistance", 3795),
            param("Ambassade d'Afrique du Sud", 3275),
            param("Organisation des Nations Unies pour le développement industriel", 3322),
            param("Agence Américaine pour le Développement International", 3342),
            param("Global Environment Fund Truste", 3888),
            param("Ministère des Affaires Foncières", 3155),
            param("ACTED", 3415),
            param("Programme des Nations Unies pour les établissements humains", 3320),
            param("Pmu Interlife", 3513),
            param("ICCO", 3475),
            param("Management Science for health", 3726),
            param("MAC ARTHUR FOUNDATION", 3985),
            param("Office International d'Immigration", 4218),
            param("Coopération de Plantation et d'élevage de LUIZA", 3837),
            param("Ambassade d'Espagne", 3284),
            param("CATHOLIC ORGANIZATION FOR RELIEF AND DEVELOPEMENT AID", 3441),
            param("Coopération technique chinoise", 3848),
            param("Agence Nationale pour la Promotion des Investissements", 3923),
            param("Université de Kinshasa", 4378),
            param("Centre des Recherches d'Energie Nucléaire", 3196),
            param("Centre Intégré de Bwamanda", 3337),
            param("Première Urgence", 3514),
            param("PNUD Trac1.1.2", 4214),
            param("Ministères des Affaires Etrangères", 3634),
            param("Investissement privé gilbratar", 4174),
            param("OXFAM GB", 3990),
            param("Association pour le Développement Social et la Sauvegarde de l'Environnement", 3565),
            param("Agence Turque de développement", 3580),
            param("Deutsche Welthungerhilf e.v.", 3645),
            param("Fondation pour la Promotion Sociale de la Culture", 3697),
            param("GOVERNMENT OF UNITED KINGDOM", 3959),
            param("GOVERNMENT OF NORWAY", 3945),
            param("S.G. Infrastructures,Travaux Publics et Reconstruction", 3237),
            param("Programme national de lutte contre le SIDA", 3865),
            param("Ministère des Relations avec le Parlement", 3733),
            param("Université Catholique de Kinshasa", 4041),
            param("S.G. Enseignement Supérieur et Universitaire", 3193),
            param("Investissement privé sud coréen", 3625),
            param("Medical Care Development International", 4297),
            param("ERAIFT", 3874),
            param("IBRD(Emergency response to cassava mosaic outbr)", 4169),
            param("Franziskaner", 3921),
            param("Institut National de Recherche Biologique", 4382),
            param("Investissement privé pakistanais", 4180),
            param("Programme National d'Assainissement", 3365),
            param("RESULT BASED MANAGEMENT GROUP (a division of 3186687 canada inc)", 3994),
            param("Ministère des Finances", 3207),
            param("Coopération Technique Belge", 1),
            param("S.G. Intégration régionale", 3181),
            param("Investissement privé guernesey", 4183),
            param("Institut des Jardins Zoologique et Botanique du Congo", 3366),
            param("Office des Petites et Moyennes Entreprises", 3371),
            param("Facilité des Etats Fragiles", 3899),
            param("NOVIB-OXFAM", 3574),
            param("International Committee of the Red Cross", 3647),
            param("UN CENTRE FOR HUMAN SETTLEMENT", 3929),
            param("Action Médicale Missionnaire Belgique", 3778),
            param("Ministère des Hydrocarbures", 3234),
            param("Internationaal Comité Rode Kruis (niet-Belgische afdeling) - ICRC/CICR - PRT", 4136),
            param("Solidarité Protestante", 3718),
            param("International Polio Virus Response", 3743),
            param("Forum Syd", 3589),
            param("S.G. Postes, Téléphones et Télécommunications", 3202),
            param("Investissement privé français", 3616),
            param("AIR SERV INTERNATIONALE", 3424),
            param("Oxfam-Grande-Bretagne", 3506),
            param("Comite International de RESCATE", 3699),
            param("Handicap International- Belgique", 3470),
            param("Agence Canadienne de Développement International", 3280),
            param("Direction Générale des Impôts", 3164),
            param("CESADEMA ONG/ASBL", 4009),
            param("Groupe Consultation CCISD et MIR ", 4030),
            param("Ministère du Plan", 3267),
            param("S.G. Portefeuille", 3184),
            param("Fondation Konrad Adenauer", 3904),
            param("Investissemement privé libanais", 3621),
            param("GT16 Education et Recherche Scientifique", 3671),
            param("DIAKONIA", 3819),
            param("VETERINAIRES SANS FRONTIERES", 4032),
            param("CARITAS", 3437),
            param("Fonds des Nations Unies pour l'enfance", 3304),
            param("Université Pédagogique Nationale ", 4381),
            param("Organisation pour l'Equipement Banana - Kinshasa", 3216),
            param("AUCC", 3689),
            param("Global Witness", 4038),
            param("Soeurs de Sainte Marie de Matadi", 3695),
            param("S.G. Sports et Loisirs", 3377),
            param("Ministère de la Jeunesse et Sports", 3255),
            param("Air Services", 3982),
            param("Dokters van de Wereld", 4106),
            param("Office d'aide humanitaire de la Commission européenne", 3559),
            param("Forum Sociale Deutsch-Land KONGO e.v", 3766),
            param("Action de carême", 3909),
            param("MEMISA BELGIQUE", 4002),
            param("UNICEF Fonds des Nations Unies pour l'Enfance", 3577),
            param("Lignes budgétaires Commission Européenne", 3584),
            param("Direction du Développement et de la Coopération Suisse", 12),
            param("Ambassade de la République de Corée", 3583),
            param("Agence de Coopération Internationale Japonaise", 3347),
            param("Ministère de la Fonction Publique", 3213),
            param("Lignes Aériennes Congolaises", 3223),
            param("Comité Provincial Equateur", 3143),
            param("Life and Peace Institute", 3486),
            param("Ministère des Affaires Etrangères d'Australie", 3644),
            param("Service Congolais des Postes et Télécommunications", 3203),
            param("Unité de coordination et de gestion du projet", 3846),
            param("Ministère de Culture et Arts", 3178),
            param("Ministère de la Justice", 3735),
            param("The Global Alliance for Vaccination and Immunisation(GAVI)", 4221),
            param("ONUSIDA/Programme des Nations Unies sur le VIH/SIDA", 3311),
            param("Bureau Central de Coordination", 3169),
            param("Investissement privé émiratie", 4173),
            param("IITA", 3796),
            param("Province du Kasai Oriental", 4204),
            param("S.G. Affaires Intérieures,Décentralisation et Sécurité", 3141),
            param("Service National des Reboisements", 3881),
            param("Fonds des Nations Unies pour la démocratie", 3319),
            param("Organisation des Nations Unies pour la science et l'éducation", 3313),
            param("PNUD EEC DRC Elections 36204", 3403),
            param("Fondacion Internacional de Solidaridad Compania de Maria", 3694),
            param("S.G. Jeunesse", 3376),
            param("LUTHERIAN WORLD FEDERATION", 3979),
            param("Ministère de la Coopération Internationale et Régionale", 3153),
            param("TRIAS VZW", 3524),
            param("NGO - WORLD VISION", 3996),
            param("LO-TCO Bistandasnämnd", 3588),
            param("Régie des Voies Fluviales", 3219),
            param("Ministère de l'Urbanisme et Habitat", 3375),
            param("Ambassade du Japon", 3291),
            param("Investissement privé sénégalais", 3623),
            param("Investissement privé ghanéen", 4184),
            param("Ministère de l'Environnement,Conservation de la Nature et Tourisme", 3204),
            param("Province du Kasai Occidental", 4203),
            param("S.G. E.P.S.P.", 3261),
            param("Fondantion pour le Développement des Capacités en Afrique", 3592),
            param("S.G. Prévoyance Sociale", 3210),
            param("SOLIDARITE", 3969),
            param("Human Rights Watch", 3474),
            param("GOVERNMENT OF FRANCE", 3937),
            param("GLOBAL FUND TO FIGHT AIDS", 4004),
            param("Carter Center", 3728),
            param("DEPARTMENT FOR INT'L DEVELOPME", 4036),
            param("Journal Transaction", 4346),
            param("Organisation mondiale du commerce", 3324),
            param("Institut Géographique du Congo", 3197),
            param("Safe Blood for Africa Foundation", 3746),
            param("GOVERNMENT OF SWEDEN", 3955),
            param("Katholiek Beurzenfonds voor Afrikanen", 4100),
            param("NORWEGIAN REFUGEE COUNCIL", 3972),
            param("S.G. Développement Rural", 3251),
            param("World Vision", 3740),
            param("S.G. Affaires Sociales", 3177),
            param("Association Provinciale pour l'Approvisionnement enMédicaments Essentiels au Sud-Kivu", 3566),
            param("Tetra Technic DPK", 3974),
            param("Association internationale de développement (Banque mondiale)", 3351),
            param("Action Damien", 3879),
            param("Medicus Mundi Navarra", 3500),
            param("FOMETRO", 3724),
            param("COOPERAZIONE E SVILUPPO", 3451),
            param("Office des Routes (OR)", 3239),
            param("Province de Bandundu", 4207),
            param("CIAT - International Center for Tropical Agriculture - CGIAR - PRT", 4126),
            param("World Wide Fund for Nature", 3532),
            param("Vredeseilanden", 3721),
            param("Internationale Medische Samenwerking (ex AZV_MSV Artsen Zonder Vakantie)", 4098),
            param("Haut Commissariat des Nations Unies pour les Refugiés", 3305),
            param("PNUD EEC Sécurité 36207", 3405),
            param("Johanniter International Assistance", 3483)));
        
        category("funding_status_id", Arrays.asList(
            param("No request", 174),
            param("No information", 173),
            param("Partially acquired", 177),
            param("Negotiating", 176),
            param("Totally acquired", 178),
            param("Request sent, no answer", 175)));
        category("agreement_id", Arrays.asList());
        category("recipient_role", Arrays.asList(
            param("Related Institution", 6),
            param("Regional Group", 12),
            param("Responsible Organization", 13),
            param("Donor", 1),
            param("Implementing Agency", 2),
            param("Beneficiary Agency", 5),
            param("Executing Agency", 4),
            param("Reporting Agency", 3),
            param("Sector Group", 11),
            param("Monitoring Agency", 7),
            param("Contracting Agency", 8)));
        category("pledge_id", Arrays.asList());
        category("mode_of_payment_id", Arrays.asList(
            param("Direct Funding", 189),
            param("Money is disbursed directly to the implementing institution and managed through a separate bank account", 288),
            param("Reimbursable", 190),
            param("Direct Payment", 188)));
        category("terms_assist_id", Arrays.asList());
        category("source_role", Arrays.asList(
            param("Related Institution", 6),
            param("Regional Group", 12),
            param("Responsible Organization", 13),
            param("Donor", 1),
            param("Implementing Agency", 2),
            param("Beneficiary Agency", 5),
            param("Executing Agency", 4),
            param("Reporting Agency", 3),
            param("Sector Group", 11),
            param("Monitoring Agency", 7),
            param("Contracting Agency", 8)));
        category("adjustment_type", Arrays.asList(
            param("Actual", 272),
            param("Planned", 271),
            param("Pipeline", 273)));
        category("recipient_org", Arrays.asList(
            param("S.G. Anciens Combattants", 3257),
            param("Investissement privé swazilandais", 3626),
            param("Fonds Forestiers pour le Bassin du Congo", 3897),
            param("MINES ADVISORY GROUP", 3971),
            param("International Rescue Committee", 3334),
            param("Bandundu", 3916),
            param("Ministère de la Santé Publique", 3369),
            param("Innovative Recourses Management", 3780),
            param("University of Guelph", 3903),
            param("S.G. Urbanisme et Habitat", 3154),
            param("Heal Africa", 3472),
            param("Goal Ireland", 3467),
            param("Comité Provincial Bandundu", 3152),
            param("Ministère des Affaires Etrangères", 3182),
            param("Atlas Logistique", 3776),
            param("Médécin Sans Frontière", 3651),
            param("11.11.11", 3783),
            param("Malteser International", 3490),
            param("Vlaams Internationaal Centrum", 4105),
            param("Investissement privé mauricien", 3629),
            param("Care Canada", 3680),
            param("GOVERNMENT OF SWITZERLAND", 3956),
            param("Search For Common Ground", 3517),
            param("IFPRODUCTIONS", 3905),
            param("POPULATION MEDIA CENTER", 3436),
            param("ACCC", 3687),
            param("Association des Rotary clubs belges pour la coopération au développement", 4096),
            param("CANADIAN INTERNATIONAL DEVELOP", 4035),
            param("S.G. Condition Féminine et Famille", 3200),
            param("FOLECO", 3864),
            param("DGD", 4129),
            param("AIDE MEDICALE INTERNATIONALE", 3423),
            param("Groupe d'Etude de Transports", 3215),
            param("Comité pour le Développement de l'Afrique Australe", 3332),
            param("Agence Française de Développement", 3343),
            param("Banque Africaine de Développement", 3381),
            param("Conférence des Nations Unies sur le commerce et le développement", 3603),
            param("Investissement privé italien", 3620),
            param("African Wildlife Foudation", 3801),
            param("Ministère des Affaires Etrangères Allemande", 3893),
            param("Commission épiscopale", 3912),
            param("Commission Européenne", 3328),
            param("Cellule d'appui à l'Ordonnateur  Fonds Européen pour le Développement", 3344),
            param("Solidarité aide humanitaire d'urgence", 3519),
            param("CEBA", 3678),
            param("The National Democratic Institute for International Affairs", 3523),
            param("COD-PROGRAMME PROMOTION SOINS", 3973),
            param("RENAPI", 3269),
            param("BD", 3784),
            param("UN Dept of Economic and Social", 3947),
            param("Office National des Transports du Congo", 3225),
            param("Volontaires des Nations Unies (admin PNUD)", 3604),
            param("PRESIDENCE DE LA REPUBLIQUE", 3358),
            param("Action Aid International DRC", 4026),
            param("Université de Bercelona", 3703),
            param("CARITAS INTERNATIONALIS", 3439),
            param("S.G. Senat", 3361),
            param("CIF Santé", 3704),
            param("Investissement privé canadien", 3613),
            param("COLLABORATION SANTE INTERNATIONAL", 3966),
            param("Frères des Hommes", 4104),
            param("Province du Nord Kivu", 4198),
            param("Fonds mondial malaria (à supprimer)", 4216),
            param("SLCD", 3782),
            param("Adventist Develop&amp;Relief Agenc", 3960),
            param("Service National", 4374),
            param("Pooled Fund Humanitaire", 3416),
            param("Fundation IEPALA", 3698),
            param("Ambassade de Turquie", 3581),
            param("S.G. Petites et Moyennes Entreprises", 3370),
            param("UNITED NATIONS VOLUNTEERS", 3926),
            param("Vision Environnement et Développement Communautaire", 3527),
            param("Département des opérations de maintien de la paix", 3605),
            param("Komyuniti cons", 3713),
            param("Institut Saint Joseph", 4014),
            param("Direction Générale  des Douanes et Assises", 3163),
            param("Comité Pilote de Réforme des Entreprises Publiques", 3591),
            param("Multi Action d' Assistances au", 4012),
            param("Medical Emergency Relief International", 3498),
            param("CREDES", 3572),
            param("Education Développement Center, Inc", 3757),
            param("S.G. Affaires Foncières", 3187),
            param("PNUD TRAC1.1.1 ", 3385),
            param("Ministère des Affaires Etrangères de Danmark", 3639),
            param("Research Triangle Institute", 4040),
            param("Renatelsat", 3245),
            param("Itineras cons", 3725),
            param("AGRO ACTION ALLEMANDE", 3422),
            param("Jesuit Refugee Service", 3978),
            param("International Labour Organisat", 3933),
            param("NGO-FONDATION FEMMES PLUS", 3999),
            param("S.G. Plan", 3205),
            param("SHC", 3717),
            param("S.G. Défense Nationale", 3256),
            param("Université de Lubumbashi", 4379),
            param("Ministère de l'Economie Nationale et Commerce", 3186),
            param("Investissement privé luxembourgois", 4177),
            param("Ambassade d'Italie", 3290),
            param("Ambassade d'Allemagne", 3276),
            param("Oxfam-Solidarité Belgique", 3508),
            param("CHAKA (ADG Gembloux - CODEART - ISF) - CHAKA", 4094),
            param("Vereniging voor Technische Samenwerking - TRIAS", 4099),
            param("Université Protestante du Congo", 3992),
            param("Commission Episcopale Nationale Congolaise", 4377),
            param("PNUD country co financing CS 11888", 3391),
            param("Various", 3738),
            param("Investissemnt privé béninois", 3611),
            param("Ministère de l'Industrie", 3240),
            param("Avocats sans frontières", 3763),
            param("Fonds Mondial", 4223),
            param("UN INDUSTRIAL DEVELOPMENT ORGA", 3928),
            param("MEDAIR", 3573),
            param("Msaada et Solidarité Internationale pour la Promotiondes Energies Renouvelables dans le tiers Monde", 3814),
            param("Réfugiés politiques", 4056),
            param("CARITAS DEVELOPPEMENT", 3440),
            param("Investissement privé belge", 3610),
            param("PNUD Programme Cost Sharing 30000", 3397),
            param("Development alternatives incorporated", 3983),
            param("Ministère des Affaires Etrangères d'Irlande", 3636),
            param("International Trade Centre", 3936),
            param("Ambassade des Pays-Bas", 3296),
            param("S.G. Industrie", 3372),
            param("Ministère de la Défense Nationale et Anciens Combattants", 3183),
            param("Enfance Tiers Monde", 3712),
            param("Investissement privé néerlandais", 4185),
            param("Matres Mundi", 3657),
            param("UNDP", 3948),
            param("S.G. Finances", 3162),
            param("Careas", 3787),
            param("GOVERNMENT OF JAPAN", 3942),
            param("Inspection Générale des Finances", 3166),
            param("Catholic Relief Services", 3442),
            param("Bureau de Coordination des Marchés des Infrastructures", 3413),
            param("Fonds d'équipement des Nations Unies (admin PNUD)", 3321),
            param("Comité Provincial Kinshasa", 3147),
            param("Investissement privé ukrainien", 4179),
            param("Agence Norvégienne de Développement", 10),
            param("ALBOAN", 3705),
            param("SOS Faim", 3719),
            param("Eximbank of India", 3594),
            param("Fonds monétaire international", 3325),
            param("Johanniter", 3920),
            param("Medecins du Monde-Belgique", 3491),
            param("SPAIN MDG FUND", 4044),
            param("S.G. Environnement et Conservation de la Nature", 3364),
            param("Unité d'Exécution du Programme National de Désarmement, Démobilisation et Réinsertion", 3866),
            param("Comité Provincial Nord-Kivu", 3149),
            param("Cabinet du Premier Ministre", 3159),
            param("OXFAM", 3336),
            param("Fonds Africain de Développement", 3357),
            param("University, college or other teaching institution, research institute or think-tank", 4369),
            param("Cooperazione Intermazionale", 3957),
            param("Associazione Volntarin Per  Il Servizio Internazionale", 3430),
            param("WSM", 3722),
            param("Tearfund", 3521),
            param("SFI/Société financière internationale", 3349),
            param("Canadian Catholic Organization for Development and Peace", 3558),
            param("Ministère des Affaires Etrangères de Pologne", 3914),
            param("Handicap International/Atlas Logistique", 3471),
            param("Programme International de Conservation des Gorilles", 3515),
            param("Ministère des Infrastructures,Travaux Publics et Reconstruction", 3246),
            param("Direction des Voies de Desserte Agricole", 3247),
            param("University of North Carolina", 4005),
            param("Action Bio", 4091),
            param("Vrijwilligers voor het Onderwijs - VRIJOND", 4114),
            param("PRIMATURE", 3363),
            param("RCN Justice&Démocratie", 3516),
            param("Institut National de Préparation Professionnelle", 3212),
            param("Organisation internationale du travail", 3308),
            param("Bureau d'Etudes d'Aménagement et 'Urbanisme", 3238),
            param("Trust Found (Banque Mondiale)", 4193),
            param("Ministère du Budget", 3172),
            param("Croix Rouge Belge", 3709),
            param("Mission  des Nations Unies pour la Stabilisation et Consolidation de la paix", 3314),
            param("Le Centre Carter", 3906),
            param("Institut National d'Etudes et des Recherches Agronomiques", 3195),
            param("Finlande", 3637),
            param("KOREA INTERNATIONAL VOLUNTEER ORGANIZATION", 4078),
            param("Consortuin CCICD-CHUM", 3931),
            param("EQUILIBRE", 4006),
            param("S.G. Justice", 3266),
            param("Chancellerie des Ordres Nationaux", 4375),
            param("S.G. Santé", 3374),
            param("UNEP", 3691),
            param("CCISD/USI", 3989),
            param("Ambassade de Belgique", 3278),
            param("Population Service International", 3745),
            param("Investissement privé nigérian", 4181),
            param("Programme National Mutlisectoriel de Lutte contre le SIDA", 3855),
            param("Institut National de Statistiques", 3922),
            param("Ambassade des Etats-Unis d'Amérique", 3285),
            param("VZW / civ.mij  : onbepaald", 4095),
            param("COD-Conseil National des ONGs", 3962),
            param("INTERACTIONS", 4017),
            param("Bureau des Nations Unies pour les services d'Appui aux Projets", 3315),
            param("United Nations Mine Action Service", 3690),
            param("Commission Electorale Indépendante", 3686),
            param("War Child Canada", 4013),
            param("United Nations Children’s Fund", 4364),
            param("GOVERNMENT OF NETHERLANDS", 3944),
            param("Programme des Nations Unies pour le Développement", 3302),
            param("Investissement privé togolais", 3627),
            param("Investissement privé hellenique", 4178),
            param("Jane Goodall Institute for Wildlife Research, Education and Conservation", 3988),
            param("Action pour le Développement et la Paix Endogènes", 3541),
            param("Agence espagnole de coopération internationale et développement", 3915),
            param("Action contre la faim USA", 3335),
            param("MONTREAL PROTOCOL", 4039),
            param("S.G. Commerce Extérieur", 3174),
            param("Cellule d'exécution des projets-Eau", 3918),
            param("CARITAS INTERNATIONAL-BELGIQUE", 3438),
            param("Port de Bruxelles", 3715),
            param("Asociacion Ayuda a Los Desempleados Del Tercer Mundo", 3702),
            param("Ministère du Genre,Famille et Enfant", 3229),
            param("Ministère du Portefeuille", 3270),
            param("The mines advisory group", 3907),
            param("Kinderen Derde Wereld - KDW/ETM", 4107),
            param("S.G. Assemblée Nationale", 3359),
            param("COOPERA", 3655),
            param("SERVICE D' APPUI AU DEVELOPPME", 4011),
            param("Ambassade de l'Inde", 3288),
            param("ORG. INTERNATIONALE DE LA FRAN", 4043),
            param("Medecins du Monde -France", 3492),
            param("Ministère des Affaires Etrangères d'Albanie", 3884),
            param("Direction de Gestion de la Dette Publique", 3171),
            param("Bureau de coordination des affaires humanitaires des Nations Unies", 3312),
            param("World Vision Canada", 3688),
            param("Agence Coréenne de Coopération Internationale", 3882),
            param("Fonds Social de la République Démocratique du Congo", 3327),
            param("Georgetown Unversity", 3748),
            param("Engender heath", 4025),
            param("Population Services International", 4352),
            param("DOCTORS ON CALL FOR SERVICE", 3456),
            param("Investissement privé américain", 3608),
            param("Armée du Salut", 3800),
            param("Protos", 3802),
            param("Pouvoir Judiciaire", 4376),
            param("COD-GROUP ETUDE ACTION DEVELOP", 4008),
            param("Danchurchaid", 3648),
            param("GOVERNMENT OF LUXEMBOURG", 3943),
            param("CROIX ROUGE BELGIQUE", 4031),
            param("Pesonnes âgées", 4054),
            param("CENTRES SOCIAUX SANITAIRES -CONGO", 3444),
            param("GOVERNMENT OF BELGIUM", 3932),
            param("Investissement privé bahaméen", 4176),
            param("Commission justice et paix belge", 3708),
            param("Paul Carlson Partnership", 4167),
            param("Koninklijk Museum voor Midden-Afrika in Tervuren", 4102),
            param("Ambassade de Royaume Uni", 3649),
            param("UNITED NATIONS DEVELOPMENT PRO", 3927),
            param("Ministère de la Recherche Scientifique", 3729),
            param("Save the Children UK", 3333),
            param("Fonds Mondial HIV/SIDA (à supprimer)", 3402),
            param("NGO Solidarité Socialiste - FCD", 3723),
            param("Cellule infrastructure", 3844),
            param("COMITATO INTERNAZIONALE PER DE SVILUPPO DEI POPULI", 3448),
            param("GROUPE ONE", 4116),
            param("Ministère du Développement Rural", 3732),
            param("Organisation Internationale pour les Migrations", 3593),
            param("Don Bosco", 3701),
            param("Bureau local RDC", 3845),
            param("Ministère de l'Energie", 3192),
            param("AIDES", 3544),
            param("Province de Kinshasa", 4197),
            param("Investssement privé autrichien", 3609),
            param("Régie de Distribution d'Eau", 3231),
            param("Commission d' Encadrement pour", 4022),
            param("Ministère des Droits Humains", 3260),
            param("Ambassade de Suède", 3660),
            param("Association pour la Protection", 4016),
            param("001981", 4045),
            param("Cellule d'Exécution des Projets PMR RH", 4190),
            param("Investissement privé congolais", 3630),
            param("Ambassade du Canada", 3677),
            param("Coopération Technique Suisse", 3913),
            param("Congolaise des Hydrocarbures", 3273),
            param("Organisation de Cooperation etde Développement Economique", 3986),
            param("Education", 3378),
            param("Avenir Congo", 4092),
            param("Central Emergency Reponse Fund (CERF)", 3854),
            param("ANES-Congo", 3871),
            param("PNUD Cost Sharing WB1 30011", 3398),
            param("UNCODED", 3727),
            param("Ministère des Affaires Etrangères Luxembourg", 3643),
            param("S.G. Agriculture, Pêche et Elevage", 3250),
            param("Ministère des Affaires Etrangères de Finlande", 3638),
            param("Province du Katanga", 4205),
            param("Entraide prot. Suisse", 3910),
            param("UNAIDS", 3984),
            param("CHRISTIAN AID", 3445),
            param("Groupe de Recherche et d'Echanges Technologiques", 3468),
            param("Ambassade de Russie", 4191),
            param("Programme alimentaire mondial", 3303),
            param("Joint United Nations Programme on HIV/AIDS", 4345),
            param("Vlaamse Interuniversitaire Raad", 3987),
            param("Investissement privé gambien", 3617),
            param("Véterinaire Sans Frontières", 3653),
            param("UNICEF Fonds d'urgence", 3578),
            param("APEFE - Association pour la Promotion de l'Education et de la Formation à l'Etranger - APEFE", 4120),
            param("Administration centrale", 4208),
            param("Ministère des Mines", 3262),
            param("Ministère des Affaires Etrangères de la République Tchèque", 3641),
            param("Search Common Ground", 3747),
            param("BUREAU INTERNATIONAL CATHOLIQUE POUR L'ENFANCE", 3435),
            param("FOODS FOR HUNGRY INTERNATIONAL", 3970),
            param("S.G. Coopération Internationale", 3180),
            param("Caritas  Uvira", 4034),
            param("New York University", 4021),
            param("BROEDERLIJK DELEN", 3818),
            param("Investissement privé turque", 4175),
            param("South-East Consortiun for International Développement", 3761),
            param("SECID", 3741),
            param("Action Agro Allemande", 3993),
            param("GT8 Groupe agriculture et développement rural", 3669),
            param("Unité de Coordinnation du Projet/PARSE", 4196),
            param("Organisation des Nations Unies", 3301),
            param("OCCDP", 3685),
            param("Non-Governmental Organisations (NGOs) and Civil Society", 4349),
            param("Japan International Cooperation System", 4165),
            param("NGO-Org Catholique d'Aide et d", 4001),
            param("Radio Télévision Nationale Congolaise", 3243),
            param("Cabinet du Président de la République", 3263),
            param("Pact Building Capacity Worldwide", 3509),
            param("S.G. Economie", 3173),
            param("Avenir Meilleur pour les Orphelins du Congo", 3568),
            param("MEDICUS MUNDI BIZKAIA", 3756),
            param("Haute Autorité des Médias", 3241),
            param("Chemin de Fer des Uélés", 3222),
            param("Center for Disease Control And Prevention", 3894),
            param("S.G. Budget", 3268),
            param("World Food Programme", 3951),
            param("Intrenational  Resources Group lt", 4168),
            param("Winrock international", 3954),
            param("Action Contre la Pauvrete", 4018),
            param("Ministère de l'Enseignement Supérieur et Universitaire", 3201),
            param("UICN", 3692),
            param("Ministère de l'Agriculture", 3160),
            param("Ministère des Affaires Entragères", 3161),
            param("Commission Nationale de Prévention Routière", 3224),
            param("Mission de police de l'Union européenne à Kinshasa", 3595),
            param("Ministère des Petites et Moyennnes Entreprises", 3730),
            param("S.G. Recherche Scientifique", 3194),
            param("Ministère des Affaires Etrangères,Commerce et Développement ", 4383),
            param("Collaboration Santé Internationale", 4015),
            param("Ministère de l'Enseignement Primaire,Secondaire et Professionnel", 3199),
            param("Institut National de Sécurité Sociale", 3209),
            param("Commission Internationale du Bassin Congo-Oubangi-Sangha", 3707),
            param("Unité Nationale de Coordination de Projet", 4210),
            param("Petits Pas", 4109),
            param("Ambassade du Brésil", 3279),
            param("Investissemement privé tanzanien", 4189),
            param("Bureau Diocesain des Oeuvres Médicales", 3785),
            param("Régie des Voies Maritimes", 3220),
            param("Groupe contre les mines", 3502),
            param("S.G. Transports et voies de communication", 3214),
            param("Missionnaires Claretiennes", 3696),
            param("Abt Associates", 3822),
            param("SOS Kinderdorp - België help de wereld", 4103),
            param("Department for International Development", 3),
            param("Police Nationale Congolaise", 4186),
            param("Unité de Coordinnation du Projet/PARSS", 4195),
            param("Investissement privé britanique", 3612),
            param("Comité Provincial Sud-Kivu", 3151),
            param("Fonds International pour le Développement Agricole", 3382),
            param("Investissement privé israëlien", 3619),
            param("Banque Centrale du Congo", 3170),
            param("Investissement privé allemand", 3615),
            param("Ministère de Coopération Economique et du Développement", 3892),
            param("Ambassade de Chine", 3281),
            param("CDI BWAMANDA", 3877),
            param("Ministère des Affaires Sociales,Action Humanitaire et Solidarité Nationale", 3158),
            param("Global rights", 3466),
            param("Investissement privé chinois", 3614),
            param("Direction Générale de la Coopération au Développement Belge", 2),
            param("Organization Navarra de Ayuda entre los Pueblos", 3693),
            param("International Centre for Transitional Justice", 4137),
            param("UniverSud Liège (ex-ACDLg/ACDST)", 4101),
            param("Unité de Coordinnation du Projet PFCN", 4192),
            param("Groupe de Recherche et d'action sur le développement durable et le développement économique durable", 3469),
            param("COD-Bureua Diocesain de Develo", 3991),
            param("Union Africaine", 4209),
            param("Direction Générale des Recettes Administratives et Domaniales", 3165),
            param("Ministère de l'Intérieur et Sécurité", 3253),
            param("Africa Parks", 3706),
            param("Province Administration Centrale", 4224),
            param("Norwegian Refugee Council", 3505),
            param("Trias", 3720),
            param("Province Orientale", 4202),
            param("UN DEMOCRACY FUND (UNDEF)", 4042),
            param("CENTRE SCIENTIFIQUE ET MEDICAL DE L'UNIVERSITE LIBRE DE BRUXELLES POUR SES ACTIVITES DE COOPERATION", 3443),
            param("ACTION CONTRE LA FAIM", 3976),
            param("Société Nationale d'Electricité", 3232),
            param("Avocats Sans Frontières Belgique", 3794),
            param("UN Development Programme", 3952),
            param("Agence Congolaise de Presse", 3244),
            param("Fonds des Nations Unies pour la population", 3310),
            param("Université de Kisangani", 4380),
            param("Fonds de Développement des Nations Unies pour la femme", 3316),
            param("Commission Electorale Nationale  Indépendante", 3362),
            param("Widelife Conservation Society", 3529),
            param("Caritas allemagne", 3891),
            param("Investissement privé indien", 3618),
            param("Banque Européenne d'Investissement", 9),
            param("Association de Sante Familiale", 3963),
            param("Ministère de la Communication et Médias", 3242),
            param("Federacion de Asociaciones Meddicus Mundi en Espagne", 3700),
            param("Investissement privé portugais", 3622),
            param("Oxfam-Quebec", 3507),
            param("Aviation sans frontière Française", 3434),
            param("Association africaine de défense des Droits de l'Homme ", 4028),
            param("Organisation mondiale de la santé", 3307),
            param("Deutsche Gesellschaft Technische Zusammenarbeit", 3454),
            param("MALTESER", 3968),
            param("Office National du Tourisme", 3368),
            param("Agence Européenne pour le Développement", 3421),
            param("Ambassade de Suisse", 3299),
            param("Other.", 4350),
            param("Cellule pour la Décentralisation", 3851),
            param("Méteorologie et Télecommunication par Satellite", 3228),
            param("FEDECAME", 3575),
            param("AFRICA CONSERVATION FUND", 3419),
            param("Investissement privé zambien", 3628),
            param("World Vision International", 3531),
            param("PMU InterLife", 3587),
            param("OXFAM SOLIDARITES BELGIQUE", 4010),
            param("Damiaanactie", 3711),
            param("Internews Network", 3798),
            param("GT5 Groupe infrastructures et transport", 3666),
            param("Solidarité Socialiste", 3774),
            param("Action contre la pauvreté", 3534),
            param("Terre sans Frontière", 3682),
            param("Mission de conseil et d’assistance en matière de réforme du secteur de la sécurité en RDC", 3596),
            param("Centre Congolais de Culture , de Formation et de Développement", 3659),
            param("NGO-DAN CHURCH AID", 3997),
            param("S.G. Affaires Humanitaires", 3176),
            param("EUROPEAN UNION", 3967),
            param("Province de l'Equateur", 4201),
            param("United Nations agency, fund or commission (UN)", 4363),
            param("Action pour la Paix, l'éducation et le Développement", 3538),
            param("S.G. Cour des Comptes", 3360),
            param("Woman for women International", 3530),
            param("Medecins sans Frontières-France", 3495),
            param("Conseil Interuniversitaire de la Communauté française de Belgique", 4128),
            param("Régie des Voies Aériennes", 3218),
            param("Fonds Médical Tropical", 3463),
            param("Ministère de la Décentralisation et Aménagement du Territoire", 3731),
            param("ICRAF International Council for Research in Agro-Forestry - CGIAR - PRT", 4133),
            param("Ministère des Postes, Téléphones et Télécommunications", 3274),
            param("Program for Apporpriate Technology in Health (PATH)", 4170),
            param("World Health Organisation", 3739),
            param("Province du Bas-Congo", 4199),
            param("GTM-FUNDACION SOLAR", 4007),
            param("GOVERNMENT OF SPAIN", 3953),
            param("DRC - CARJTAS MANIEMA", 4003),
            param("Province de Maniema", 4206),
            param("Comité International de la Croix Rouge", 3633),
            param("Rotary Belgique", 3716),
            param("Aviation sans frontière Belgique", 3433),
            param("Action contre la faim", 3803),
            param("Action pour le Bien-Etre Commun", 4019),
            param("Société Nationale des Chemins de Fer du Congo", 3217),
            param("Missionnaires du Divin Maitre", 3995),
            param("Fonds mondial tuberculose (à supprimer)", 4217),
            param("Third Country Government (Delegated co-operation)", 4359),
            param("Medecins sans Frontières-Belgique", 3493),
            param("CRC Sogema", 3975),
            param("Diakonie", 3348),
            param("EQUILIBRE DE L'AIDE D'URGENCE AU DEVELOPPEMENT COMMUNAUTAIRE", 3458),
            param("Ministère de l'Emploi,Travail et Prévoyance Sociale", 3188),
            param("Ministère des Affaires Etrangères de la Grèce", 3640),
            param("Institut Congolais pour la Conservation de la Nature", 3856),
            param("Ministère des Affaires Entragères Thailandaise", 3853),
            param("Comité Provincial Oriental", 3150),
            param("Fundacion Albihar", 3658),
            param("Electoral Institule of Southeren Africa", 3772),
            param("Haut Commissariat des Nations Unies pour les droits humains", 3317),
            param("Norway Red Cross", 3453),
            param("Organisation des Nations Unies pour l'alimentation et l'agriculture", 3306),
            param("Investissement privé sud africain", 3624),
            param("Agence d'aide à la Coopération Tecnhique et au Développement", 3749),
            param("Caritate Aegrorum Servi", 4112),
            param("PAGE", 3744),
            param("Ministère des Transports et Voies de Communication", 3373),
            param("Intenational Org for Migration", 3935),
            param("Service National d'Hydraulique Rurale", 3248),
            param("Family Health International", 3459),
            param("Caritas Allemagne", 4023),
            param("Lutheran World Federation", 3489),
            param("TEARFUNND", 4027),
            param("Service Laïque de Coopération au Développement", 4147),
            param("Accompagnement Technique pour", 4024),
            param("Ecole Nationale des Finances", 3168),
            param("VZW CAP SANTE", 4160),
            param("Norwegian Chruch Aid", 3980),
            param("Commission Diocesaine Justice", 4020),
            param("Ministère des Affaires Etrangères de la Norvège", 3635),
            param("Agence Suèdoise Internationale de Développement (ASDI)", 3867),
            param("ACDLg", 3576),
            param("Food for The Hungry International", 3793),
            param("Stichting Vluchteling", 3908),
            param("John Snow inc", 3964),
            param("A spécifier", 4049),
            param("Coopération italienne", 3601),
            param("S.G. Communications et Médias", 3807),
            param("Conseil Permanent de la Comptabilite au Congo", 3167),
            param("Province du Sud Kivu", 4200),
            param("Mercy Corps", 3501),
            param("Kredistanst FW", 3380),
            param("SNV Organisation Néerlandaise de Développement", 3754),
            param("S.G. Hydrocarbures", 3271),
            param("Staff Member", 4355),
            param("German Agro Action", 3764),
            param("Ambassade de France", 3286),
            param("Healthnet International", 3779),
            param("Investissement privé centrafricain", 4182),
            param("S.G. Energie", 3230),
            param("NGO-CRAFOD", 4000),
            param("Européenne à suprimer", 3562),
            param("International Federation of Red Cross and Red Crescent Societies", 3646),
            param("NGO-GOAL IRELAND", 3998),
            param("Compagnie Maritime du Congo", 3227),
            param("Conférence épiscopale", 3710),
            param("Centre Bethanie", 3797),
            param("ACGT/Agence Congolaise des Grands Travaux", 4194),
            param("Ambassade de Norvège", 3295),
            param("Norwegian Church Aid", 3504),
            param("Municipalité métropolitaine d'Istanbul", 3582),
            param("UN Office for Project Services", 3950),
            param("UNICEF Autres Ressources", 3917),
            param("S.G. Mines", 3189),
            param("Action pour Enfants Oubliés", 3537),
            param("PARLEMENT", 3264),
            param("Banque internationale pour la reconstruction et le développement", 3350),
            param("Province Nationale", 4211),
            param("AEDES", 3571),
            param("ASSOCIATION POUR LA SANTE FAMILIALE", 3428),
            param("GT4 Groupe gouvernance économique", 3665),
            param("Unité de Coordination des Projets", 3570),
            param("Association de Coopération et de Recherches pour le Développement", 3789),
            param("Association Régionale d'Approvisionnement en Médicaments Essentiels", 3567),
            param("Service National des Energies Nouvelles", 3249),
            param("World Hope International", 3965),
            param("A préciser", 4062),
            param("International Foundation for Education and Self-Help", 3478),
            param("Louvain Développement", 3488),
            param("CONCERN WORLD WIDE", 3450),
            param("S.G. Travail", 3208),
            param("GOVERNMENT OF ITALY", 3941),
            param("Development & training service", 3958),
            param("Ambassade d'Autriche", 3277),
            param("Office de Voiries et Drainage", 3236),
            param("Investissemement privé camerounais", 4188),
            param("DRC-National Execution", 3940),
            param("PNUD PAF - UNAIDS Fund 11940", 3392),
            param("PNUD cost sharing Gouv 30071", 3401),
            param("Interchurch Medical Assistance", 3795),
            param("Ambassade d'Afrique du Sud", 3275),
            param("Organisation des Nations Unies pour le développement industriel", 3322),
            param("Agence Américaine pour le Développement International", 3342),
            param("Global Environment Fund Truste", 3888),
            param("Ministère des Affaires Foncières", 3155),
            param("ACTED", 3415),
            param("Programme des Nations Unies pour les établissements humains", 3320),
            param("Pmu Interlife", 3513),
            param("ICCO", 3475),
            param("Management Science for health", 3726),
            param("MAC ARTHUR FOUNDATION", 3985),
            param("Office International d'Immigration", 4218),
            param("Coopération de Plantation et d'élevage de LUIZA", 3837),
            param("Ambassade d'Espagne", 3284),
            param("CATHOLIC ORGANIZATION FOR RELIEF AND DEVELOPEMENT AID", 3441),
            param("Coopération technique chinoise", 3848),
            param("Agence Nationale pour la Promotion des Investissements", 3923),
            param("Université de Kinshasa", 4378),
            param("Centre des Recherches d'Energie Nucléaire", 3196),
            param("Centre Intégré de Bwamanda", 3337),
            param("Première Urgence", 3514),
            param("PNUD Trac1.1.2", 4214),
            param("Ministères des Affaires Etrangères", 3634),
            param("Investissement privé gilbratar", 4174),
            param("OXFAM GB", 3990),
            param("Association pour le Développement Social et la Sauvegarde de l'Environnement", 3565),
            param("Agence Turque de développement", 3580),
            param("Deutsche Welthungerhilf e.v.", 3645),
            param("Fondation pour la Promotion Sociale de la Culture", 3697),
            param("GOVERNMENT OF UNITED KINGDOM", 3959),
            param("GOVERNMENT OF NORWAY", 3945),
            param("S.G. Infrastructures,Travaux Publics et Reconstruction", 3237),
            param("Programme national de lutte contre le SIDA", 3865),
            param("Ministère des Relations avec le Parlement", 3733),
            param("Université Catholique de Kinshasa", 4041),
            param("S.G. Enseignement Supérieur et Universitaire", 3193),
            param("Investissement privé sud coréen", 3625),
            param("Medical Care Development International", 4297),
            param("ERAIFT", 3874),
            param("IBRD(Emergency response to cassava mosaic outbr)", 4169),
            param("Franziskaner", 3921),
            param("Institut National de Recherche Biologique", 4382),
            param("Investissement privé pakistanais", 4180),
            param("Programme National d'Assainissement", 3365),
            param("RESULT BASED MANAGEMENT GROUP (a division of 3186687 canada inc)", 3994),
            param("Ministère des Finances", 3207),
            param("Coopération Technique Belge", 1),
            param("S.G. Intégration régionale", 3181),
            param("Investissement privé guernesey", 4183),
            param("Institut des Jardins Zoologique et Botanique du Congo", 3366),
            param("Office des Petites et Moyennes Entreprises", 3371),
            param("Facilité des Etats Fragiles", 3899),
            param("NOVIB-OXFAM", 3574),
            param("International Committee of the Red Cross", 3647),
            param("UN CENTRE FOR HUMAN SETTLEMENT", 3929),
            param("Action Médicale Missionnaire Belgique", 3778),
            param("Ministère des Hydrocarbures", 3234),
            param("Internationaal Comité Rode Kruis (niet-Belgische afdeling) - ICRC/CICR - PRT", 4136),
            param("Solidarité Protestante", 3718),
            param("International Polio Virus Response", 3743),
            param("Forum Syd", 3589),
            param("S.G. Postes, Téléphones et Télécommunications", 3202),
            param("Investissement privé français", 3616),
            param("AIR SERV INTERNATIONALE", 3424),
            param("Oxfam-Grande-Bretagne", 3506),
            param("Comite International de RESCATE", 3699),
            param("Handicap International- Belgique", 3470),
            param("Agence Canadienne de Développement International", 3280),
            param("Direction Générale des Impôts", 3164),
            param("CESADEMA ONG/ASBL", 4009),
            param("Groupe Consultation CCISD et MIR ", 4030),
            param("Ministère du Plan", 3267),
            param("S.G. Portefeuille", 3184),
            param("Fondation Konrad Adenauer", 3904),
            param("Investissemement privé libanais", 3621),
            param("GT16 Education et Recherche Scientifique", 3671),
            param("DIAKONIA", 3819),
            param("VETERINAIRES SANS FRONTIERES", 4032),
            param("CARITAS", 3437),
            param("Fonds des Nations Unies pour l'enfance", 3304),
            param("Université Pédagogique Nationale ", 4381),
            param("Organisation pour l'Equipement Banana - Kinshasa", 3216),
            param("AUCC", 3689),
            param("Global Witness", 4038),
            param("Soeurs de Sainte Marie de Matadi", 3695),
            param("S.G. Sports et Loisirs", 3377),
            param("Ministère de la Jeunesse et Sports", 3255),
            param("Air Services", 3982),
            param("Dokters van de Wereld", 4106),
            param("Office d'aide humanitaire de la Commission européenne", 3559),
            param("Forum Sociale Deutsch-Land KONGO e.v", 3766),
            param("Action de carême", 3909),
            param("MEMISA BELGIQUE", 4002),
            param("UNICEF Fonds des Nations Unies pour l'Enfance", 3577),
            param("Lignes budgétaires Commission Européenne", 3584),
            param("Direction du Développement et de la Coopération Suisse", 12),
            param("Ambassade de la République de Corée", 3583),
            param("Agence de Coopération Internationale Japonaise", 3347),
            param("Ministère de la Fonction Publique", 3213),
            param("Lignes Aériennes Congolaises", 3223),
            param("Comité Provincial Equateur", 3143),
            param("Life and Peace Institute", 3486),
            param("Ministère des Affaires Etrangères d'Australie", 3644),
            param("Service Congolais des Postes et Télécommunications", 3203),
            param("Unité de coordination et de gestion du projet", 3846),
            param("Ministère de Culture et Arts", 3178),
            param("Ministère de la Justice", 3735),
            param("The Global Alliance for Vaccination and Immunisation(GAVI)", 4221),
            param("ONUSIDA/Programme des Nations Unies sur le VIH/SIDA", 3311),
            param("Bureau Central de Coordination", 3169),
            param("Investissement privé émiratie", 4173),
            param("IITA", 3796),
            param("Province du Kasai Oriental", 4204),
            param("S.G. Affaires Intérieures,Décentralisation et Sécurité", 3141),
            param("Service National des Reboisements", 3881),
            param("Fonds des Nations Unies pour la démocratie", 3319),
            param("Organisation des Nations Unies pour la science et l'éducation", 3313),
            param("PNUD EEC DRC Elections 36204", 3403),
            param("Fondacion Internacional de Solidaridad Compania de Maria", 3694),
            param("S.G. Jeunesse", 3376),
            param("LUTHERIAN WORLD FEDERATION", 3979),
            param("Ministère de la Coopération Internationale et Régionale", 3153),
            param("TRIAS VZW", 3524),
            param("NGO - WORLD VISION", 3996),
            param("LO-TCO Bistandasnämnd", 3588),
            param("Régie des Voies Fluviales", 3219),
            param("Ministère de l'Urbanisme et Habitat", 3375),
            param("Ambassade du Japon", 3291),
            param("Investissement privé sénégalais", 3623),
            param("Investissement privé ghanéen", 4184),
            param("Ministère de l'Environnement,Conservation de la Nature et Tourisme", 3204),
            param("Province du Kasai Occidental", 4203),
            param("S.G. E.P.S.P.", 3261),
            param("Fondantion pour le Développement des Capacités en Afrique", 3592),
            param("S.G. Prévoyance Sociale", 3210),
            param("SOLIDARITE", 3969),
            param("Human Rights Watch", 3474),
            param("GOVERNMENT OF FRANCE", 3937),
            param("GLOBAL FUND TO FIGHT AIDS", 4004),
            param("Carter Center", 3728),
            param("DEPARTMENT FOR INT'L DEVELOPME", 4036),
            param("Journal Transaction", 4346),
            param("Organisation mondiale du commerce", 3324),
            param("Institut Géographique du Congo", 3197),
            param("Safe Blood for Africa Foundation", 3746),
            param("GOVERNMENT OF SWEDEN", 3955),
            param("Katholiek Beurzenfonds voor Afrikanen", 4100),
            param("NORWEGIAN REFUGEE COUNCIL", 3972),
            param("S.G. Développement Rural", 3251),
            param("World Vision", 3740),
            param("S.G. Affaires Sociales", 3177),
            param("Association Provinciale pour l'Approvisionnement enMédicaments Essentiels au Sud-Kivu", 3566),
            param("Tetra Technic DPK", 3974),
            param("Association internationale de développement (Banque mondiale)", 3351),
            param("Action Damien", 3879),
            param("Medicus Mundi Navarra", 3500),
            param("FOMETRO", 3724),
            param("COOPERAZIONE E SVILUPPO", 3451),
            param("Office des Routes (OR)", 3239),
            param("Province de Bandundu", 4207),
            param("CIAT - International Center for Tropical Agriculture - CGIAR - PRT", 4126),
            param("World Wide Fund for Nature", 3532),
            param("Vredeseilanden", 3721),
            param("Internationale Medische Samenwerking (ex AZV_MSV Artsen Zonder Vakantie)", 4098),
            param("Haut Commissariat des Nations Unies pour les Refugiés", 3305),
            param("PNUD EEC Sécurité 36207", 3405),
            param("Johanniter International Assistance", 3483)));
        category("transaction_type", Arrays.asList(
            param("disbursement", 1),
            param("expenditure", 2),
            param("annual proposed project cost", 15),
            param("mtef projection", 3),
            param("pledges commitment", 5),
            param("release of funds", 8),
            param("commitment", 0),
            param("pledge", 7),
            param("pledges disbursement", 6),
            param("disbursement order", 4),
            param("estimated donor disbursement", 9)));
        category("financing_instrument_id", Arrays.asList());
    }
}
