//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.15 at 03:49:20 GMT+04:00 
//

package org.digijava.module.message.jaxb.impl.runtime;

public interface PrefixCallback
{
    void onPrefixMapping( String prefix, String uri ) throws org.xml.sax.SAXException;
}
