package org.dgfoundation.amp.nireports.testcases.tanzania.dimensions;

import org.dgfoundation.amp.nireports.testcases.HNDNode;
import org.dgfoundation.amp.nireports.testcases.HardcodedNiDimension;

import java.util.Arrays;
import java.util.List;

import static org.dgfoundation.amp.nireports.testcases.HNDNode.element;

public class OrganizationsTestDimension extends HardcodedNiDimension {

    public OrganizationsTestDimension(String name, int depth) {
        super(name, depth);
    }

    public final static OrganizationsTestDimension instance = new OrganizationsTestDimension("orgs", 3);

    @Override
    protected List<HNDNode> buildHardcodedElements() {
        return Arrays.asList(
        element(1, "Government", 
            element(18, "Accounts", 
                element(6646, "Zanzibar" ), 
                element(6649, "State House" ), 
                element(6650, "Public Debt and General Services" ), 
                element(6651, "Accountant General's Department" ), 
                element(6652, "Prime Minister" ), 
                element(6653, "Vice President" ), 
                element(6654, "Registrar of Political Parties" ), 
                element(6657, "President's Office and Cabinet Secretariat" ), 
                element(6658, "Vice President's Office" ), 
                element(6659, "President's Office - Public Service Management" ), 
                element(6660, "Ethics Secretariat" ), 
                element(6662, "Prime Minister's Office" ), 
                element(6664, "Defence" ), 
                element(6665, "The National Service" ), 
                element(6666, "Judiciary" ), 
                element(6668, "The National Assembly Fund" ), 
                element(6671, "National Audit Office" ), 
                element(6678, "Ministry of Community Development, Gender and Children" ), 
                element(6679, "Commission for Human Rights and Good Governance" ), 
                element(6680, "Prime Minister's Office-Regional Administration and Local Government" ), 
                element(6683, "Law Reform Commission" ), 
                element(6684, "Industial Court of Tanzania" ), 
                element(6685, "Electoral Commission" ), 
                element(6686, "Commercial Court" ), 
                element(6688, "Planning Commision" ), 
                element(6691, "Land Court" ), 
                element(6692, "Anti-Drug Commission" ), 
                element(6693, "Tanzania Commisision for AIDS" ), 
                element(6694, "Immigration Department" ), 
                element(6695, "Public Service Commission" ), 
                element(6698, "Minstry of Infrastructure Development" ), 
                element(6700, "Bagamoyo District Council" ), 
                element(6702, "Tanzania Social Action Fund" ), 
                element(6708, "Tanzania Roads Agency" ), 
                element(6710, "Mwanza (Region)" ), 
                element(6711, "Tanzania Revenue Authority (TRA)" ), 
                element(6713, "Sokoine University of Agriculture" ), 
                element(6912, "Tanzania Commission of Science and Technology" ), 
                element(6913, "Ardhi University" ), 
                element(6914, "Muhimbili Othpaedic Institute Development" ), 
                element(6915, "Prevention and Combating Corruption Bureau" ), 
                element(6916, "National Environment Management Council (NEMC) of Tanzania" ), 
                element(6917, "National Tuberculosis and Leprosy Program" ), 
                element(6918, "Ruvuma Regional Medical Center" ), 
                element(6919, "Small Industries Development Organization" ), 
                element(6942, "National Identification Development Agency" ), 
                element(7063, "Preventation and Combating Corruption Bureau" ), 
                element(7064, "President Office State House" ), 
                element(7068, "Ministry of Community Development Gender and Children" ) ), 
            element(56, "Revolutionary Government of Zanzibar", 
                element(6647, "Ministry of Finance Zanzibar" ), 
                element(6648, "Ministry of Health Zanzibar" ), 
                element(6674, "Ministry of Water" ), 
                element(6703, "Ministry of Finance and Economic Affairs Znz" ), 
                element(6704, "Ministry of Health and Social Welfare Znz" ), 
                element(6705, "Ministry of Water, Construction, Energy and Lands" ), 
                element(6706, "Ministry of Education and Vocational Training ZNZ" ), 
                element(6897, "Ministry of Agriculture, and Natural Resources -znz" ), 
                element(6898, "Zanzibar Electoral Commission" ), 
                element(6899, "Zanzibar House of Representatives" ), 
                element(6900, "Chief Minister's Office - Znz" ), 
                element(6901, "Zanzibar Aids Control Programme" ), 
                element(6902, "Zanzibar Institute of Financial Administration" ), 
                element(6903, "Office of the Chief Government Statistician Znz" ), 
                element(6904, "Zanzibar Broadcasting Corporation" ), 
                element(6905, "Ministry of Labour, Youth, Women and Children Development" ), 
                element(6906, "Zanzibar Water Authority" ), 
                element(6907, "Ministry of Communications and Transport" ), 
                element(6908, "Zanzibar Electricity Corporation" ), 
                element(6944, "Ministry of Tourism Trade and Investment" ), 
                element(6945, "Ministry of State (Presidents Office) Constitutional Affairs and Good Governanace" ), 
                element(6946, "Ministry of Information Culture and Sports" ), 
                element(7057, "Ministry of Industry Trade and Marketing" ), 
                element(7111, "Ministry of Constitution and Legal Affairs - Zanzibar" ), 
                element(7144, "PO Economy & Planning Department" ), 
                element(7155, "Ministry of Social Welfare, Youth, Women and Children Development" ), 
                element(7323, "Zanzibar Labour Law Reform" ), 
                element(7351, "Ministry of State First Vice President Office" ), 
                element(7352, "Ministry of State Second Vice President Office" ), 
                element(7353, "Zanzibar Planning Commission" ), 
                element(7362, "Prisons Zanzibar" ), 
                element(7363, "Judiciary/High Court Zanzibar" ), 
                element(7364, "Director for Public Prosecution Zanzibar" ), 
                element(7365, "North B District Unguja" ), 
                element(7366, "North A District Unguja" ), 
                element(7367, "Zanzibar Aids Commission" ), 
                element(7375, "Ministry of Livestock and Fishery ZnZ" ), 
                element(7404, "zMITM - Ministry of Industry Trade and Marketing- Zanzibar" ) ), 
            element(57, "Ministry of Education Group", 
                element(6716, "Muhimbili University of Health and Allied Sciences" ), 
                element(7339, "University Of Dodoma" ) ), 
            element(66, "Ministry of Agriculture Group" ), 
            element(67, "Ministry of Health and Social Welfare Group", 
                element(6722, "Tanzania Food and Drug Authority" ), 
                element(6869, "National AIDS Control Programme" ), 
                element(6870, "Muhimbili National Hospital" ), 
                element(6871, "National Tuberclosis and Leprosy Control Programme" ), 
                element(6872, "Bugando Medical Center" ), 
                element(6873, "MuhimbiliHealth Information Center" ), 
                element(6875, "National Institute for Medical research" ), 
                element(6876, "Mbeya regional Medical Office" ), 
                element(6877, "Rukwa Regional Medical Office" ), 
                element(6878, "Mbeya Refferral Hospital" ), 
                element(6881, "Arusha Zonal Training Center ( CEDHA)" ), 
                element(6882, "Iringa Public Health Training Institute" ), 
                element(7021, "Centre for Educational Development in Health Arusha (CEDHA)" ), 
                element(7022, "Drug Control Commission" ), 
                element(7024, "Mbeya Referral Hospital" ), 
                element(7025, "Mbeya Regional Medical" ), 
                element(7027, "National AIDS Control Program" ), 
                element(7028, "National Malaria Control Program (NMCP)" ), 
                element(7029, "National Tuberculosis and Leprosy Control Program" ), 
                element(7030, "Primary Health Care Institute Iringa" ), 
                element(7179, "Institute of Social Work" ), 
                element(7298, "Medical Store Department" ) ), 
            element(68, "Ministry of Finance", 
                element(6723, "Bank of tanzania" ), 
                element(6868, "External Finance Department" ), 
                element(6883, "EDF-Programme Support Unit" ), 
                element(7026, "Millennium Challenge Account/Tanzania" ), 
                element(7071, "Central Bank of Tanzania" ), 
                element(7175, "Financial Intelligence Unit" ), 
                element(7425, "The Treaury" ) ), 
            element(69, "Ministry of Energy and Minerals", 
                element(6724, "Tanesco" ), 
                element(6889, "Rural Energy Agency" ) ), 
            element(70, "Ministry of Education and Vocation Training", 
                element(6712, "University of Dar-Es-Salaam" ), 
                element(6880, "Kigoma Zonal Training Center" ), 
                element(6940, "Vocational Education and Training Authority" ), 
                element(6951, "Tanzanian Commission for University" ), 
                element(6952, "Centre National des Peuvres Universitaires et scholaires" ), 
                element(7023, "Kigoma Zonal training Centre (KZTC)" ), 
                element(7376, "Institute of Adult Education" ) ), 
            element(71, "Iringa region", 
                element(6727, "Makete" ), 
                element(6728, "Ludewa" ), 
                element(6729, "Njombe" ), 
                element(6750, "Mufindi DC" ), 
                element(6751, "Kilolo DC" ), 
                element(6752, "Makete DC" ), 
                element(6753, "Njombe DC" ), 
                element(6754, "Iringa MC" ), 
                element(6755, "Njombe TC" ), 
                element(7107, "Iringa Regional Administration Secretary" ), 
                element(7159, "Iringa DC" ) ), 
            element(72, "Mwanza", 
                element(6730, "Sengerema" ), 
                element(6816, "Ukerewe DC" ), 
                element(6817, "Magu DC" ), 
                element(6818, "Kwimba DC" ), 
                element(6819, "Sengerema DC" ), 
                element(6820, "Geita DC" ), 
                element(6821, "Missungwi DC" ), 
                element(6822, "Mwanza CC" ), 
                element(7098, "Mwanza" ), 
                element(7101, "Regional Health Management Team-Mwanza" ), 
                element(7167, "Misungwi DC" ), 
                element(7405, "Mwanza Urban Water Supply & Sewage Authority" ) ), 
            element(73, "Arusha", 
                element(6733, "Monduli DC" ), 
                element(6734, "Arusha MC" ), 
                element(6735, "Karatu DC" ), 
                element(6736, "Ngorongoro DC" ), 
                element(6737, "Meru DC" ), 
                element(6738, "Arusha DC" ), 
                element(6739, "Longido DC" ), 
                element(7142, "Tanzania National Parks" ), 
                element(7166, "Arumeru DC" ) ), 
            element(74, "Dar es Salaam", 
                element(6740, "Kinondoni MC" ), 
                element(6741, "Ilala MC" ), 
                element(6742, "Temeke MC" ), 
                element(6743, "Dar es Salaam CC" ), 
                element(7060, "Prime Ministers Offices" ), 
                element(7113, "Vice president Office DMD" ), 
                element(7114, "President Office ,Public Service and Good Governance" ), 
                element(7164, "DAO UNGUJA CENTRAL" ), 
                element(7178, "RAS Dar es Salaam" ), 
                element(7396, "Dar Es Salaam Water & Sewage Authority ,Tanzania" ) ), 
            element(75, "Dodoma", 
                element(6744, "Kondoa DC" ), 
                element(6745, "Mpwapwa DC" ), 
                element(6746, "Kongwa DC" ), 
                element(6747, "Dodoma MC" ), 
                element(6748, "Bahi DC" ), 
                element(6749, "Chamwino DC" ), 
                element(6929, "Mkonze Village Council" ), 
                element(7075, "Capital City Development" ), 
                element(7112, "National Assembly" ) ), 
            element(77, "Kagera", 
                element(6756, "Karagwe DC" ), 
                element(6757, "Bukoba DC" ), 
                element(6758, "Muleba DC" ), 
                element(6759, "Biharamulo DC" ), 
                element(6760, "Ngara DC" ), 
                element(6761, "Bukoba MC" ), 
                element(6762, "Chato DC" ), 
                element(6763, "Misenyi DC" ), 
                element(7100, "Regional Health Management Team-Kagera" ) ), 
            element(78, "Kigoma", 
                element(6767, "Kibondo DC" ), 
                element(6768, "Kasulu DC" ), 
                element(6769, "Kigoma DC" ), 
                element(6770, "Kigoma MC" ), 
                element(7370, "RAS Kigoma" ), 
                element(7372, "Kigoma Ujiji" ) ), 
            element(79, "DC Kilimanjaro", 
                element(6771, "Rombo DC" ), 
                element(6772, "Mwanga DC" ), 
                element(6773, "Same DC" ), 
                element(6774, "Moshi DC" ), 
                element(6775, "Hai DC" ), 
                element(6776, "Moshi MC" ), 
                element(6777, "Siha DC" ) ), 
            element(80, "Lindi", 
                element(6778, "Kilwa DC" ), 
                element(6779, "Lindi DC" ), 
                element(6780, "Nachingwea DC" ), 
                element(6781, "Liwale DC" ), 
                element(6782, "Ruangwa DC" ), 
                element(6783, "Lindi TC" ), 
                element(6927, "Liwale District Council" ) ), 
            element(81, "Manyara", 
                element(6784, "Babati DC" ), 
                element(6785, "Babati TC" ), 
                element(6786, "Hanang DC" ), 
                element(6787, "Mbulu DC" ), 
                element(6788, "Simanjiro DC" ), 
                element(6789, "Kiteto DC" ) ), 
            element(82, "Mara", 
                element(6790, "Tarime DC" ), 
                element(6791, "Serengeti DC" ), 
                element(6792, "Musoma DC" ), 
                element(6793, "Bunda DC" ), 
                element(6794, "Musoma MC" ), 
                element(6795, "Rorya DC" ), 
                element(7140, "District Executive Director Bunda" ) ), 
            element(83, "Mbeya", 
                element(6796, "Chunya DC" ), 
                element(6797, "Mbeya DC" ), 
                element(6798, "Kyela DC" ), 
                element(6799, "Rungwe DC" ), 
                element(6800, "Ileje DC" ), 
                element(6801, "Mbozi DC" ), 
                element(6802, "Mbarali DC" ), 
                element(6803, "Mbeya CC" ), 
                element(7160, "Mbeya Regional Secretariat" ), 
                element(7168, "MBEYA RAS" ) ), 
            element(84, "Morogoro", 
                element(6804, "Kilosa DC" ), 
                element(6805, "Morogoro DC" ), 
                element(6806, "Kilombero DC" ), 
                element(6807, "Ulanga DC" ), 
                element(6808, "Morogoro MC" ), 
                element(6809, "Mvomero DC" ), 
                element(6943, "Morogoro Regional Administration Secretariat" ) ), 
            element(85, "Mtwara", 
                element(6810, "Mtwara DC" ), 
                element(6811, "Newala DC" ), 
                element(6812, "Masasi DC" ), 
                element(6813, "Tandahimba DC" ), 
                element(6814, "Mtwara MC" ), 
                element(6815, "Nanyumbu DC" ), 
                element(7097, "Mtwara" ), 
                element(7102, "Regional Health Management Team-Mtwara" ) ), 
            element(86, "Pwani", 
                element(6823, "Bagamoyo DC" ), 
                element(6824, "Kibaha DC" ), 
                element(6825, "Kisarawe DC" ), 
                element(6826, "Mkuranga DC" ), 
                element(6827, "Rufiji DC" ), 
                element(6828, "Mafia DC" ), 
                element(6829, "Kibaha TC" ), 
                element(7103, "Regional Health Management Team-Pwani" ) ), 
            element(87, "Rukwa", 
                element(6830, "Mpanda DC" ), 
                element(6831, "Sumbawanga DC" ), 
                element(6832, "Nkansi DC" ), 
                element(6833, "Sumbawanga MC" ), 
                element(6834, "Mpanda TC" ) ), 
            element(88, "Ruvuma", 
                element(6835, "Tunduru DC" ), 
                element(6836, "Songea DC" ), 
                element(6837, "Mbinga DC" ), 
                element(6838, "Songea MC" ), 
                element(6839, "Namtumbo DC" ) ), 
            element(89, "Shinyanga", 
                element(6840, "Bariadi DC" ), 
                element(6841, "Maswa DC" ), 
                element(6842, "Shinyanga DC" ), 
                element(6843, "Kahama DC" ), 
                element(6844, "Bukombe DC" ), 
                element(6845, "Meatu DC" ), 
                element(6846, "Shinyanga MC" ), 
                element(6847, "Kishapu DC" ) ), 
            element(90, "Singida", 
                element(6848, "Iramba DC" ), 
                element(6849, "Singida DC" ), 
                element(6850, "Manyoni DC" ), 
                element(6851, "Singida MC" ) ), 
            element(91, "Tabora", 
                element(6852, "Nzega DC" ), 
                element(6853, "Igunga DC" ), 
                element(6854, "Tabora DC" ), 
                element(6855, "Urambo DC" ), 
                element(6856, "Sikonge DC" ), 
                element(7143, "RAS Tabora" ) ), 
            element(92, "Tanga", 
                element(6857, "Tabora MC" ), 
                element(6858, "Lushoto DC" ), 
                element(6859, "Korogwe DC" ), 
                element(6860, "Muheza DC" ), 
                element(6861, "Tanga CC" ), 
                element(6862, "Pangani DC" ), 
                element(6863, "Handeni DC" ), 
                element(6864, "Kilindi DC" ), 
                element(6865, "Korogwe TC" ), 
                element(6866, "Mkinga DC" ), 
                element(7099, "Tanga" ), 
                element(7104, "Regional Health Management Team-Tanga" ) ), 
            element(94, "Kagera", 
                element(7096, "Kagera" ), 
                element(7139, ".       District Executive Director Bukoba" ), 
                element(7371, "RAS Kagera" ) ), 
            element(95, "Ministry of Agriculture,Food Security and Cooperatives", 
                element(6884, "Tanzania Coffee Research Institute" ), 
                element(6885, "Tea Research Institute of Tanzania" ), 
                element(7176, "Tanzania Food and Nutrion Center (TFNC)" ) ), 
            element(96, "Public Prosecution", 
                element(6887, "Attorney General Chambers" ), 
                element(7170, "Director of Public Prosecution" ) ), 
            element(97, "Ministry of Justice and Constitutional Affairs", 
                element(6890, "National electroral Commission" ), 
                element(7177, "Registration, Insolvency and Trusteeship Agency (RITA)" ) ), 
            element(98, "Ministry of Finance.", 
                element(6888, "National Bureau of Statistics" ), 
                element(6911, "National Museum and House of Culture" ) ), 
            element(99, "National Electroral Commission" ), 
            element(100, "Ministry of Water and Irrigation", 
                element(6909, "Dar es salaam Water Sewarage Company" ), 
                element(6910, "Ministry of Water and Irrigation" ), 
                element(6941, "Dodoma Urban Water and Sewage Authority" ) ), 
            element(101, "Ministry of Natural Resources and Tourism", 
                element(6923, "Natural Resources and Tourism" ) ), 
            element(119, "Ministry of Livestock Development and Fisheries" ), 
            element(120, "Ministry of Communication Science and Technology" ), 
            element(121, "Ministry of Industry and Trade" ), 
            element(122, "President Office", 
                element(7070, "President Office" ), 
                element(7136, "Presdent office Planning Commission" ), 
                element(7308, "Presidential Delivery Bureau" ) ), 
            element(127, "GOVERNMENT COOPERATION", 
                element(7056, "Ministry of labour and Youth Development" ), 
                element(7162, "DAO CHAKECHAKE PEMBA" ), 
                element(7163, "DAO MKOANI PEMBA" ), 
                element(7165, "DAO UNGUJA URBAN" ) ), 
            element(128, "Ministry of Home Affairs", 
                element(7131, "Police" ) ), 
            element(131, "Kilimanjaro", 
                element(7145, "RAS Kilimanjaro" ) ), 
            element(134, "Iringa DC" ), 
            element(135, "Njombe Region", 
                element(7161, "RAS Njombe" ) ), 
            element(136, "Vice President's Office", 
                element(7169, "Lake Tanganyika Authority" ) ), 
            element(137, "RoGZ" ), 
            element(139, "Government of Tanzania Mainland", 
                element(6643, "Ministry of Finance and Economic Affairs" ), 
                element(6655, "Ministry of Public Safety and Security" ), 
                element(6656, "Ministry of Home Affairs - Prison Service" ), 
                element(6661, "Ministry of Foreign Affairs and International Cooperation" ), 
                element(6667, "Ministry of Justice and Constitutional Affairs" ), 
                element(6669, "Ministry of Agriculture, Food Security and Cooperatives" ), 
                element(6670, "Ministry of Industry and Trade" ), 
                element(6672, "Ministry of Education and Vocational Training" ), 
                element(6673, "Ministry of Lands, Housing and Human Settlements Development" ), 
                element(6675, "Ministry of Finance" ), 
                element(6676, "Ministry of Home Affairs" ), 
                element(6677, "Ministry of Health and Social Welfare" ), 
                element(6681, "Ministry of Defence and National Services" ), 
                element(6682, "Ministry of Energy and Minerals" ), 
                element(6687, "Ministry of Labour, Employment and Youth Development" ), 
                element(6689, "Ministry of Higher Education, Science and Technology" ), 
                element(6690, "Ministry of Natural Resources and Tourism" ), 
                element(6696, "Ministry of Information, Culture and Sports" ), 
                element(6697, "Ministry of East African Cooperatiion" ), 
                element(6699, "Ministry of Livestock Develpment" ), 
                element(6717, "Ministry of Communication, Science and Technology" ), 
                element(7054, "Ministry of Works" ), 
                element(7055, "Ministry of Transportation" ), 
                element(7058, "Ministry of Constitution and Legal Affairs" ), 
                element(7059, "Ministry of Communication Science and Technology" ), 
                element(7061, "Ministry of Community Development and Gender" ), 
                element(7062, "Ministry of Foreign Affairs and Internation Cooperations" ), 
                element(7065, "Ministry of Information, Youth,communication and Sports" ), 
                element(7066, "Ministry of Defence and National Security" ), 
                element(7069, "Ministry of Livestock Development  and Fisheries" ), 
                element(7338, "Tanzania Government Chemist Laboratory Agency" ), 
                element(7342, "Tanzania Bureau of Standards" ), 
                element(7357, "Tanzania Mineral Audit Agency" ), 
                element(7377, "Agency for the Development of  Education Management" ), 
                element(7378, "University of Dodoma" ), 
                element(7379, "Nelson Mandela African Institute for Science and Technology in Tanzania" ), 
                element(7383, "Mzumbe University" ), 
                element(7387, "Public Procurement Regulatory Authority" ), 
                element(7388, "Agricultural Research Institute" ), 
                element(7395, "Tanzania Institute of Education" ), 
                element(7427, "TANZANIA COTTON BOARD" ), 
                element(7432, "Tanzania Mortgage Refinance Company" ), 
                element(7450, "Kibaha Education Centre" ), 
                element(7451, "NATIONAL SERVICE CORPORATION SOLE" ) ), 
            element(140, "Zanzibar", 
                element(7419, "Mnazi Mmoja Hospital Zanzibar" ), 
                element(7433, "Zanzibar- President  Office State House and Good Governance" ), 
                element(7436, "Zanzibar- Presdent Office Regional Administration and Special Departments" ), 
                element(7437, "Zanzibar President Office Labor and Public Services" ), 
                element(7438, "Zanzibar First Vice President office" ), 
                element(7439, "Zanzibar Second Vise President Office" ), 
                element(7440, "Zanzibar Ministry of Finance" ), 
                element(7441, "Zanzibar  Ministry of Education and Vocational Training" ), 
                element(7442, "Zanzibar Ministry of Health" ), 
                element(7443, "Zanzibar Ministry of Consitution Affairs and Justice" ), 
                element(7444, "Zanzibar Ministry of Information, Culture, Tourism and Sports" ), 
                element(7445, "Zanzibar Ministry of Empowerment, Social welfare, Youth,Women and Children" ), 
                element(7446, "Zanzibar Ministry of livestock and Fisheries" ), 
                element(7447, "Zanzibar Ministry of Infrastructure and Communication" ), 
                element(7448, "Zanzibar Ministry of Agriculture and Natural Resources" ), 
                element(7449, "Zanzibar Ministry of Land, Housing ,Water and Energy" ) ) ), 
        element(3, "Multilateral", 
            element(7, "World Bank Group", 
                element(119, "International Development Association" ), 
                element(6584, "International Development Agency (IDA)" ), 
                element(6663, "World Bank" ), 
                element(6709, "International Bank for Reconstruction and Development" ), 
                element(7174, "World Bank Externally Financed Output" ) ), 
            element(8, "United Nations", 
                element(104, "Food and Agriculture Organisation" ), 
                element(105, "International Fund for Agricultural Development (IFAD)" ), 
                element(106, "International Labour Organisation (ILO)" ), 
                element(107, "United Nations Programme on HIV and AIDS" ), 
                element(110, "United Nations Educational, Scientific and Cultural Organisation (UNESCO)" ), 
                element(111, "United Nations Population Fund (UNFPA)" ), 
                element(112, "United Nations High Commissioner for Refugees (UNHCR)" ), 
                element(113, "United Nations Children's Fund (UNICEF)" ), 
                element(114, "United Nations Human Settlements Programme" ), 
                element(115, "United Nations Industrial Development Organisation (UNIDO)" ), 
                element(6575, "Global Environment Facility" ), 
                element(6585, "x_International Fund for Agriculture Development" ), 
                element(6621, "x_UN-Habitat" ), 
                element(6622, "UNCDF" ), 
                element(6624, "United Nations Development Programme (UNDP)" ), 
                element(6625, "United Nations Environment Programme" ), 
                element(6633, "United Nations Development Fund for Women (UN Women/UNIFEM)" ), 
                element(6635, "United Nations Volunteers" ), 
                element(6639, "World Food Programme (WFP)" ), 
                element(6640, "World Health Organization (WHO)" ), 
                element(6725, "UN Joint Programme Fund" ), 
                element(6766, "International Organization For Migration" ) ), 
            element(9, "European Community", 
                element(79, "European Commission" ), 
                element(6566, "European Investment Bank" ), 
                element(6567, "European Union" ), 
                element(6568, "European Development Fund" ), 
                element(7186, "Food and Agricultural Research Management LBG" ), 
                element(7187, "PATRIC MTENGA HERI" ), 
                element(7190, "SECO Engineers & contractors LTD" ), 
                element(7191, "PKF Tanzania" ), 
                element(7192, "SAFEGE SA" ), 
                element(7193, "UNIVERSITA DEGLI STUDI DI ROMA LASAPIENZA" ), 
                element(7194, "COLLEGIO UNIVERSITARIO ASPIRANT EMEDICI MISSIONARI -MEDIC CON L'AFRICA ONLUS ASSOCIAZIONE" ), 
                element(7195, "CARDINO EMERGING MARKETS (UK) LTD" ), 
                element(7196, "SENSE INTERNATIONAL LBG" ), 
                element(7197, "THE TRAIDCRAFT EXCHANGE LBG" ), 
                element(7198, "COMFED INTERNATIONAL LBG" ), 
                element(7199, "COMITATO EUROPEO PER LA FORMAZIONEE L'AGRICOLTURA ONLUS ASSOCIAZIONE" ), 
                element(7200, "ZOOLOGISHE GESELLSCHAFT FRANKFURTVON 1858 EV" ), 
                element(7201, "SUGAR BOARD OF TANZANIA" ), 
                element(7202, "CONCERN WORLDWIDE LBG" ), 
                element(7203, "ACTIONAID  LBG" ), 
                element(7204, "PLAN INTERNATIONAL FRANCE ASSOCIATION" ), 
                element(7205, "ERNST AND YOUNG" ), 
                element(7207, "COMMUNITY FOREST PEMBA (CFP) ASSOCIATION" ), 
                element(7208, "INSTITUTE OF RURAL DEVELOPMENT PLANNING" ), 
                element(7209, "THE SAVE THE CHILDREN FUND LBG" ), 
                element(7210, "DELOITE & TOUCHE PARTNERSHIP" ), 
                element(7211, "SASCO CONSTRUCTION LTD" ), 
                element(7212, "MEX Company LTD" ), 
                element(7213, "SEARCH FOR COMMON GROUND VZW" ), 
                element(7214, "UNIVERSITY OF GREENWICH" ), 
                element(7215, "LUQMAN CONSTRUCTION COMPANY LTD" ), 
                element(7216, "THE ESTERN AND SOUTHERN AFRICA SMALLSCALE FARMERS FORUM ASSOCIATION" ), 
                element(7217, "NIB-PLAN CONSULT LIMITED" ), 
                element(7218, "EFREM  VALENTINE KIMARO" ), 
                element(7219, "ASSOCIATION CENTRE INTERNATIONAL DE DEVELOPMENT ET DE RECHERCHE" ), 
                element(7220, "INSTITUTO OIKOS ONLUS ASSOCIAZIONE" ), 
                element(7221, "MTANDAO WA VIKUNDI VYA WAKULIMA TANZANIA" ), 
                element(7222, "AFRICA MEDICA AND RESEARCH FOUNDATION UNITED KINGDOM LBG" ), 
                element(7223, "JAMUHURI YA MUUNGANO" ), 
                element(7224, "OXFAM GB LBG" ), 
                element(7225, "The Registered Trustee of Archdioscese of Dar Es Salaam" ), 
                element(7226, "VEREIN CHRISTOFEL -BLINDENMISSION" ), 
                element(7227, "STICHING CORDAID" ), 
                element(7228, "MARE STOPES INTERNATIONAL LBG" ), 
                element(7229, "CAMFED INTERNATIONAL LBG" ), 
                element(7230, "ALLIANCE FRANCAISE DAR ES SALAAM ASSOCIATION" ), 
                element(7231, "THE BRITISH COUNCIL COUNCIL ROYAL CHARTER" ), 
                element(7232, "ATOS BELGIUM NV" ), 
                element(7233, "CHRISTIAN ENGINEERS IN DEVELOPMENT" ), 
                element(7234, "MWH SA" ), 
                element(7235, "SITTE CONSORTIUM SOCIETE MOMENTANEE" ), 
                element(7236, "SARRAF" ), 
                element(7237, "ASSOCIAZIONE DI COOPERATION RURALE IN AFRICA E AMERICA LATINA" ), 
                element(7238, "FIDA INTERNATIONAL RY" ), 
                element(7239, "MOORE STEPHENS LLP" ), 
                element(7240, "I.T. TRANSPORT LTD" ), 
                element(7241, "DEUTSCHE STIFTUNG WELBEVOLKERRUNG (DSW)" ), 
                element(7242, "LUDWING-MAXIMILIANS -UNIVERSITAT MUNCHEN" ), 
                element(7243, "EGIS INTERNATIONAL SA" ), 
                element(7244, "CRONTMIJ AS" ), 
                element(7245, "KREDITANSTAL FUR WIEDERAUFBAU" ), 
                element(7246, "PRICEWATERHOUSECOOPERS LTD" ), 
                element(7247, "DFC FA" ), 
                element(7248, "AGRER SA" ), 
                element(7249, "STICHING HIVOS (HUMANISTICH INSTITUUT VOOR ON ONTWIKKELING  SAMENWERKING)" ), 
                element(7250, "DIWI CONSULT INTERNATIONAL GMBH" ), 
                element(7251, "DORSH INTERNATIONAL CONSULTANTS GMBH" ), 
                element(7252, "CEEST FOUNDATION OF REGISTERED TRUSTEED TRUSTEES" ), 
                element(7253, "UICN- Union International Pour La Conservation De La Nature Et De Seressources" ), 
                element(7254, "ASSOCAZIONE INTERNAZIONALE VOLONTARI LAICI" ), 
                element(7255, "COWI BELGIUM SPRL" ), 
                element(7256, "IMPRESA CONSTRUCTION GIUSEPPE MALTAURO" ), 
                element(7257, "SUA-Sokoine University of Agriculture" ), 
                element(7258, "JOS HANSEN & SOEHNE GMBH JR INTERNATIONAL BAU GMBH" ), 
                element(7259, "HELPAGE INTERNATIONAL LBG" ), 
                element(7260, "WWF-UK LBG" ), 
                element(7261, "PENROSE" ), 
                element(7262, "GRONTMJ AS" ), 
                element(7263, "EUROPEAN CONSULTAIONS SPRL" ), 
                element(7264, "SOGEA SATOM SAS" ), 
                element(7265, "Mouchel LTD" ), 
                element(7266, "Business and Strategies in Europe SA" ), 
                element(7267, "AIDE A LA DECISION ECONOMIQUE SA" ), 
                element(7268, "MASI" ), 
                element(7269, "BASIC NEED NEEDS TRUST" ), 
                element(7270, "EAST AFRICA COMMUNITY EAC" ), 
                element(7271, "CASCO CONTRUCTION LTD" ), 
                element(7272, "GOPA" ), 
                element(7273, "FONDAZIONE ACCRA -CCS" ), 
                element(7274, "MEKONSULT PARTNERSHIP" ), 
                element(7275, "CARE OSTRREICH VEREIN FUR ENTWICKLUNGSZSAMMENARRBEIT AND HUMANITARE HILFE" ), 
                element(7276, "FORMATION POUR L'EPANOUISSEMENT ETLE RENOUVEAU DE LA TERRE" ), 
                element(7277, "LUX Development SA" ), 
                element(7278, "CARE DANMARK FONDEN FOR FRIVLING U LANDSBITAND" ), 
                element(7279, "MAZARS SA" ), 
                element(7280, "AFRICAN MEDICAL AND RESEARCH FOUNDATION LBG" ), 
                element(7281, "PENDHARKAR & ASSOCIATES LTD" ), 
                element(7282, "NANDHRA ENGINEERING & CONSTRUCTION COMPANY LTD" ), 
                element(7283, "BELGISCHE TECHNISCHE COOPERATIVE NV" ), 
                element(7284, "CMC AUTOMOBILES LTD" ), 
                element(7285, "E PIHLAND SON AS" ), 
                element(7286, "COMITATO EUROPEO PER LA FORMAZIONEE L' AGRICOLTURA ONLUS ASSOCIAZIONE" ), 
                element(7287, "ONGAWA INGENIERIA PARA EL DESARROLLO HUMANO ASOCIACION" ), 
                element(7288, "ASSOCIAZIONE INTERNAZIONALE VOLONTARI LAIC" ), 
                element(7289, "NIRAS RADGIVENDE INGENIORER OG PLANLAEGGERE AS" ), 
                element(7290, "E PIHIL AND SON AS" ), 
                element(7291, "POYRY ENVIRONMENT GMBH" ), 
                element(7292, "HTSPE LIMITED" ), 
                element(7293, "POLICY FORUM LIMITED BY GUARANTEE" ), 
                element(7294, "POLICY FORUM LIMITED BY GUARANTEE.." ), 
                element(7295, "TEA RESEARCH INSITUTE OF TANZANIA LTD" ), 
                element(7296, "CHRISTOFFEL-BLINDENMISSION DEUTSCHLAND EV" ), 
                element(7297, "Agricultural Council of Tanzania" ), 
                element(7320, "RANS COMPANY LTD." ), 
                element(7327, "Particip GMBH Consultants fur Entiwicklung and UMWELT" ), 
                element(7328, "THE EASTERN AND SOUTHERN AFRICA SMALL SCALE FARMERS FORUM ASSOCIATION" ), 
                element(7329, "MUSIC MAYDAY TANZANIA COMPANY LTD LBG." ), 
                element(7330, "ALLIANCE FRANCAISE DAR ES SALAAM ASSOCIATION LANDELL MILLS LTD." ), 
                element(7331, "POHL CONSULTATING ASSOCIATES GMBH" ), 
                element(7332, "RESOURCES AND LOGISTICS SARL" ) ), 
            element(19, "African Development Bank", 
                element(70, "African Development Bank (AfDB)" ), 
                element(6548, "African Development Fund" ) ), 
            element(24, "OPEC", 
                element(97, "OPEC Fund" ), 
                element(6599, "x_Kuwait Fund" ), 
                element(6600, "Saudi OPEC Funds" ) ), 
            element(25, "Nordic Development Fund", 
                element(95, "Nordic Development Fund" ) ), 
            element(31, "International Monetary Fund", 
                element(6588, "International Monetary Fund (IMF)" ) ), 
            element(32, "Global Fund", 
                element(86, "Global Fund for HIV, TB and Malaria" ) ), 
            element(33, "Global Environment Facility", 
                element(6571, "FDB" ) ), 
            element(36, "x_European Union", 
                element(7311, "MUSIC MAYDAY TANZANIA COMPANY LIMITED LBG" ), 
                element(7318, "KREDITASNTALT FUR WIEDERAUFBAU" ), 
                element(7319, "CARDNO EMERGING MARKETS (UK) LTD" ) ), 
            element(38, "Common Fund for Commodities", 
                element(76, "Common Fund for Commodities" ) ), 
            element(40, "Arab Bank for Economic Development in Africa", 
                element(73, "Arab Bank for Economic Development in Africa (BADEA)" ), 
                element(6554, "BA-DEA" ) ), 
            element(43, "x_ADB" ), 
            element(103, "KUWAIT FUND" ), 
            element(125, "Abu Dhabi", 
                element(7095, "Abu Dhabi Fund for Development" ) ) ), 
        element(4, "Bilateral", 
            element(6, "Belgium", 
                element(74, "Belgium" ), 
                element(7386, "Belgium Technical Cooperation" ) ), 
            element(10, "France", 
                element(81, "France" ), 
                element(6947, "Local and International NGOs" ), 
                element(6948, "AHADI Foundation,Central Tanganyika Diocese,Aide et Action (French NGO)" ), 
                element(6950, "French Embassy" ), 
                element(7110, "FRANCE/France Development Agency (AFD)" ) ), 
            element(11, "Switzerland", 
                element(102, "Swiss Development Cooperation" ), 
                element(6618, "Switzerland" ) ), 
            element(12, "Germany", 
                element(84, "KFW" ), 
                element(6576, "Germany" ), 
                element(6577, "Gesellschaft für Technische Zusammenarbeit (GTZ)" ), 
                element(6731, "InWent" ), 
                element(6732, "Geswan Development Service" ), 
                element(6920, "Centrum fuer internationale Migration und Entwicklung" ), 
                element(7073, "Deutsche Gesellschaft für Internationale Zusammenarbeit (GIZ) GmbH" ), 
                element(7086, "Germany/Kfw" ), 
                element(7087, "Germany/GIZ" ), 
                element(7105, "Germany/Deutsher Entwicklungsdienst (DED)" ), 
                element(7106, "Germany/Internationale Wieiterbuildung Und Entwicklung gGmbH (InWent)" ) ), 
            element(13, "United Kingdom", 
                element(103, "Department for International Development (DfID)" ), 
                element(6620, "Volunteer Services Overseas" ) ), 
            element(14, "Japan", 
                element(90, "Japan" ), 
                element(6596, "Japan International Cooperation Agency" ) ), 
            element(15, "Norway", 
                element(96, "Norway" ) ), 
            element(16, "Netherlands", 
                element(94, "Netherlands" ) ), 
            element(17, "USA", 
                element(118, "United States Agency for International Development" ), 
                element(6718, "Center for Disease Control" ), 
                element(6719, "Millennium Challenge Corporation (MCC)" ), 
                element(6720, "Dept Of Defense" ), 
                element(6721, "peace corps" ), 
                element(6726, "Department of State" ), 
                element(7008, "Department of Agriculture" ), 
                element(7009, "Department of Interior" ), 
                element(7088, "United States Government (USG)" ), 
                element(7089, "United States Government/USAID" ), 
                element(7090, "United States Government/CDC" ), 
                element(7091, "United States Government/Peace Corps" ), 
                element(7092, "United States Government/DoD" ), 
                element(7093, "United States Govrenment/DoS" ), 
                element(7094, "United States Government/MCC" ) ), 
            element(20, "Sweden", 
                element(101, "Sweden" ), 
                element(6617, "x_Kingdom of Sweden" ), 
                element(6701, "Swedish International Development Agency" ) ), 
            element(21, "Spain", 
                element(100, "Republic of Spain" ) ), 
            element(22, "Saudi Arabia", 
                element(99, "Saudi Fund" ), 
                element(6613, "Kingdom of Saudi Arabia" ), 
                element(6707, "Al-Youseif Establishment" ) ), 
            element(23, "PR China", 
                element(6611, "People's Republic of China" ) ), 
            element(26, "Mozambique", 
                element(93, "Mozambique" ), 
                element(6601, "x_Republic of Mozambique" ) ), 
            element(27, "Kuwait Fund", 
                element(92, "Kuwait Fund for Arab Economic Development" ) ), 
            element(28, "Korea", 
                element(91, "Korea" ), 
                element(6924, "Economic Development Cooperation Fund Korea" ), 
                element(6939, "Korea International Cooperation Agency" ) ), 
            element(29, "Ireland", 
                element(88, "Ireland" ), 
                element(6592, "Concern Ireland" ) ), 
            element(30, "Italy", 
                element(89, "Italy" ), 
                element(6593, "x_Italian Republic" ), 
                element(6765, "Italian Development Cooperation" ) ), 
            element(35, "Finland", 
                element(80, "Finland" ) ), 
            element(37, "Denmark", 
                element(77, "Denmark" ) ), 
            element(39, "Canada", 
                element(75, "Canada" ), 
                element(7402, "Association of Canadian Community Colleges (ACCC)" ) ), 
            element(42, "Australia", 
                element(71, "Australia" ) ), 
            element(46, "Austria" ), 
            element(47, "India", 
                element(6589, "Republic of India" ), 
                element(6590, "Iran" ) ), 
            element(48, "Hungary", 
                element(6581, "Republic of Hungary" ) ), 
            element(49, "Iran" ), 
            element(51, "China", 
                element(6925, "The Export-Import Bank of China" ) ), 
            element(52, "Czech", 
                element(6562, "Czech Republic" ) ), 
            element(53, "Egypt", 
                element(6565, "Arab Republic of Egypt" ) ), 
            element(54, "Poland", 
                element(6610, "Republic of Poland" ) ) ), 
        element(5, "NGO National", 
            element(58, "National NGOs", 
                element(6549, "African Medical and Research Foundation -Tanzania" ), 
                element(6714, "NGO (Small Projects)" ), 
                element(6874, "Ifakara Medical Research Center" ), 
                element(6879, "National Malaria Control Programme" ), 
                element(6932, "Tanzania Youth Coalition" ), 
                element(6933, "Appropriate Technology training Institute" ), 
                element(6934, "Research on Poverty Alleviation" ), 
                element(6936, "Labour Market Information System" ), 
                element(7033, "AIDS Business Coalition of Tanzania(ABCT)" ), 
                element(7034, "CAMFED" ), 
                element(7035, "International Youth Foundation" ), 
                element(7036, "Kikundi cha HudumaMajumbani (KIHUMBE)" ), 
                element(7037, "Maasai Women Development Organization ( MWEDO)" ), 
                element(7038, "Mary knoll Sisters –EMUSOI" ), 
                element(7039, "Mbeya HIV Network Tanzania" ), 
                element(7040, "Pastoral Activities & Services for People with AIDS (PASADA" ), 
                element(7041, "Rsearch & Education for Democracy in Tanzania" ), 
                element(7042, "Resource Oriented Development Initiatives" ), 
                element(7043, "Savannas Forever Tanzania" ), 
                element(7044, "Selian Lutheran Hospital" ), 
                element(7045, "SONGONET-HIV Ruvuma" ), 
                element(7046, "Tanzania Community Civic Initiative" ), 
                element(7047, "Tanzania Marketing and Communications (T-MARK)" ), 
                element(7048, "Tanzania Youth Alliance" ), 
                element(7049, "Uzikwaza" ), 
                element(7050, "WAMA Foundation" ), 
                element(7051, "Women in Law and Development in Africa ( WILDAF" ), 
                element(7053, "Kilimanjaro International Corporation" ), 
                element(7067, "Appropriate Rural Technology Institute Africa" ), 
                element(7077, "PINGO" ), 
                element(7081, "Foundation for Civil Society" ), 
                element(7082, "Haki Elimu" ), 
                element(7083, "Tanzania Education Network" ), 
                element(7084, "Pastoralists Indigenous Non-Govermental Organisations" ), 
                element(7085, "Tanzania Women Lawyers Association" ), 
                element(7115, "SIKIKA" ), 
                element(7116, "CCBRT" ), 
                element(7117, "MEDIA COUNCIL OF TANZANIA" ), 
                element(7118, "RURAL LIVELIHOOD DEVELOPMENT PROGRAMME" ), 
                element(7119, "ANSAF" ), 
                element(7120, "AGENDA PARTICIPATION 2000(AP 2000)" ), 
                element(7121, "ST. FRANCIS HOSPITAL" ), 
                element(7123, "The Catholic Archdiocese of Tabora" ), 
                element(7124, "Nuru Orphans Centre" ), 
                element(7125, "Nanungu Secondary School" ), 
                element(7126, "Tanzania Association of NGOs" ), 
                element(7127, "Misenyi AIDS & Poverty Eradication Crusade (MAPEC)" ), 
                element(7128, "The Registered Trustees of Share and Care Foundation" ), 
                element(7129, "Buza Primary School" ), 
                element(7130, "Network Against Female Genital Mutilation" ), 
                element(7132, "Tanzania Forest conservation Group" ), 
                element(7133, "POLICY FORUM" ), 
                element(7138, "Economic Research Social Reform" ), 
                element(7147, "Tanzania Gender Networking Programm" ), 
                element(7148, "Tanzania Media Women’s Association" ), 
                element(7149, "Tanzania Women Cross-Party Platform" ), 
                element(7151, "Maasai Women Development Organization" ), 
                element(7153, "Women Legal Aid Centre" ), 
                element(7154, "Kilimanjaro Women Information Exchange and Consultancy Organization" ), 
                element(7156, "Third Millennium Peace Innitiative Foundation" ), 
                element(7157, "Tanzania Plantations & Agricultural Workers Union" ), 
                element(7183, "Christian Social Services Commission (CSSC)" ), 
                element(7184, "Comprehensive Community Based Rehabilitation in Tanzania (CCBRT)" ), 
                element(7185, "Association of Private Health Facilities in Tanzania (APHFTA)" ), 
                element(7301, "Legal and Human Rights Center" ), 
                element(7305, "BRAC Maendeleo Tanzania" ), 
                element(7309, "Legal Srvice Facility" ), 
                element(7324, "House of Peace" ), 
                element(7325, "Gender Training Institute" ), 
                element(7326, "Tanzania Police Female Network" ), 
                element(7334, "Hydom Lutheran Hospital" ), 
                element(7335, "Tanzania Traditional Energy Development Organization" ), 
                element(7356, "National Organization for Legal Aid" ), 
                element(7358, "Legal Services Facility" ), 
                element(7361, "Legal and Human Rights Centre" ), 
                element(7368, "Financial Sector Deepening Trust" ), 
                element(7369, "Private Agriculture Sector Support" ), 
                element(7401, "National Council of People Living with HIV AIDS" ), 
                element(7406, "Parapanda Threatre Trust Lab" ), 
                element(7409, "Women In Social Entrepreunship" ), 
                element(7410, "Tanga  Women Development" ), 
                element(7411, "CARE Tanzania" ), 
                element(7413, "Agricultural Market Development Trust" ), 
                element(7421, "Tanga Women Development" ), 
                element(7422, "MUDA AFRICA LIMITED BY GUARANTEE" ), 
                element(7426, "NAFASI  ART SPACE NGO" ), 
                element(7455, "vodafone foundation" ) ), 
            element(62, "Tanzania", 
                element(6926, "Ikisongo Pastoralist Initiatives" ), 
                element(6928, "Malangali Development Association" ), 
                element(6930, "Vikundi vya Biashara Ndogondogo" ), 
                element(7399, "Tanzania Forest Conservation. Group- TFCG" ), 
                element(7416, "Tanzania Private Sector Foundation" ), 
                element(7417, "Confederation of Tanzania Industries" ), 
                element(7429, "WORLD WIDE FUND FOR NATURE TANZANIA PROGRAMME OFFICE SOCIETY" ), 
                element(7457, "Development Credit Authority" ) ), 
            element(117, "CAMFED" ) ), 
        element(6, "NGO International", 
            element(50, "Italy (NGO)", 
                element(6557, "Caritas-va (D DOD)" ), 
                element(6867, "Development iniatives" ), 
                element(6891, "Associazione di Cooperazione Rurale in Africa ed America Latina" ), 
                element(6892, "Medici con l’ Africa CUAMM" ), 
                element(6893, "Comitato Europeo per la Formazione e l’Agricoltura" ), 
                element(6894, "ISTITUTO OIKOS" ), 
                element(6895, "IVO DE CARNERI - Fondazione Ivo De Carneri" ), 
                element(6896, "Cooperazione Paesi Emergenti" ), 
                element(7108, "Movimento per la Lotta alla Fame nel Mondo" ), 
                element(7109, "ARCI Cultura e Sviluppo" ), 
                element(7423, "AGMIN ITALTY SRL" ) ), 
            element(55, "UK", 
                element(6619, "Concern-uk" ) ), 
            element(59, "Switzerland", 
                element(6715, "Swiss Tropical Institute" ), 
                element(7397, "Helvetas Swiss Intercooperation" ), 
                element(7398, "SIMAVI" ) ), 
            element(60, "USA", 
                element(6921, "Pact Tanzania" ), 
                element(6922, "Population Services International" ), 
                element(6953, "Academy for Educational Development (AED)" ), 
                element(6954, "African Palliative Care Association" ), 
                element(6955, "African Wildlife Foundation (AWF)" ), 
                element(6956, "Adventists Development and Relief Agency" ), 
                element(6957, "Africare" ), 
                element(6958, "American International Health Alliance" ), 
                element(6959, "American Society of Clinical Pathology" ), 
                element(6960, "Associates in Rural Development" ), 
                element(6961, "Association of Public Health Laboratories" ), 
                element(6962, "American Red Cross" ), 
                element(6965, "Catholic Relief Services (CRS)" ), 
                element(6966, "Comprehensive Africa Agriculture Development" ), 
                element(6967, "Education Development Center inc" ), 
                element(6969, "Emerging Markets Group Ltd.(D&T)" ), 
                element(6970, "Engender Health" ), 
                element(6971, "Family Health International (FHI)" ), 
                element(6972, "Floresta" ), 
                element(6973, "Foundation for HISS" ), 
                element(6974, "Francois-Xavier Bagnoud Center" ), 
                element(6975, "Global Deaf Connection" ), 
                element(6976, "Harvard University School of Public Health" ), 
                element(6977, "IntraHealth International" ), 
                element(6980, "Johns Hopkins University" ), 
                element(6981, "MACRO International" ), 
                element(6982, "Management Sciences for Health Inc" ), 
                element(6983, "Mennonite Economic Development Associates ( MEDA)" ), 
                element(6984, "Partnership for Supply Chain Management" ), 
                element(6985, "Pathfinder International" ), 
                element(6986, "Program for Appropriate Technology in Health (PATH)" ), 
                element(6987, "Research Triangle Institute (RTI)" ), 
                element(6988, "Salvation Army" ), 
                element(6989, "Search for Common Ground" ), 
                element(6990, "Salesian Mission" ), 
                element(6991, "Strategic Radio Communication for Development" ), 
                element(6992, "Technoserve Inc" ), 
                element(6993, "The African Field Epidemiology Network" ), 
                element(6994, "The American Society for Microbiology" ), 
                element(6995, "The Mitchell Group inc" ), 
                element(6996, "The World Wildlife Fund Inc (WWF)" ), 
                element(6997, "Touch Foundation, Inc" ), 
                element(6998, "Tulane University" ), 
                element(6999, "UNC Chapel Hill" ), 
                element(7000, "University of Maine" ), 
                element(7001, "University Research Corporation, LLC" ), 
                element(7002, "World Education inc" ), 
                element(7004, "Florida International University" ), 
                element(7005, "University of California at San Francisco" ), 
                element(7006, "University of Rhode Island" ), 
                element(7007, "University of Washington" ), 
                element(7010, "National Institutes of Health" ) ), 
            element(93, "Canada (NGO)", 
                element(6764, "Development intenational Desjadins" ), 
                element(7394, "Canadian Network for International Surgery" ) ), 
            element(102, "International NGO", 
                element(6968, "Elizabeth Glaser Pediatric AIDS Foundation (EGPAF)" ), 
                element(6978, "Jane Goodall Institute" ), 
                element(6979, "JHPIEGO" ), 
                element(7003, "World Vision, inc" ), 
                element(7076, "Save the Children" ), 
                element(7078, "Forum Syd" ), 
                element(7079, "Student Partnership Worldwide" ), 
                element(7158, "CARITAS" ), 
                element(7171, "Cambridge Education" ), 
                element(7172, "British Council" ), 
                element(7173, "Oxford Policy Management" ), 
                element(7180, "FEMINA Health Information Project" ), 
                element(7181, "Funding Innovation for Business In Africa" ), 
                element(7302, "Voluntary Services Overseas" ), 
                element(7303, "Restless Development" ), 
                element(7304, "Gatsy Charitable Foundation" ), 
                element(7306, "Helen Keller International" ), 
                element(7307, "Aga Khan Foundation" ), 
                element(7333, "Clinton Health Access Initiative" ), 
                element(7337, "Global Network of Religions For Children" ), 
                element(7340, "ACDI/VOCA" ), 
                element(7344, "MCCAFREY" ), 
                element(7345, "societa Italiana Di Monitoraggio SPA" ), 
                element(7349, "SWECO INTERNATIONAL AB" ), 
                element(7354, "VECO" ), 
                element(7355, "Canadian International Immunization Initiative" ), 
                element(7373, "South Africa Extension Unit" ), 
                element(7380, "TRIAS" ), 
                element(7403, "PLAN INTERNATIONAL DEUTSCHLAND EV" ), 
                element(7407, "Humberger Wasserwerke GMBH" ), 
                element(7424, "NOVAK" ), 
                element(7430, "ASTALDI SPA" ), 
                element(7453, "fhi360" ), 
                element(7454, "population council" ), 
                element(7456, "ICF Internationa" ), 
                element(7458, "PELUM" ) ), 
            element(111, "Center for International Development & Research(CIDR", 
                element(7017, "Center for International Development & Research(CIDR" ) ), 
            element(112, "Health Insurance Fund", 
                element(7018, "Health Insurance Fund" ) ), 
            element(113, "PharmAccess", 
                element(7019, "PharmAccess" ) ), 
            element(114, "SolarAid", 
                element(7020, "SolarAid" ) ), 
            element(129, "Switzerland (NGOs)", 
                element(7134, "Center for Development and Enviroment(university of Bern.)" ), 
                element(7135, "Swiss Federal Laboratories for Material testing and research" ) ) ), 
        element(7, "Other", 
            element(45, "Tanzania Import", 
                element(6551, "Austria" ), 
                element(6558, "CFC" ), 
                element(6559, "CFTC" ), 
                element(6561, "CS" ), 
                element(6574, "GDS (DED-GFR)" ), 
                element(6582, "IAEA" ), 
                element(6586, "IFDB" ), 
                element(6594, "ITU" ), 
                element(6598, "Kuwait" ), 
                element(6602, "NDF" ), 
                element(6605, "NIR/NTF" ), 
                element(6606, "NORTF" ), 
                element(6608, "NSD" ), 
                element(6612, "RA/CIMADE" ), 
                element(6616, "SSO" ), 
                element(6628, "x_UNFPA" ), 
                element(6631, "x_UNIDO" ), 
                element(6634, "UNSO" ), 
                element(6636, "UPU" ), 
                element(6637, "USA CRS" ), 
                element(6641, "WIPO" ), 
                element(6642, "WMO" ), 
                element(6931, "University Consultancy Bureau" ), 
                element(6935, "Dar Es Salaam Institute of Technology" ), 
                element(6937, "Trade Union Congress of Tanzania" ), 
                element(7400, "Eastern and Southern Africa Ant-Money Laundering Group" ) ), 
            element(130, "High Learning Institutions", 
                element(7137, "Department of Economics, University of Dar es Salaam" ), 
                element(7336, "HAUKELAND UNIVERSITESSYKEHUS" ), 
                element(7341, "Tumaini University Makumira" ), 
                element(7389, "University of Saskatchewan" ), 
                element(7412, "Uongozi Institute" ) ) ), 
        element(8, "Private", 
            element(34, "GAVI Alliance", 
                element(82, "GAVI Alliance" ) ), 
            element(41, "Axios Corporation", 
                element(6552, "Axios" ) ), 
            element(44, "African Capacity Building Foundation", 
                element(69, "African Capacity Building Foundation" ), 
                element(6949, "EAC" ) ), 
            element(105, "Balm in Gilead", 
                element(7011, "Balm in Gilead" ) ), 
            element(106, "Booz Allen Hamilton", 
                element(7012, "Booz Allen Hamilton" ) ), 
            element(107, "Fintracinc", 
                element(7013, "Fintracinc" ) ), 
            element(108, "General Mills", 
                element(7014, "General Mills" ) ), 
            element(109, "John Snow Inc.", 
                element(7015, "John Snow Inc." ) ), 
            element(110, "The Futures Group International", 
                element(7016, "The Futures Group International" ) ), 
            element(115, "UCC", 
                element(7031, "University Computing Center" ) ), 
            element(116, "Agricultural Council of Tanzania (ACT", 
                element(7032, "Agricultural Council of Tanzania (ACT" ) ), 
            element(118, "Deloitte Consulting Limited", 
                element(7052, "Deloitte Consulting Limited" ) ), 
            element(123, "Foundation", 
                element(7072, "Bill & Melinda Gates" ), 
                element(7074, "Foundation for Innovative for New Diagnistic" ), 
                element(7182, "Hanns R. Neumann Stiftung" ) ), 
            element(124, "Fund", 
                element(7080, "Tanzania Media Fund" ), 
                element(7360, "Association of Local Authority of Tanzania" ), 
                element(7415, "Local Investment Climate" ), 
                element(7420, "Small Industrial Facilitation Fund" ) ), 
            element(126, "CRDB BANK", 
                element(7122, "CRDB" ) ), 
            element(132, "Professinal Association", 
                element(7146, "Tanzania Women Judges Association" ), 
                element(7152, "Tanzania Women Parliamentary Group" ), 
                element(7346, "PARTICIP GMBH CONSULTANTS FUR ENTWICKLUNG UND UMWELT" ), 
                element(7348, "IBF INTERNATIONALCONSULTING SA" ), 
                element(7374, "Association of Tanzania Employers" ), 
                element(7408, "Ace International Consultants SL" ), 
                element(7414, "Association of Local Authorities of Tanzania" ) ), 
            element(133, "Limited Companies", 
                element(7150, "Tanzania Women’s Chamber of Commerce" ), 
                element(7206, "KPMG" ), 
                element(7310, "Rex Attorneys" ), 
                element(7343, "Lukolo Company Limited" ), 
                element(7347, "UNIT EXPORT LIMITED" ), 
                element(7350, "DUNEA NV" ), 
                element(7359, "WISE Development Ltd" ), 
                element(7418, "COWI Tanzania Limited" ), 
                element(7428, "CAMCO ADVISORY SERVICES (TANZANIA) LTD" ), 
                element(7431, "SMEC INTERNATIONAL PTY LIMITED" ) ) ), 
        element(9, "FUND", 
            element(999999999, "Undefined", 
                element(0, null ) ) ));
    }
}

