package org.dgfoundation.amp.nireports.testcases.tanzania.dimensions;

import org.dgfoundation.amp.nireports.testcases.HNDNode;
import org.dgfoundation.amp.nireports.testcases.HardcodedNiDimension;

import java.util.Arrays;
import java.util.List;

import static org.dgfoundation.amp.nireports.testcases.HNDNode.element;

public class SectorsTestDimension extends HardcodedNiDimension {

    public SectorsTestDimension(String name, int depth) {
        super(name, depth);
    }

    public final static SectorsTestDimension instance = new SectorsTestDimension("sectors", 3);

    @Override
    protected List<HNDNode> buildHardcodedElements() {
        return Arrays.asList(
        element(256, "PRIVATE SECTOR DEVELOPMENT", 
            element(330, "SMEs and Informal Sector" ), 
            element(331, "Agriculture" ) ), 
        element(257, "ROADS", 
            element(332, "Bridge Construction and Maintenance" ), 
            element(333, "Rural/District Roads and Maintenance" ), 
            element(334, "Trunk Roads and Maintenance" ), 
            element(335, "Urban Roads and Maintenance" ) ), 
        element(258, "RURAL DEVELOPMENT", 
            element(336, "Education" ), 
            element(337, "Food Security" ), 
            element(338, "Health/Nutrition" ), 
            element(339, "HIV/AIDS" ), 
            element(340, "Water and Sanitation" ) ), 
        element(259, "SOCIAL DEVELOPMENT", 
            element(341, "Crime and Drug Abuse" ), 
            element(342, "Culture" ), 
            element(343, "Gender" ), 
            element(344, "Housing" ), 
            element(345, "Labour/Workers Rights" ), 
            element(346, "Monitoring/Research" ), 
            element(347, "Urban Development" ) ), 
        element(260, "INFRASTRUCTURE", 
            element(263, "Roads" ), 
            element(264, "Railways" ) ), 
        element(261, "WATER", 
            element(355, "Irrigation" ), 
            element(356, "Rural Water Supply and Sanitation" ), 
            element(357, "Urban Water Supply and Sanitation" ), 
            element(362, "Industrial Development" ) ), 
        element(268, "CULTURE" ), 
        element(269, "INNOVATIONS & TECHNOLOGY" ), 
        element(348, "TRANSPORT AND COMMUNICATION", 
            element(349, "Air Transport" ), 
            element(350, "Rail Transport" ), 
            element(351, "Telecomunication" ), 
            element(352, "Water Transport and Shipping" ), 
            element(353, "Telecommunications" ), 
            element(354, "Television, Radio and Print Media" ) ), 
        element(358, "OTHER" ), 
        element(361, "EMERGENCY" ), 
        element(363, "ICT" ), 
        element(237, "AGRICULTURE", 
            element(271, "Agricultural Marketing and Co-operatives" ), 
            element(272, "Agricultural Research" ), 
            element(273, "Agricultural Sector Policy Planning and Management" ), 
            element(274, "Irrigation" ), 
            element(275, "Livestock" ), 
            element(276, "Fisheries" ), 
            element(277, "Food Security" ), 
            element(278, "Forestry" ) ), 
        element(238, "BUDGET SUPPORT" ), 
        element(239, "DEBT RELIEF" ), 
        element(240, "DEVELOPMENT ADMINISTRATION", 
            element(279, "General Statistics (incl. demography)" ), 
            element(280, "General Cartography" ), 
            element(281, "Foreign Affairs" ), 
            element(282, "Regional Integration" ), 
            element(283, "Donor/Embassy Administration" ), 
            element(284, "NGO Coordination" ) ), 
        element(241, "DEFENSE AND SECURITY" ), 
        element(242, "ECONOMIC MANAGEMENT", 
            element(285, "Public Financial Management" ), 
            element(286, "Economic Planning and Policy" ), 
            element(287, "Tax Administration" ), 
            element(288, "Poverty Reduction Strategy Monitoring" ), 
            element(289, "Aid Coordination" ) ), 
        element(243, "EDUCATION", 
            element(290, "Primary Education" ), 
            element(291, "Secondary Education" ), 
            element(292, "Tertiary Education" ), 
            element(293, "Non-formal Education" ), 
            element(294, "Vocational Education" ) ), 
        element(244, "ENERGY AND MINERALS", 
            element(295, "Conventional Energy Resource Generation and Transmission" ), 
            element(296, "Energy Conservation" ), 
            element(297, "Geothermal Power Generation and Transmission" ), 
            element(298, "Hydroelectric Power Generation and Transmission" ), 
            element(299, "Minerals" ), 
            element(300, "New and Renewable Energy" ) ), 
        element(245, "ENVIRONMENT", 
            element(301, "Environmental Management" ), 
            element(302, "Pollution" ), 
            element(303, "Environmental Preservation" ), 
            element(304, "Wildlife and Natural Parks" ) ), 
        element(246, "GENDER" ), 
        element(247, "GOVERNANCE", 
            element(305, "Democratic Development" ), 
            element(306, "Anti-corruption" ), 
            element(307, "Civil Service Reform" ), 
            element(308, "Local Government Reform" ), 
            element(309, "Decentralisation" ), 
            element(310, "Public Sector Reform" ) ), 
        element(248, "HEALTH", 
            element(311, "Family Planning" ), 
            element(312, "Health Nutrition" ), 
            element(313, "Hospital and Clinics" ), 
            element(314, "Immunization and other disease control campaign" ), 
            element(315, "Primary Health Care incl. maternal and child health" ) ), 
        element(249, "HIV/AIDS" ), 
        element(250, "HUMAN RESOURCE DEVELOPMENT" ), 
        element(251, "HUMANITARIAN (INCL REFUGEES)", 
            element(316, "Disaster Response" ), 
            element(317, "Refugees" ), 
            element(318, "Emergency Food Aid" ) ), 
        element(252, "INDUSTRY AND TRADE" ), 
        element(253, "LEGAL" ), 
        element(254, "NATURAL RESOURCES AND TOURISM", 
            element(319, "Environmental Management/Preservation" ), 
            element(320, "Forestry and Beekeeping" ), 
            element(321, "Land" ), 
            element(322, "Pollution Control" ), 
            element(323, "Sector Policy/Planning" ), 
            element(324, "Wildlife and Natural Parks" ), 
            element(325, "Urban Environment" ) ), 
        element(255, "PUBLIC FINANCIAL MANAGEMENT", 
            element(326, "AcGen" ), 
            element(327, "Audit" ), 
            element(328, "Fiscal" ), 
            element(329, "Macro" ) ));
    }
}

