<?php

function hs_select_locations_hierarchical_select_params() {
  $params = array(
    'id',
  	'separator'
  );
  return $params;
}

function hs_select_locations_hierarchical_select_root_level($params) {
  $hierarchy = hs_select_locations_build_tree($params['pid']);
  $children = $hierarchy['root']['children'];
  $level = array();
  foreach ($children as $key => $value) {
    $level[$key] = $hierarchy[$key]['label'];
  }

  return $level; 
}

function hs_select_locations_hierarchical_select_lineage($item, $params) {
	 $parts = explode($params['separator'], $item);
	 $lineage = array();
  for ($i = 0; $i < count($parts); $i++) {
    $lineage[$i] = implode($params['separator'], array_slice($parts, 0, $i + 1));
  }
	return $lineage;
}

/**
 * Implementation of hook_hierarchical_select_children().
 */
function hs_select_locations_hierarchical_select_children($parent, $params) {
  $hierarchy = hs_select_locations_load_tree($parent);
  return $hierarchy[$parent];
  $hierarchy = hs_select_locations_build_tree($parent);
  
  $items = $hierarchy['root'][$parent]['children'];
  
  return $items;
}

/**
 * Implementation of hook_hierarchical_select_valid_item().
 */
function hs_select_locations_hierarchical_select_valid_item($item, $params) {
	
	return (is_numeric($item) && $item > 0);
	
  $hierarchy = hs_select_locations_load_tree($item);
  /* check is it in root */
  if(array_key_exists($item, $hierarchy[0])) {
  		return $hierarchy[0][$item];
  }
  
  if(array_key_exists($item, $hierarchy))
  	return $hierarchy[$item];
  return -1;
}


/**
 * Implementation of hook_hierarchical_select_item_get_label().
 */
function hs_select_locations_hierarchical_select_item_get_label($item, $params) {
  $hierarchy = hs_select_locations_load_tree($params['pid']);
  
  return $hierarchy[$item]['label'];
}

function hs_select_locations_get_items($parent = 0) {
	db_set_active("amp_projects");
	$items = array();
	
	if($parent == 0) {
		$op = 'IS NULL';
	} else {
		$op = '=';
	}
	
	global $language;
    $translate_field = "translate_field('org.digijava.module.aim.dbentity.AmpCategoryValueLocations', 'name', loc.id, 'amp_category_value_location', 'location_name', 'id', '" . $language->language . "')";    
	
	$query = db_select('amp_category_value_location', 'location')->fields('location', array('id'));
	$query->addExpression($translate_field, 'location_name');
	$query->condition('location.parent_location', $parent, $op);
	$query->orderBy('location_name', 'ASC');
	$result = $query->execute();
	
 	foreach ($result as $record) {
      $items[$record->id] = check_plain($record->location_name);
    }
	db_set_active();
	
	return $items;
}

function hs_select_locations_load_tree($parent = 0) {
	db_set_active("amp_projects");
	
	$items = array();
	
	if (!is_numeric($parent)) {
		return $items;
	}
	
	if (empty($parent)) {
		// We retrieve the country setting for the AMP installation
		$query = db_select('amp_global_settings', 'setting')->fields('setting', array('settingsvalue'));
		$query->condition('setting.settingsname', 'Default Country', '=');
		$defaultCountry = $query->execute()->fetchCol();
		
		if (!empty($defaultCountry)) {
			$defaultCountry = current($defaultCountry);
		}
		
		// Convert the country ISO to location ID such that we only handle regions within the current country
		if (!empty($defaultCountry)) {
			$query = db_select('amp_category_value_location', 'loc')->fields('loc', array('id'));
			$query->condition('loc.iso', $defaultCountry, '=');
			$query->condition('loc.parent_location', NULL, 'is');
			$parents = $query->execute()->fetchCol();
			if (!empty($parents)) {
				$isTopParent = TRUE;
				$parent = current($parents);
			}
		}
	}
	
	if (empty($parent)) {
		$parent = 0;
		$op = 'IS NULL';
	} else {
		$op = '=';
	}

	global $language;
    $translate_field = "translate_field('org.digijava.module.aim.dbentity.AmpCategoryValueLocations', 'name', loc.id, 'amp_category_value_location', 'location_name', 'id', '" . $language->language . "')";    
	
	$query = db_select('amp_category_value_location', 'loc')->fields('loc', array('id', 'parent_location'));
	$query->addExpression($translate_field, 'location_name');
	$query->condition('loc.parent_location', $parent, $op);
	 		
	$query->orderBy('location_name', 'ASC');
	$result = $query->execute();
	
	if ($isTopParent) {
		$parent = 0;
	}
	foreach ($result as $record) {
      $items[$parent][$record->id] = $record->location_name;
      $sub_items = hs_select_locations_load_tree($record->id);
      if(!empty($sub_items)) {
      	$items +=  $sub_items;
      }
    }
    
	db_set_active();
	return $items;
}


function hs_select_locations_build_tree($parent, $heirarchy = array()) {
	$original_tree =  hs_select_locations_load_tree($parent);
	$tree = array();
	foreach ($original_tree[$parent] as $key => $value) {
		$tree['root']['children'][$key] = $key;
		$tree[$key]['label'] = $value;
		if(!empty($original_tree[$key])) {
			foreach ($original_tree[$key] as $child_key => $child_value) {
				$tree[$key]['children'][$child_key] = $child_key;
				$tree[$child_key]['label'] = $child_value;
			}
		}
	}
	return $tree;
}
/**
 * Implementation of hook_hierarchical_select_implementation_info().
 */
function hs_select_locations_hierarchical_select_implementation_info() {
  return array(
    'hierarchy type' => t('Custom'),
    'entity type'    => t('N/A'),
  );
}

function hs_select_locations_get_item_name($id) {
	db_set_active("amp_projects");
	
	global $language;
    $translate_field = "translate_field('org.digijava.module.aim.dbentity.AmpCategoryValueLocations', 'name', loc.id, 'amp_category_value_location', 'location_name', 'id', '" . $language->language . "')";    
	
	$query = db_select('amp_category_value_location', 'loc')->fields('loc', array('id'));
	$query->addExpression($translate_field, 'location_name');
	$query->leftJoin('amp_location', 'aloc', 'aloc.location_id=loc.id');
	$query->fields('aloc', array('amp_location_id'));
	$query->condition('loc.id', $id, '=');
	
	$result = $query->execute();
	$item = array();
	foreach ($result as $record) {
		$item[] = array('id' => $record->id, 'name' => check_plain($record->location_name));
	}

	db_set_active();
	return $item;
}