//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.19 at 04:51:40 GMT+04:00 
//


package org.digijava.module.ampharvester.jaxb10.impl;

public class FundingDetailTypeImpl implements org.digijava.module.ampharvester.jaxb10.FundingDetailType, com.sun.xml.bind.JAXBObject, org.digijava.module.ampharvester.jaxb10.impl.runtime.UnmarshallableObject, org.digijava.module.ampharvester.jaxb10.impl.runtime.XMLSerializable, org.digijava.module.ampharvester.jaxb10.impl.runtime.ValidatableObject
{

    protected boolean has_Amount;
    protected long _Amount;
    protected boolean has_AdjustmentType;
    protected int _AdjustmentType;
    protected java.util.Calendar _Date;
    protected java.lang.String _CurrencyCode;
    protected boolean has_PerspectiveType;
    protected int _PerspectiveType;
    public final static java.lang.Class version = (org.digijava.module.ampharvester.jaxb10.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (org.digijava.module.ampharvester.jaxb10.FundingDetailType.class);
    }

    public long getAmount() {
        return _Amount;
    }

    public void setAmount(long value) {
        _Amount = value;
        has_Amount = true;
    }

    public int getAdjustmentType() {
        return _AdjustmentType;
    }

    public void setAdjustmentType(int value) {
        _AdjustmentType = value;
        has_AdjustmentType = true;
    }

    public java.util.Calendar getDate() {
        return _Date;
    }

    public void setDate(java.util.Calendar value) {
        _Date = value;
    }

    public java.lang.String getCurrencyCode() {
        return _CurrencyCode;
    }

    public void setCurrencyCode(java.lang.String value) {
        _CurrencyCode = value;
    }

    public int getPerspectiveType() {
        return _PerspectiveType;
    }

    public void setPerspectiveType(int value) {
        _PerspectiveType = value;
        has_PerspectiveType = true;
    }

    public org.digijava.module.ampharvester.jaxb10.impl.runtime.UnmarshallingEventHandler createUnmarshaller(org.digijava.module.ampharvester.jaxb10.impl.runtime.UnmarshallingContext context) {
        return new org.digijava.module.ampharvester.jaxb10.impl.FundingDetailTypeImpl.Unmarshaller(context);
    }

    public void serializeBody(org.digijava.module.ampharvester.jaxb10.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        if (!has_Amount) {
            context.reportError(com.sun.xml.bind.serializer.Util.createMissingObjectError(this, "Amount"));
        }
        if (!has_AdjustmentType) {
            context.reportError(com.sun.xml.bind.serializer.Util.createMissingObjectError(this, "AdjustmentType"));
        }
        if (!has_PerspectiveType) {
            context.reportError(com.sun.xml.bind.serializer.Util.createMissingObjectError(this, "PerspectiveType"));
        }
    }

    public void serializeAttributes(org.digijava.module.ampharvester.jaxb10.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        if (!has_Amount) {
            context.reportError(com.sun.xml.bind.serializer.Util.createMissingObjectError(this, "Amount"));
        }
        if (!has_AdjustmentType) {
            context.reportError(com.sun.xml.bind.serializer.Util.createMissingObjectError(this, "AdjustmentType"));
        }
        if (!has_PerspectiveType) {
            context.reportError(com.sun.xml.bind.serializer.Util.createMissingObjectError(this, "PerspectiveType"));
        }
        context.startAttribute("", "adjustmentType");
        try {
            context.text(javax.xml.bind.DatatypeConverter.printInt(((int) _AdjustmentType)), "AdjustmentType");
        } catch (java.lang.Exception e) {
            org.digijava.module.ampharvester.jaxb10.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endAttribute();
        context.startAttribute("", "amount");
        try {
            context.text(javax.xml.bind.DatatypeConverter.printLong(((long) _Amount)), "Amount");
        } catch (java.lang.Exception e) {
            org.digijava.module.ampharvester.jaxb10.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endAttribute();
        context.startAttribute("", "currencyCode");
        try {
            context.text(((java.lang.String) _CurrencyCode), "CurrencyCode");
        } catch (java.lang.Exception e) {
            org.digijava.module.ampharvester.jaxb10.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endAttribute();
        context.startAttribute("", "date");
        try {
            context.text(javax.xml.bind.DatatypeConverter.printDate(((java.util.Calendar) _Date)), "Date");
        } catch (java.lang.Exception e) {
            org.digijava.module.ampharvester.jaxb10.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endAttribute();
        context.startAttribute("", "perspectiveType");
        try {
            context.text(javax.xml.bind.DatatypeConverter.printInt(((int) _PerspectiveType)), "PerspectiveType");
        } catch (java.lang.Exception e) {
            org.digijava.module.ampharvester.jaxb10.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endAttribute();
    }

    public void serializeURIs(org.digijava.module.ampharvester.jaxb10.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        if (!has_Amount) {
            context.reportError(com.sun.xml.bind.serializer.Util.createMissingObjectError(this, "Amount"));
        }
        if (!has_AdjustmentType) {
            context.reportError(com.sun.xml.bind.serializer.Util.createMissingObjectError(this, "AdjustmentType"));
        }
        if (!has_PerspectiveType) {
            context.reportError(com.sun.xml.bind.serializer.Util.createMissingObjectError(this, "PerspectiveType"));
        }
    }

    public java.lang.Class getPrimaryInterface() {
        return (org.digijava.module.ampharvester.jaxb10.FundingDetailType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000b"
+"expandedExpq\u0000~\u0000\u0002xpppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsr\u0000 com.sun.msv."
+"grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameClasst\u0000\u001fLco"
+"m/sun/msv/grammar/NameClass;xq\u0000~\u0000\u0003ppsr\u0000\u001bcom.sun.msv.grammar."
+"DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype/Datatype;L\u0000\u0006"
+"exceptq\u0000~\u0000\u0002L\u0000\u0004namet\u0000\u001dLcom/sun/msv/util/StringPair;xq\u0000~\u0000\u0003ppsr"
+"\u0000 com.sun.msv.datatype.xsd.IntType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000+com.sun.msv"
+".datatype.xsd.IntegerDerivedType\u0099\u00f1]\u0090&6k\u00be\u0002\u0000\u0001L\u0000\nbaseFacetst\u0000)L"
+"com/sun/msv/datatype/xsd/XSDatatypeImpl;xr\u0000*com.sun.msv.data"
+"type.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatyp"
+"e.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype.xsd.XS"
+"DatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUrit\u0000\u0012Ljava/lang/String;L"
+"\u0000\btypeNameq\u0000~\u0000\u0016L\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/datatype/xsd/Whi"
+"teSpaceProcessor;xpt\u0000 http://www.w3.org/2001/XMLSchemat\u0000\u0003int"
+"sr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Collapse\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u0000*com.sun.msv.datatype.xsd.MaxInclusiveFacet\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000#com.sun.msv.datatype.xsd.RangeFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\nl"
+"imitValuet\u0000\u0012Ljava/lang/Object;xr\u00009com.sun.msv.datatype.xsd.D"
+"ataTypeWithValueConstraintFacet\"\u00a7Ro\u00ca\u00c7\u008aT\u0002\u0000\u0000xr\u0000*com.sun.msv.da"
+"tatype.xsd.DataTypeWithFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0005Z\u0000\fisFacetFixedZ\u0000\u0012nee"
+"dValueCheckFlagL\u0000\bbaseTypeq\u0000~\u0000\u0012L\u0000\fconcreteTypet\u0000\'Lcom/sun/ms"
+"v/datatype/xsd/ConcreteType;L\u0000\tfacetNameq\u0000~\u0000\u0016xq\u0000~\u0000\u0015ppq\u0000~\u0000\u001d\u0000\u0001"
+"sr\u0000*com.sun.msv.datatype.xsd.MinInclusiveFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000"
+"~\u0000\u001fppq\u0000~\u0000\u001d\u0000\u0000sr\u0000!com.sun.msv.datatype.xsd.LongType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000"
+"xq\u0000~\u0000\u0011q\u0000~\u0000\u0019t\u0000\u0004longq\u0000~\u0000\u001dsq\u0000~\u0000\u001eppq\u0000~\u0000\u001d\u0000\u0001sq\u0000~\u0000%ppq\u0000~\u0000\u001d\u0000\u0000sr\u0000$com"
+".sun.msv.datatype.xsd.IntegerType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0011q\u0000~\u0000\u0019t\u0000\u0007in"
+"tegerq\u0000~\u0000\u001dsr\u0000,com.sun.msv.datatype.xsd.FractionDigitsFacet\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001I\u0000\u0005scalexr\u0000;com.sun.msv.datatype.xsd.DataTypeWithLe"
+"xicalConstraintFacetT\u0090\u001c>\u001azb\u00ea\u0002\u0000\u0000xq\u0000~\u0000\"ppq\u0000~\u0000\u001d\u0001\u0000sr\u0000#com.sun.ms"
+"v.datatype.xsd.NumberType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0013q\u0000~\u0000\u0019t\u0000\u0007decimalq\u0000~"
+"\u0000\u001dq\u0000~\u00003t\u0000\u000efractionDigits\u0000\u0000\u0000\u0000q\u0000~\u0000-t\u0000\fminInclusivesr\u0000\u000ejava.lan"
+"g.Long;\u008b\u00e4\u0090\u00cc\u008f#\u00df\u0002\u0000\u0001J\u0000\u0005valuexr\u0000\u0010java.lang.Number\u0086\u00ac\u0095\u001d\u000b\u0094\u00e0\u008b\u0002\u0000\u0000xp\u0080\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0000q\u0000~\u0000-t\u0000\fmaxInclusivesq\u0000~\u00007\u007f\u00ff\u00ff\u00ff\u00ff\u00ff\u00ff\u00ffq\u0000~\u0000(q\u0000~\u00006sr\u0000\u0011java.l"
+"ang.Integer\u0012\u00e2\u00a0\u00a4\u00f7\u0081\u00878\u0002\u0000\u0001I\u0000\u0005valuexq\u0000~\u00008\u0080\u0000\u0000\u0000q\u0000~\u0000(q\u0000~\u0000:sq\u0000~\u0000<\u007f\u00ff\u00ff\u00ff"
+"sr\u00000com.sun.msv.grammar.Expression$NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001"
+"\u0002\u0000\u0000xq\u0000~\u0000\u0003ppsr\u0000\u001bcom.sun.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tloca"
+"lNameq\u0000~\u0000\u0016L\u0000\fnamespaceURIq\u0000~\u0000\u0016xpq\u0000~\u0000\u001aq\u0000~\u0000\u0019sr\u0000#com.sun.msv.gr"
+"ammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u0016L\u0000\fnamespac"
+"eURIq\u0000~\u0000\u0016xr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u000ead"
+"justmentTypet\u0000\u0000sq\u0000~\u0000\tppsq\u0000~\u0000\fppq\u0000~\u0000(q\u0000~\u0000@sq\u0000~\u0000Aq\u0000~\u0000)q\u0000~\u0000\u0019sq\u0000"
+"~\u0000Ct\u0000\u0006amountq\u0000~\u0000Gsq\u0000~\u0000\tppsq\u0000~\u0000\fppsr\u0000#com.sun.msv.datatype.xs"
+"d.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxq\u0000~\u0000\u0013q\u0000~\u0000\u0019t\u0000\u0006strings"
+"r\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Preserve\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u001c\u0001q\u0000~\u0000@sq\u0000~\u0000Aq\u0000~\u0000Qq\u0000~\u0000\u0019sq\u0000~\u0000Ct\u0000\fcurrencyCodeq\u0000~\u0000"
+"Gsq\u0000~\u0000\tppsq\u0000~\u0000\fppsr\u0000!com.sun.msv.datatype.xsd.DateType\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0001\u0002\u0000\u0000xr\u0000)com.sun.msv.datatype.xsd.DateTimeBaseType\u0014W\u001a@3\u00a5\u00b4\u00e5\u0002\u0000"
+"\u0000xq\u0000~\u0000\u0013q\u0000~\u0000\u0019t\u0000\u0004dateq\u0000~\u0000\u001dq\u0000~\u0000@sq\u0000~\u0000Aq\u0000~\u0000\\q\u0000~\u0000\u0019sq\u0000~\u0000Ct\u0000\u0004dateq\u0000"
+"~\u0000Gsq\u0000~\u0000\tppq\u0000~\u0000\u000fsq\u0000~\u0000Ct\u0000\u000fperspectiveTypeq\u0000~\u0000Gsr\u0000\"com.sun.msv"
+".grammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv"
+"/grammar/ExpressionPool$ClosedHash;xpsr\u0000-com.sun.msv.grammar"
+".ExpressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rstreamVersio"
+"nL\u0000\u0006parentt\u0000$Lcom/sun/msv/grammar/ExpressionPool;xp\u0000\u0000\u0000\u0004\u0001pq\u0000~"
+"\u0000\u0007q\u0000~\u0000\u0006q\u0000~\u0000\u0005q\u0000~\u0000\bx"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends org.digijava.module.ampharvester.jaxb10.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(org.digijava.module.ampharvester.jaxb10.impl.runtime.UnmarshallingContext context) {
            super(context, "----------------");
        }

        protected Unmarshaller(org.digijava.module.ampharvester.jaxb10.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return org.digijava.module.ampharvester.jaxb10.impl.FundingDetailTypeImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        attIdx = context.getAttribute("", "amount");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText1(v);
                            state = 6;
                            continue outer;
                        }
                        break;
                    case  9 :
                        attIdx = context.getAttribute("", "date");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText2(v);
                            state = 12;
                            continue outer;
                        }
                        break;
                    case  6 :
                        attIdx = context.getAttribute("", "currencyCode");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText3(v);
                            state = 9;
                            continue outer;
                        }
                        break;
                    case  12 :
                        attIdx = context.getAttribute("", "perspectiveType");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText4(v);
                            state = 15;
                            continue outer;
                        }
                        break;
                    case  15 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  0 :
                        attIdx = context.getAttribute("", "adjustmentType");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText5(v);
                            state = 3;
                            continue outer;
                        }
                        break;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        private void eatText1(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Amount = javax.xml.bind.DatatypeConverter.parseLong(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
                has_Amount = true;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText2(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Date = javax.xml.bind.DatatypeConverter.parseDate(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText3(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _CurrencyCode = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText4(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _PerspectiveType = javax.xml.bind.DatatypeConverter.parseInt(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
                has_PerspectiveType = true;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText5(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _AdjustmentType = javax.xml.bind.DatatypeConverter.parseInt(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
                has_AdjustmentType = true;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        attIdx = context.getAttribute("", "amount");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText1(v);
                            state = 6;
                            continue outer;
                        }
                        break;
                    case  9 :
                        attIdx = context.getAttribute("", "date");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText2(v);
                            state = 12;
                            continue outer;
                        }
                        break;
                    case  6 :
                        attIdx = context.getAttribute("", "currencyCode");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText3(v);
                            state = 9;
                            continue outer;
                        }
                        break;
                    case  12 :
                        attIdx = context.getAttribute("", "perspectiveType");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText4(v);
                            state = 15;
                            continue outer;
                        }
                        break;
                    case  15 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  0 :
                        attIdx = context.getAttribute("", "adjustmentType");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText5(v);
                            state = 3;
                            continue outer;
                        }
                        break;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        if (("amount" == ___local)&&("" == ___uri)) {
                            state = 4;
                            return ;
                        }
                        break;
                    case  9 :
                        if (("date" == ___local)&&("" == ___uri)) {
                            state = 10;
                            return ;
                        }
                        break;
                    case  6 :
                        if (("currencyCode" == ___local)&&("" == ___uri)) {
                            state = 7;
                            return ;
                        }
                        break;
                    case  12 :
                        if (("perspectiveType" == ___local)&&("" == ___uri)) {
                            state = 13;
                            return ;
                        }
                        break;
                    case  15 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  0 :
                        if (("adjustmentType" == ___local)&&("" == ___uri)) {
                            state = 1;
                            return ;
                        }
                        break;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        attIdx = context.getAttribute("", "amount");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText1(v);
                            state = 6;
                            continue outer;
                        }
                        break;
                    case  5 :
                        if (("amount" == ___local)&&("" == ___uri)) {
                            state = 6;
                            return ;
                        }
                        break;
                    case  14 :
                        if (("perspectiveType" == ___local)&&("" == ___uri)) {
                            state = 15;
                            return ;
                        }
                        break;
                    case  2 :
                        if (("adjustmentType" == ___local)&&("" == ___uri)) {
                            state = 3;
                            return ;
                        }
                        break;
                    case  9 :
                        attIdx = context.getAttribute("", "date");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText2(v);
                            state = 12;
                            continue outer;
                        }
                        break;
                    case  6 :
                        attIdx = context.getAttribute("", "currencyCode");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText3(v);
                            state = 9;
                            continue outer;
                        }
                        break;
                    case  12 :
                        attIdx = context.getAttribute("", "perspectiveType");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText4(v);
                            state = 15;
                            continue outer;
                        }
                        break;
                    case  8 :
                        if (("currencyCode" == ___local)&&("" == ___uri)) {
                            state = 9;
                            return ;
                        }
                        break;
                    case  15 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  11 :
                        if (("date" == ___local)&&("" == ___uri)) {
                            state = 12;
                            return ;
                        }
                        break;
                    case  0 :
                        attIdx = context.getAttribute("", "adjustmentType");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText5(v);
                            state = 3;
                            continue outer;
                        }
                        break;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  10 :
                            eatText2(value);
                            state = 11;
                            return ;
                        case  3 :
                            attIdx = context.getAttribute("", "amount");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                eatText1(v);
                                state = 6;
                                continue outer;
                            }
                            break;
                        case  9 :
                            attIdx = context.getAttribute("", "date");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                eatText2(v);
                                state = 12;
                                continue outer;
                            }
                            break;
                        case  6 :
                            attIdx = context.getAttribute("", "currencyCode");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                eatText3(v);
                                state = 9;
                                continue outer;
                            }
                            break;
                        case  12 :
                            attIdx = context.getAttribute("", "perspectiveType");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                eatText4(v);
                                state = 15;
                                continue outer;
                            }
                            break;
                        case  13 :
                            eatText4(value);
                            state = 14;
                            return ;
                        case  15 :
                            revertToParentFromText(value);
                            return ;
                        case  7 :
                            eatText3(value);
                            state = 8;
                            return ;
                        case  1 :
                            eatText5(value);
                            state = 2;
                            return ;
                        case  0 :
                            attIdx = context.getAttribute("", "adjustmentType");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                eatText5(v);
                                state = 3;
                                continue outer;
                            }
                            break;
                        case  4 :
                            eatText1(value);
                            state = 5;
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

    }

}
