<?php

/**
 * @file
 * owlcarousel_ui.module
 */
 
/**
 * Implements hook_menu().
 */
function owlcarousel_ui_menu() {
  $items['admin/config/user-interface/owlcarousel'] = array(
    'title' => 'Owl Carousel',
    'description' => 'Owlcarousel instance settings list.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('owlcarousel_settings_form'),
    'access arguments' => array('administer owlcarousel settings'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'owlcarousel_ui.admin.inc',
  );
  $items['admin/config/user-interface/owlcarousel/%'] = array(
    'title' => 'Owl Carousel Instance Settings',
    'description' => 'List instance settings.',
    'page callback' => 'owlcarousel_instance_settings_form',
    'page arguments' => array(4),
    'access arguments' => array('administer owlcarousel settings'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'owlcarousel_ui.admin.inc',
  );
  $items['admin/config/user-interface/owlcarousel/import'] = array(
    'title' => 'Import Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('owlcarousel_variable_settings_import_form'),
    'access arguments' => array('administer owlcarousel settings'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'owlcarousel_ui.admin.inc',
  );
  $items['admin/config/user-interface/owlcarousel/%/export'] = array(
    'title' => 'Export Settings',
    'page callback' => 'owlcarousel_export_instance_settings',
    'page arguments' => array(4),
    'access arguments' => array('administer owlcarousel settings'),
    'type' => MENU_CALLBACK,
    'file' => 'owlcarousel_ui.admin.inc',
  );
  $items['admin/config/user-interface/owlcarousel/%/delete/%'] = array(
    'title' => 'Delete Settings',
    'page callback' => 'owlcarousel_delete_instance_settings',
    'page arguments' => array(4, 6),
    'access arguments' => array('administer owlcarousel settings'),
    'type' => MENU_CALLBACK,
    'file' => 'owlcarousel_ui.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function owlcarousel_ui_permission() {
  return array(
    'administer owlcarousel settings' => array(
      'title' => t('Administer Owl Carousel settings'),
    ),
  );
}

/**
 * Implements hook_variable_settings_form_alter().
 */
function owlcarousel_ui_variable_settings_form_alter(&$form, $form_state, $form_id) {
  if (isset($form_state['build_info']['args'][0]) && $form_state['build_info']['args'][0] == 'owlcarousel') {
    $instance = $form_state['build_info']['args'][1];
 
    $check = _owlcarousel_return_instances($instance);
    if ($check) {
      // Include additional submit handler to update settings cache.
      $form['#submit'][] = 'owlcarousel_variable_settings_submit';
 
      // This needs a graceful solution... =/
      $settings = owlcarousel_ui_build_instance_settings($instance, $form['#variable_edit_form']);
      foreach ($form as $key => $component) {
        if (strpos($key, '[instance_id]') !== FALSE) {
          $form[$key] = $settings[$key];
        }
      }
    }
    else {
      hide($form);

      // Alert user; no group was found.
      drupal_set_message(t('No settings group found with the name @name.', array('@name' => $instance)), 'warning');
    }
  }
}

/**
 * Format variable settings form to only display our
 * instance variables.
 */
function owlcarousel_ui_build_instance_settings($instance, $settings) {
  module_load_include('form.inc', 'variable');  

  foreach ($settings as $key => $setting) {
    $variable = variable_get_child($setting, $instance);
    $form[$setting][$variable['name']] = variable_form_element($variable);

    if ($setting == 'owlcarousel_navigation_text_[instance_id]') {
      $form[$setting][$variable['name']][0]['#title'] = t('Previous');
      $form[$setting][$variable['name']][1]['#title'] = t('Next');
    }
  }

  return $form;
}

/**
 * Helper function, return list of setting variables.
 */
function _owlcarousel_return_setting_vars() {
  $query = 'SELECT name FROM {variable} WHERE name LIKE :name';
  $results = db_query($query, array(':name' => db_like('owlcarousel_') . '%'))->fetchAll();

  return $results;
}
