<?php
// $Id: update.0001.php,v 1.2 2012/01/04 04:08:26 vamirbekyan Exp $

// Prepare an array of modules to be enabled.
$module_list = array(
  // Drupal core modules
  'block',
  'translation',
  'dblog',
  'field',
  'field_sql_storage',
  'field_ui',
  'file',
  'filter',
  'image',
  'locale',
  'menu',
  'node',
  'options',
  'path',
  'system',
  'taxonomy',
  'text',
  'update',
  'user',

  // Contrib modules
  'admin_menu',
  'ctools',
  'ctools_custom_content',
  'page_manager',
  'views_content',
  'update_scripts',
  'features',
  'i18n_block',
  'i18n',
  'i18n_menu',
  'i18n_string',
  'i18n_translation',
  'i18n_variable',
  'nodequeue',
  'dhtml_menu',
  'dhtml_menu',
  'entity',
  'entity_token',
  'libraries',
  'pathauto',
  'token',
  'variable',
  'variable_admin',
  'variable_realm',
  'variable_store',
  'panels_mini',
  'panels',
  'googleanalytics',
  'wysiwyg',
  'views',
  'views_slideshow',
  'views_slideshow_cycle',
  'views_slideshow_ddblock',
  'views_ui',
);

// Enable modules and dependecies
_us_install_modules($module_list);